### PR TITLE
Add docs for using registry on macOS

### PR DESCRIPTION
**Pull request by fiorix**

### CODE REVIEW

**Comment by fiorix** [comment]
Hey @tstromberg, I see you as the one and only editor of this document. Is it worth pursuing this PR or do you have plans to update it yourself?

**Comment by sharifelgamal** [comment]
We absolutely accept PRs for documentation, Thomas just happens to be the person who created this particular document, and we haven't updated it since.

**Comment by fiorix** [comment]
I've just signed the CLA.

**Comment by fiorix** [comment]
/assign @afbjorklund

(following instructions from the bot)

**Comment by fiorix** [comment]
Was looking at the failed tests and they all seem unrelated to my change to documentation.

**Pull request merged**
