### PR TITLE
Fix "--native-ssh" flag of "minikube ssh"

### PR DESCRIPTION
**Pull request by joshmue**
The "--native-ssh" flag was completely discarded; This PR fixes that and also makes sure that the SSH client is created after it is configured accordingly.

Refs #8359

Signing of CLA ~~will follow~~ is done.

### CODE REVIEW

**Comment by sharifelgamal** [comment]
This looks like it's doing the right thing. I'll mark it for testing once the CLA is signed.

**Comment by joshmue** [comment]
> This looks like it's doing the right thing. I'll mark it for testing once the CLA is signed.

@sharifelgamal (Just in case you did not receive any notification): The CLA is signed now.

**Review by medyagh — APPROVED** [review]
thank you

**Pull request merged**
