### PR TITLE
Assorted fixes for `--vm-driver=none`

### PR DESCRIPTION
**Pull request by intelfx**
This pull-request includes various fixes to Minikube, all related in some extent to its `--vm-driver=none` mode which I've been exclusively using.

There also are some refactorings that I've been doing in the process of understanding the code, they are not strictly necessary but I believe they make the code clearer a bit.

Besides refactorings, there are two major changes:
- ExecRunner is changed to use sudo internally, thus it is not required to run `minikube` as root anymore;
- `--vm-driver=none` now uses 127.0.0.1 instead of the host's external IP.

I'm not entirely positive on the last change, but binding to the host's external IP is unforgivable (because it is bound to change, and I hated to restart the cluster whenever I changed networks on my workstation laptop). I suspected that the host's external IP is used here because it gets propagated inside some containers (which obviously won't work with a loopback address), but I've perused the code lightly and couldn't find any places where this would matter.

Anyway, 127.0.0.1 seems to work, and I tried to ask on #minikube in Slack to confirm this but got no response. If someone explains how exactly it is wrong to use 127.0.0.1, I'll change this to add a throwaway private IP to the host's loopback interface and use it.

### CODE REVIEW

**Comment by dlorenc** [comment]
> ExecRunner is changed to use sudo internally, thus it is not required to run minikube as root anymore;

Can you explain how this part works? Will a password prompt appear on the command line for a user to  provide sudo credentials?

**Comment by dlorenc** [comment]
@minikube-bot OK to test

**Comment by intelfx** [comment]
@dlorenc Yes, something like this.

In fact, it already happens in master, because the `none` driver already uses sudo in commands it runs internally.

**Comment by intelfx** [comment]
I see that the tests are failing (esp. the "none" test), but I don't see where things went wrong. `minikube start` just returned 1 with no errors in the log? Can someone please point it out?

**Comment by intelfx** [comment]
Alright, I see it:

```
		[preflight] Some fatal errors occurred:
			[ERROR Port-8443]: Port 8443 is in use
			[ERROR Port-2379]: Port 2379 is in use
		[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
		E0814 04:22:19.033684    8176 start.go:295] Error starting cluster:  failed to init kubeadm: failed to run command `
		sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
		sudo /usr/bin/kubeadm alpha phase addon kube-dns
		`: exit status 2
```

Is this a problem with my changes or with your CI environment?

**Comment by dlorenc** [comment]
> @dlorenc @luxas PTAL

I think there's a small issue with the none driver integration test I'm fixing in another PR. Once I get that in, I'd like to see this pass the none driver integration test once. I'll ping you later today to rebase.

**Comment by dlorenc** [comment]
OK, would you mind rebasing and running tests again?

**Comment by intelfx** [comment]
Alright, now it fails in a more meaningful way. OK if I play the battleship game with your CI by repeatedly pushing different things and checking how they break?

**Comment by dlorenc** [comment]
> Alright, now it fails in a more meaningful way. OK if I play the battleship game with your CI by repeatedly pushing different things and checking how they break?

Yeah sure, I think you're pretty close.

**Comment by intelfx** [comment]
@marceloboeira You should’ve not, because this PR fails the CI and I haven’t yet had the time to find and fix the problem :)

--
Ivan Shapovalov / intelfx /

(Sent from a phone. Havoc may be wreaked on the formatting.)

**Comment by tstromberg** [comment]
Do you mind addressing the merge conflict? I'd like to see about merging this if it's still viable. My apologies for the unnecessarily long delay in reviewing this PR.

**Comment by intelfx** [comment]
Yeah, I got sidetracked with other work. Amazingly, I was able to rebase it without conflicts (and it even compiled without problems!).
Let's see if your CI still opposes this patch...

**Comment by intelfx** [comment]
/remove-lifecycle rotten
There are some nontrivial changes in master since this PR. I’l revise in a few days.

**Comment by afbjorklund** [comment]
I don't think running the node on `localhost` is a good idea, the VM that is provided to the `none` driver is supposed to come with a suitable network for running Kubernetes on - similar to the 192.168.100 ?

It seems what is really needed here is a better way to run minikube directly on the laptop... It was never meant to require using `sudo` to run or to bind to the laptop external IP (normally DHCP), for minikube

**Comment by tstromberg** [comment]
Thank you for the contribution. Due to recent inactivity, I will be marking this PR as closed until it can be rebased again on master.  Please re-open once that is done. Thank you again!

**Pull request closed without merging**
