### PR TITLE
Remove crio-wipe service that is not required

### LINKED ISSUE #18025: minikube crio-wipe
### What Happened?

the /lib/systemd/system/crio.service  unit file contains 
```
After=crio-wipe.service
Requires=crio-wipe.service
```
which effectively cleans up all but the preloaded images on every boot.
This makes every startup slow as hell  and wastes nw bandwidth and time.

It seem upstream dropped that one too https://github.com/cri-o/cri-o/pull/3545 around 1.18-ish

### Attach the log file

N/A

### Operating System

Redhat/Fedora

### Driver

KVM2

### PR DESCRIPTION
**Pull request by afbjorklund**
https://github.com/cri-o/cri-o/pull/3545/commits/086982d6184f73681999828905b5a422a92f7024

Closes #18025

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
Thanks, used the wrong command

**Review by spowelljr — APPROVED** [review]

**Pull request merged**
