### PR TITLE
Add .exe to url for the kubectl command, the other is an invalid url

### PR DESCRIPTION
**Pull request by cyberious**

### CODE REVIEW

**Comment by cyberious** [comment]
I signed it!

**Comment by cyberious** [comment]
Not worth my time fighting through all of your CLA, hope somebody fixes it.

**Comment by themalkolm** [comment]
@cyberious  I just gave up on the same step for exactly the same issue :D https://github.com/kubernetes/minikube/pull/941

**Comment by dlorenc** [comment]
Thanks for the fix, but unfortunately we do require the CLA for all contributions :( I'll close this for now, but please feel free to reopen if you're willing to sign the CLA.

**Comment by cyberious** [comment]
It's not a matter of signing the CLA but the automated additions, I signed both, but requiring it to be signed by the exact same email address that I want to put on public commits is a bit overkill.

**Pull request closed without merging**
