### PR TITLE
BuildKit 0.8.2

### PR DESCRIPTION
**Pull request by afbjorklund**
No support for systemd yet, unfortunately

### CODE REVIEW

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
The iso tests not going through for this PR...

**Comment by afbjorklund** [comment]
> The iso tests not going through for this PR...

That is strange, because we don't _have_ any tests for BuildKit.

**Review by sharifelgamal — APPROVED** [review]
KVM tests seem to be looking good against the new ISO, and Docker tests look ok against new kicbase.

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-image
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-image

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Pull request merged**
