### PR TITLE
[es] Add some translations to translations/es.json

### PR DESCRIPTION
**Pull request by gamba47**
Adding some new translations to spanish language.

### CODE REVIEW

**Comment by medyagh** [comment]
@gamba47 would u plz sign the CLA so we could accept this contribution ?

**Comment by gamba47** [comment]
> @gamba47 would u plz sign the CLA so we could accept this contribution ?

done i forgot to do this!

**Comment by sharifelgamal** [comment]
It also looks like your commit is not associated with your github user, make sure you git config is set correctly to fix that.

**Comment by gamba47** [comment]
> It also looks like your commit is not associated with your github user, make sure you git config is set correctly to fix that.

ok let me check, i'm a newbie using git sorry.

**Comment by gamba47** [comment]
> It also looks like your commit is not associated with your github user, make sure you git config is set correctly to fix that.

i'm stuck!
I will check everything again but i have:

- E-mail added and verified on github
- git config user.email    ok in my pc 

thanks for your time!

**Comment by sharifelgamal** [comment]
what about `git config user.name`?

**Comment by gamba47** [comment]
> **cla/linuxfoundation ** — commit missing GitHub user

I'm using mi real name not mi nick name. If i change it how can i replace this pr ?

**Comment by gamba47** [comment]
Hi i try to add another commit but only create another request https://github.com/kubernetes/minikube/pull/13180

I'm stuck, please let me know if you have any idea.

Sorry for this.

**Comment by spowelljr** [comment]
Hi @gamba47, run `git config -l | grep user` and verify that both `user.name` & `user.email` are set. Then also verify that `user.email` matches both your GitHub account and is the same email you submitted in the CLA, if you used a different email just submit the CLA again with this email. Then on your branch run `git reset --soft HEAD~2` which will undo your commits but leave your changes staged. Then create a new commit again and `git push -f origin <master>` to overwrite the existing commits with your new one.

**Comment by gamba47** [comment]
I have two users, my personal user gamba47 with gmail account and another for work.

repos1

In this particular folder i have this configuration:

image

I follow your steps without success.

In the first commit in this pr my user is wrong
image



Now i understand the `git reset --soft HEAD~2`   
thanks!

**Comment by gamba47** [comment]
Hi guys. Can i close this pr and open another with the changes using my username correctly ? i did not find how to change my first commit user.name. Sorry

let me know.

**Comment by sharifelgamal** [comment]
Absolutely. Feel free to close this PR and open a new one.

**Comment by gamba47** [comment]
Closing and second try at https://github.com/kubernetes/minikube/pull/13196

**Pull request closed without merging**
