### PR TITLE
Fix missing copyright headers.

### PR DESCRIPTION
**Pull request by dlorenc**
Also fix files with missing copyright headers :)
This addresses #35

### CODE REVIEW

**Comment by eparis** [comment]
why not the hack/verify-boilerplate stuff fomr the main repo? Which checks more than just .go and provides some hope of consistency across the projects?

**Comment by dlorenc** [comment]
> why not the hack/verify-boilerplate stuff fomr the main repo? Which checks more than just .go and provides some hope of consistency across the projects?

Ah, good idea. It doesn't look portable right now (the paths to check are hardcoded), but it's probably a good idea to try to reuse it. I'll reduce this PR to just fix the missing headers and investigate that later.

**Comment by eparis** [comment]
I think the things that are hard coded are the locations/names of the templates (hack/boilerplate) and the list of things that are excluded. It should just `cp` over here just fine...

**Comment by dlorenc** [comment]
> I think the things that are hard coded are the locations/names of the templates (hack/boilerplate) and the list of things that are excluded. It should just cp over here just fine...

I was a little worried about this line:
https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.py#L31

We also use Godeps with vendor/ here, so this line would need to change:
https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.py#L103

I'll send a PR over there to make those flags.

**Comment by eparis** [comment]
yes, the `../../` is to get from `hack/boilerplate/` to the root of the project. So I guess you'd need to change that if you didn't put the script in the same place.

ignoring `vendor` could be in both repos. instead of as a flag.

**Comment by dlorenc** [comment]
> yes, the ../../ is to get from hack/boilerplate/ to the root of the project. So I guess you'd need to change that if you didn't put the script in the same place.
> 
> ignoring vendor could be in both repos. instead of as a flag.

Haven't sent a PR yet, but this commit looks like it works:
https://github.com/dlorenc/kubernetes/commit/fbf7d3f1f2173f58d90da74b56013161dc0022b4

Mind if I send you that as a PR? I could drop the ignore flag and just add vendor to the hardcoded list if you prefer.

**Comment by eparis** [comment]
I say add `vendor` to the hard code list and up to you if you want/need the flag.

**Comment by dlorenc** [comment]
> I say add vendor to the hard code list and up to you if you want/need the flag.

SGTM.

**Pull request merged**
