### PR TITLE
Fix addon registry doesn't follow Minikube DNS domain name configuration (--dns-domain)

### PR DESCRIPTION
**Pull request by rogeriomm**
- Registry bug 
minikube-with-bug-registry version
minikube-with-bug-registry -p cluster-unfixed start --dns-domain cluster.xpt
minikube-with-bug-registry -p cluster-unfixed status
minikube-with-bug-registry -p cluster-unfixed addons enable registry
kubectl -n kube-system  get pods | grep registry-proxy-
kubectl -n kube-system logs registry-proxy-m5v47 | head -n 3
nc -v $(minikube -p cluster-unfixed ip) 5000
minikube-with-bug-registry -p cluster-unfixed logs

[logs-unfixed.txt](https://github.com/kubernetes/minikube/files/10355025/logs-unfixed.txt)

minikube-bug

- Registry bug fixed
minikube-master-fix-registry version
minikube-master-fix-registry -p cluster-fixed start --dns-domain cluster.xpt
minikube-master-fix-registry -p cluster-fixed status
minikube-master-fix-registry -p cluster-fixed addons enable registry
kubectl -n kube-system  get pods | grep registry-proxy-
kubectl -n kube-system logs registry-proxy-m5v47 | head -n 3
nc -v $(minikube -p cluster-fixed ip) 5000
minikube-master-fix-registry -p cluster-fixed ssh sudo cat /etc/kubernetes/addons/registry-proxy.yaml
minikube-master-fix-registry -p cluster-fixed logs

[logs-fixed.txt](https://github.com/kubernetes/minikube/files/10354987/logs-fixed.txt)

minikube-fixed

### CODE REVIEW

**Review by medyagh — COMMENTED** [review]
thank you @rogeriomm for fixing this, do you mind sharing Before and After this PR minikube output in the PR description ?

**Comment by rogeriomm** [comment]
> thank you @rogeriomm for fixing this, do you mind sharing Before and After this PR minikube output in the PR description ?

Done

**Review by medyagh — APPROVED** [review]
thank you for fixing this issue, look forward to see more contributions from you

**Comment by medyagh** [comment]
thank you @rogeriomm for the PR and patience on the review time

**Pull request merged**
