### PR TITLE
v1.4 rebase

### PR DESCRIPTION
**Pull request by r2d4**
This PR rebases the commits in the v1.4 branch onto master.  When v1.4 becomes GA, we will merge the v1.4 specific changes into master and create a v1.5 branch in the same fashion.  

In the time being, this branch will be used to build all the localkube releases for the kubernetes v1.4-beta releases.

I did my best to run `make gendocs` and run tests during the rebase to ensure each commit was still testable.

### CODE REVIEW

**Comment by dlorenc** [comment]
Thanks @r2d4! Let's merge when tests pass. Were there any manual changes required other than the make gendocs?

**Comment by r2d4** [comment]
Yeah, there were naturally some conflicts with Godeps and additionally one with minikube/cmd/minikube/root_ test.go  I'm not sure how to explicitly see those.  

I'm not sure the best way to go about doing this.  Gladly taking suggestions from anyone with more git-fu. I wanted to make sure that each commit was still testable where there were conflicts.

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
The one failure from that run looked like a flake, just verifying

**Comment by dlorenc** [comment]
LGTM

For cla history, this is just a rebase PR. All commits passed CLA bot the first time.

**Pull request merged**
