### PR TITLE
Enable GatewayPorts in sshd_config, for proxying in services into minikube

### PR DESCRIPTION
**Pull request by teejae**

### CODE REVIEW

**Comment by tstromberg** [comment]
Looks good. Just curious - what do you plan to do with this?

**Comment by teejae** [comment]
@tstromberg I was interested in proxying services from host machine into minikube for pods to access.

Per: https://medium.com/tarkalabs/proxying-services-into-minikube-8355db0065fd
Related Issue: https://github.com/kubernetes/minikube/issues/2735

Btw, is anyone working on getting that addon mentioned in https://github.com/kubernetes/minikube/issues/2735?

**Comment by teejae** [comment]
Signed CLA

**Comment by teejae** [comment]
@tstromberg, are you waiting for someone else to LGTM? just checking.

**Comment by tstromberg** [comment]
Thank you! This will definitely help with #2735 - Feel free to "/assign" yourself to that issue now that you have a PR that references it. =)

**Pull request merged**
