### PR TITLE
Fix parallels support after #953

### PR DESCRIPTION
**Pull request by bassam**
This PR adds vendor deps for parallels, fixes a compile issue, and enables parallels
as one of the default driver.

It's a continuation of the work in #953 and replaces #2807

/cc @denji @tstromberg

### CODE REVIEW

**Comment by afbjorklund** [comment]
Does those vendor changes mean we have to bundle the driver ? Or why can't we just use it as external ?

**Comment by tstromberg** [comment]
> Does those vendor changes mean we have to bundle the driver ? Or why can't we just use it as external ?

Good point. What is the authoritative download location for the driver?

**Comment by afbjorklund** [comment]
AFAIK it lives at https://github.com/machine-drivers/docker-machine-parallels

**Comment by bassam** [comment]
one is a fork of the other. I've use `github.com/Parallels/docker-machine-parallels` in this PR.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Pull request merged**
