### PR TITLE
container-runtime: add nvidia-docker

### PR DESCRIPTION
**Pull request by d4l3k**
This adds a new container-runtime that sets the correct configuration options for using with https://github.com/NVIDIA/k8s-device-plugin#nvidia-device-plugin-for-kubernetes

This requires a custom Dockerfile with `nvidia-container-toolkit` and a matching `libnvidia-ml.so.1` file. The driver version on the host needs to exactly match the version of nvml in the container.

kicbase Dockerfile

```
FROM gcr.io/k8s-minikube/kicbase:v0.0.37

RUN curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | sudo apt-key add -
RUN curl -s -L https://nvidia.github.io/libnvidia-container/$(. /etc/os-release;echo $ID$VERSION_ID)/libnvidia-container.list | tee /etc/apt/sources.list.d/libnvidia-container.list
RUN apt-get update && sudo apt-get install -y nvidia-container-toolkit && rm -rf /var/lib/apt/lists/*

ADD libnvidia-ml.so.1 /usr/lib/libnvidia-ml.so.1
```

Commands to run:

```
# Build docker image
cp /usr/lib/libnvidia-ml.so.1 .
docker build -t nvidiakic .

# Example start minikube with nvidia-docker
go run ./cmd/minikube start --container-runtime nvidia-docker --base-image='nvidiakic' --iso-url='https://storage.googleapis.com/minikube/iso/minikube-v1.29.0-amd64.iso,https://github.com/kubernetes/minikube/releases/download/v1.29.0/minikube-v1.29.0-amd64.iso' --driver docker --cpus=max --memory=max --nodes=2

# install the normal k8s-deviced-plugin (not the minikube addon!)
kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.13.0/nvidia-device-plugin.yml
```

Related issue #10229

### CODE REVIEW

**Comment by d4l3k** [comment]
I just signed the CLA, hasn't updated yet though

**Comment by d4l3k** [comment]
@sharifelgamal when you get a chance could you take a look at this PR?

I'm also wondering if you have any suggestions on how to handle the nvidia dependencies. I assume it doesn't make sense to add them to kicbase? Also the libnvidia-ml needs to match the host. We could try and grab it at runtime and overlay it in the container but that's pretty hacky. For my use case, right now building an custom kicbase is an acceptable step so this PR is sufficient

Thanks!

**Comment by sazzy4o** [comment]
The nvidia `oci` [hook](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#step-2-1-check-the-installation) creates the following mounts (on my ubuntu machine), so I don't think it is crazy to do overlays:
```
--mount=type=bind,source=/usr/bin/nvidia-smi,destination=/usr/bin/nvidia-smi,ro=true \
--mount=type=bind,source=/usr/bin/nvidia-debugdump,destination=/usr/bin/nvidia-debugdump,ro=true \
--mount=type=bind,source=/usr/bin/nvidia-persistenced,destination=/usr/bin/nvidia-persistenced,ro=true \
--mount=type=bind,source=/usr/bin/nvidia-cuda-mps-control,destination=/usr/bin/nvidia-cuda-mps-control,ro=true \
--mount=type=bind,source=/usr/bin/nvidia-cuda-mps-server,destination=/usr/bin/nvidia-cuda-mps-server,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-ml.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.525.78.01,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.525.78.01,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libcuda.so,destination=/usr/lib/x86_64-linux-gnu/libcuda.so.525.78.01,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.525.78.01,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.525.78.01,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-ml.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libcuda.so,destination=/usr/lib/x86_64-linux-gnu/libcuda.so.1,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.1,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-ml.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-ml.so,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-cfg.so,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libcuda.so,destination=/usr/lib/x86_64-linux-gnu/libcuda.so,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so,ro=true \
--mount=type=bind,source=/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so,destination=/usr/lib/x86_64-linux-gnu/libnvidia-allocator.so,ro=true \
--mount=type=bind,source=/run/nvidia-persistenced/socket,destination=/run/nvidia-persistenced/socket \
--mount=type=bind,source=/dev/nvidiactl,destination=/dev/nvidiactl \
--mount=type=bind,source=/dev/nvidia-uvm,destination=/dev/nvidia-uvm \
--mount=type=bind,source=/dev/nvidia-uvm-tools,destination=/dev/nvidia-uvm-tools \
--mount=type=bind,source=/dev/nvidia0,destination=/dev/nvidia0 \
--mount=type=bind,source=/proc/driver/nvidia/gpus/0000:65:00.0,destination=/proc/driver/nvidia/gpus/0000:65:00.0 \
--mount=type=tmpfs,destination=/proc/driver/nvidia \
```

**Comment by anthonyalayo** [comment]
What's left here? Merging this would be great!

**Comment by medyagh** [comment]
@d4l3k sorry for the long delay in PR review, I would llke to know how this PR is different from nivdia addon  ? can nvidia addon be enabled with this PR as well ?

also I would like you to contribute the kicbase changes as well so we could test it too

**Comment by d4l3k** [comment]
Kvm requires the GPU to use pcie pass through to the underlying VM. This PR instead makes the gpu device available with the host gpu driver so it can be shared between the host and minikube workers

**Comment by spowelljr** [comment]
Hi @d4l3k, I tried your example and it seems to work. Is there a way I can confirm that the pods have access to the GPUs? I tried using TensorFlow but was getting:
```
2023-09-11 22:46:18.090397: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
```

**Comment by d4l3k** [comment]
@spowelljr do you have access to the `nvidia-smi` command line within the container? That should tell you if you can access the GPUs or not

I was testing this with TorchX https://pytorch.org/torchx/latest/quickstart.html but that requires some familiarity with pytorch to get started

**Comment by d4l3k** [comment]
I wonder if there's other better options here as well via some of the other runtimes that might be easier to integrate https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuration

**Comment by spowelljr** [comment]
I tried getting `nvidia-smi` in the container but haven't been successful yet.

I see examples like this (https://jacobtomlinson.dev/posts/2022/how-to-check-your-nvidia-driver-and-cuda-version-in-kubernetes/)

But when I try `nvidia-smi` is not present, maybe they re-pushed the imaged with changes?

I tried installing the nvidia driver in a pod but got `Failed to initialize NVML: Unknown Error` when running `nvidia-smi`

I'm new to running GPUs and AI/ML workloads in Kubernetes, so I'm welcome to any tips you may have

**Comment by d4l3k** [comment]
@spowelljr have you tried getting nvidia-smi to work under just `nvidia-docker` as a first step? Once you have a good repro can then try it in minikube as well

**Comment by spowelljr** [comment]
@d4l3k I was able to get `nvidia-smi` to run in a container and have Tensorflow pickup the GPU, but I needed to do a couple more steps.

1. I had to install NVIDIA Container Toolkit on my host machine
2. I had to add `--gpus=all` to the command that starts the minikube container

Then I was able to use your PR to start minikube

**Comment by d4l3k** [comment]
Ahh nice! That makes sense, need it installed on the host to mount it and also need to set a Docker flags

**Comment by spowelljr** [comment]
@d4l3k If the tests look good I'll merge this PR. I'm working on a follow up PR that will make this work via a flag when starting minikube. I've discovered that I was able to get it to work without `ADD libnvidia-ml.so.1 /usr/lib/libnvidia-ml.so.1` which could simplify the flow. Could you confirm if you're able to get it to work without it or why you needed it.

**Comment by d4l3k** [comment]
@spowelljr thanks for pushing this through! Looks good to me :)

As for the `ADD libnvidia-ml.so.1` it's been a while but I believe this was due to the fact that I had a different CUDA/driver version in the container compared to my host machine. I was using Arch Linux which had a newer CUDA and driver version than the one available in the container OS. If you were running the same distribution on host and container it may have avoided that issue?

It may also be nvidia-container-toolkit takes care of it now and it's no longer necessary

**Review by spowelljr — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
