### PR TITLE
[WIP] Move 1.8 go

### PR DESCRIPTION
**Pull request by dims**

### CODE REVIEW

**Comment by r2d4** [comment]
It's probably good to have this open and start running integration tests against it

TODOs: 

- [ ]  install go 1.8 on our master jenkins builder
- [ ]  wait for k8s upstream to move to go 1.8

**Comment by dims** [comment]
agree @r2d4

**Comment by aaron-prindle** [comment]
Ref: #1172

**Comment by r2d4** [comment]
@dims to test in parallel with go 1.7, 
what do you think installing go 1.8 on the build server as `go18` and calling `go18` in this script https://github.com/kubernetes/minikube/blob/master/hack/jenkins/minikube_cross_build_and_upload.sh#L40-L47

**Comment by dims** [comment]
@r2d4 i used the gimme script from travis, don't know how to test it :) PTAL

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by dims** [comment]
looks like the go 1.8 installed find. go test hit a problem. trying to add $HOME/go to the GOPATH to see if that helps

**Comment by dims** [comment]
@dlorenc the Linux-VirtualBox actually finished running! Linux-KVM is still running, i have disabled the OSX and windows stuff.

**Comment by dims** [comment]
Looks like we are all green @r2d4 @dlorenc i'll run this every few days to catch if anything breaks

**Comment by dlorenc** [comment]
Now that 1.6 is merged, should we merge this?

**Comment by r2d4** [comment]
Looks like they didn't make it to go1.8 for k8s1.6, still tracking https://github.com/kubernetes/minikube/issues/1172

**Comment by dims** [comment]
@r2d4 @dlorenc looks like https://github.com/kubernetes/kubernetes/issues/38228 has merged

**Pull request closed without merging**
