### PR TITLE
Add SCTP support in the minikube ISO image

### LINKED ISSUE #12890: Missing SCTP support in the minikube VM image
The SCTP protocol is GA since Kubernetes 1.20, https://kubernetes.io/docs/concepts/services-networking/service/#sctp.

**Steps to reproduce the issue:** 

1. `minikube start --vm=true`
2. 
```
$ minikube ssh
                         _             _
            _         _ ( )           ( )
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ dmesg | grep -i sctp
[   46.458442] IPVS: Registered protocols (TCP, UDP, SCTP, AH, ESP)
$
```

When SCTP is enabled the `dmesg` should have a line saying something like ` sctp: Hash tables configured (bind 4096/4096)`

<details>

</details>

### PR DESCRIPTION
**Pull request by nickolaev**
The SCTP protocol is GA since Kubernetes 1.20, https://kubernetes.io/docs/concepts/services-networking/service/#sctp

Fixes #12890

### CODE REVIEW

**Comment by nickolaev** [comment]
Bump. Can someone please peek this configuration change?

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Review by sharifelgamal — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
