### PR TITLE
add wireguard module

### PR DESCRIPTION
**Pull request by Shareed2k**
add wireguard kernel module, option to create vpn and use kernel module of wireguard

### CODE REVIEW

**Comment by Shareed2k** [comment]
I signed it

**Comment by Shareed2k** [comment]
I signed it

**Comment by ilya-zuyev** [comment]
HI @Shareed2k! Thanks for your PR! Could add some description explaining why WireGuard should be enabled in minikube iso kernel and which usage scenarios it unlocks?

**Comment by ilya-zuyev** [comment]
Hi @Shareed2k! Are you still working on this PR?

**Comment by Shareed2k** [comment]
No you can close it

**Pull request closed without merging**
