### PR TITLE
Update k8s.

### PR DESCRIPTION
**Pull request by dlorenc**
This updates kubernetes to 760c563c7257dd7f9044073a2956a2bca1b455e7, or v1.3.0-alpha.3-2304-g760c563.

### CODE REVIEW

**Comment by dlorenc** [comment]
Integration tests pass, running conformance now.

**Comment by dlorenc** [comment]
Same two failures from before, this should be good to merge:
```
Summarizing 2 Failures:

[Fail] [k8s.io] Networking [It] should function for intra-pod communication [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:133

[Fail] [k8s.io] DNS [It] should provide DNS for services [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:204

Ran 98 of 309 Specs in 2230.791 seconds
FAIL! -- 96 Passed | 2 Failed | 0 Pending | 211 Skipped --- FAIL: TestE2E (2230.80s)
FAIL
```

**Comment by luxas** [comment]
LGTM
BTW, Shouldn't it be `v1.3.0-alpha.5` something if it's HEAD?
And has Kubernetes removed some deps or why has it decreased so greatly? I think it's good, but anyway...

**Comment by dlorenc** [comment]
I think you're right. I've seen this before... I think I have to do a "git fetch --tags" or something and then re-godep save. I'll give it a try. The files should be correct, but godep gets confused about tags.

**Pull request merged**
