### PR TITLE
ServiceCmd restructuring to repair docker/port-forward issues

### LINKED ISSUE #13075: Enhance service command to support multiple services
It would be great to see 
https://github.com/txn2/kubefwd incorporated so that you can forward all services in a namespace in a single request.

This would help those running within docker where metallb does not work due to the host not being able to NAT requests into the kubernetes container. Other examples are when you have multiple services and need to implement multiple shells and commands to handle the port forward / services requests.

### LINKED ISSUE #13736: Getting "panic: runtime error" when using minikube service in 1.25.2
### What Happened?

I create a new minikube cluster

    minikube start --memory=8192 --cpus=4 -n 2

I create a namespace and deploytment/service...

    kubectl create ns foo
    kubectl apply -f test-app/app.yml
    
  

```
app.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: foo
  name: test-app
---
apiVersion: v1
kind: Service
metadata:
  name: test-app
  namespace: foo
  labels:
    app: test-app
    service: test-app
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
      version: v1
  template:
    metadata:
      labels:
        app: test-app
        version: v1
    spec:
      serviceAccountName: test-app
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: Always
        name: test-app
        ports:
        - containerPort: 80

```

Next I start up as a service...

    minikube service test-app -n foo --url
    
in `1.25.1` everything runs fine when I try from `1.25.2` I get...

```
minikube service test-app -n foo --url    
😿  service foo/test-app has no node port
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.glob..func35(0x70d4760?, {0xc000ec42c0?, 0x1, 0x4})
	/Users/.../Code/lib/minikube/cmd/minikube/cmd/service.go:138 +0x645
github.com/spf13/cobra.(*Command).execute(0x70d4760, {0xc000ec4280, 0x4, 0x4})
	/Users/.../go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x70d4260)
	/Users/.../go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8164510/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

### LINKED ISSUE #13746: minikube service failing to tunnel in 1.25.2, workaround of kubectl port-forward service still works
### What Happened?

I had minikube version 1.23.2. I could run **minikube service _servicename_** fine. I would get a table that looks like this:

image
My browser would automatically open to the 127.0.0.1 URL for the tunnel and everything worked great. This is using a very simple NodePort deployment.

Then I updated minikube to version 1.25.2. Nothing else changed on my system. Now when I run **minikube service _servicename_**, I only get this and no table:
image
And my browser automatically tries to open a 192.68 address, so it seems the tunnel is failing.

Using the instructions at https://minikube.sigs.k8s.io/docs/start/ I did a quick test by running:
kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment hello-minikube --type=NodePort --port=8080

Then the following instructions at that page say:
image

I tried **minikube service hello-minikube** and it had the same issue as my other example above. Doesn't show a table, and tries to go to a 192.x address instead of a localhost one.

I tried the second suggestion to use **kubectl port-forward service/hello-minikube 7080:8080** then go to localhost:7080 and this _did_ work.
So I tried the same approach using kubectl port-forward service for my other application hellodjango-kube (shown in initial screenshots) and that also worked.

I tested with a Mac with an Intel chip. However, I have heard from several others who have run into this exact issue with 1.25.2, with both Windows 10 and Mac, including M1 Macs. 

### Attach the log file

[logforyou.txt](https://github.com/kubernetes/minikube/files/8184501/logforyou.txt)

### Operating System

macOS (Default)

### Driver

Docker

### PR DESCRIPTION
**Pull request by ckannon**
fixes #13736
fixes #13746
fixes #13075

Before:
```
ckannon-macbookpro:minikube ckannon$ mk service test-app -n test --url
😿  service test/test-app has no node port
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.glob..func35(0x7194960, {0xc000e20200, 0x1, 0x4})
        /Users/ckannon/dev/minikube/cmd/minikube/cmd/service.go:138 +0x645
github.com/spf13/cobra.(*Command).execute(0x7194960, {0xc000e201c0, 0x4, 0x4})
        /Users/ckannon/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x7194460)
        /Users/ckannon/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/ckannon/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /Users/ckannon/dev/minikube/cmd/minikube/cmd/root.go:157 +0xb9f
main.main()
        /Users/ckannon/dev/minikube/cmd/minikube/main.go:86 +0x255
ckannon-macbookpro:minikube ckannon$ 
```

After:
```
ckannon-macbookpro:minikube ckannon$ mk service test-app -n test --url
😿  service test/test-app has no node port
🏃  Starting tunnel for service test-app.
http://127.0.0.1:50772
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.

### CODE REVIEW

**Comment by ckannon** [comment]
@medyagh can I get an /ok-to-test please?

**Review by medyagh — COMMENTED** [review]
thank you for this PR, do u mind adding before/after this PR in the PR description

**Comment by ckannon** [comment]
Also - fixed tests so that all but one works for docker / port-forwarding drivers.

Before:
```
ckannon-macbookpro:minikube ckannon$ mk service test-app -n test --url
😿  service test/test-app has no node port
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.glob..func35(0x7194960, {0xc000e20200, 0x1, 0x4})
        /Users/ckannon/dev/minikube/cmd/minikube/cmd/service.go:138 +0x645
github.com/spf13/cobra.(*Command).execute(0x7194960, {0xc000e201c0, 0x4, 0x4})
        /Users/ckannon/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x7194460)
        /Users/ckannon/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/ckannon/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /Users/ckannon/dev/minikube/cmd/minikube/cmd/root.go:157 +0xb9f
main.main()
        /Users/ckannon/dev/minikube/cmd/minikube/main.go:86 +0x255
ckannon-macbookpro:minikube ckannon$ 
```

After:
ckannon-macbookpro:minikube ckannon$ mk service test-app -n test --url
😿  service test/test-app has no node port
🏃  Starting tunnel for service test-app.
http://127.0.0.1:50772
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.

**Review by medyagh — APPROVED** [review]
thank you very much for not only fixing this regress but also added tests so it doesnt happen again! 

good work

**Pull request merged**
