### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by haf**
Add some spacing to allow people to scan the readme to lessen threshold for getting started

### CODE REVIEW

**Comment by haf** [comment]
I hereby release the newlines to the public domain. Not going to sign CLA for this.

**Comment by dlorenc** [comment]
Thanks! I'll check to see if I'm allowed to merge this without you signing the CLA.

**Comment by dlorenc** [comment]
Hey,

Sadly we can't take this without you signing the CLA. Note that if you do sign it, it'll be valid for all Google projects (not just this one). Any chance you can sign it?

**Comment by dlorenc** [comment]
I'm going to close this out. Please re-open if you can sign the README.

**Pull request closed without merging**
