### PR TITLE
start.go: logging message typo correction

### PR DESCRIPTION
**Pull request by ethan-daocloud**
Signed-off-by: ethan <guangming.wang@daocloud.io>

### CODE REVIEW

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
@ethan-daocloud  thank you so much for fixing this issue !

**Pull request merged**
