### PR TITLE
Update Dashboard version to 1.7.1

### PR DESCRIPTION
**Pull request by maciaszczykm**
Closes #2112.

### CODE REVIEW

**Comment by maciaszczykm** [comment]
@minikube-bot ok to test

**Comment by maciaszczykm** [comment]
@r2d4 Can you approve?

**Comment by micdah** [comment]
Wuhu! Looking forward to I can now delete the `kill_dashboard.sh` script I have roaming around in my user folder. 😄

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by maciaszczykm** [comment]
Thank you too :)

**Comment by Kitanotori** [comment]
How do I upgrade the dashboard (noob level advice preferred..)? Running the latest v0.23.0 minikube.

**Comment by micdah** [comment]
Any word on when a new minikube release will be made? It would be really excellent to have this issue fixed so that people do not have to kill the dashboard every few hours. :smile:

**Comment by jgoclawski** [comment]
You can also hotfix it yourself, while waiting for the new release. Dashboard runs as an addon, so any changes you make via kubectl (like changing the image version), will be reverted after a few seconds. But you can modify the addon definition itself and those changes will be applied and will be persistent.

I'm using the `none` driver and the location of the file to modify is: `/etc/kubernetes/addons/dashboard-rc.yaml`. I guess that the same path is present in a VM after running `minikube ssh` (haven't checked that).

So the fix is to change the image tag from 1.7.0 to 1.7.1:

`sed -i s/1.7.0/1.7.1/g /etc/kubernetes/addons/dashboard-rc.yaml`

and wait a moment (< 1 min.) for the addon manager to apply those changes.

**Comment by micdah** [comment]
@jgoclawski Of course! What an excellent suggestion, works like a charm, I simply added this to our setup script which all developers use to get minikube in shape:
```bash
minikube ssh "sudo sed -i s/1.7.0/1.7.1/g /etc/kubernetes/addons/dashboard-rc.yaml"
```

Great workaround until a new release is made. 😄

**Pull request merged**
