### PR TITLE
Remove both the CoreDNS and KubeDNS addons. Let Kubeadm install the c…

### PR DESCRIPTION
**Pull request by dlorenc**
…orrect DNS addon.

Ref https://github.com/kubernetes/minikube/pull/3080
https://github.com/kubernetes/minikube/issues/2808

### CODE REVIEW

**Comment by dlorenc** [comment]
> Does this also mean that we no longer require to maintain the yaml files for [kube-dns](https://github.com/kubernetes/minikube/tree/master/deploy/addons/kube-dns) and [CoreDNS](https://github.com/kubernetes/minikube/tree/master/deploy/addons/coredns)?

Yup, removed these!

**Comment by dlorenc** [comment]
After some discussion yesterday we realized we can delete even more code, and not specify the DNS addon to kubeadm at all. Added that change as well.

With k8s 1.10, we get kube-dns, with 1.11 we get coredns.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by nyetwurk** [comment]
`kubeadm upgrade plan` hangs, so I have no way to upgrade from 1.10.0 to anything else.

**Pull request merged**
