### PR TITLE
Optionally use ssh for docker-env instead of tcp

### PR DESCRIPTION
**Pull request by afbjorklund**
Since Docker 18.09, it supports ssh: as well as tcp:
for connecting to the docker daemon (in $DOCKER_HOST).

This avoids setting up certificates, but leaves key
handling (host keys and identity keys) to ssh config.

See #9229

Once this is default, we _only_ have to set up ssh...

And it will use `/var/run/docker.sock`, over ssh.

### CODE REVIEW

**Comment by medyagh** [comment]
this is a cool PR, I look forward to see if this will fix some docker-env cert issues

**Comment by medyagh** [comment]
/ok-to-test

do. youmind adding an integeration test for this , maybe under funcationl test

**Review by medyagh — CHANGES_REQUESTED** [review]
we need to add docs on how to use this flag (specially docs on how to add SSH key)

**Comment by afbjorklund** [comment]
> we need to add docs on how to use this flag (specially docs on how to add SSH key)

For some reason we always need to clean up Docker's mess (undocumented DOCKER_HOST)

**Comment by afbjorklund** [comment]
We could export the value in a variable, but it seems a bit misleading if Docker is not using it ?
Also it is not mandatory to use ssh-agent, so we probably don't want to run `ssh-add` from env.

Currently we are using a special `ssh-key` command, to get the value to use for ssh identity.
Was planning to add a similar `ssh-host` (or something) command, to get the ssh host key(s).

**Comment by afbjorklund** [comment]
Probably they will use the ssh tunnel rather than the main ip, but same difference...

Most likely we want to **only** show the `rsa` host key, to match our `id_rsa` identity key.

That way there is only one host key to worry about, the comment only goes on stderr:

`# 127.0.0.1:35717 SSH-2.0-OpenSSH_8.1`

**Comment by afbjorklund** [comment]
One weird thing is that it doesn't actually talk _directly_ to the docker socket, it starts a `docker` program to do it:

`error during connect: Get http://docker/v1.40/version: command [ssh -l docker -p 35717 -- 127.0.0.1 docker system dial-stdio] has exited with exit status 255, please make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=Host key verification failed.`

```

Usage:	docker system dial-stdio

Proxy the stdio stream to the daemon connection. Should not be invoked manually.
```

So the client will need a `ssh` binary and the server will need a `docker` binary, behind the scenes

**Comment by afbjorklund** [comment]
@medyagh now there is a `-ssh-add` option, to add the key to ssh-agent

**Comment by medyagh** [comment]
we will do this PR after the release and also after the non-defaut docker PR is merged to ensure they work well together

**Pull request merged**
