### PR TITLE
Don't pull dashboard container image if present

### PR DESCRIPTION
**Pull request by r2d4**
One step in supporting an offline setup, see #391

### CODE REVIEW

**Comment by jimmidyson** [comment]
@minikube-bot test this please

**Comment by jimmidyson** [comment]
LGTM

@dlorenc How can I kick off Jenkins testing? Normally would expect to add comment like ok to test or something? What's the magic incantation here?

**Comment by dlorenc** [comment]
Ah I think it's:
@minikube-bot ok to test

for the first time someone sends a PR.

**Comment by jimmidyson** [comment]
@dlorenc Aha thanks!

**Comment by jimmidyson** [comment]
@r2d4 Need you to sign the CLA before we can merge this. Thanks for sending in the PR!

**Comment by r2d4** [comment]
I signed it!

- I didn't have my @google email associated with my github yet.  Lets see if the CLA bot picks it up now.

**Comment by jimmidyson** [comment]
Awesome thanks @r2d4! Merging...

**Pull request merged**
