### PR TITLE
Site: reformat documentation sidebar

### LINKED ISSUE #15263: Improve formatting for documentation sidebar
## Problem

The sidebar in the Minikube documentation is not formatted appropriately.  There are a couple of issues that stand out:
- The bullet/markers on parent pages disrupt the alignment of the content.
- The hierarchy is difficult to see because there is not enough left padding on child items.
- The Lora font is imported from Google Fonts with only the default font weight; the Docsy theme uses varying font weights in the sidebar to indicate active items (which is not currently visible)

## Solution

The left figure shows the current sidebar; the right figure shows the proposed changes.

minikube_sidebar_proposal

I'll submit a PR — created this issue to open up discussion.

### PR DESCRIPTION
**Pull request by rahil-p**
### Description
Reformats sidebar to fix alignment issues, emphasize the hierarchy of pages, and indicate open/active items.

fixes #15263

### Before / After

minikube_sidebar_proposal

### CODE REVIEW

**Review by medyagh — CHANGES_REQUESTED** [review]
Thank you very much ! This is something that was bugging myself and I’m glad you volunteered to contribute this.

Is it possible to make the indentation a little bit less ? Specially on the first page maybe a tiny bit less indented ?

**Comment by rahil-p** [comment]
@medyagh

> Thank you very much ! This is something that was bugging myself and I’m glad you volunteered to contribute this.
> 
> Is it possible to make the indentation a little bit less ? Specially on the first page maybe a tiny bit less indented ?

 
Here's a before/after from reducing the padding. How does this look?

Let me know, and I'll iterate or commit the change.

minikube_sidebar_proposal

**Comment by spowelljr** [comment]
Hi @rahil-p, the reduced padding looks good, I'll merge this.

I have another website related problem if you're interested, not sure if this is a framework constraint, but if you click a sub-section in `Benchmarks` it stops showing the other sub-sections. Not sure if that's by design, but makes it looks like there aren't other sections.

Before clicking sub-section
Screen Shot 2022-11-02 at 7 27 42 AM
After (note `Image Build Benchmarks` is gone)
Screen Shot 2022-11-02 at 7 27 53 AM

**Review by spowelljr — APPROVED** [review]

**Comment by rahil-p** [comment]
@spowelljr

That issue is coming from [here](https://github.com/kubernetes/minikube/blob/master/site/layouts/partials/sidebar-tree.html#L36-L57).  Minikube overrides the Docsy sidebar to ensure sections like ["Handbook"](https://minikube.sigs.k8s.io/docs/handbook/) remain expanded.

I'm able to fix the issue by updating the Docsy submodule and removing that override file, but at the cost of causing the expanded sections (e.g. "Handbook") to collapse:

localhost_1313_docs_benchmarks_imagebuild_macbenchmark_

Is that a worthwhile tradeoff?

**Pull request merged**
