### PR TITLE
Upgrade to Podman 2.1

### PR DESCRIPTION
**Pull request by RA489**
Upgrade to Podman 2.1.1
fixes https://github.com/kubernetes/minikube/issues/9638

### CODE REVIEW

**Review by afbjorklund — CHANGES_REQUESTED** [review]
We decided to wait with this, until later (PR #9635)

**Comment by RA489** [comment]
> We decided to wait with this, until later (PR #9636)

/hold

**Comment by afbjorklund** [comment]
Note that it needs more changes, since podman v2 doesn't support varlink any more (reason why we didn't upgrade to 2.0)

Closing as duplicate of #9635

**Pull request closed without merging**
