### PR TITLE
add ceph fs kernel driver to arm iso

### PR DESCRIPTION
**Pull request by BlaineEXE**
The Minikube ISO for aarch64 did not contain the Ceph Filesystem kernel driver build parameters present for the x86_64 build. This is critical for running Rook (https://rook.io) storage on Minikube.

`CONFIG_CEPH_LIB=y` was already present, however `CONFIG_CEPH_FS=m` and `CONFIG_CEPH_FS_POSIX_ACL=y` (both present in the x86_64 image) were not present and are added here.

### CODE REVIEW

**Comment by BlaineEXE** [comment]
This adds 2 kernel configs that I missed when contributing https://github.com/kubernetes/minikube/pull/16019 last year.

**Comment by BlaineEXE** [comment]
I think this may also need `ok-to-build-iso`, but I'm not certain

**Review by nirs — COMMENTED** [review]
Looks good, we will need these changes soon for Ramen.
https://github.com/RamenDR/ramen/pull/1192

**Comment by Fenrur** [comment]
No news here for build the iso ?

**Comment by BlaineEXE** [comment]
I saw that @afbjorklund and @medyagh approved @nirs 's PR yesterday. Do either of you have time to look at this PR? It seems like the default assigned reviewers might not have time. It's quite simple, and I've heard of a few more Rook users/devs (including myself) who are currently blocked by this.

**Comment by spowelljr** [comment]
ok-to-build-iso

**Review by spowelljr — APPROVED** [review]
Sorry for the delay

**Comment by BlaineEXE** [comment]
Thanks! :)

**Pull request merged**
