### PR TITLE
aarch64/iso: Add CONFIG_BPF_SYSCALL=y to aarch64 config

### PR DESCRIPTION
**Pull request by kakkoyun**
fixes https://github.com/kubernetes/minikube/issues/14674

### CODE REVIEW

**Comment by kakkoyun** [comment]
@afbjorklund @eiffel-fl Any input on this?

**Comment by kakkoyun** [comment]
> How are you?

All good. I hope you too :blush: 

> Just to know were you able to build the image for arm64 and to test it?

TBH I haven't. I trusted the CI for that. I have an ARM64 machine nearby. Is there a good doc to build the image?

**Comment by kakkoyun** [comment]
@eiffel-fl Thanks for taking the time and testing it. You're amazing :pray:

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by brancz** [comment]
I work with @kakkoyun and I can confirm that our eBPF workloads work with the iso you built! 🎉 

(he's on vacation, what can we do to get this PR along? :) )

**Comment by medyagh** [comment]
[kakkoyun](https://github.com/kakkoyun) Thank you for your patient, we will build the iso and see if it passes the tests.

@kakkoyun have you built the iso yourself to check if the changes work?

**Comment by klaases** [comment]
> Hey @spowelljr @afbjorklund @klaases, pinging you again. What should I do to get this merged? Please let me know if anything is missing.

Hi @kakkoyun please check to make sure that your changes work with the newly built ISO

> Pull the changes locally if you want to test with them or update your PR further.

**Comment by kakkoyun** [comment]
> I work with @kakkoyun and I can confirm that our eBPF workloads work with the iso you built (tested on an M1 Max 2021 with minikube 1.26.0)! tada
> 
> (he's on vacation, what can we do to get this PR along? :) )

@klaases @medyagh Yep, As my colleague @brancz mentioned above we have tested it. Everything works fine.

> Hi @kakkoyun, we have updated your PR with the reference to newly built ISO. Pull the changes locally if you want to test with them or update your PR further.

Shall I test it again considering the above message?

**Comment by brancz** [comment]
We tested the ISO that @eiffel-fl built, but I can't seem to find how to download the ISO built from the PR. Is the link maybe expired? Would love to get this merged for the next release, let us know how we can be helpful.

**Comment by brancz** [comment]
That would be incredible, let us know if we can be of any help! :)

**Pull request closed without merging**
