### PR TITLE
instructions on how to use the docker daemon

### PR DESCRIPTION
**Pull request by jstrachan**
added a little section to the docs of how to reuse the VM's docker daemon

### CODE REVIEW

**Comment by aaron-prindle** [comment]
@jstrachan 
To configure the VM docker daemon, minikube has a `minikube docker-env` command which creates export statements for the following docker environment variables from the VM:
DOCKER_TLS_VERIFY
DOCKER_HOST
DOCKER_CERT_PATH

It is used as shown below :
`$(minikube docker-env)`

The docs for this command are [here](https://github.com/kubernetes/minikube/blob/master/docs/minikube_docker-env.md)

**Comment by jstrachan** [comment]
@aaron-prindle whoah thats awesome - I'd totally missed that command!

How about we mention it on the home page so its a little more obvious - I just wasted an hour trying to figure that out - and totally missed the `docker-env` comand! :)

**Comment by jstrachan** [comment]
how about I close this PR and submit a new one that just references the `$(minikube docker-env)` instead?

**Comment by aaron-prindle** [comment]
@jstrachan 
That would be great, thanks!

**Pull request closed without merging**
