### PR TITLE
Update k8s.

### PR DESCRIPTION
**Pull request by dlorenc**
In preparation for the DNS Server work.
cc @luxas

### CODE REVIEW

**Comment by dlorenc** [comment]
Integration tests are passing. Will post conformance tests when they finish.

**Comment by luxas** [comment]
Updates on the conformance test?

**Comment by dlorenc** [comment]
5 failures:
```
Summarizing 5 Failures:

[Fail] [k8s.io] Networking [It] should function for intra-pod communication [Conformance]
/Users/dlorenc/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/networking.go:122

[Fail] [k8s.io] DNS [It] should provide DNS for the cluster [Conformance]
/Users/dlorenc/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/dns.go:236

[Fail] [k8s.io] Secrets [It] should be consumable from pods in volume [Conformance]
/Users/dlorenc/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1669

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods [Conformance] [Flaky]
/Users/dlorenc/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1301

[Fail] [k8s.io] DNS [It] should provide DNS for services [Conformance]
/Users/dlorenc/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/dns.go:236

Ran 97 of 293 Specs in 2242.750 seconds
FAIL! -- 92 Passed | 5 Failed | 0 Pending | 196 Skipped --- FAIL: TestE2E (2242.76s)
FAIL
```

Note the two DNS failures are red-herrings, and #158 will be a better indicator of DNS. We run DNS in-process, and those tests fail because they look for a pod with the correct labels instead of actually checking that DNS works.

**Comment by luxas** [comment]
I guess we want this before v0.2?

**Comment by dlorenc** [comment]
Let's merge right after the cut.

**Comment by luxas** [comment]
I suppose it's ok to merge now?

**Comment by dlorenc** [comment]
Yeah, feel free.

**Comment by luxas** [comment]
LGTM

**Comment by luxas** [comment]
We should figure out a way to get the k8s version info from a commit in `Godeps.json`.
Right now the constant is outdated, and no k8s version numbers are set.

**Comment by dlorenc** [comment]
Ah yeah, that should be trivial. I'll send a PR.

**Pull request merged**
