### PR TITLE
Update instructions to account for secure Minikube

### PR DESCRIPTION
**Pull request by yissachar**

### CODE REVIEW

**Comment by luxas** [comment]
@yissachar Please sign the CLA

**Comment by dlorenc** [comment]
cc @yissachar We'd be happy to merge this PR, but we'll need you to sign the CLA first. Have you had a chance to look at it yet?

**Comment by yissachar** [comment]
Waiting for my friendly corporate overlords to review it, sorry for the delay.

**Comment by dlorenc** [comment]
No rush! Just wanted to make sure you saw this.

**Comment by dlorenc** [comment]
Hey, now that we've automated the kubectl config I think this is obsolete. Sorry we couldn't get this merged!

**Comment by yissachar** [comment]
That's true. Run instructions are still out of date though, and should be updated to reflect the current Minikube state. I would open a new PR to do this but unfortunately still haven't received the go ahead on the CLA.

**Comment by dlorenc** [comment]
Ah sorry, I thought I had already merged #100 which should address that. I just merged it now so I think we're good.

We appreciate the issues you report, even if you're having trouble with the CLA!

**Pull request closed without merging**
