### PR TITLE
Add TZ database

### PR DESCRIPTION
**Pull request by gtirloni**
Adds TZ database to fix broken /etc/localtime symlink reported by #1324

### CODE REVIEW

**Comment by gtirloni** [comment]
I signed it!

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by r2d4** [comment]
Lets see how much this increases the .iso size by.  If its too large, we might just want to remove all references of timezone data.

**Comment by gtirloni** [comment]
That's a good point! Looks like it increased by 622KiB.

If we only need to support UTC, then it might indeed be overkill to have the whole thing. I was trying to follow the most generic approach by using a buildroot package, but the build process could always just create that specific UTC file and be done with it too.

**Comment by r2d4** [comment]
Thats totally fine.  Thanks for the PR!

**Pull request merged**
