### PR TITLE
Add `minikube license` command

### PR DESCRIPTION
**Pull request by spowelljr**
On releases, `make generate-licenses` is ran, it downloads all the licenses from dependencies, tars them, and uploads them to GCS.

Then, when the `minikube license` command is ran it downloads the licenses tar and untars them to the directory specified by `-d` or `--dir` (defaults to the current dir).

```
$ minikube license -d ./here
$ minikube ls -la ./here/licenses
total 0
drwxr-xr-x  12 ...  primarygroup   384 Oct 17 15:35 .
drwxr-xr-x  43 ...  primarygroup  1376 Oct 17 15:35 ..
drwxr-xr-x   3 ...  primarygroup    96 Oct 17 15:33 cloud.google.com
drwxr-xr-x  68 ...  primarygroup  2176 Oct 17 15:33 github.com
drwxr-xr-x   3 ...  primarygroup    96 Oct 17 15:33 go.opencensus.io
drwxr-xr-x   3 ...  primarygroup    96 Oct 17 15:33 go.opentelemetry.io
drwxr-xr-x   5 ...  primarygroup   160 Oct 17 15:33 go.uber.org
drwxr-xr-x   3 ...  primarygroup    96 Oct 17 15:33 golang.org
drwxr-xr-x   6 ...  primarygroup   192 Oct 17 15:33 google.golang.org
drwxr-xr-x   6 ...  primarygroup   192 Oct 17 15:33 gopkg.in
drwxr-xr-x  12 ...  primarygroup   384 Oct 17 15:33 k8s.io
drwxr-xr-x   5 ...  primarygroup   160 Oct 17 15:33 sigs.k8s.io

$ head -15 ./here/licenses/cloud.google.com/go/compute/metadata/LICENSE 

                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.
```

### CODE REVIEW

**Review by medyagh — APPROVED** [review]
can u plz paste in the PR description example of the output?

**Comment by spowelljr** [comment]
> can u plz paste in the PR description example of the output?

It already does, running the command generates a `licenses` dir that contains all the licenses, I updated the description to use the tree command is that makes it easier to see.

**Review by medyagh — CHANGES_REQUESTED** [review]
I am thinking License is a better name than Credit
since credit might imply the contributors to minikube which is misleading

https://www.git-tower.com/help/guides/integration/cli-commands/windows

**Comment by spowelljr** [comment]
> I am thinking License is a better name than Credit since credit might imply the contributors to minikube which is misleading

Rename the command from `credits` to `license`

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
Would be nice to have an integration test for it

**Comment by spowelljr** [comment]
> Would be nice to have an integration test for it

Added a functional test

**Pull request merged**
