### PR TITLE
Enable host path provisioner

### PR DESCRIPTION
**Pull request by viglesiasce**
With the addition of PVC dynamic provisioners the Host Path Provisioner was added for cases just like MiniKube. Users can now test their deployments with ephemeral volumes locally and leverage persistent disks when using a cloud provider.

In the [kubernetes/charts project](https://github.com/kubernetes/charts) we are moving to a model that allows charts to have persistence enabled by default. In the 1.4 timeframe, GCE, AWS and Host Path are supported. As chart maintainers and creators, we would like to be able to test charts using minikube when possible.

### CODE REVIEW

**Comment by viglesiasce** [comment]
Forgot to add that I tested on xhyve and KVM drivers.

**Comment by jimmidyson** [comment]
LGTM

**Comment by jimmidyson** [comment]
Actually... if this is only for 1.4 then it should be committed to the k8s-1.4 branch rather than master.

**Comment by viglesiasce** [comment]
Thanks @jimmidyson for the prompt response.

It works in 1.3, just alpha.

**Comment by jimmidyson** [comment]
Prompt response because I want it too (I'm that selfish :-b). Once this is merged we can cherry pick into 1.4 branch. Thanks!

**Comment by dlorenc** [comment]
LGTM as well. Not sure why Jenkins hasn't picked this up yet, will check.

**Comment by jimmidyson** [comment]
@k8s-bot ok to test

**Comment by jimmidyson** [comment]
@minikube-bot ok to test

**Comment by dlorenc** [comment]
@minikube-bot add to whitelist

**Pull request merged**
