### PR TITLE
Modify "example command" in cli reference for "config".

### PR DESCRIPTION
**Pull request by r0v**
tmp

### CODE REVIEW

**Review by priyawadhwa — APPROVED** [review]
Thank you for fixing this error in the documentation! It looks like you just need to sign the CLA for this to merge -- could you please follow the steps listed here:

https://github.com/kubernetes/minikube/pull/9618#issuecomment-723294303

**Review by priyawadhwa — COMMENTED** [review]
Hey @r0v , friendly ping -- could you please sign the CLA so that we can merge this fix?

**Comment by r0v** [comment]
@priyawadhwa Yep, I forgot about that.

**Review by tstromberg — APPROVED** [review]
Thank you for fixing this!

**Pull request merged**
