### PR TITLE
R2d4 kubeadm none

### PR DESCRIPTION
**Pull request by dlorenc**
This puts a commit on top of the ones in #2352 which I think finishes the fix.

Sending this one to test it in CI.

### CODE REVIEW

**Comment by dlorenc** [comment]
@r2d4 this should actually work now.

**Comment by dlorenc** [comment]
OK, actually actually working now.

**Comment by dlorenc** [comment]
Weird, it's passing now. It must have run at a stale commit.

**Comment by dlorenc** [comment]
cc @r2d4 how do you want to merge this? you can cherry-pick my commits or I guess we can rebase this one?

**Comment by r2d4** [comment]
@dlorenc you can go ahead and rebase this one and I can close mine

**Comment by dlorenc** [comment]
@r2d4 rebased.

**Pull request merged**
