### PR TITLE
Use correct port for echoserver - fixes "Connection reset by peer" LoadBalancer issue

### PR DESCRIPTION
**Pull request by GRXself**
Our image only listens on TCP port 8080, expose the deployment to the port 8000 will make it inaccessable.

### CODE REVIEW

**Comment by GRXself** [comment]
I have signed the CLA now.
/meow

**Comment by GRXself** [comment]
This PR is trying to resolve the issue https://github.com/kubernetes/minikube/issues/9498, I run the test on my local, it passed

**Review by tstromberg — APPROVED** [review]

**Comment by tstromberg** [comment]
Thank you for fixing this!

**Pull request merged**
