### PR TITLE
Document minikube kubectl autocompletion

### LINKED ISSUE #9603: Minikube Kubectl - completion does not work on zsh using alias
In the documentation it says
>You can also alias kubectl="minikube kubectl --" for easier usage.

when I use the current kubectl application from yum auto completion works:

```
➜  ~ kubectl
annotate        certificate     cordon          drain           get             port-forward    run             uncordon
api-versions    cluster-info    cp              edit            label           proxy           scale           version
apply           completion      create          exec            logs            replace         set
attach          config          delete          explain         options         rolling-update  taint
autoscale       convert         describe        expose          patch           rollout         top
```

When I use the "minikube kubectl -- " command it no longer works
```
➜  ~ minikube kubectl -- __minikube_handle_flag:31: bad math expression: operand expected at `'
➜  ~ minikube kubectl --
Desktop/              Downloads/            minikube-linux-amd64  Pictures/             Templates/
Documents/            install.sh*           Music/                Public/               Videos/

```

And I also get the same result when I now switch to an alias - I get an error and zsh instead completes with the files and folders from my current directory
```
➜  ~ alias kubectl="minikube kubectl --"
➜  ~ kubectl __minikube_handle_flag:31: bad math expression: operand expected at `'
     kubectl
Desktop/              Downloads/            minikube-linux-amd64  Pictures/             Templates/
Documents/            install.sh*           Music/                Public/               Videos/
```

I guess this is because zsh sees that "kubectl" is only an alias to "minikube ..." so it selects the minikube completion to handle this. From my understanding minikube could fix this in their completion, or there needs to be another way to do the alias so that zsh knows to call the kubectl autocompletion instead.

### PR DESCRIPTION
**Pull request by StefanLobbenmeier**
fixes #9603

### CODE REVIEW

**Comment by StefanLobbenmeier** [comment]
> after that, please reply here with a new comment and we'll verify

**Comment by StefanLobbenmeier** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

Just gonna try again :)

**Comment by StefanLobbenmeier** [comment]
Ok just got the confirmation from Hello Sign, should be good now

I signed it

**Review by medyagh — APPROVED** [review]
thanks

**Pull request merged**
