### PR TITLE
Add the multi VM drives discription.

### PR DESCRIPTION
**Pull request by warmchang**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
@warmchang You will need to run `make gendocs`:
https://github.com/kubernetes/minikube/blob/master/Makefile#L144

This will modify the text in our auto-generated docs here:
https://github.com/kubernetes/minikube/blob/master/docs/minikube_start.md

**Comment by warmchang** [comment]
hi @Prindle, can we confirm the auto-generated docs should be keep or drop?
I found this: https://github.com/kubernetes/minikube/issues/1338
在 2017年4月10日 下午10:24，Aaron Prindle <notifications@github.com>写道：

@warmchang<https://github.com/warmchang> You will need to run make gendocs:
https://github.com/kubernetes/minikube/blob/master/Makefile#L144

This will modify the text in our auto-generated docs here:
https://github.com/kubernetes/minikube/blob/master/docs/minikube_start.md

―

**Comment by warmchang** [comment]
Update the auto-generated file (minikube_start.md),

**Comment by r2d4** [comment]
Can you rebase this PR?  We removed the autogenerated docs, so you might have to change this PR a bit to not include docs/minikube_start.md

**Comment by warmchang** [comment]
oops, I rebased & pushed again, @r2d4

**Pull request merged**
