### PR TITLE
Fix links by using Hugo modules tag

### LINKED ISSUE #5696: gluster link is 404
This link is broken:
https://minikube.sigs.k8s.io/docs/tasks/deploy/addons/storage-provisioner-gluster/README.md
in this page:
https://minikube.sigs.k8s.io/docs/tasks/addons/

### PR DESCRIPTION
**Pull request by nanikjava**
fixes #5696

The link is broken as the config.toml is not using module.mounts.

To fix this need to add [module] section to point to the deploy/ folder as the README.md files are inside that folder

### CODE REVIEW

**Comment by medyagh** [comment]
@nanikjava  the preview shows the link is still broken
see  https://deploy-preview-5702--kubernetes-sigs-minikube.netlify.com/
I tried see https://deploy-preview-5702--kubernetes-sigs-minikube.netlify.com/addons/gvisor/README.md

**Comment by nanikjava** [comment]
> @nanikjava thanks for spotting the broken link
> 
> the preview shows the link is still broken see https://deploy-preview-5702--kubernetes-sigs-minikube.netlify.com/
> I tried see https://deploy-preview-5702--kubernetes-sigs-minikube.netlify.com/addons/gvisor/README.md

WIll take a look at it, as running it locally it works so there must be some configuration that I'm not using properly.

**Comment by nanikjava** [comment]
@medyagh did some more changes to the configuration and tested it works fine. Let me know how it looks on your end. Thanks

**Comment by medyagh** [comment]
@nanikjava  it is still broken, you can see the Preview by clicking on the `deploy/netlify Details`  in the PR checks

**Comment by nanikjava** [comment]
> @nanikjava it is still broken, you can see the Preview by clicking on the `deploy/netlify Details` in the PR checks

I've setup netlify to read from my minikube repo will investigate it.

Meantime can you tell me configuration that minikube is using so can configure it the same. This is what my account looks like

Screenshot from 2019-10-24 08-43-20

**Comment by nanikjava** [comment]
Posted too soon, found the netlify.toml file inside the source code.

**Comment by medyagh** [comment]
@nanikjava you dont have to setup netlifty on your account, on this PR bellow, you can have a preview per PR.

you can click on Details infront of deploy/netlify. I know it is a bit hard to find first time.
Screenshot_2019-09-25_11-35-30

**Comment by medyagh** [comment]
I am glad now it is LESS broken than before, but it is still broken in a way, that the MD file shows as Raw when you click on gvisor addon .

this PR is for sure a step better than what it is already ! is there an way we could make the Markdown file for gvisor not look raw ?

**Comment by medyagh** [comment]
@nanikjava  thank you so much for finding a way to fix that !

one small thing left, at least on my browser, the top part of the gvisor readme is not visible.

If you find a way to fix this, I believe it can be applied to all other embedded .MD files.

Screenshot_2019-10-25_14-17-27


Thanks again

**Comment by medyagh** [comment]
Thank you so much @nanikjava for doing this ! this will make a difference on users experience !

**Pull request merged**
