### PR TITLE
added logo assets

### PR DESCRIPTION
**Pull request by VictoriaDomalik**
added the approved full logo asset

### CODE REVIEW

**Comment by dlorenc** [comment]
Thanks @vagababov, could you sign the CLA by following the process here: https://cla.developers.google.com/

**Comment by jimmidyson** [comment]
Not sure about the transparent inner heptagon - would that be better filled with white in case the background where it's used is similar enough to some of the colours of the inner cube?

**Comment by jimmidyson** [comment]
Although that would then look rubbish with the white helm... Hmm. Feel that the inner heptagon should be filled somehow but I'm no designer :)

**Comment by VictoriaDomalik** [comment]
@dlorenc My git config didn't match the CLA. I've updated it now, is there anything else I need to do?

**Comment by dlorenc** [comment]
I think you need to reply with "@googlebot I signed it!" to make it check again.

**Comment by VictoriaDomalik** [comment]
@googlebot I signed it!

**Comment by VictoriaDomalik** [comment]
I've signed it now

**Comment by VictoriaDomalik** [comment]
I signed it!

**Comment by dlorenc** [comment]
@VictoriaDomalik hmm, it looks like you still haven't signed it as "sassy_iphone_user". Could you either sign it as that user as well, or amend the commits so they have the correct username? Sorry for all the trouble here.

**Comment by VictoriaDomalik** [comment]
w00t!

**Comment by dlorenc** [comment]
LGTM

**Pull request merged**
