### PR TITLE
Add code for downloading kicbase image to cache

### LINKED ISSUE #10912: --download-only should store/load kicbase on local filesystem
To ensure minikube can startup in an air-gapped environment.

Related issue: #10149

### PR DESCRIPTION
**Pull request by afbjorklund**
Download the image to the cache, instead of to the daemon.

This way it also works for Podman, and not only for Docker

Left to decide:

1) Should we store the KIC images in a separate directory
Before they were mixed with the container runtime images

2) Delete the old Docker-only code, only use the cache ?
This means **not** using the digest, always load from files

Currently the image is 354M on the disk (gz-compressed)

Closes #10912 #7766

### CODE REVIEW

**Comment by afbjorklund** [comment]
Note that in order to make this work for Podman, we need to fix `LoadFromTarball` to be compatible

It would also be nice to avoid loading again, if the image is already present in the container engine...

**Comment by afbjorklund** [comment]
But the current daemon.Write is quite stupid, so not too hard to re-implement with podman:

https://github.com/google/go-containerregistry/blob/main/pkg/v1/daemon/write.go#L57

Instead of using github.com/docker/docker/client, one could just fork a `sudo podman` ?

If we want to implement the lookup, we would also need something instead of daemon.Image

This is the other end, so instead of `| sudo podman load` it would need `sudo podman save |`

----

// Write saves the image into the daemon as the given tag.
func Write(tag name.Tag, img v1.Image) (string, error)

// Tag adds a tag to an already existent image.
func Tag(src, dest name.Tag) error

// Image provides access to an image reference from the Docker daemon,
// applying functional options to the underlying imageOpener before
// resolving the reference into a v1.Image.
func Image(ref name.Reference, options ...ImageOption) (v1.Image, error)

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
Looks good to me , Thank you for this PR

**Pull request merged**
