### PR TITLE
Remove some more vendored k8s.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by dlorenc** [comment]
This should fix #2869 as well.

**Comment by stantonxu** [comment]
@dlorenc , it seems to me that you only removed the package `log` under `cfssl`, the other packages under `cfssl` are still there. It still has the dependency on `google/certificate-transparency-go`, so we still need to update the dependency of `cfssl`, as it currently depends on `google/certificate-transparency/go`, which will make the `make test` still fail with golang 1.10.

**Comment by dlorenc** [comment]
> @dlorenc , it seems to me that you only removed the package log under cfssl, the other packages under cfssl are still there. It still has the dependency on google/certificate-transparency-go, so we still need to update the dependency of cfssl, as it currently depends on google/certificate-transparency/go, which will make the make test still fail with golang 1.10.
> 
>  Revert View details

Yeah thanks for noticing, I'll take another look.

**Comment by stantonxu** [comment]
@dlorenc yes, `cfssl` is gone now. Thanks.

**Pull request merged**
