### PR TITLE
Use etcd embed package, switch apiserver to use etcdv3

### PR DESCRIPTION
**Pull request by r2d4**
Etcd's embed package does a lot of the heavy lifting we were doing previously, as well as configure etcd v3 endpoints.

### CODE REVIEW

**Comment by r2d4** [comment]
Fixes https://github.com/kubernetes/minikube/issues/1254

**Comment by dlorenc** [comment]
Can you verify that an in-place upgrade works? Basically start minikube without this, deploy a bunch of stuff, then do a minikube start with this.

**Comment by r2d4** [comment]
I will try, but I don't think it will work.  The upgrade from 1.6 to 1.7 won't work without a recreate either.  I'm not sure exactly what we can do to support this sort of stuff.

**Comment by r2d4** [comment]
Well, I was wrong in both cases.  It should work upgrading from 1.6.x => 1.7.0 and etcd2 => etcd3.

```
minikube start --kubernetes-version v1.6.4
minikube stop
minikube start --kubernetes-version v1.7.0
```

**Pull request merged**
