### PR TITLE
Docker v1.12.0

### PR DESCRIPTION
**Pull request by r2d4**
Upgrading docker to v1.12.0 which was released a few days ago https://github.com/boot2docker/boot2docker/releases/tag/v1.12.0

### CODE REVIEW

**Comment by dlorenc** [comment]
Ah I think we need to keep this pinned. This will update Docker to 1.12.0, which hasn't been tested with kubernetes yet.

We should be able to find an issue in kubernetes/kubernetes that tracks support for 1.12.0. Until that's fixed we have to stay at 1.11.x

**Comment by r2d4** [comment]
Gotcha.  Its here I believe kubernetes/kubernetes#28698

**Comment by dlorenc** [comment]
Looks like there are still some issues with the 1.12 validation.

**Comment by pmentz** [comment]
Please keep in mind, that Docker 1.12 is only compatible with Windows 10 which has not been rolled out in many enterprise environments.

**Comment by dlorenc** [comment]
Closing since Kubernetes is sticking with 1.11 for 1.4.

**Pull request closed without merging**
