### PR TITLE
Add insecure-registry option to minikube start

### PR DESCRIPTION
**Pull request by ascheman**
Implementation of kubernetes/minikube#385

### CODE REVIEW

**Comment by ascheman** [comment]
Have no idea why travis fails (local "make test" works for me ;-)?

**Comment by dlorenc** [comment]
It looks like a gofmt issue in start.go and cluster.go. If you run ./test.sh locally, what do you see?
Running gofmt on those files should fix travis.

**Comment by ascheman** [comment]
Thanks @dlorenc!

I get the following output
```
Running go tests...
# k8s.io/minikube/pkg/minikube/cluster
pkg/minikube/cluster/cluster.go:237: undefined: Asset
FAIL    k8s.io/minikube/cmd/minikube/cmd [build failed]
```

For some reason the generated file ```pkg/minikube/cluster/assets.go``` is not loaded correctly during build (it contains the missing func Asset)?

**Comment by ascheman** [comment]
Build works now, had to fix some formatting and usage vs. docs as well.

**Comment by jimmidyson** [comment]
LGTM - thanks!

**Pull request merged**
