### PR TITLE
Check for uint32 overflow in go9p third party

### PR DESCRIPTION
**Pull request by afbjorklund**
See #11078

### CODE REVIEW

**Comment by medyagh** [comment]
@afbjorklund the build fails

**Comment by afbjorklund** [comment]
> @afbjorklund the build fails

Yeah, my code didn't work on actual 32-bit platforms

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
Looks good to me , Thank you for this PR and improving minikube,

**Pull request merged**
