### PR TITLE
Added command to remove and kill all kubernetes containers from docke…

### PR DESCRIPTION
**Pull request by aaron-prindle**
…r when the minikube none driver is stopped

### CODE REVIEW

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by aaron-prindle** [comment]
I believe this change has always worked, for a period the none CI was not working properly after addon config were changed and it was trying to use old-misconfigured containers is it was cleaning itself up.  This will clean up spawned containers for users on stop/delete to prevent that issue.

**Comment by r2d4** [comment]
@aaron-prindle do you want to try to disable the hack/jenkins script that deletes the docker containers?  since this should be sufficient now

**Comment by aaron-prindle** [comment]
I think we can just merge this as is for now.  The containers from the last run are still running on the docker daemon for the none driver.  As I don't believe any configuration was changed it would probably be fine but I don't want to take any chances.

**Comment by r2d4** [comment]
But we won't really know if it works unless we disable our jenkins script that does a similar thing?

**Comment by aaron-prindle** [comment]
done

**Comment by r2d4** [comment]
@aaron-prindle can you rebase and retest this?

**Comment by aaron-prindle** [comment]
rebased, tests running

**Comment by Siilwyn** [comment]
So #1769 is fixed right?

**Pull request merged**
