### PR TITLE
optimizing Chinese translation

### PR DESCRIPTION
**Pull request by BlackHole1**

### CODE REVIEW

**Comment by tstromberg** [comment]
@BlackHole1 - Please visit https://identity.linuxfoundation.org/projects/cncf to sign the CLA. Thank you!

**Comment by tstromberg** [comment]
This looks good. Can it be merged yet?

**Comment by BlackHole1** [comment]
I am also thinking about this problem because I found in the process of translation that if all the keywords are translated, some programmers in mainland China may not be able to go to google well. Because most of the problems on google are in English, if you search in Chinese, you may get nothing.

I'd like to hear your opinion. @tstromberg

**Comment by tstromberg** [comment]
Getting the problems translated would be nice, but not necessary for the first PR: there is a lot of text there.

**Comment by BlackHole1** [comment]
@tstromberg Ok, but please wait a few days, I'm adding some.

**Comment by priyawadhwa** [comment]
Hey @BlackHole1, thanks for opening this PR. We recently updated some of these translations, so you'll have to rebase your PR and fix any merge conflicts. Other than that, is this ready to be merged?

**Comment by BlackHole1** [comment]
@priyawadhwa @tstromberg hi guys. This branch has rebased the latest master branch code. And perfect a little translation. Now it can be merged.

**Comment by tstromberg** [comment]
Thank you!

**Pull request merged**
