### PR TITLE
json example Line up indention

### PR DESCRIPTION
**Pull request by oliveratutexas**
Indention for containers and volumes didn't line up.

### CODE REVIEW

**Comment by medyagh** [comment]
@oliveratutexas  welcome to contributing to minikube, would you please the CLA https://identity.linuxfoundation.org/projects/cncf

**Comment by priyawadhwa** [comment]
Hey @@oliveratutexas could you please sign the CLA as described here: https://github.com/kubernetes/minikube/pull/9594#issuecomment-720160945

**Comment by ilya-zuyev** [comment]
@oliveratutexas Thanks for your contribution! Could you sign the CNCF CLA? We need it before we can merge this PR.

**Comment by tstromberg** [comment]
Closing this stale PR for now - please re-open when you have a chance to sign the CLA.

**Pull request closed without merging**
