### PR TITLE
Upgrade Headlamp version to 0.15.1

### PR DESCRIPTION
**Pull request by yolossn**

### CODE REVIEW

**Comment by spowelljr** [comment]
CLA needs to be signed

**Comment by yolossn** [comment]
> What is up with all the headlamp spam ?

Sorry for the inconvenience, We recently had our organization moved from `kinvolk` to `headlamp-k8s` and one of the Github Actions setup to automate the process of creating the Update PR picked up the wrong configurations. We have fixed it and will make sure it works properly going forward. The same has been mentioned [here](https://github.com/kubernetes/minikube/pull/15817#issuecomment-1423081107). Once again sorry for the spam.

**Comment by yolossn** [comment]
@spowelljr I signed the CLA multiple times but the status is not updated. Is there something that I am missing?

**Comment by yolossn** [comment]
> Your commit email is with `sannagaraj@microsoft.com` but your commit on #15869 is using `nssvlr@gmail.com` so I'm assuming you signed the CLA with the latter. If you could change the commit to use the email you signed the CLA with it should resolve.

I signed the CLA with both the emails but still faced the same issue. I tried changing both the commits to use the same commit email `sannagaraj@microsoft.com` and still CLA fails on this one and passes on #15869.

**Comment by spowelljr** [comment]
I'm not too sure, if you make another branch and commit with the microsoft email and then create a PR as a test I'd be curious if it passes or not. If it does maybe closing this PR and reopening could resolve it. If it doesn't then there seems there would be an issue with the microsoft email and the CLA check.

**Comment by yolossn** [comment]
> I'm not too sure, if you make another branch and commit with the microsoft email and then create a PR as a test I'd be curious if it passes or not. If it does maybe closing this PR and reopening could resolve it. If it doesn't then there seems there would be an issue with the microsoft email and the CLA check.

Thanks for the pointer, I created a new [PR](https://github.com/kubernetes/minikube/pull/15994) and the CLA passed, so Ill close this PR and open a new one.

**Comment by yolossn** [comment]
Opened a new [PR](https://github.com/kubernetes/minikube/pull/15995) for the same.

**Pull request closed without merging**
