### PR TITLE
parallelize updating cluster and setting up certs

### PR DESCRIPTION
**Pull request by priyawadhwa**
Reduces time in setupKubeadm function from 4.6s to 3.2s

slowjam before change: http://104.197.255.167:8000

slowjam after change: http://34.67.230.103:8000

### CODE REVIEW

**Comment by medyagh** [comment]
The following Docker Driver Failures 


### TestStartStop/group/containerd - 251.5s
* known flake 


--- needs to verified that is not related to this PR:
### TestStartStop/group/crio - 759.66s
### TestStartStop/group/embed-certs - 144.29s
### TestFunctional/parallel/ComponentHealth

**Comment by tstromberg** [comment]
How much time does this save?

**Comment by tstromberg** [comment]
This seems good. Looking at SlowJam, `SetupCerts` still blocks for an additional second:

Screen Shot 2020-04-03 at 9 17 42 AM

If we parallelized the `cmd.Copy(f)` call in SetupCerts, we might get to where SetupCerts is no longer the blocker.

Here's a bigger idea, that should result in shaving >5s off of the Docker runtime:

- Update kic_runner to make it possible to re-use a persistent ssh connection rather than `docker cp` / `docker run`.  See `ssh_runner` as an example for a persistent client, where we add sessions for each command.

If you compare the slowjam profiles of hyperkit versus docker, you can see the benefit:

SetupCerts:
- 2.7s on Docker
- 0.6s on hyperkit

Rough napkin math: Each command or copy on Docker costs at least 0.1 seconds. On ssh it doesn't even show up in the SlowJam graph. I reckon we execute and copy ~60 commands. Thus, I think we should be able to expect 5s in time savings.

**Comment by tstromberg** [comment]
For comparison, SetupCerts on hyperkit. Same code, different runner:

Screen Shot 2020-04-03 at 9 57 08 AM

**Pull request merged**
