### PR TITLE
Rename `out.T` to `out.Step`

### LINKED ISSUE #9664: Rename `out.T` to `out.Step`
This will more accurately describe what this function is doing, as discussed here:

https://github.com/kubernetes/minikube/pull/9621#discussion_r520907966

This should be as simple as renaming 

https://github.com/kubernetes/minikube/blob/f6fa0ec0f6e5aa5e5f0d493cfac000bebad96429/pkg/minikube/out/out.go#L76

to `Step` and doing a find and replace in the code.

### PR DESCRIPTION
**Pull request by Evalle**
### PR Summary:
- Renames `out.T` to `out.Step`
- Fixes #9664 

### Comments for a reviewer:
I can see that there are still number of functions in out.go with T in the names:
`out.ErrT`, `out.SuccessT`, `out.FatalT`, `out.WarningT`, `out.FailureT`
should we rename them as well? WDYT @priyawadhwa  ?

### CODE REVIEW

**Comment by priyawadhwa** [comment]
Hey @Evalle I wouldn't worry about any of the other functions, renaming `out.T` to `out.Step` should be sufficient!

**Comment by priyawadhwa** [comment]
Looks like there are still some missing instances that need to be renamed:

```
[/home/runner/work/minikube/minikube/pkg/minikube/download/driver.go:36:6: T not declared by package out /home/runner/work/minikube/minikube/pkg/minikube/download/iso.go:130:6: T not declared by package out /home/runner/work/minikube/minikube/pkg/minikube/download/preload.go:141:6: T not declared by package out]"
```

To build minikube locally, and ensure that you've renamed every instance of `out.T` you can run `make` in the minikube directory.

**Review by priyawadhwa — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by Evalle** [comment]
@priyawadhwa thanks for the review! Some of the tests are still marked as failed. Are there any actions needed from my side?

**Comment by priyawadhwa** [comment]
Hey @Evalle LGTM! Thank you for fixing this.

**Pull request merged**
