### PR TITLE
Special case port mapping publish on macOS

### LINKED ISSUE #12658: minikube with podman on macOS darwin/amd64 doesn't work
**Steps to reproduce the issue:** 

1. Install minikube with `brew`:
   ```
   $ minikube version
   minikube version: v1.23.2
   commit: 0a0ad764652082477c00d51d2475284b5d39ceed
   ```
1. Following the [minikube podman instructions](https://minikube.sigs.k8s.io/docs/drivers/podman/), create and start the VM with `podman machine`:
   ```
   $ podman machine ls
   NAME                    VM TYPE     CREATED        LAST UP            CPUS        MEMORY      DISK SIZE
   podman-machine-default  qemu        7 minutes ago  Currently running  4           8.59GB      53.69GB
   ```
1. Start minikube with the podman driver and CRI-O container runtime fails:
   ```
   $ minikube start --driver=podman --container-runtime=cri-o 
   😄  minikube v1.23.2 on Darwin 11.6
   ✨  Using the podman (experimental) driver based on user configuration
   
   ❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'podman' is not supported on darwin/amd64
   ```
3. Try the second method:
   ```
   $ minikube start --driver=podman
   😄  minikube v1.23.2 on Darwin 11.6
   ✨  Using the podman (experimental) driver based on user configuration
   
   ❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'podman' is not supported on darwin/amd64
   ```

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

```
$ minikube logs --file=logs.txt
🤷  Profile "minikube" not found. Run "minikube profile list" to view all profiles.
👉  To start a cluster, run: "minikube start"
```

If this is a known issue, maybe it should be added to the ["Known Issues" section](https://minikube.sigs.k8s.io/docs/drivers/podman/#known-issues)?

**Full output of failed command if not `minikube start`:**

```
% minikube start --alsologtostderr -v=7 --driver=podman --container-runtime=cri-o
I1005 09:39:38.863234   21025 out.go:298] Setting OutFile to fd 1 ...
I1005 09:39:38.863516   21025 out.go:350] isatty.IsTerminal(1) = true
I1005 09:39:38.863524   21025 out.go:311] Setting ErrFile to fd 2...
I1005 09:39:38.863531   21025 out.go:350] isatty.IsTerminal(2) = true
I1005 09:39:38.863622   21025 root.go:313] Updating PATH: /Users/kevin/.minikube/bin
W1005 09:39:38.863741   21025 root.go:291] Error reading config file at /Users/kevin/.minikube/config/config.json: open /Users/kevin/.minikube/config/config.json: no such file or directory
I1005 09:39:38.863940   21025 out.go:305] Setting JSON to false
I1005 09:39:38.900145   21025 start.go:111] hostinfo: {"hostname":"Kevins-MBP.attlocal.net","uptime":1008238,"bootTime":1632443740,"procs":464,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"11.6","kernelVersion":"20.6.0","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"c2591f4e-ee82-33cc-8c59-db81d9ad80dd"}
W1005 09:39:38.900322   21025 start.go:119] gopshost.Virtualization returned error: not implemented yet
I1005 09:39:38.922270   21025 out.go:177] 😄  minikube v1.23.2 on Darwin 11.6
😄  minikube v1.23.2 on Darwin 11.6
I1005 09:39:38.922492   21025 notify.go:169] Checking for updates...
I1005 09:39:38.923318   21025 driver.go:343] Setting default libvirt URI to qemu:///system
I1005 09:39:39.426347   21025 podman.go:121] podman version: 3.3.1
I1005 09:39:39.448592   21025 out.go:177] ✨  Using the podman (experimental) driver based on user configuration
✨  Using the podman (experimental) driver based on user configuration
I1005 09:39:39.448637   21025 start.go:278] selected driver: podman
I1005 09:39:39.448643   21025 start.go:751] validating driver "podman" against <nil>
I1005 09:39:39.491992   21025 out.go:177] 

W1005 09:39:39.492219   21025 out.go:242] ❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'podman' is not supported on darwin/amd64
❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'podman' is not supported on darwin/amd64
```

### PR DESCRIPTION
**Pull request by kgibm**
fixes #12658

Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

### CODE REVIEW

**Comment by kgibm** [comment]
Looking at the first log, the error seems to be related to Docker pull request limits:

> ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/golang/manifests/sha256:39f9d94d45e404c98c3aa3c9b2406185f46ffddefeb45cdd9b778024626302fc: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by spowelljr** [comment]
A large amount of the test environments didn't report back, so going to run the tests again.

**Comment by spowelljr** [comment]
> First test error seems to be:
> 
> > Error response from daemon: cannot create network 683cd12d1eddbbf070e65dfdac992936ad3eaba811349fd9017b386ad031bdf3 (br-683cd12d1edd): conflicts with network 242e5ea9b5729ee491a318a05d91513f513576e09c7633b19207dbd56a7d298a (br-242e5ea9b572): networks have overlapping IPv4
> 
> Conflicting networks? And this was on Windows so it should not have been affected by this patch.

Yeah, this PR seems fine to me

**Review by spowelljr — APPROVED** [review]

**Pull request merged**
