### PR TITLE
Move logs to /var/lib/localkube.

### LINKED ISSUE #282: Kubernetes node seems to report its condition "OutOfDisk" quite often
Hi, Thanks as always for developing/sharing minikube :)

Recently my kubernetes node running on minikube reports its condition "OutOfDisk" quite often.
It is ok that I can't schedule any pod while it is "OutOfDisk", because it is how Kubernetes works.

The problem is that (1) my deployment seems pretty common and (2) I can't work around it.

For (1), I'm running 12 pods including mysql, memcached, elasticmq, postfix, nginx, my php apps, or etc which I believe is a common deployment for a web app thus I wish it could work without any problem.

For (2), restarting minikubeVM does fix the problem for a while(varies from several minutes to several hours) but not forever. Destroying/re-creating minikubeVM also fix the problem for several hours.
Removing stopped containers and dangling docker images, removing old docker container logs doesn't work.

---

Now, It looks to me like minikubeVM has too small capacity for the root disk or using small tmpfs device to persist something(maybe big log/temp files?).

Would you mind gaining the default capacity or provide an option to customize it, or mount another non-tmpfs device somewhere?

---

Here is the output from `kubectl describe no` which does report the "OutOfDisk" condition:

```
Name:			127.0.0.1
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=127.0.0.1
Taints:			<none>
CreationTimestamp:	Wed, 06 Jul 2016 12:38:55 +0900
Phase:
Conditions:
  Type			Status	LastHeartbeatTime			LastTransitionTime			Reason				Message
  ----			------	-----------------			------------------			------				-------
  OutOfDisk 		True 	Thu, 07 Jul 2016 11:08:49 +0900 	Thu, 07 Jul 2016 11:03:59 +0900 	KubeletOutOfDisk 		out of disk space
  MemoryPressure 	False 	Thu, 07 Jul 2016 11:08:49 +0900 	Wed, 06 Jul 2016 12:38:55 +0900 	KubeletHasSufficientMemory 	kubelet has sufficient memory available
  Ready 		True 	Thu, 07 Jul 2016 11:08:49 +0900 	Wed, 06 Jul 2016 12:38:55 +0900 	KubeletReady 			kubelet is posting ready status
```

And the output from `df -h`:

```
docker@minikubeVM:~$ sudo df -h
Filesystem                Size      Used Available Use% Mounted on
tmpfs                   896.3M    652.4M    243.9M  73% /
tmpfs                   497.9M   1016.0K    496.9M   0% /dev/shm
/dev/sda1                17.9G     10.7G      6.2G  63% /mnt/sda1
cgroup                  497.9M         0    497.9M   0% /sys/fs/cgroup
Users                   464.8G    170.4G    294.4G  37% /Users
/dev/sda1                17.9G     10.7G      6.2G  63% /mnt/sda1/var/lib/docker/aufs
```

AFAIK, Kubernetes node goes "OutOfDisk" when remaining capacity for the root disk or the docker disk goes under, by default, 256MB according to:

* [The LowDiskSpaceThresholdMB option for kubelet](https://github.com/kubernetes/kubernetes/blob/ab37fbf4c268b6b0eca4d3aba0284480a972c754/cmd/kubelet/app/options/options.go#L219)
* [which defaults to 256MB](https://github.com/kubernetes/kubernetes/blob/ab37fbf4c268b6b0eca4d3aba0284480a972c754/cmd/kubelet/app/options/options.go#L110)
* [used by DiskSpacePolicy which seems to determine whether the node is out of disk or not](https://github.com/kubernetes/kubernetes/blob/ab37fbf4c268b6b0eca4d3aba0284480a972c754/cmd/kubelet/app/server.go#L171)

`/dev/sda1                17.9G     10.7G      6.2G  63% /mnt/sda1` seems to be ok because its far larger than 256MB.
`tmpfs                   896.3M    652.4M    243.9M  73% /` seems to be problematic though.

Looking into `/var/log` revealed that my localkube.out is nearly 40MB:

```
docker@minikubeVM:~$ ls -lah /var/log
total 40832
drwxrwxr-x    3 root     staff        420 Jul  6 03:40 ./
drwxrwxr-x    8 root     staff        180 Jul  6 03:39 ../
-rw-r--r--    1 root     root           0 Jul  6 03:38 autologin
-rw-r--r--    1 root     root        5.8K Jul  6 03:38 boot2docker.log
drwxr-xr-x    2 root     root         600 Jul  7 03:12 containers/
lrwxrwxrwx    1 root     root          31 Jul  6 03:39 docker.log -> /var/lib/boot2docker/docker.log
-rw-r--r--    1 root     root       66.8K Jul  7 02:04 gcp-containers.log.pos
-rw-r--r--    1 root     root          54 Jul  6 03:40 gcp-docker.log.pos
-rw-r--r--    1 root     root          52 Jul  6 03:40 gcp-etcd.log.pos
-rw-r--r--    1 root     root          62 Jul  6 03:40 gcp-kube-apiserver.log.pos
-rw-r--r--    1 root     root          71 Jul  6 03:40 gcp-kube-controller-manager.log.pos
-rw-r--r--    1 root     root          62 Jul  6 03:40 gcp-kube-scheduler.log.pos
-rw-r--r--    1 root     root          55 Jul  6 03:40 gcp-kubelet.log.pos
-rw-r--r--    1 root     root          55 Jul  6 03:40 gcp-salt.pos
-rw-r--r--    1 root     root          61 Jul  6 03:40 gcp-startupscript.log.pos
-rw-r--r--    1 docker   staff        146 Jul  6 03:38 localkube.err
-rw-r--r--    1 docker   staff      39.7M Jul  7 05:07 localkube.out
-rw-rw-rw-    1 root     root           0 Jul  6 03:38 parallels.log
-rw-r--r--    1 root     root        6.0K Jul  7 05:06 udhcp.log
-rw-r--r--    1 root     root          28 Jul  6 03:39 userdata.log
-rw-rw-r--    1 root     staff       3.4K Jul  7 04:30 wtmp
```

so mounting another device at `/var/log` would free up the `/` a bit?

### PR DESCRIPTION
**Pull request by dlorenc**
Fixes #282.

### CODE REVIEW

**Comment by luxas** [comment]
LGTM

**Comment by jimmidyson** [comment]
I just tried the same thing & logs weren't written properly for some reason. Did this work for you?

**Comment by luxas** [comment]
Haven't tested it though...

**Comment by jimmidyson** [comment]
Logs:

```
Starting local Kubernetes cluster...
I0708 20:53:48.070174    2908 cluster.go:244] Setting up certificates for IP: %s 192.168.42.108
I0708 20:53:48.345407    2908 cluster.go:172] sudo killall localkube | true
I0708 20:53:48.453895    2908 cluster.go:174] killall: localkube: no process killed

I0708 20:53:48.453907    2908 cluster.go:172] 
# Run with nohup so it stays up. Redirect logs to useful places.
PATH=/usr/local/sbin:$PATH nohup sudo /usr/local/bin/localkube   --v 8 --generate-certs=false --logtostderr=true > /var/lib/localkube/localkube.err 2> /var/lib/localkube/localkube.out < /dev/null &

I0708 20:53:48.562198    2908 cluster.go:174] sh: can't create /var/lib/localkube/localkube.err: Permission denied

Kubernetes is available at https://192.168.42.108:443.
Kubectl is now configured to use the cluster.
```

**Comment by jimmidyson** [comment]
Which highlights another issue... need to better handle the process failing to start up for whatever reason.

**Comment by jimmidyson** [comment]
Fixed shell redirection in #303.

**Comment by dlorenc** [comment]
D'oh, thanks. I thought I tested it but didn't rebuild fully.

**Comment by dlorenc** [comment]
I verified this works now with #303

**Pull request merged**
