### PR TITLE
fix issue #11348 zsh completion broken

### PR DESCRIPTION
**Pull request by Keyhoh**
Fix https://github.com/kubernetes/minikube/issues/11348.

In `GenerateZshCompletion` changed `GenBashCompletion` to `GenZshCompletion`.

This is a minimal fix.
However, there is a much bigger and better fix.
Please consider  https://github.com/kubernetes/minikube/pull/11329.

### CODE REVIEW

**Review by medyagh — APPROVED** [review]

**Review by medyagh — CHANGES_REQUESTED** [review]
Build is failing please take a look

**Comment by Keyhoh** [comment]
> Build is failing please take a look

it seems to be due to timeout.
https://github.com/kubernetes/minikube/actions/runs/1209563749

build successful on my pc.

**Comment by spowelljr** [comment]
I'll re-run the job

**Review by spowelljr — APPROVED** [review]

**Comment by spowelljr** [comment]
@Keyhoh Because you have `Fix #11348` upon merging this PR, that issue will be closed. Will this fully solve the issue listed? Just making sure you're aware, if you don't want merging this PR to close that issue just remove `Fix` and it won't close it.

**Comment by Keyhoh** [comment]
> @Keyhoh Because you have `Fix #11348` in your PR description, upon merging this PR, that issue will be closed. Will this fully solve the issue listed?

yes, will solve.

**Pull request merged**
