### PR TITLE
move node ip save farther down stack

### PR DESCRIPTION
**Pull request by sharifelgamal**
We need to capture the new IP address for a node as soon as it saved so that anything calling it will automatically get the new IP.

### CODE REVIEW

**Comment by medyagh** [comment]
average on this PR is 2 seconds slower

Average time for minikube: 28.659565924000002
Average time for Minikube (PR 8168): 30.896566772

I wonder if that is related.

**Comment by medyagh** [comment]
@sharifelgamal do you mind pulling upstream and let the test run one more time

**Comment by sharifelgamal** [comment]
> average on this PR is 2 seconds slower
> 
> Average time for minikube: 28.659565924000002
> Average time for Minikube (PR 8168): 30.896566772
> 
> I wonder if that is related.

Unlikely, the times were totally sunk by the one run that was 33 seconds. We should do something slightly better with the timings, like run 5 and drop the highest and lowest number.

**Pull request merged**
