### PR TITLE
Kicbase: Update entrypoint from kind

### PR DESCRIPTION
**Pull request by spowelljr**

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
first failure seems to be go mod networking issue 
a rebuild should be fixing it
```
14:52:43 #64 411.8 /[go/pkg/mod/](http://goto.google.com/pkg/mod/k8s.io/client-go)[k8s.io/client-go](http://k8s.io/client-go@v0.20.4/kubernetes/scheme/register.go:56:2)[@v0.20.4/kubernetes/scheme/register.go:56:2](http://k8s.io/client-go@v0.20.4/kubernetes/scheme/register.go:56:2): [k8s.io/api@v0.20.4](http://k8s.io/api@v0.20.4): http2: client connection force closed via ClientConn.Close
```

**Comment by medyagh** [comment]
Ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
Thank you

**Pull request merged**
