### PR TITLE
ISO: Upgrade Docker, from 20.10.6 to 20.10.7

### PR DESCRIPTION
**Pull request by afbjorklund**
* runc v1.0.0-rc95

* containerd v1.4.6

This is for the ISO, I think that the KIC will do the upgrade automatically ?

```
The following packages will be upgraded:
  containerd.io docker-ce docker-ce-cli
3 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Need to get 94.5 MB of archives.
After this operation, 324 kB of additional disk space will be used.
Get:1 https://download.docker.com/linux/ubuntu focal/stable amd64 containerd.io amd64 1.4.6-1 [28.3 MB]
Get:2 https://download.docker.com/linux/ubuntu focal/stable amd64 docker-ce-cli amd64 5:20.10.7~3-0~ubuntu-focal [41.4 MB]
Get:3 https://download.docker.com/linux/ubuntu focal/stable amd64 docker-ce amd64 5:20.10.7~3-0~ubuntu-focal [24.8 MB]
```

### CODE REVIEW

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Review by sharifelgamal — APPROVED** [review]

**Comment by medyagh** [comment]
Ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-iso

**Pull request closed without merging**
