### PR TITLE
Adding upgrade minikube docs for mac

### LINKED ISSUE #5107: update docs about brew cask re-install
on both of my mac machines, work and personal I get this : when I upgrade minikube using 
```
brew cask install minikube
```

the exact error message : 
```
==> Purging files for version 1.3.1 of Cask minikube
Error: It seems there is already a Binary at '/usr/local/bin/minikube'; not linking.
```

I also tried the following, no help:

brew cask upgrade minikube
brew cask uninstall minikube
brew uninstall minikube
brew upgrade minikube

<details>
<pre>

=> Deleted Formulae
libggz                                                libguess                                              lysp

Error: Could not link:
/usr/local/etc/bash_completion.d/brew

Please delete these paths and run `brew update`.
Error: Could not link:
/usr/local/share/zsh/site-functions/_brew

Please delete these paths and run `brew update`.
Error: Could not link:
/usr/local/share/man/man1/brew-cask.1
/usr/local/share/man/man1/brew.1

Please delete these paths and run `brew update`.
Error: Could not link:
/usr/local/share/doc/homebrew

Please delete these paths and run `brew update`.
==> Satisfying dependencies
==> Installing Formula dependencies: kubernetes-cli
==> Installing kubernetes-cli
==> Downloading https://homebrew.bintray.com/bottles/kubernetes-cli-1.15.2.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/21/2156fdcf1e31852d9dcc12159cddc77b3f25d0d4a145de933c4141c1268bebcb?__gda__=exp=1565995598~hmac=024d266bc281ffca48
######################################################################## 100.0%
==> Pouring kubernetes-cli-1.15.2.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/kubectl
Target /usr/local/bin/kubectl
already exists. You may want to remove it:
  rm '/usr/local/bin/kubectl'

To force the link and overwrite all conflicting files:
  brew link --overwrite kubernetes-cli

To list all files that would be deleted:
  brew link --overwrite --dry-run kubernetes-cli

Possible conflicting files are:
/usr/local/bin/kubectl
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/kubernetes-cli/1.15.2: 234 files, 47.9MB
==> Downloading https://storage.googleapis.com/minikube/releases/v1.3.1/minikube-darwin-amd64
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'minikube'.
==> Installing Cask minikube
==> Purging files for version 1.3.1 of Cask minikube
Error: It seems there is already a Binary at '/usr/local/bin/minikube'; not linking.
 $ minikube version

</pre>
</details>

Update: 

I was able to solve the problem this way :
```
$ rm /usr/local/bin/minikube
$ brew cask reinstall minikube
```

I bet we need to update the brew formula to do that for us !

### PR DESCRIPTION
**Pull request by rbrishabh**
Fixes #5107 

Hey @medyagh !

Let me know if this needs any more changes! Thanks! =)

### CODE REVIEW

**Comment by rbrishabh** [comment]
I have signed the CLA!

**Comment by rbrishabh** [comment]
I have signed the CLA!

**Comment by medyagh** [comment]
Thank you so much @rbrishabh  for this quick PR and fixing the docs ! I bet this will save a lot of time for ppl facing that issue

**Comment by rbrishabh** [comment]
You're welcome! Will be around shooting down more issues! =)

**Pull request merged**
