### PR TITLE
CI: add test order to gopogh report

### PR DESCRIPTION
**Pull request by medyagh**
- Add sort by test order (and default to order by test order rather than duration)
-  Adds alternating background color to test name
Screen Shot 2020-12-01 at 11 44 48 AM

### CODE REVIEW

**Comment by medyagh** [comment]
/hold 
github action that releases binaries are down, will need to wait till gopogh binaries are published

**Review by priyawadhwa — APPROVED** [review]

**Review by ilya-zuyev — APPROVED** [review]
lgtm

**Pull request merged**
