### PR TITLE
Add document for adding new driver

### PR DESCRIPTION
**Pull request by anfernee**
Add document for adding drivers, as promised in #2526

### CODE REVIEW

**Comment by anfernee** [comment]
cc @dlorenc @r2d4

**Comment by anfernee** [comment]
@afbjorklund FYI, this is the docs probably you will be interested in.
cc @dlorenc @r2d4

**Comment by anfernee** [comment]
ping @luxas @dlorenc

**Comment by afbjorklund** [comment]
@anfernee : not sure I follow entirelly, wouldn't I still have to _rebuild_ minikube in order to add a driver ?

**Comment by anfernee** [comment]
Yes @afbjorklund you still need to rebuild minikube.

**Comment by anfernee** [comment]
Thanks @dlorenc

**Comment by afbjorklund** [comment]
Rebased my "qemu" driver to the new registry. It basically starts out the same as "kvm" does...

Theoretically qemu also runs on other platforms (without kvm), but it is probably slow (emulation).
And I don't really feel like testing it (thus set it to "linux"), but it could work for certain odd scenarios.

Not sure that adding a new driver directory was easier than changing cluster code, but happy if you are

**Pull request merged**
