### PR TITLE
Removed dependency on localkube to wait for the network to be up

### PR DESCRIPTION
**Pull request by aaron-prindle**
Ref: #1277

### CODE REVIEW

**Comment by r2d4** [comment]
I think we have to split up the commands before we remove this dependency.  I could be wrong though

**Comment by dlorenc** [comment]
> I think we have to split up the commands before we remove this dependency. I could be wrong though

I don't think so. IIRC we might have to investigate some flakiness inside of localkube itself.

**Comment by dlorenc** [comment]
Aaron, can you run the tests like 10 times and see if there are any new flakes?

**Comment by aaron-prindle** [comment]
commit: 1298
1 failing test (Linux-KVM)  I believe this is not related to the code change.

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by r2d4** [comment]
I'm a little concerned that KVM hasn't passed.  I'm pretty sure his was the issue that we saw before

**Comment by aaron-prindle** [comment]
We could make waiting for the network be driver specific to KVM.  Or we could wait for a custom network check that avoids the delay issues mentioned in #1277

**Comment by r2d4** [comment]
Maybe we can do some manual testing to see how much faster this gets us

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
@r2d4 the error looks different than before, it's actually related to SSH'ing in. I just tested this with KVM locally a bunch of times and didn't see any issues.

**Comment by dlorenc** [comment]
I ran some completely non-scientific benchmarks. With this change (linux/kvm):
```shell
1m7.390s
1m3.078s
0m57.739s
0m58.045s
0m58.333s
1m1.243s
0m56.404s
1m0.327s
0m58.563s
0m56.925s
```

Without it:
```shell
2m57.594s
3m2.195s
2m57.785s
2m57.945s
2m57.570s
2m56.606s
2m57.460s
2m57.988s
3m0.304s
2m56.295s
```

This looks pretty significant.

**Comment by r2d4** [comment]
I'm fine merging this in once we fix the KVM test. I haven't gotten a chance to try this out, but I'll look at it today and try to look at the issue.

**Comment by dlorenc** [comment]
@aaron-prindle could you rebase and re-run the tests?

**Comment by aaron-prindle** [comment]
rebased, re-running tests

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Pull request merged**
