### PR TITLE
restart kubelet if config changes

### LINKED ISSUE #8735: v1.9 -> v1.12 Docker upgrade takes >5 minutes (apiserver process never appeared, needs reset)
Reproduction:

`minikube-1.9.2 start --driver=docker`
`minikube-1.9.2 stop`
`minikube-1.12.0 start --driver=docker`

Startup took longer than usual, because I guess we moved kubelet flags?

```
I0716 16:31:06.874296   21759 kubeadm.go:471] needs reconfigure: configs differ:
-- stdout --
--- /var/tmp/minikube/kubeadm.yaml	2020-07-16 23:27:55.408896615 +0000
+++ /var/tmp/minikube/kubeadm.yaml.new	0001-01-01 00:00:00.000000000 +0000
@@ -25,12 +25,18 @@
     enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
 certificatesDir: /var/lib/minikube/certs
 clusterName: mk
-controlPlaneEndpoint: 172.17.0.2:8443
+controlPlaneEndpoint: control-plane.minikube.internal:8443
 dns:
   type: CoreDNS
 etcd:
   local:
     dataDir: /var/lib/minikube/etcd
+controllerManager:
+  extraArgs:
+    "leader-elect": "false"
+scheduler:
+  extraArgs:
+    "leader-elect": "false"
 kubernetesVersion: v1.18.0
 networking:
   dnsDomain: cluster.local
@@ -39,13 +45,16 @@
 ---
 apiVersion: kubelet.config.k8s.io/v1beta1
 kind: KubeletConfiguration
+clusterDomain: "cluster.local"
 # disable disk resource management by default
 imageGCHighThresholdPercent: 100
 evictionHard:
   nodefs.available: "0%"
   nodefs.inodesFree: "0%"
   imagefs.available: "0%"
+failSwapOn: false
 ---
 apiVersion: kubeproxy.config.k8s.io/v1alpha1
 kind: KubeProxyConfiguration
+clusterCIDR: "10.244.0.0/16"
 metricsBindAddress: 172.17.0.2:10249
...
I0716 16:31:06.975636   21759 kubeadm.go:564] reconfiguring cluster from /var/tmp/minikube/kubeadm.yaml
I0716 16:31:06.975662   21759 ssh_runner.go:148] Run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.18.0:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml"
I0716 16:31:07.035591   21759 ssh_runner.go:148] Run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.18.0:$PATH kubeadm init phase kubeconfig all --config /var/tmp/minikube/kubeadm.yaml"
I0716 16:31:08.227329   21759 ssh_runner.go:188] Completed: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.18.0:$PATH kubeadm init phase kubeconfig all --config /var/tmp/minikube/kubeadm.yaml": (1.191705974s)
I0716 16:31:08.227358   21759 ssh_runner.go:148] Run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.18.0:$PATH kubeadm init phase control-plane all --config /var/tmp/minikube/kubeadm.yaml"
I0716 16:31:08.324243   21759 ssh_runner.go:148] Run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.18.0:$PATH kubeadm init phase etcd local --config /var/tmp/minikube/kubeadm.yaml"
I0716 16:31:08.382915   21759 api_server.go:48] waiting for apiserver process to appear ...
...
W0716 16:35:07.048355   21759 logs.go:124] failed describe nodes: command: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.0/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.0/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: 
** stderr ** 
The connection to the server localhost:8443 was refused - did you specify the right host or port?

** /stderr **
I0716 16:35:07.048380   21759 logs.go:117] Gathering logs for etcd [69ab94613059] ...
I0716 16:35:07.048388   21759 ssh_runner.go:148] Run: /bin/bash -c "docker logs --tail 400 69ab94613059"
I0716 16:35:07.107775   21759 logs.go:117] Gathering logs for coredns [044b58430e88] ...
I0716 16:35:07.107801   21759 ssh_runner.go:148] Run: /bin/bash -c "docker logs --tail 400 044b58430e88"
I0716 16:35:09.667793   21759 ssh_runner.go:148] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0716 16:35:09.679914   21759 kubeadm.go:507] restartCluster took 4m2.869955715s
🤦  Unable to restart cluster, will reset it: apiserver healthz: apiserver process never appeared
```

The cluster was able to recover, but the upgrade time was 2X the usual.

### PR DESCRIPTION
**Pull request by sharifelgamal**
Fixes #8735

### CODE REVIEW

**Comment by medyagh** [comment]
the none upgtade test failed two times on this PR 
https://storage.googleapis.com/minikube-builds/logs/8817/b9c2182/none_Linux.html

**Comment by sharifelgamal** [comment]
> needs pass on none

It's passing

**Comment by medyagh** [comment]
> > needs pass on none
> 
> It's passing

once none shows green, this PR is good to merge

**Pull request merged**
