### PR TITLE
Update _index.md

### PR DESCRIPTION
**Pull request by anastaciocintra**
the links of latest downloads are mixed and/or does not exist

### CODE REVIEW

**Comment by anastaciocintra** [comment]
ok, CLA was signed

**Comment by anastaciocintra** [comment]
I signed it

**Review by afbjorklund — CHANGES_REQUESTED** [review]
Note: amd64 and x86_64 is the **same** architecture, so there is nothing to be changed here

```
e312901e12c347d0e4eec74d94b8d75512943eb62479b441bb1332f05cde0d09  minikube-linux-amd64
e312901e12c347d0e4eec74d94b8d75512943eb62479b441bb1332f05cde0d09  minikube-linux-x86_64
```

Thanks for reminding us that we don't need to upload the extra binary ("x86_64), though.

**Comment by afbjorklund** [comment]
The headlines have been updated, and the extra copies removed. So there is nothing more to do here.

https://minikube.sigs.k8s.io/docs/start/

* amd64 / x86_64

* arm64 / aarch64

**Pull request closed without merging**
