### PR TITLE
Stop using sudo for check_install_gh

### PR DESCRIPTION
**Pull request by andriyDev**
This was breaking out integration tests since they were unable to report flakes.

### CODE REVIEW

**Comment by andriyDev** [comment]
So close! Just need to figure out why it's printing some messages with no flake rates.

**Comment by medyagh** [comment]
> These are the flake rates of all failed tests on KVM_Linux_containerd.
> 
> Failed Tests	Flake Rate (%)
> TestErrorSpam/setup	100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=KVM_Linux_containerd&test=TestErrorSpam/setup))

@andriyDev the clicked links are empty

**Comment by medyagh** [comment]
> > These are the flake rates of all failed tests on KVM_Linux_containerd.
> > Failed Tests	Flake Rate (%)
> > TestErrorSpam/setup	100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=KVM_Linux_containerd&test=TestErrorSpam/setup))
> 
> @andriyDev the clicked links are empty

never mind it just took a few seconds to load (too impatient here)

**Comment by medyagh** [comment]
could we flip the colors ? duration to be blue and flake rate to be red ?

**Review by medyagh — APPROVED** [review]
looks good, plz merge when you feel comfortable, (the color request should be done in follow up prs)

**Comment by medyagh** [comment]
> These are the flake rates of all failed tests on Docker_Linux_containerd.
> 
> Failed Tests	Flake Rate (%)
> TestFunctional/parallel/LogsCmd	0.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_containerd&test=TestFunctional/parallel/LogsCmd))
> TestFunctional/parallel/LogsFileCmd	0.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_containerd&test=TestFunctional/parallel/LogsFileCmd))

@andriyDev why this says 0% flake rate ? this show average of flake rate in past 1 month ?
how about the column be more useful... in the graph I see this test has been flaking more than 0% for sure

**Comment by andriyDev** [comment]
> @andriyDev why this says 0% flake rate ? this show average of flake rate in past 1 month ?
> how about the column be more useful... in the graph I see this test has been flaking more than 0% for sure
Right now the flake rates are computed for the last 5 runs (pretty much), I'll increase it. The flake rate of 0% makes sense, since the flake occurred really late. 8f019e04 was merged in 20h ago, this PR was tested 14h ago, there was also some time in between 8f019e04 being merged and jenkins running on master, and also there is time in between the jenkins run and the flake rates being recomputed. The point being that the fact that a non-zero flake rate was not reported is reasonable. We shouldn't expect flake rate data to be accounted for over the past day - some may be processed, but we shouldn't rely on that.

**Pull request merged**
