### PR TITLE
configure auto-pause-interval addon

### LINKED ISSUE #10595: auto-pause: make time to pause configurable

### PR DESCRIPTION
**Pull request by wzslr321**
fixes #10595

Make AutoPause interval configurable by both persistent config with addons and minikube start flag. Defaults to 1 minute.

Configurable addon
```
➜  minikube git:(auto-pause-time-config) ✗ ./out/minikube addons configure auto-pause-interval
-- Enter interval time of auto-pause-interval (in minutes): 3
✅  auto-pause-interval was successfully configured
➜  minikube git:(auto-pause-time-config) ✗ cat ~/.minikube/profiles/minikube/config.json | grep AutoPauseInterval
    "AutoPauseInterval": 180000000000
```

Configurable flag on `minikube start`
```
➜  minikube git:(auto-pause-time-config) ✗ ./out/minikube start --auto-pause-interval=2m0s
😄  minikube v1.31.1 on Darwin 13.0.1 (arm64)
🆕  Kubernetes 1.27.4 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.27.4
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.27.3 on Docker 24.0.4 ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

❗  /usr/local/bin/kubectl is version 1.25.2, which may have incompatibilities with Kubernetes 1.27.3.
    ▪ Want kubectl v1.27.3? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

### CODE REVIEW

**Comment by medyagh** [comment]
@wzslr321 thanks for this PR can u plz fix the lint?

**Comment by wzslr321** [comment]
> @wzslr321 thanks for this PR can u plz fix the lint?

Yes, sorry I did not notice it before. I fixed the lint by running `make generate-docs` and reordering the imports in `cmd/auto-pause/auto-pause.go`. `make lint` passes now, at least locally

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
thank you for your contribution @wzslr321 look forward to see more contributions from you

**Pull request merged**
