### PR TITLE
Use configured DNS domain in bootstrapper kubeadm templates

### LINKED ISSUE #4963: Use configured DNS domain in bootstrapper kubeadm templates
The following two lines specify `cluster.local`, but if minikube was started with `--dns-domain bla`, that domain should probably be used instead.

https://github.com/kubernetes/minikube/blob/ae9f406b3852802b14c6b797a51d41eedd6d85b1/pkg/minikube/bootstrapper/kubeadm/templates.go#L87

https://github.com/kubernetes/minikube/blob/ae9f406b3852802b14c6b797a51d41eedd6d85b1/pkg/minikube/bootstrapper/kubeadm/templates.go#L141

### PR DESCRIPTION
**Pull request by nanikjava**
Fixes #4963

Following are the file changes:

kubeadm.go --> Add DNSDomain as one the field
kubeadm_test.go --> Add new test case to test the dns changes
templates.go --> Add the new DNSDomain into the template

Add new testdata for the kubeadm_test.go

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by nanikjava** [comment]
> Thanks for this PR and also adding unit tests ! could you add something in the website, either documentation or a tutorial that shows how to use this feature?

@medyagh Sure can do that, is the website in the docs/ folder of the minikube project ?. Thanks

**Comment by nanikjava** [comment]
> > Thanks for this PR and also adding unit tests ! could you add something in the website, either documentation or a tutorial that shows how to use this feature?
> 
> @medyagh Sure can do that, is the website in the docs/ folder of the minikube project ?. Thanks

Never mind found the folder for the website and added a new file called dns.md under Networking/ folder. Thanks

**Comment by medyagh** [comment]
Awesome thanks

**Pull request merged**
