### PR TITLE
Make the update check async.

### PR DESCRIPTION
**Pull request by dlorenc**
What do you all think of this pattern?

The basic idea is that we check for updates asynchronously, and print out the message after the command finishes.

### CODE REVIEW

**Comment by r2d4** [comment]
I think this makes a lot of sense.  We should also keep this simple like it is here :+1:

**Comment by jimmidyson** [comment]
Hmm not sure. Seems a bit odd to start a new minikube vm & only get told after command has completed a new version is available.

**Comment by dlorenc** [comment]
> Hmm not sure. Seems a bit odd to start a new minikube vm & only get told after command has completed a new version is available.

Yeah, that's the downside :(

The only other idea I have to is to do the check asynchronously and store the result of it somewhere, then print out the message at the start of the next command.

Any thoughts on that approach?

**Comment by jimmidyson** [comment]
Personally I don't mind the synchronous update check, as long as we keep connect/read timeouts low to fail fast if connectivity is not there. I assume the move to asynchronous check is to just to gain a marginal speedup in startup time?

As an aside, with minishift (minikube fork for openshift) I've enabled autoupdate that I proposed earlier for minikube. This does the update check once per day by default (as minikube does) & being a synchronous check enables the autoupdate to be triggered, if user agrees to it. This means binary is updated in place & then re-exec'ed to use the updated binary. This works great.

**Pull request closed without merging**
