### PR TITLE
Upgrade golang to v1.13.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
it fails consistently 

```
09:53:51 # k8s.io/minikube/pkg/minikube/translate
09:53:51 pkg/minikube/translate/translate.go:77:12: undefined: Asset
09:53:51 note: module requires Go 1.13
09:53:57 Makefile:411: recipe for target 'out/docker-machine-driver-hyperkit' failed
09:53:57 make: *** [out/docker-machine-driver-hyperkit] Error 2
09:54:04 # k8s.io/minikube/pkg/minikube/translate
09:54:04 pkg/minikube/translate/translate.go:77:12: undefined: Asset
09:54:09 Makefile:409: recipe for target 'out/docker-machine-driver-hyperkit' failed
09:54:09 make: *** [out/docker-machine-driver-hyperkit] Error 2
09:54:16 make: *** [out/docker-machine-driver-kvm2] Error 2
09:54:16 Makefile:490: recipe for target 'out/docker-machine-driver-kvm2' failed
09:54:17 Makefile:485: recipe for target 'out/docker-machine-driver-kvm2' failed
09:54:17 make: *** [out/docker-machine-driver-kvm2] Error 2

```

@chenrui333 do you mind checking locally to see if you can build locally ?
it seems to be having issues to build kvm and hyperkit drivers ! not sure how that would be related to go 1.13

**Comment by chenrui333** [comment]
Sure, I am checking it now!

**Comment by chenrui333** [comment]
@medyagh is there any way that i can see the cross-build jenkins config? I dont have a good idea to do the local testing.

**Comment by medyagh** [comment]
> @medyagh is there any way that i can see the cross-build jenkins config? I dont have a good idea to do the local testing (other than just do the build thing).

if you click on the commit status icon in the checks, it will take u to the link

https://storage.googleapis.com/minikube-builds/logs/5495/build.txt

I tried it locally 
```
 $ go version
go version go1.13.1 darwin/amd64
```
I got some similar errors:
```
ERROR: logging before flag.Parse: I1003 14:14:20.017384   65559 translate.go:92] Setting Language to en-US ...
E1003 14:14:20.021145   65559 out.go:95] [unset errFile]: X Unable to get the status of the cluster.
FAIL	k8s.io/minikube/cmd/minikube/cmd	1.098s

```

**Comment by chenrui333** [comment]
I see, I will try to run the steps in my local now. :)

**Comment by chenrui333** [comment]
` make -j 16 all` works well in my local.

**Comment by chenrui333** [comment]
Found out the root cause, the kube-cross does not have v1.13 build image :)

**Comment by chenrui333** [comment]
I will just close the PR for now, when kube-cross image got updated to v1.13 and then we can talk about this upgrade. :)

**Comment by chenrui333** [comment]
It has been recently updated to 1.12.10, I guess we will need to work thru from there.
https://github.com/kubernetes/kubernetes/tree/master/build/build-image/cross

**Comment by chenrui333** [comment]
Closing the PR for now. As there is not much we can do due to the kube-cross coupling.

**Pull request closed without merging**
