### PR TITLE
Make sure to update the package metadata

### LINKED ISSUE #10264: DEB_REVISION is not propagated into .deb metadata
> Are you mentioning the versions reported by `apt`/`dpkg`, or the one reported by `minikube version`?

The former -- the version info in the `.deb` package metadata.

A quick check identifies the issue here: https://github.com/kubernetes/minikube/blob/master/Makefile#L478

That should be `sed -E -i 's/--VERSION--/'$(DEB_VERSION)-$(DEB_REVISION)'/g' ...`

_Originally posted by @mgabeler-lee-6rs in https://github.com/kubernetes/minikube/issues/10224#issuecomment-767185001_

### PR DESCRIPTION
**Pull request by afbjorklund**
The revision/release was hardcoded as 0

Closes #10264

### CODE REVIEW

**Review by sharifelgamal — APPROVED** [review]

**Review by priyawadhwa — COMMENTED** [review]
Looks like lint is failing:

```
hack/update/github.go:231:14: SA1019: semver.Max is deprecated: use Compare instead. In most cases, returning a canonicalized version is not expected or desired.  (staticcheck)
				stable = semver.Max(ver, stable)
				         ^
hack/update/github.go:233:14: SA1019: semver.Max is deprecated: use Compare instead. In most cases, returning a canonicalized version is not expected or desired.  (staticcheck)
				latest = semver.Max(ver, latest)
```

**Comment by afbjorklund** [comment]
> Looks like lint is failing:

Probably just stale PR

**Comment by priyawadhwa** [comment]
nice!

**Pull request merged**
