### PR TITLE
updating for syntax error and being deprecated

### PR DESCRIPTION
**Pull request by asloan7**

### CODE REVIEW

**Comment by medyagh** [comment]
@asloan7  do you mind sharing what is the reason for chaning -A to a longer format ?

**Comment by asloan7** [comment]
@medyagh Maybe it is my version of kubectl, but I get: 
kubectl get pod -A
Error: unknown shorthand flag: 'A' in -A

**Comment by tstromberg** [comment]
I don't believe `kubectl get po -A` is being deprecated any time soon.

**Comment by asloan7** [comment]
What I was trying to say is kubectl get po -A does not work with older versions of kubectl, while kubectl get pods --all-namespaces works with all versions.

**Pull request closed without merging**
