### PR TITLE
out.FatalT should be followed by non-zero exit

### PR DESCRIPTION
**Pull request by prezha**
we should not fall through and exit with code 0 on fatal errors

### before
```
$ minikube -p ha-741094 node stop m02 -v=7 --alsologtostderr
...
I0115 19:17:18.946620   30826 out.go:177] ✋  Stopping node "ha-741094-m02"  ...
✋  Stopping node "ha-741094-m02"  ...
...
I0115 19:17:19.065289   30826 main.go:141] libmachine: Stopping "ha-741094-m02"...
I0115 19:17:19.065308   30826 main.go:141] libmachine: (ha-741094-m02) Calling .GetState
I0115 19:17:19.068085   30826 main.go:141] libmachine: (ha-741094-m02) Calling .Stop
I0115 19:17:19.075758   30826 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 0/60
I0115 19:17:20.078748   30826 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 1/60
I0115 19:17:21.081220   30826 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 2/60
...
I0115 19:18:16.315134   30826 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 57/60
I0115 19:18:17.321792   30826 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 58/60
I0115 19:18:18.328580   30826 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 59/60
I0115 19:18:19.329504   30826 stop.go:66] stop err: unable to stop vm, current state "Running"
W0115 19:18:19.329612   30826 out.go:239] 💣  Failed to stop node m02
💣  Failed to stop node m02
I0115 19:18:19.329659   30826 out.go:177] 🛑  Successfully stopped node ha-741094-m02
🛑  Successfully stopped node ha-741094-m02
```

### after
```
$ minikube -p ha-741094 node stop m02 -v=7 --alsologtostderr
...
I0115 20:19:49.428676   26589 out.go:177] ✋  Stopping node "ha-741094-m02"  ...
✋  Stopping node "ha-741094-m02"  ...
...
I0115 20:19:49.535496   26589 main.go:141] libmachine: Stopping "ha-741094-m02"...
I0115 20:19:49.535517   26589 main.go:141] libmachine: (ha-741094-m02) Calling .GetState
I0115 20:19:49.537771   26589 main.go:141] libmachine: (ha-741094-m02) Calling .Stop
I0115 20:19:49.544569   26589 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 0/60
I0115 20:19:50.550725   26589 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 1/60
I0115 20:19:51.557722   26589 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 2/60
...
I0115 20:20:46.813681   26589 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 57/60
I0115 20:20:47.816495   26589 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 58/60
I0115 20:20:48.824214   26589 main.go:141] libmachine: (ha-741094-m02) Waiting for machine to stop 59/60
I0115 20:20:49.825782   26589 stop.go:66] stop err: unable to stop vm, current state "Running"
W0115 20:20:49.825984   26589 out.go:239] 💣  Failed to stop node m02: Temporary Error: stop: unable to stop vm, current state "Running"
💣  Failed to stop node m02: Temporary Error: stop: unable to stop vm, current state "Running"
```
---

bonus: we've [decided](https://github.com/kubernetes/minikube/pull/17965#issuecomment-1915760341) to remove out.FatalT() altogether, to avoid any future confusion

### CODE REVIEW

**Review by medyagh — APPROVED** [review]
good catch, our naming is kind of confusing,

 it would be nice to add a comment on the func that this func does Not Exit...so future users dont rely on it to Exit for them. or maybe we should have had a better name for it...what do you think?

**Comment by prezha** [comment]
> good catch, our naming is kind of confusing,
> 
> it would be nice to add a comment on the func that this func does Not Exit...so future users dont rely on it to Exit for them. or maybe we should have had a better name for it...what do you think?

agree - it isn't obvious

there are a total of five places we currently use it (two of which are in the same code segment), so it shouldn't be too hard to refactor

we could add a func comment, but people might still miss it, so was thinking about two other options:

- remove it: _out.FatalT(...)_ is just a shorthand for _out.ErrT(style.Fatal, ...)_, so we can use out.ErrT directly instead and avoid confusion
- change the signature of out.FatalT() to include an exit code - eg: `FatalT(code int, format string, a ...V)`, then call os.Exit(code) within out.FatalT() body - similar to eg, https://pkg.go.dev/log#Fatal or https://pkg.go.dev/k8s.io/klog/v2#Fatal, we just allow the user to specify the exit code instead of using the fixed one (1 or 255 respectively)

wdyt @medyagh ?

**Comment by prezha** [comment]
somewhat exotic bonus - successful minikube TestHA run on raspberry pi 5 with the latest k8s v1.29.1:
> make integration -e TEST_ARGS="-minikube-start-args='--driver=docker --container-runtime=docker --kubernetes-version=v1.29.1 --alsologtostderr -v=7' -test.run TestHA --cleanup=false"

Screenshot-2024 01 19-19 04 29
[rPi5-k8s-v1.29.1 - TestHA - docker_docker - PASS.log](https://github.com/kubernetes/minikube/files/13993271/rPi5-k8s-v1.29.1.-.TestHA.-.docker_docker.-.PASS.log)

**Comment by medyagh** [comment]
> * remove it: _out.FatalT(...)_ is just a shorthand for _out.ErrT(style.Fatal, ...)_, so we can use out.ErrT directly instead and avoid confusion

@prezha this suggestion seems more appealing
```remove it: out.FatalT(...) is just a shorthand for out.ErrT(style.Fatal, ...), so we can use out.ErrT directly instead and avoid confusion```

**Review by spowelljr — APPROVED** [review]

**Pull request merged**
