### PR TITLE
addons: Fix auto-pause addon

### PR DESCRIPTION
**Pull request by spowelljr**
Reverting https://github.com/kubernetes/minikube/pull/11909 and https://github.com/kubernetes/minikube/pull/17070 as they both caused issues related to the auto-pause addon.

Starting with https://github.com/kubernetes/minikube/pull/17070, the PR added calling `viper.GetString(config.ProfileName)` in `cmd/auto-pause/auto-pause.go`. The problem is `cmd/auto-pause/auto-pause.go` is built and then ran inside the Kicbase/ISO, so  `mustload.Partial(profile)` always fails since we're inside the Kicbase/ISO and there is no `~/.minikube` folder, causing the the auto-pause binary to exit and breaking the addon and `kubectl` commands.

I'm not sure the exact cause of the failure related to https://github.com/kubernetes/minikube/pull/11909 (will revisit once addon is back in a working state) but after the pods are unpaused `kubectl` commands hang for a while until finally responding with `Unable to connect to the server: EOF`.

I also updated the auto-pause addon image since `v0.0.4` was only built for arm64 so other architectures fail with an exec error.

**Before:**
```
$ minikube start

$ minikube addons enable auto-pause

# kubectl commands fail
$ kubectl get pods -A
The connection to the server 192.168.49.2:32443 was refused - did you specify the right host or port?

# auto-pause-hook pod is exited
$ minikube ssh -- docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED              STATUS                          PORTS     NAMES
cdad0268cc7d   a633c3ce5969                "/auto-pause-hook -t…"   21 seconds ago       Exited (1) 21 seconds ago                 k8s_webhook_env-inject-5d9dd8dcc4-wdxmj_auto-pause_187b3ee3-535b-415e-a280-efa86b5828c3_3

# pod logs
$ minikube ssh -- docker logs cdad0268cc7d
exec /auto-pause-hook: exec format error
```

**After updating auto-pause image:**
```
$ minikube start

$ minikube addons enable auto-pause

# kubectl commands fail
$ kubectl get pods -A
Unable to connect to the server: EOF

# auto-pause-hook pod is now running, but pods never pause
$ minikube ssh -- docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS         PORTS     NAMES
c7a7b43fb227   haproxy                               "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes             k8s_auto-pause_auto-pause-proxy-7ff85b7ccd-hn9hc_auto-pause_f7bd4bcb-805d-42db-878a-3d1ad02f950e_0
b3c2aafbc82d   6e38f40d628d                          "/storage-provisioner"   4 minutes ago   Up 4 minutes             k8s_storage-provisioner_storage-provisioner_kube-system_ba7c0ef4-36c1-42a5-9fe0-5964cf9a447a_1
2e129bb2c486   gcr.io/k8s-minikube/auto-pause-hook   "/auto-pause-hook -t…"   4 minutes ago   Up 4 minutes             k8s_webhook_env-inject-5bb6dbcc76-9xkhd_auto-pause_701dff42-7e8e-4388-a58a-1d4604e58658_0
3ed9b664e2b4   registry.k8s.io/pause:3.9             "/pause"                 4 minutes ago   Up 4 minutes             k8s_POD_env-inject-5bb6dbcc76-9xkhd_auto-pause_701dff42-7e8e-4388-a58a-1d4604e58658_0
6f6ee436c9ca   registry.k8s.io/pause:3.9             "/pause"                 4 minutes ago   Up 4 minutes             k8s_POD_auto-pause-proxy-7ff85b7ccd-hn9hc_auto-pause_f7bd4bcb-805d-42db-878a-3d1ad02f950e_0
a1a032d31569   ead0a4a53df8                          "/coredns -conf /etc…"   4 minutes ago   Up 4 minutes             k8s_coredns_coredns-5dd5756b68-b9gm9_kube-system_9dc4b9d6-ce8f-4715-8a66-9da7cbd6e97a_0
6d7bc0311de5   registry.k8s.io/pause:3.9             "/pause"                 4 minutes ago   Up 4 minutes             k8s_POD_coredns-5dd5756b68-b9gm9_kube-system_9dc4b9d6-ce8f-4715-8a66-9da7cbd6e97a_0
0d9a4fd733f9   83f6cc407eed                          "/usr/local/bin/kube…"   4 minutes ago   Up 4 minutes             k8s_kube-proxy_kube-proxy-8xbn7_kube-system_da68458c-a369-46c4-a64a-40ec48ee7515_0
2e58e00c426d   registry.k8s.io/pause:3.9             "/pause"                 4 minutes ago   Up 4 minutes             k8s_POD_kube-proxy-8xbn7_kube-system_da68458c-a369-46c4-a64a-40ec48ee7515_0
4b726f2d4116   registry.k8s.io/pause:3.9             "/pause"                 4 minutes ago   Up 4 minutes             k8s_POD_storage-provisioner_kube-system_ba7c0ef4-36c1-42a5-9fe0-5964cf9a447a_0
1b818d739c3b   d058aa5ab969                          "kube-controller-man…"   5 minutes ago   Up 5 minutes             k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_50fff44a7ec6d278bc69a88fb5e5ffb3_0
3d9a33f78509   e3db313c6dbc                          "kube-scheduler --au…"   5 minutes ago   Up 5 minutes             k8s_kube-scheduler_kube-scheduler-minikube_kube-system_07d7d29a0bbc0cb1afbf9aa7d7199363_0
6aee4bcc4dac   7fe0e6f37db3                          "kube-apiserver --ad…"   5 minutes ago   Up 5 minutes             k8s_kube-apiserver_kube-apiserver-minikube_kube-system_aea4614c7753758bf033c8a972477ded_0
ee003044a13a   73deb9a3f702                          "etcd --advertise-cl…"   5 minutes ago   Up 5 minutes             k8s_etcd_etcd-minikube_kube-system_9aac5b5c8815def09a2ef9e37b89da55_0
a52733a5b8e7   registry.k8s.io/pause:3.9             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_kube-scheduler-minikube_kube-system_07d7d29a0bbc0cb1afbf9aa7d7199363_0
00c136b8849b   registry.k8s.io/pause:3.9             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_kube-controller-manager-minikube_kube-system_50fff44a7ec6d278bc69a88fb5e5ffb3_0
627da05b53ed   registry.k8s.io/pause:3.9             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_kube-apiserver-minikube_kube-system_aea4614c7753758bf033c8a972477ded_0
cca26e9932b4   registry.k8s.io/pause:3.9             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_etcd-minikube_kube-system_9aac5b5c8815def09a2ef9e37b89da55_0
```

**After updating auto-pause image and reverting https://github.com/kubernetes/minikube/pull/17070**
```
$ minikube start

$ minikube addons enable auto-pause

# kubectl command works before pods pause
$ kubectl get pods -A
NAMESPACE     NAME                                READY   STATUS    RESTARTS      AGE
auto-pause    auto-pause-proxy-7ff85b7ccd-n57cl   1/1     Running   0             30s
auto-pause    env-inject-54f7c5c846-mlzm8         1/1     Running   0             30s
kube-system   coredns-5dd5756b68-xwzsj            1/1     Running   0             94s
kube-system   etcd-minikube                       1/1     Running   0             108s
kube-system   kube-apiserver-minikube             1/1     Running   0             110s
kube-system   kube-controller-manager-minikube    1/1     Running   0             109s
kube-system   kube-proxy-vp4bf                    1/1     Running   0             95s
kube-system   kube-scheduler-minikube             1/1     Running   0             108s
kube-system   storage-provisioner                 1/1     Running   1 (64s ago)   107s

# pods now pause
$ minikube ssh -- docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED              STATUS                  PORTS     NAMES
9057137cc70a   haproxy                               "docker-entrypoint.s…"   About a minute ago   Up About a minute                 k8s_auto-pause_auto-pause-proxy-7ff85b7ccd-n57cl_auto-pause_43f117ab-07cc-46ad-bb36-552bfe2c4b4c_0
5e1fcff2c437   gcr.io/k8s-minikube/auto-pause-hook   "/auto-pause-hook -t…"   About a minute ago   Up About a minute                 k8s_webhook_env-inject-54f7c5c846-mlzm8_auto-pause_56ce262a-66b9-4c83-bcd8-04293565cae4_0
841866e62e0b   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                      k8s_POD_env-inject-54f7c5c846-mlzm8_auto-pause_56ce262a-66b9-4c83-bcd8-04293565cae4_0
8ddce79ec2fb   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                      k8s_POD_auto-pause-proxy-7ff85b7ccd-n57cl_auto-pause_43f117ab-07cc-46ad-bb36-552bfe2c4b4c_0
98b89a8b7ea9   6e38f40d628d                          "/storage-provisioner"   2 minutes ago        Up 2 minutes (Paused)             k8s_storage-provisioner_storage-provisioner_kube-system_e5de9255-f33f-4d6c-bf72-4808f4e828bb_1
585925b5f240   ead0a4a53df8                          "/coredns -conf /etc…"   3 minutes ago        Up 3 minutes (Paused)             k8s_coredns_coredns-5dd5756b68-xwzsj_kube-system_bd6e5ea4-addc-4fba-9b93-f00cae72252e_0
d1646c57f29b   registry.k8s.io/pause:3.9             "/pause"                 3 minutes ago        Up 3 minutes (Paused)             k8s_POD_coredns-5dd5756b68-xwzsj_kube-system_bd6e5ea4-addc-4fba-9b93-f00cae72252e_0
7604e383b585   83f6cc407eed                          "/usr/local/bin/kube…"   3 minutes ago        Up 3 minutes (Paused)             k8s_kube-proxy_kube-proxy-vp4bf_kube-system_5506bff2-a687-4ba3-93e6-4a6bd73920a6_0
f1b265367b12   registry.k8s.io/pause:3.9             "/pause"                 3 minutes ago        Up 3 minutes (Paused)             k8s_POD_kube-proxy-vp4bf_kube-system_5506bff2-a687-4ba3-93e6-4a6bd73920a6_0
fde6777fb737   registry.k8s.io/pause:3.9             "/pause"                 3 minutes ago        Up 3 minutes (Paused)             k8s_POD_storage-provisioner_kube-system_e5de9255-f33f-4d6c-bf72-4808f4e828bb_0
bca11dec7c97   d058aa5ab969                          "kube-controller-man…"   3 minutes ago        Up 3 minutes (Paused)             k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_50fff44a7ec6d278bc69a88fb5e5ffb3_0
f0569bdaf8b6   e3db313c6dbc                          "kube-scheduler --au…"   3 minutes ago        Up 3 minutes (Paused)             k8s_kube-scheduler_kube-scheduler-minikube_kube-system_07d7d29a0bbc0cb1afbf9aa7d7199363_0
3522253dbe40   73deb9a3f702                          "etcd --advertise-cl…"   3 minutes ago        Up 3 minutes (Paused)             k8s_etcd_etcd-minikube_kube-system_9aac5b5c8815def09a2ef9e37b89da55_0
dac6e843e2af   7fe0e6f37db3                          "kube-apiserver --ad…"   3 minutes ago        Up 3 minutes (Paused)             k8s_kube-apiserver_kube-apiserver-minikube_kube-system_aea4614c7753758bf033c8a972477ded_0
a814df62f676   registry.k8s.io/pause:3.9             "/pause"                 3 minutes ago        Up 3 minutes (Paused)             k8s_POD_kube-controller-manager-minikube_kube-system_50fff44a7ec6d278bc69a88fb5e5ffb3_0
7557b54567dc   registry.k8s.io/pause:3.9             "/pause"                 3 minutes ago        Up 3 minutes (Paused)             k8s_POD_kube-apiserver-minikube_kube-system_aea4614c7753758bf033c8a972477ded_0
820703ee6d9c   registry.k8s.io/pause:3.9             "/pause"                 3 minutes ago        Up 3 minutes (Paused)             k8s_POD_etcd-minikube_kube-system_9aac5b5c8815def09a2ef9e37b89da55_0
79f32f8a9fb2   registry.k8s.io/pause:3.9             "/pause"                 3 minutes ago        Up 3 minutes (Paused)             k8s_POD_kube-scheduler-minikube_kube-system_07d7d29a0bbc0cb1afbf9aa7d7199363_0

# kubectl commands fail after pods pause
$ kubectl get pods -A
Unable to connect to the server: EOF
```

**After updating auto-pause image and reverting https://github.com/kubernetes/minikube/pull/17070 & https://github.com/kubernetes/minikube/pull/11909**
```
$ minikube start

$ minikube addons enable auto-pause

# wait for pods to pause
$ minikube ssh -- docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED              STATUS                       PORTS     NAMES
58356bd2fa40   haproxy                               "docker-entrypoint.s…"   About a minute ago   Up About a minute                      k8s_auto-pause_auto-pause-proxy-7ff85b7ccd-lqs49_auto-pause_4a617e82-39d3-4795-a74c-4186d61cf612_0
b5f56391234c   gcr.io/k8s-minikube/auto-pause-hook   "/auto-pause-hook -t…"   About a minute ago   Up About a minute                      k8s_webhook_env-inject-54f7c5c846-85kn2_auto-pause_cba2568e-94f8-4cf0-beaf-02c3971028d2_0
8986c92c1d60   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute                      k8s_POD_env-inject-54f7c5c846-85kn2_auto-pause_cba2568e-94f8-4cf0-beaf-02c3971028d2_0
4e2b8f5fecdc   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute                      k8s_POD_auto-pause-proxy-7ff85b7ccd-lqs49_auto-pause_4a617e82-39d3-4795-a74c-4186d61cf612_0
801aff141efc   6e38f40d628d                          "/storage-provisioner"   About a minute ago   Up About a minute (Paused)             k8s_storage-provisioner_storage-provisioner_kube-system_4dfb8171-2f07-4b90-b89e-c1c273469279_0
d450bb75db95   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute (Paused)             k8s_POD_storage-provisioner_kube-system_4dfb8171-2f07-4b90-b89e-c1c273469279_0
b83a00c98ae5   ead0a4a53df8                          "/coredns -conf /etc…"   About a minute ago   Up About a minute (Paused)             k8s_coredns_coredns-5dd5756b68-fjpb5_kube-system_e5cc620a-9500-4f29-98a3-0d3fc12469ec_0
063d13bda46c   83f6cc407eed                          "/usr/local/bin/kube…"   About a minute ago   Up About a minute (Paused)             k8s_kube-proxy_kube-proxy-jd65x_kube-system_6b489829-bca7-427b-ad06-ef25dc76ce90_0
01c42046954a   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute (Paused)             k8s_POD_coredns-5dd5756b68-fjpb5_kube-system_e5cc620a-9500-4f29-98a3-0d3fc12469ec_0
89c40b61f80e   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute (Paused)             k8s_POD_kube-proxy-jd65x_kube-system_6b489829-bca7-427b-ad06-ef25dc76ce90_0
85d7ea562ec5   d058aa5ab969                          "kube-controller-man…"   About a minute ago   Up About a minute (Paused)             k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_50fff44a7ec6d278bc69a88fb5e5ffb3_0
c6d3defb4517   e3db313c6dbc                          "kube-scheduler --au…"   About a minute ago   Up About a minute (Paused)             k8s_kube-scheduler_kube-scheduler-minikube_kube-system_07d7d29a0bbc0cb1afbf9aa7d7199363_0
81dc46894749   7fe0e6f37db3                          "kube-apiserver --ad…"   About a minute ago   Up About a minute (Paused)             k8s_kube-apiserver_kube-apiserver-minikube_kube-system_aea4614c7753758bf033c8a972477ded_0
ad5ba3631ad0   73deb9a3f702                          "etcd --advertise-cl…"   About a minute ago   Up About a minute (Paused)             k8s_etcd_etcd-minikube_kube-system_9aac5b5c8815def09a2ef9e37b89da55_0
2486c85ba54a   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute (Paused)             k8s_POD_kube-scheduler-minikube_kube-system_07d7d29a0bbc0cb1afbf9aa7d7199363_0
da4aa2835406   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute (Paused)             k8s_POD_kube-controller-manager-minikube_kube-system_50fff44a7ec6d278bc69a88fb5e5ffb3_0
f3ee2c57e82e   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute (Paused)             k8s_POD_kube-apiserver-minikube_kube-system_aea4614c7753758bf033c8a972477ded_0
dce98d83b9a8   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute (Paused)             k8s_POD_etcd-minikube_kube-system_9aac5b5c8815def09a2ef9e37b89da55_0

# execute kubectl command to unpause the pods
$ kubectl get pods -A
NAMESPACE     NAME                                READY   STATUS    RESTARTS   AGE
auto-pause    auto-pause-proxy-7ff85b7ccd-lqs49   1/1     Running   0          82s
auto-pause    env-inject-54f7c5c846-85kn2         1/1     Running   0          82s
kube-system   coredns-5dd5756b68-fjpb5            1/1     Running   0          115s
kube-system   etcd-minikube                       1/1     Running   0          2m7s
kube-system   kube-apiserver-minikube             1/1     Running   0          2m7s
kube-system   kube-controller-manager-minikube    1/1     Running   0          2m7s
kube-system   kube-proxy-jd65x                    1/1     Running   0          115s
kube-system   kube-scheduler-minikube             1/1     Running   0          2m7s
kube-system   storage-provisioner                 1/1     Running   0          2m6s

# pods are unpaused
$ minikube ssh -- docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED              STATUS              PORTS     NAMES
58356bd2fa40   haproxy                               "docker-entrypoint.s…"   About a minute ago   Up About a minute             k8s_auto-pause_auto-pause-proxy-7ff85b7ccd-lqs49_auto-pause_4a617e82-39d3-4795-a74c-4186d61cf612_0
b5f56391234c   gcr.io/k8s-minikube/auto-pause-hook   "/auto-pause-hook -t…"   About a minute ago   Up About a minute             k8s_webhook_env-inject-54f7c5c846-85kn2_auto-pause_cba2568e-94f8-4cf0-beaf-02c3971028d2_0
8986c92c1d60   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute             k8s_POD_env-inject-54f7c5c846-85kn2_auto-pause_cba2568e-94f8-4cf0-beaf-02c3971028d2_0
4e2b8f5fecdc   registry.k8s.io/pause:3.9             "/pause"                 About a minute ago   Up About a minute             k8s_POD_auto-pause-proxy-7ff85b7ccd-lqs49_auto-pause_4a617e82-39d3-4795-a74c-4186d61cf612_0
801aff141efc   6e38f40d628d                          "/storage-provisioner"   2 minutes ago        Up 2 minutes                  k8s_storage-provisioner_storage-provisioner_kube-system_4dfb8171-2f07-4b90-b89e-c1c273469279_0
d450bb75db95   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_storage-provisioner_kube-system_4dfb8171-2f07-4b90-b89e-c1c273469279_0
b83a00c98ae5   ead0a4a53df8                          "/coredns -conf /etc…"   2 minutes ago        Up 2 minutes                  k8s_coredns_coredns-5dd5756b68-fjpb5_kube-system_e5cc620a-9500-4f29-98a3-0d3fc12469ec_0
063d13bda46c   83f6cc407eed                          "/usr/local/bin/kube…"   2 minutes ago        Up 2 minutes                  k8s_kube-proxy_kube-proxy-jd65x_kube-system_6b489829-bca7-427b-ad06-ef25dc76ce90_0
01c42046954a   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_coredns-5dd5756b68-fjpb5_kube-system_e5cc620a-9500-4f29-98a3-0d3fc12469ec_0
89c40b61f80e   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_kube-proxy-jd65x_kube-system_6b489829-bca7-427b-ad06-ef25dc76ce90_0
85d7ea562ec5   d058aa5ab969                          "kube-controller-man…"   2 minutes ago        Up 2 minutes                  k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_50fff44a7ec6d278bc69a88fb5e5ffb3_0
c6d3defb4517   e3db313c6dbc                          "kube-scheduler --au…"   2 minutes ago        Up 2 minutes                  k8s_kube-scheduler_kube-scheduler-minikube_kube-system_07d7d29a0bbc0cb1afbf9aa7d7199363_0
81dc46894749   7fe0e6f37db3                          "kube-apiserver --ad…"   2 minutes ago        Up 2 minutes                  k8s_kube-apiserver_kube-apiserver-minikube_kube-system_aea4614c7753758bf033c8a972477ded_0
ad5ba3631ad0   73deb9a3f702                          "etcd --advertise-cl…"   2 minutes ago        Up 2 minutes                  k8s_etcd_etcd-minikube_kube-system_9aac5b5c8815def09a2ef9e37b89da55_0
2486c85ba54a   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_kube-scheduler-minikube_kube-system_07d7d29a0bbc0cb1afbf9aa7d7199363_0
da4aa2835406   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_kube-controller-manager-minikube_kube-system_50fff44a7ec6d278bc69a88fb5e5ffb3_0
f3ee2c57e82e   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_kube-apiserver-minikube_kube-system_aea4614c7753758bf033c8a972477ded_0
dce98d83b9a8   registry.k8s.io/pause:3.9             "/pause"                 2 minutes ago        Up 2 minutes                  k8s_POD_etcd-minikube_kube-system_9aac5b5c8815def09a2ef9e37b89da55_0
```

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-buikd-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
After unpausing the pods `kubectl` commands are hanging, investigating

**Comment by spowelljr** [comment]
ok-to-build-image

**Review by medyagh — COMMENTED** [review]
really good deep investigations ! thank you for such a great deep curiosity into the code ! Salute !

**Review by medyagh — APPROVED** [review]

**Comment by spowelljr** [comment]
ok-to-build-image

**Pull request merged**
