### PR TITLE
Upgrade Buildroot to 2021.02 LTS with Linux 4.19

### LINKED ISSUE #11810: KVM: Cilium CNI not working with buildroot 2021.02 systemd
After https://github.com/kubernetes/minikube/pull/11688/ was merged, we noticed integration test failures for Cilium CNI.
All test setups with KVM driver had the same error - https://storage.googleapis.com/minikube-builds/logs/11791/b8ae8cd/KVM_Linux.html#fail_TestNetworkPlugins%2fgroup%2fcilium%2fDNS

```
ilyaz@myhost --- g/minikube ‹buildroot-2021.02› » out/minikube start -p test --driver=kvm --cni=cilium                                                                                                                                            130 ↵
* [test] minikube v1.21.0 on Ubuntu 21.04
* Using the kvm2 driver based on user configuration
* Starting control plane node test in cluster test
* Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.20.7 on Docker 20.10.6 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Configuring Cilium (Container Networking Interface) ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: storage-provisioner, default-storageclass

! /home/ilyaz/google-cloud-sdk/bin/kubectl is version 1.17.17-dispatcher, which may have incompatibilites with Kubernetes 1.20.7.
  - Want kubectl v1.20.7? Try 'minikube kubectl -- get pods -A'
* Done! kubectl is now configured to use "test" cluster and "default" namespace by default

ilyaz@myhost --- g/minikube ‹buildroot-2021.02› » kubectl  --context test  replace --force -f test/integration/testdata/netcat-deployment.yaml
deployment.apps/netcat replaced
service/netcat replaced

ilyaz@myhost --- g/minikube ‹buildroot-2021.02› » kubectl --context test exec -it deploy/netcat -- /bin/sh                                                                                                                                          1 ↵
/ # nslookup google.com
^C
/ # ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes

^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 0 packets received, 100% packet loss


/ # uname -a
Linux netcat-66fbc655d5-phln5 4.19.194 #1 SMP Fri Jun 25 23:10:48 UTC 2021 x86_64 Linux


/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
19: eth0@if20: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether da:a8:6b:5f:bf:65 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.244/32 scope global eth0
       valid_lft forever preferred_lft forever
```
ISO containing the issue: https://storage.googleapis.com/minikube-builds/iso/11688/minikube-v1.21.0-1624660371-11688.iso
Revert PR: https://github.com/kubernetes/minikube/pull/11799

### PR DESCRIPTION
**Pull request by afbjorklund**
Upgrade kernel minor version to distribution default

Add patch to allow building go inside minikube mod

Add sysctl override to revert systemd 245+ rp_filter

BR2_PACKAGE_LUAJIT
    Make sure to build lua required for sysdig

BR2_PACKAGE_LZ4_PROGS
    Make sure to build lz4 required for preload

BR2_PACKAGE_UTIL_LINUX_BINARIES
    Make sure to build lsblk required for automount

----

Squashed version of PR  #11688, but upgraded from 2021.02.3 to 2021.02.4 and with systemd patch for cilium

Go compiler upgraded from go1.15.13 to go1.15.15, rebased back-port to be able to build in minikube module

For #11652

Closes  #11810

### CODE REVIEW

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

Built OK here.

**Comment by afbjorklund** [comment]
```
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ uname -a
Linux minikube 4.19.202 #1 SMP Sat Aug 14 21:54:23 CEST 2021 x86_64 GNU/Linux
$ grep PRETTY /etc/os-release 
PRETTY_NAME="Buildroot 2021.02.4"
```

**Comment by afbjorklund** [comment]
`No such object: minikube-builds/logs/12268/iso-81/iso_build.txt`

**Comment by medyagh** [comment]
ok-to-test

**Comment by medyagh** [comment]
the failures are not related to this PR

**Pull request merged**
