### PR TITLE
doc: update minikube quick start in macos

### PR DESCRIPTION
**Pull request by AlphaWong**
LoadBalancer issue in macOS for MiniKube

# reference
https://github.com/kubernetes/minikube/issues/7344#issuecomment-688179776

### CODE REVIEW

**Review by tstromberg — CHANGES_REQUESTED** [review]
This doesn't seem right to me - LoadBalancer should work on macOS with all drivers.

**Comment by AlphaWong** [comment]
> This doesn't seem right to me - LoadBalancer should work on macOS with all drivers.

I get a wanting in default docker driver 

```
Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
```

People inside https://github.com/kubernetes/minikube/issues/7344#issuecomment-688179776 also share the same experience. It seems not working in current version.

Which version u testing with?

**Review by medyagh — CHANGES_REQUESTED** [review]
I think you meant to add this to docker driver docs, in MacOS.

https://minikube.sigs.k8s.io/docs/drivers/docker/#known-issues

**Comment by AlphaWong** [comment]
> I think you meant to add this to docker driver docs, in MacOS.
> 
> https://minikube.sigs.k8s.io/docs/drivers/docker/#known-issues

I agree that we should put it at other page but end up the quick start from https://minikube.sigs.k8s.io/docs/start/ to https://minikube.sigs.k8s.io/docs/drivers/ is not quick enough also it prefers `docker` driver at MacOS. 

Seems more people like me as a new joiner we would like to get our local workplace up and run first. I believe some amendment or hints is required to help new user.

The real case is that I would like to setup a deployment with nginx ingress with my local Minikube for testing and I find the `localBalance` stuck at pending. The resolution needs to destroy the whole Minikube vm and reinstall is not that ideal in my concern.

Therefore, hints the user about the `loadBalance` issue or vm type or know issue can save a lot of time as it is not all the people know the history or know issue or read all the thread about Minikube. As Minikube is a good project and almost is a good learning playground for anyone I hold my opinion for adding any hints or remark on it.

Moreover, after google introduce https://github.com/GoogleContainerTools/skaffold for ensure the local and remote working environment alignment, more and more people install Minikube in their local. It is ready better to have some hints about it.

see the reference below and the screenshot.

# screenshot


# reference
https://github.com/kubernetes/minikube/issues/7344#issuecomment-727538130

**Review by afbjorklund — CHANGES_REQUESTED** [review]
This should be more general, that you still need to use --vm=true if you want working network...

The docker driver is supposed to be able to limp along using `minikube tunnel` and such though.

**Comment by priyawadhwa** [comment]
Hey @AlphaWong are you still working on this? I agree that `--vm=true` would be better as it is more generic.

**Comment by priyawadhwa** [comment]
Hey @AlphaWong this PR has been quiet for a few months now, so I'm going to close it for now. Feel free to reopen whenever you have a chance to take a look!

**Pull request closed without merging**
