### PR TITLE
Updating documentation to move minikube and kubectl to executables dir

### PR DESCRIPTION
**Pull request by kailashkhalasi**

### CODE REVIEW

**Comment by dlorenc** [comment]
Will you be able to sign the CLA?

**Comment by kailashkhalasi** [comment]
Hello,

I have just signed the CLA.

Thanks,
Kailash

**Comment by dlorenc** [comment]
The CLA bot hasn't updated though, are you sure you signed it with the same email the commit came from?

**Comment by dlorenc** [comment]
Ping @kailashkhalasi can you check the CLA bot?

**Comment by dlorenc** [comment]
I'm going to close this. Please reopen if you can get the CLA bot working.

**Pull request closed without merging**
