### PR TITLE
cmd: minikube: print newlines for service not ready

### PR DESCRIPTION
**Pull request by philips**
No newlines were printed before which made it look weird.

### CODE REVIEW

**Comment by r2d4** [comment]
@minikube-bot add to whitelist

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by dlorenc** [comment]
@minikube-bot add to whitelist

**Comment by r2d4** [comment]
LGTM thanks!

**Pull request merged**
