### PR TITLE
Fix typo in github actions CI tutorial

### PR DESCRIPTION
**Pull request by ollipa**
Fix a small typo in github actions CI tutorial :nerd_face:

### CODE REVIEW

**Comment by ollipa** [comment]
I signed it

**Comment by medyagh** [comment]
Needs cla

**Comment by priyawadhwa** [comment]
Hey @ollipa -- looks like there is still a CLA issue (I checked for it manually but we haven't received it). Could you try going through the instructions to sign it again?

**Comment by ollipa** [comment]
I signed it

**Pull request merged**
