### PR TITLE
WIP: Addons gcp-auth: Refresh pull secret every hour

### PR DESCRIPTION
**Pull request by spowelljr**
Related to https://github.com/GoogleContainerTools/gcp-auth-webhook/issues/105

### CODE REVIEW

**Comment by spowelljr** [comment]
Will reopen once upstream PR is merged

https://github.com/GoogleContainerTools/gcp-auth-webhook/pull/110

**Comment by HarryWeppner** [comment]
@spowelljr, can this PR now be re-opened or is there another, related PR that updated minikube already? Thanks!

**Comment by spowelljr** [comment]
@HarryWeppner The change is merged with https://github.com/kubernetes/minikube/pull/18222

**Pull request closed without merging**
