### PR TITLE
Update Kubernetes default version to v1.15.0

### PR DESCRIPTION
**Pull request by tstromberg**
Also, refactor the kubeadm tests to decrease toil when new releases are made. This happened to also mean that testdata for v1.11.x was added as well.

### CODE REVIEW

**Comment by tstromberg** [comment]
Feel free to merge if test results look good, as I'll be mostly out of reach. Thanks!

**Comment by tstromberg** [comment]
Still needs some test data updates.

**Comment by medyagh** [comment]
> Still needs some test data updates.

seems like the unit tests failed in travis:
```
            ---
            apiVersion: kubeadm.k8s.io/v1beta1
            kind: ClusterConfiguration
            imageRepository: test/repo
            apiServer:
              extraArgs:
                enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
            certificatesDir: /var/lib/minikube/certs/
            clusterName: kubernetes
            controlPlaneEndpoint: localhost:8443
            dns:
              type: CoreDNS
            etcd:
              local:
                dataDir: /data/minikube
            kubernetesVersion: v1.14.0
            networking:
              dnsDomain: cluster.local
              podSubnet: ""
              serviceSubnet: 10.96.0.0/12
            ---
            apiVersion: kubelet.config.k8s.io/v1beta1
            kind: KubeletConfiguration
            imageGCHighThresholdPercent: 100
            evictionHard:
              nodefs.available: "0%"
              nodefs.inodesFree: "0%"
              imagefs.available: "0%"
FAIL
coverage: 33.1% of statements
FAIL	k8s.io/minikube/pkg/minikube/bootstrapper/kubeadm	0.052s
```

**Comment by tstromberg** [comment]
@minikube-bot ok to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
hyperkit failure is unrelated CI issue with the new Mac being brought up.

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
The none test failure is a flake.

**Pull request merged**
