### PR TITLE
Revert "Ensure that data block device is ready before formatting"

### PR DESCRIPTION
**Pull request by aaron-prindle**
This reverts commit c769ef46ed821b2e3c6998b7670fad0a0fc24b75.

### CODE REVIEW

**Comment by dlorenc** [comment]
cc @dalehamel sorry Dale, this was causing some trouble with startup on 4 core machines. There's some kind of race condition we're trying to track down, but for now we'll have to roll this back so we can get a good release out.

**Comment by dalehamel** [comment]
Can you post some logs for the minikube-automount service that you think
could be involved in the race, so I can take a look?

**Comment by dlorenc** [comment]
Here's a diff of the automount logs from two runs with the same config - one that failed and one that didnt:

https://gist.github.com/r2d4/0eeb02dc81f39d715278eca6d15a902f

One interesting thing to note is that the failing run took approximately 30m and the passing run took approximately 50s.

**Comment by dalehamel** [comment]
@dlorenc i don't see anything in the failing run that seems to point to the code from the PR in question.

If you sum up all of the "wait_for" conditions, there's no way that it could add **that** much runtime. 

I think there must be something hanging waiting for input or something to that effect.

Without access to the raw logs or more details on the failure though, I'm afraid I can't say for certain :/

With regards to getting the PR in question un-reverted (after the release) what approach should I take? Un-revert it and try and reduce/simplify the changes?

**Comment by dlorenc** [comment]
Yeah, we'll help get it back in. We've only been able to reproduce this with the PR, and with --cpus=4. Without the PR, and without the cpus=4 we don't see this. 

We'll probably need to recreate your PR to roll this forward with a bunch more logging and timing information in the automount logs to figure out what's going on.

**Comment by dalehamel** [comment]
@dlorenc looking at the diff a little closer, I realized that the code is actually clearly **making it past** the changes that I made (IE - it as actually *mounting* the disks that have been formatted, see https://gist.github.com/r2d4/0eeb02dc81f39d715278eca6d15a902f#file-automount-diff-L64) - if it has gotten that far I don't see how the changes I introduced to try and avoid the race condition could be responsible for this new 4 core failure, as the control flow outside of the branch that I made the changes on should remain untouched.

Granted, I understand the approach of doing the selective reverting in order to eliminate variables, however, my opinion is that this is probably a red herring.

**Comment by dalehamel** [comment]
> We'll probably need to recreate your PR to roll this forward with a bunch more logging and timing information in the automount logs to figure out what's going on.

Yeah, this would be helpful for sure.

We could see if we can get better results by just leaning on the `wait_for` function for things that are racey, not exactly getting rid of the race condition but hopefully dodging it, and drop the module rebinding all together, as that's the only thing that I could see having unintended consequences here.

**Comment by dlorenc** [comment]
I have a couple other log files on my workstation that I can attach tomorrow. It's definitely strange, the mounts are getting created, incorrectly.

This doesn't manifest until you try to run a docker image, we end up getting errors from the docker daemon during volume creation like:
`operation not supported`

and the `docker info` output shows that the underlying fs for the docker graph dir is a ramfs, not extf.

**Comment by dalehamel** [comment]
> and the docker info output shows that the underlying fs for the docker graph dir is a ramfs, not extf.

That's exactly the problem I was trying to solve^ so if that's still happening, this PR didn't do what was intended anyways.

:+1: to revert, hopefully we can figure out a better solution to solving this race. I suspect just leaning heavily on the `wait_for` function and not doing any unbinding/rebinding should prove fruitful.

**Comment by dlorenc** [comment]
> That's exactly the problem I was trying to solve^ so if that's still happening, this PR didn't do what was intended anyways.
> 
> 👍 to revert, hopefully we can figure out a better solution to solving this race. I suspect just leaning heavily on the wait_for function and not doing any unbinding/rebinding should prove fruitful.

Ah whoops :) I was on vacation and missed most of the discussion on the initial PR.

**Pull request merged**
