### PR TITLE
add autobuild and push for ISO

### LINKED ISSUE #10571: automate ISO build/push in PR
simmilar to ok-to-build-image

there should be ok-to-build-iso

### PR DESCRIPTION
**Pull request by sharifelgamal**
Closes #10571

### CODE REVIEW

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Review by medyagh — CHANGES_REQUESTED** [review]
lets fix github action yamls to add time out or run download only before

**Review by medyagh — APPROVED** [review]

**Pull request merged**
