### PR TITLE
Add CRI-O to TestStartStop

### PR DESCRIPTION
**Pull request by tstromberg**
This helps us from accidentally breaking CRI-O support in future PR's.

This PR does fall short of running *all* tests in CRI-O, but that will have to wait for the Prow migration where we can run more advanced test matrixes.

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by afbjorklund** [comment]
LGTM, possibly add `--network-plugin=cni` ?

**Comment by afbjorklund** [comment]
The documentation even says:

```shell
$ minikube start \
    --network-plugin=cni \
    --enable-default-cni \
    --container-runtime=cri-o
```
https://github.com/kubernetes/minikube/blob/master/docs/alternative_runtimes.md#using-cri-o

So should probably use the exact same parameters, when testing ?

i.e. `--enable-default-cni` too

**Comment by tstromberg** [comment]
> The documentation even says:
> 
> ```shell
> $ minikube start \
>     --network-plugin=cni \
>     --enable-default-cni \
>     --container-runtime=cri-o
> ```
> 
> https://github.com/kubernetes/minikube/blob/master/docs/alternative_runtimes.md#using-cri-o
> 
> So should probably use the exact same parameters, when testing ?
> 
> i.e. `--enable-default-cni` too

I shouldn't have to look at documentation to select a container runtime - our defaults are terrible. Opened #3567 to address.  Updated PR.

**Pull request merged**
