### PR TITLE
Fix addons list output format option

### PR DESCRIPTION
**Pull request by woodcockjosh**
Fixes option to set the output format for listing addons

### CODE REVIEW

**Comment by medyagh** [comment]
I am not familiar with what this PR is trying to solve, do we have an issue for this ?  or was it side effect of a recently merged PR ?

**Comment by woodcockjosh** [comment]
> I am not familiar with what this PR is trying to solve, do we have an issue for this ? or was it side effect of a recently merged PR ?

@medyagh Apparently this feature doesn't work at all. I didn't open an issue because it was trivial. However, there is a question about whether or not it should be implemented seeing as it doesn't work for anyone. Maybe instead we should implement a `-o json` like I did with the profile list rather than allowing user to specify a custom format.

**Comment by tstromberg** [comment]
Since this may be your first integration test addition, I thought I'd point you to some useful docs for iterating quickly on integration tests:

https://github.com/kubernetes/minikube/blob/master/test/integration/README.md

**Comment by woodcockjosh** [comment]
@tstromberg I will have time to try to add a test tomorrow

**Comment by woodcockjosh** [comment]
@medyagh this is complete

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
Thank you!

**Pull request merged**
