### PR TITLE
storageclass no longer beta #4148

### PR DESCRIPTION
**Pull request by keramiozsoy**
I changed for this pr #4148

- https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/storage-class/local/default.yaml

### CODE REVIEW

**Comment by keramiozsoy** [comment]
I signed it

**Comment by keramiozsoy** [comment]
I signed it

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
Thank you!

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Pull request merged**
