### PR TITLE
WIP: Debug flaky parallel/DryRun

### PR DESCRIPTION
**Pull request by lingsamuel**
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>

a debug PR, do not merge #9785

### CODE REVIEW

**Comment by medyagh** [comment]
@lingsamuel I wonder if you have acess to a windows machine if not I could provide you with a Windows machine on Azure for testing, if needed please ping me on Slack, I will provide u credentials for our test machine

**Comment by lingsamuel** [comment]
@medyagh Thanks! That's what I need, pinged on Slack.
(To verification: my Slack member ID is U01G6SGJQTA)

**Comment by medyagh** [comment]
@lingsamuel any finding from this finding ? Could it be we just have to skip the dry run test on windows ?

**Comment by lingsamuel** [comment]
Nothing found till now. The exit is abnormal and unstable, couldn't find any way to reproduce it stably.
And I am very sorry, recently I am not working on this, it's harder than what I thought and I am busy in real life.

**Pull request closed without merging**
