### PR TITLE
Increase number of inodes

### LINKED ISSUE #1443: More inodes needed
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Could be either, depending on view

**Minikube version** (use `minikube version`):

v0.18.0

**Environment**:
- **OS**:   Ubuntu 16.04.2 using vagrant-lxc to run inside Ubuntu 16.04.2
- **VM Driver**: kvm
- **ISO version**: v0.18.0
- **Install tools**:
- **Others**:

**What happened**:

Ran out of inodes.

```
$ df -i
Filesystem      Inodes   IUsed  IFree IUse% Mounted on
devtmpfs        245140     337 244803    1% /dev
tmpfs           256053       1 256052    1% /dev/shm
tmpfs           256053     797 255256    1% /run
tmpfs           256053      14 256039    1% /sys/fs/cgroup
tmpfs           256053      59 255994    1% /tmp
/dev/sda1      2434064 2428665   5399  100% /mnt/sda1
```

**What you expected to happen**:

Default minikube environment would have enough inodes to run a replica of a good sized production environment

**How to reproduce it** (as minimally and precisely as possible):

Build a good number of docker images.

**Anything else do we need to know**:

See https://github.com/kubernetes/minikube/issues/1380 for a better long term solution and more background information, but in the interim, just formatting the partition with more inodes could help a lot.     We could format with mkfs.ext4 -N 20000000; a better idea might be just to choose a better inode ratio, perhaps mkfs.ext4 -T news.

### PR DESCRIPTION
**Pull request by bryanlarsen**
fixes #1443

### CODE REVIEW

**Comment by aaron-prindle** [comment]
@minikube-bot ok to test

**Comment by bryanlarsen** [comment]
inodes before: 2434064
inodes after: 9732096

**Comment by aaron-prindle** [comment]
Nice!

**Comment by bryanlarsen** [comment]
I now run out of disk space before I run out of inodes, so this seems like a reasonable figure.

**Pull request merged**
