### PR TITLE
Add images and improve parsing for kubernetes 1.11 

### PR DESCRIPTION
**Pull request by mlgibbons**
Updated parsing logic to handle K8S v1.11 in same fashion as other versions

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by mlgibbons** [comment]
This change addresses some issues with the list of images which were cached for K8S v1.11.0 and which were detected during additional offline testing. An issue has been raised against kubeadm - https://github.com/kubernetes/kubeadm/issues/1198 - in relation to the incorrect images being returned for coredns and pause.

**Comment by mlgibbons** [comment]
Bug confirmed in kubeadm 1.11 and fixed in 1.12 - https://github.com/kubernetes/kubeadm/issues/1198 - see comment in issue.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by mlgibbons** [comment]
@tstromberg I'm wondering what is preventing this from being merged? What's the next step?

**Comment by mlgibbons** [comment]
@tstromberg Thanks. I see that the changes are approved but I'm unclear if the tests which are required are complete - there seem to be a lot pending. We need to upgrade to our minikube version to 0.32 to address a dashboard CVE but need this change in there hence my desire to understand when they'll be merged to master. Thanks.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Pull request merged**
