### PR TITLE
Very minor grammar corrections to aid readability

### PR DESCRIPTION
**Pull request by noah-de**
Thank you for providing this excellent documentation. These are minor readability corrections.

### CODE REVIEW

**Comment by noah-de** [comment]
I signed the CLA

**Comment by tstromberg** [comment]
Do you need any help getting the CLA signed?

**Comment by noah-de** [comment]
Yes, thank you!
I never got the email CLA email from HelloSign.
The Linux Foundation website has a FAQ about that, but the FAQ (#3) refers to a location on the webpage that doesn't appear to exist.

I sent an email to CNCF, but have not heard back.
Many thanks for any assistance that you can provide!

**Comment by noah-de** [comment]
@tstromberg
I just  got the email and signed the document!

**Comment by tstromberg** [comment]
Thank you!

**Pull request merged**
