### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by yosshy**
/hold for japanese developer's review
/assign @t-inu
/cc @atoato88 @s-kawamura-w664

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
It's good for more readable format. :smile:

**Comment by t-inu** [comment]
LGTM

**Review by s-kawamura-w664 — COMMENTED** [review]
LGTM too.

**Comment by yosshy** [comment]
@atoato88 @t-inu @s-kawamura-w664 thank you for your reviews.

/unhold
/assign @prezha
Japanese reviews finished. Please merge it.

**Review by medyagh — APPROVED** [review]

**Pull request merged**
