### PR TITLE
Fixed issue with Make failing due to wrong static-pods location

### PR DESCRIPTION
**Pull request by heckdevice**
Make failing Location was ../static-pods, should be ./static-pods

### CODE REVIEW

**Comment by heckdevice** [comment]
I signed it!

**Comment by heckdevice** [comment]
I signed it!

**Comment by heckdevice** [comment]
I signed it!

**Comment by dlorenc** [comment]
I think the issue is that there are two commits here, from different email addresses. If you squash them together you should be all set.

**Comment by heckdevice** [comment]
Raising another from main account

**Pull request closed without merging**
