### PR TITLE
Update ingress images

### LINKED ISSUE #8636: update kube-webhook-certgen image 1.2.0 -> 1.2.2 in deploy.yaml
Need to update kube-webhook-certgen image 1.2.0. -> 1.2.2 in [ingress-dp.yaml.tmpl]( https://github.com/kubernetes/minikube/blob/master/deploy/addons/ingress/ingress-dp.yaml.tmpl)
https://github.com/kubernetes/minikube/tree/master/deploy/addons/ingress

kube-webhook-certgen has been updated recently  to 1.2.2 for adding s390x support.

https://github.com/jet/kube-webhook-certgen/issues/15

https://hub.docker.com/r/jettech/kube-webhook-certgen/tags

as per steps given here :
https://kubernetes.github.io/ingress-nginx/deploy/

### PR DESCRIPTION
**Pull request by hjmodi**
fixes #8636

### CODE REVIEW

**Comment by hjmodi** [comment]
@medyagh @sid226 can one of you point me to a doc to help me understand how are add-ons tested?

**Comment by medyagh** [comment]
@hjmodi 

you can run this locally

 env TEST_ARGS="-test.run TestAddons" make integration

**Comment by hjmodi** [comment]
Integration test output
`~/minikube$ env TEST_ARGS="-test.run TestAddons" make integration
which go-bindata || GO111MODULE=off GOBIN="/home/hjmodi/go/bin" go get github.com/jteeuwen/go-bindata/...
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/TheDebianProject.DebianGNULinux_1.1.8.0_x64__76v4gfsz19hv4:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Go/bin:/mnt/c/Users/hjmod/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/hjmod/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/hjmod/go/bin:/home/hjmodi/kubernetes/third_party/etcd:/usr/local/go/bin:/home/hjmodi/go/bin" go-bindata -nomemcopy -o pkg/minikube/assets/assets.go -pkg assets deploy/addons/...
gofmt -s -w pkg/minikube/assets/assets.go
which go-bindata || GO111MODULE=off GOBIN="/home/hjmodi/go/bin" go get github.com/jteeuwen/go-bindata/...
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/TheDebianProject.DebianGNULinux_1.1.8.0_x64__76v4gfsz19hv4:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Go/bin:/mnt/c/Users/hjmod/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/hjmod/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/hjmod/go/bin:/home/hjmodi/kubernetes/third_party/etcd:/usr/local/go/bin:/home/hjmodi/go/bin" go-bindata -nomemcopy -o pkg/minikube/translate/translations.go -pkg translate translations/...
gofmt -s -w pkg/minikube/translate/translations.go
go build  -tags "container_image_ostree_stub containers_image_openpgp go_getter_nos3 go_getter_nogcs" -ldflags="-X k8s.io/minikube/pkg/version.version=v1.12.0 -X k8s.io/minikube/pkg/version.isoVersion=v1.12.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="ce6688b1ec0c36558b16224d0d0f62de88d06685"" -o out/minikube k8s.io/minikube/cmd/minikube
go test -v -test.timeout=60m ./test/integration --tags="integration container_image_ostree_stub containers_image_openpgp go_getter_nos3 go_getter_nogcs" -test.run TestAddons
Found 8 cores, limiting parallelism with --test.parallel=4
=== RUN   TestAddons
    TestAddons: addons_test.go:44: (dbg) Run:  out/minikube start -p addons-20200713155121-5179 --wait=false --memory=2600 --alsologtostderr --addons=ingress --addons=registry --addons=metrics-server --addons=helm-tiller --addons=olm
    TestAddons: addons_test.go:44: (dbg) Done: out/minikube start -p addons-20200713155121-5179 --wait=false --memory=2600 --alsologtostderr --addons=ingress --addons=registry --addons=metrics-server --addons=helm-tiller --addons=olm : (3m9.2619444s)
=== RUN   TestAddons/parallel
=== RUN   TestAddons/parallel/Registry
=== PAUSE TestAddons/parallel/Registry
=== RUN   TestAddons/parallel/Ingress
=== PAUSE TestAddons/parallel/Ingress
=== RUN   TestAddons/parallel/MetricsServer
=== PAUSE TestAddons/parallel/MetricsServer
=== RUN   TestAddons/parallel/HelmTiller
=== PAUSE TestAddons/parallel/HelmTiller
=== RUN   TestAddons/parallel/Olm
=== PAUSE TestAddons/parallel/Olm
=== CONT  TestAddons/parallel/Registry
=== CONT  TestAddons/parallel/HelmTiller
=== CONT  TestAddons/parallel/Olm
    TestAddons/parallel/Olm: addons_test.go:334: Skipping olm test till this timeout issue is solved https://github.com/operator-framework/operator-lifecycle-manager/issues/1534#issuecomment-632342257
=== CONT  TestAddons/parallel/MetricsServer
=== CONT  TestAddons/parallel/Ingress
    TestAddons/parallel/HelmTiller: addons_test.go:293: tiller-deploy stabilized in 3.3281418s
    TestAddons/parallel/Registry: addons_test.go:173: registry stabilized in 3.3271233s
    TestAddons/parallel/MetricsServer: addons_test.go:249: metrics-server stabilized in 3.3315024s
    TestAddons/parallel/Ingress: addons_test.go:100: (dbg) TestAddons/parallel/Ingress: waiting 12m0s for pods matching "app.kubernetes.io/name=ingress-nginx" in namespace "kube-system" ...
    TestAddons/parallel/MetricsServer: addons_test.go:251: (dbg) TestAddons/parallel/MetricsServer: waiting 6m0s for pods matching "k8s-app=metrics-server" in namespace "kube-system" ...
    TestAddons/parallel/HelmTiller: addons_test.go:295: (dbg) TestAddons/parallel/HelmTiller: waiting 6m0s for pods matching "app=helm" in namespace "kube-system" ...
    TestAddons/parallel/Registry: addons_test.go:175: (dbg) TestAddons/parallel/Registry: waiting 6m0s for pods matching "actual-registry=true" in namespace "kube-system" ...
    TestAddons/parallel/Ingress: helpers_test.go:332: "ingress-nginx-admission-create-h4gs7" [451bcf60-29cc-4f1b-ab2a-0f50f7f2c2e8] Succeeded: Initialized:PodCompleted / Ready:PodCompleted / ContainersReady:PodCompleted
    TestAddons/parallel/Ingress: addons_test.go:100: (dbg) TestAddons/parallel/Ingress: app.kubernetes.io/name=ingress-nginx healthy within 87.9763ms
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Run:  kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml
    TestAddons/parallel/HelmTiller: helpers_test.go:332: "tiller-deploy-78ff886c54-pc6dq" [c4bb22ff-f201-442b-8a8f-03d60aeb3917] Running
    TestAddons/parallel/MetricsServer: helpers_test.go:332: "metrics-server-7bc6d75975-gv4nc" [11150228-9fb6-4322-9eb1-6d3fd35f6249] Running
    TestAddons/parallel/Registry: helpers_test.go:332: "registry-7fc6j" [4367bb45-3291-4e9d-aa5e-61c60e344883] Running
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml: exit status 1 (1.2848605s)

        ** stderr **
                Error from server (InternalError): Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.kube-system.svc:443/extensions/v1beta1/ingresses?timeout=30s: dial tcp 10.110.178.58:443: connect: connection refused

        ** /stderr **
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Run:  kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml: exit status 1 (2.4353024s)

        ** stderr **
                Error from server (InternalError): Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.kube-system.svc:443/extensions/v1beta1/ingresses?timeout=30s: dial tcp 10.110.178.58:443: connect: connection refused

        ** /stderr **
    TestAddons/parallel/MetricsServer: addons_test.go:251: (dbg) TestAddons/parallel/MetricsServer: k8s-app=metrics-server healthy within 5.1230356s
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Run:  kubectl --context addons-20200713155121-5179 top pods -n kube-system
    TestAddons/parallel/HelmTiller: addons_test.go:295: (dbg) TestAddons/parallel/HelmTiller: app=helm healthy within 5.1231141s
    TestAddons/parallel/HelmTiller: addons_test.go:310: (dbg) Run:  kubectl --context addons-20200713155121-5179 run --rm helm-test --restart=Never --image=alpine/helm:2.16.3 -it --namespace=kube-system --serviceaccount=tiller -- version
    TestAddons/parallel/Registry: addons_test.go:175: (dbg) TestAddons/parallel/Registry: actual-registry=true healthy within 5.1628035s
    TestAddons/parallel/Registry: addons_test.go:178: (dbg) TestAddons/parallel/Registry: waiting 10m0s for pods matching "registry-proxy=true" in namespace "kube-system" ...
    TestAddons/parallel/Registry: helpers_test.go:332: "registry-proxy-shh8j" [51a926d2-c648-4367-bcf7-d5db8417dd52] Running
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 top pods -n kube-system: exit status 1 (170.9862ms)

        ** stderr **
                W0713 15:54:39.259342    5835 top_pod.go:266] Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m26.259328s
                error: Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m26.259328s

        ** /stderr **
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Run:  kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml: exit status 1 (1.4385135s)

        ** stderr **
                Error from server (InternalError): Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.kube-system.svc:443/extensions/v1beta1/ingresses?timeout=30s: dial tcp 10.110.178.58:443: connect: connection refused

        ** /stderr **
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Run:  kubectl --context addons-20200713155121-5179 top pods -n kube-system
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 top pods -n kube-system: exit status 1 (143.5422ms)

        ** stderr **
                W0713 15:54:42.897828    5879 top_pod.go:266] Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m29.8978195s
                error: Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m29.8978195s

        ** /stderr **
    TestAddons/parallel/Registry: addons_test.go:178: (dbg) TestAddons/parallel/Registry: registry-proxy=true healthy within 5.0305517s
    TestAddons/parallel/Registry: addons_test.go:183: (dbg) Run:  kubectl --context addons-20200713155121-5179 delete po -l run=registry-test --now
    TestAddons/parallel/Registry: addons_test.go:188: (dbg) Run:  kubectl --context addons-20200713155121-5179 run --rm registry-test --restart=Never --image=busybox -it -- sh -c "wget --spider -S http://registry.kube-system.svc.cluster.local"
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Run:  kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml: exit status 1 (2.0482005s)

        ** stderr **
                Error from server (InternalError): Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.kube-system.svc:443/extensions/v1beta1/ingresses?timeout=30s: dial tcp 10.110.178.58:443: connect: connection refused

        ** /stderr **
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Run:  kubectl --context addons-20200713155121-5179 top pods -n kube-system
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 top pods -n kube-system: exit status 1 (213.5813ms)

        ** stderr **
                W0713 15:54:47.272434    5935 top_pod.go:266] Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m34.2724219s
                error: Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m34.2724219s

        ** /stderr **
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Run:  kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Run:  kubectl --context addons-20200713155121-5179 top pods -n kube-system
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 top pods -n kube-system: exit status 1 (379.21ms)

        ** stderr **
                W0713 15:54:51.465364    5963 top_pod.go:266] Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m38.4653498s
                error: Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m38.4653498s

        ** /stderr **
    TestAddons/parallel/HelmTiller: addons_test.go:310: (dbg) Done: kubectl --context addons-20200713155121-5179 run --rm helm-test --restart=Never --image=alpine/helm:2.16.3 -it --namespace=kube-system --serviceaccount=tiller -- version: (12.9702485s)
    TestAddons/parallel/HelmTiller: addons_test.go:327: (dbg) Run:  out/minikube -p addons-20200713155121-5179 addons disable helm-tiller --alsologtostderr -v=1
    TestAddons/parallel/Ingress: addons_test.go:105: (dbg) Done: kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-ing.yaml: (1.596187s)
    TestAddons/parallel/Ingress: addons_test.go:119: (dbg) Run:  kubectl --context addons-20200713155121-5179 replace --force -f testdata/nginx-pod-svc.yaml
    TestAddons/parallel/Ingress: addons_test.go:124: (dbg) TestAddons/parallel/Ingress: waiting 4m0s for pods matching "run=nginx" in namespace "default" ...
    TestAddons/parallel/Ingress: helpers_test.go:332: "nginx" [c838deb3-9bb3-4a50-9af4-4330080a934f] Pending / Ready:ContainersNotReady (containers with unready status: [nginx]) / ContainersReady:ContainersNotReady (containers with unready status: [nginx])
    TestAddons/parallel/HelmTiller: addons_test.go:327: (dbg) Done: out/minikube -p addons-20200713155121-5179 addons disable helm-tiller --alsologtostderr -v=1: (2.3183727s)
    TestAddons/parallel/Registry: addons_test.go:188: (dbg) Done: kubectl --context addons-20200713155121-5179 run --rm registry-test --restart=Never --image=busybox -it -- sh -c "wget --spider -S http://registry.kube-system.svc.cluster.local": (12.7752207s)
    TestAddons/parallel/Registry: addons_test.go:198: Unable to complete rest of the test due to connectivity assumptions
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Run:  kubectl --context addons-20200713155121-5179 top pods -n kube-system
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Non-zero exit: kubectl --context addons-20200713155121-5179 top pods -n kube-system: exit status 1 (124.4336ms)

        ** stderr **
                W0713 15:54:58.242245    6035 top_pod.go:266] Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m45.2422323s
                error: Metrics not available for pod kube-system/coredns-66bff467f8-5zslr, age: 2m45.2422323s

        ** /stderr **
    TestAddons/parallel/Ingress: helpers_test.go:332: "nginx" [c838deb3-9bb3-4a50-9af4-4330080a934f] Running
    TestAddons/parallel/Ingress: addons_test.go:124: (dbg) TestAddons/parallel/Ingress: run=nginx healthy within 14.2727842s
    TestAddons/parallel/Ingress: addons_test.go:134: (dbg) Run:  out/minikube -p addons-20200713155121-5179 ssh "curl -s http://127.0.0.1/ -H 'Host: nginx.example.com'"
    TestAddons/parallel/MetricsServer: addons_test.go:257: (dbg) Run:  kubectl --context addons-20200713155121-5179 top pods -n kube-system
    TestAddons/parallel/MetricsServer: addons_test.go:275: (dbg) Run:  out/minikube -p addons-20200713155121-5179 addons disable metrics-server --alsologtostderr -v=1
    TestAddons/parallel/Ingress: addons_test.go:155: (dbg) Run:  out/minikube -p addons-20200713155121-5179 addons disable ingress --alsologtostderr -v=1
    TestAddons/parallel/Ingress: addons_test.go:155: (dbg) Done: out/minikube -p addons-20200713155121-5179 addons disable ingress --alsologtostderr -v=1: (4.397265s)
    TestAddons: addons_test.go:71: (dbg) Run:  out/minikube stop -p addons-20200713155121-5179
    TestAddons: addons_test.go:71: (dbg) Done: out/minikube stop -p addons-20200713155121-5179: (31.6157726s)
    TestAddons: addons_test.go:75: (dbg) Run:  out/minikube addons enable dashboard -p addons-20200713155121-5179
    TestAddons: addons_test.go:79: (dbg) Run:  out/minikube addons disable dashboard -p addons-20200713155121-5179
    TestAddons: helpers_test.go:170: Cleaning up "addons-20200713155121-5179" profile ...
    TestAddons: helpers_test.go:171: (dbg) Run:  out/minikube delete -p addons-20200713155121-5179
    TestAddons: helpers_test.go:171: (dbg) Done: out/minikube delete -p addons-20200713155121-5179: (4.66408s)
--- PASS: TestAddons (267.93s)
    --- PASS: TestAddons/parallel (0.00s)
        --- SKIP: TestAddons/parallel/Olm (0.00s)
        --- PASS: TestAddons/parallel/HelmTiller (23.75s)
        --- SKIP: TestAddons/parallel/Registry (26.53s)
        --- PASS: TestAddons/parallel/MetricsServer (37.65s)
        --- PASS: TestAddons/parallel/Ingress (41.66s)
PASS
Tests completed in 4m27.9320554s (result code 0)
ok      k8s.io/minikube/test/integration        268.017s`

**Comment by hjmodi** [comment]
For manual , does the following work?

```~/minikube$ out/minikube start
😄  minikube v1.12.0 on Debian 10.4
✨  Using the docker driver based on existing profile

❗  'docker' driver reported a issue that could affect the performance.
💡  Suggestion: enable overlayfs kernel module on your Linux

👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
🤦  Unable to restart cluster, will reset it: getting k8s client: client config: client config: context "minikube" does not exist
🔎  Verifying Kubernetes components...
🔎  Verifying ingress addon...
🌟  Enabled addons: default-storageclass, ingress, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

❗  /usr/local/bin/kubectl is version 1.16.6-beta.0, which may be incompatible with Kubernetes 1.18.3.
💡  You can also use 'minikube kubectl -- get pods' to invoke a matching version
hjmodi@DESKTOP-1UU3TVT:~/minikube$ kubectl get pods -n kube-system
NAME                                        READY   STATUS      RESTARTS   AGE
coredns-66bff467f8-wxrx6                    1/1     Running     0          110s
etcd-minikube                               1/1     Running     0          114s
ingress-nginx-admission-create-n8df2        0/1     Completed   0          110s
ingress-nginx-admission-patch-xlww2         0/1     Completed   0          110s
ingress-nginx-controller-69ccf5d9d8-g62tm   1/1     Running     0          110s
kube-apiserver-minikube                     1/1     Running     0          114s
kube-controller-manager-minikube            1/1     Running     0          114s
kube-proxy-fdzr2                            1/1     Running     0          110s
kube-scheduler-minikube                     1/1     Running     0          113s
storage-provisioner                         1/1     Running     0          112s
hjmodi@DESKTOP-1UU3TVT:~/minikube$ kubectl create deployment web --image=gcr.io/google-samples/hello-app:1.0
deployment.apps/web created
hjmodi@DESKTOP-1UU3TVT:~/minikube$ kubectl expose deployment web --type=NodePort --port=8080
service/web exposed
hjmodi@DESKTOP-1UU3TVT:~/minikube$ kubectl get service web
NAME   TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
web    NodePort   10.110.185.63   <none>        8080:31215/TCP   14s
hjmodi@DESKTOP-1UU3TVT:~/minikube$ minikube service web --url
-bash: minikube: command not found
hjmodi@DESKTOP-1UU3TVT:~/minikube$ /out/minikube service web --url
-bash: /out/minikube: No such file or directory
hjmodi@DESKTOP-1UU3TVT:~/minikube$ out/minikube service web --url
🏃  Starting tunnel for service web.
|-----------|------|-------------|------------------------|
| NAMESPACE | NAME | TARGET PORT |          URL           |
|-----------|------|-------------|------------------------|
| default   | web  |             | http://127.0.0.1:41107 |
|-----------|------|-------------|------------------------|
http://127.0.0.1:41107
❗  Because you are using a Docker driver on linux, the terminal needs to be open to run it.
^Z
[1]+  Stopped                 out/minikube service web --url
hjmodi@DESKTOP-1UU3TVT:~/minikube$ bg
[1]+ out/minikube service web --url &
hjmodi@DESKTOP-1UU3TVT:~/minikube$ curl http://127.0.0.1:41107
Hello, world!
Version: 1.0.0
Hostname: web-6785d44d5-h9pqv
hjmodi@DESKTOP-1UU3TVT:~/minikube$```

**Pull request merged**
