### PR TITLE
ISO: Upgrade Docker, from 20.10.6 to 20.10.8

### PR DESCRIPTION
**Pull request by afbjorklund**
https://docs.docker.com/engine/release-notes/#20108

* runc v1.0.1

* containerd v1.4.9

Squashed it together with 20.10.7, from PR #11593

### CODE REVIEW

**Comment by afbjorklund** [comment]
The test failures with the Docker driver (and KIC) are unrelated to this PR, which only changes the ISO

**Comment by medyagh** [comment]
@afbjorklund sorry needs a rebase (since other ISO PR was merged now this one is not happy)

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
I added a bug about the failing test for KVM_Linux: #12145

**Review by medyagh — APPROVED** [review]

**Pull request merged**
