### PR TITLE
Update kubernetes to v1.3.0-beta.2

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by dlorenc** [comment]
Hey,

Thanks for the update! Were any manual changes required? Could you write a quick note about how you did the update (what commands you ran)? Godep is pretty finnicky, so it might make it easier to debug later if you share how you did the update itself.

Otherwise LGTM!

**Comment by jimmidyson** [comment]
No manual changes required. To update I did the following:

* In minikube local clone, ran `godep restore` to ensure all minikube vendored deps are in GOPATH
* Change dir to $GOPATH/k8s.io/kubernetes, checkout v1.3.0-beta2
* Run `godep restore` to ensure any updated kubernetes vendored deps are in GOPATH
* Change dir back to minikube dir, run `godep save ./...`

This is a workflow that I've found works pretty well, although sometimes it's best to delete Godeps & vendor dirs & run `godep save ./...` to ensure there is a clean & repeatable set of dependencies. Have to say I'm more of a fan of glide rather than godep for vendoring but understand the reason to keep the tool aligned with kubernetes itself.

**Comment by dlorenc** [comment]
Thanks, that's basically what I've been doing. It looks like there's been some movement on switching core k8s to glide, so hopefully we switch over soon too :)

**Comment by dlorenc** [comment]
LGTM.

**Pull request merged**
