### PR TITLE
Configure /data as a persisted directory.

### LINKED ISSUE #414: Directories not persisted across reboots
I've got mongodb running on minikube but when I `minikube stop` and then `minikube start` all the data that was in mongodb is lost. I have the pod mounting a host volume located at `/data/mdb`. The same thing is happening with elasticsearch.

I am opening this issue at the request of @dlorenc on the slack channel.

### PR DESCRIPTION
**Pull request by dlorenc**
Fixes #414.

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by aaron-prindle** [comment]
LGTM

**Comment by dlorenc** [comment]
Thanks! Note that we'll need to build a new ISO to get this out.

**Comment by aaron-prindle** [comment]
Should we do a separate release for this (v0.7.2?) or should we wait for
v0.8.0 release?

**Comment by dlorenc** [comment]
0.8.0 should be fine.

**Pull request merged**
