### PR TITLE
Disable hyperv dynamic memory for hyperv driver

### PR DESCRIPTION
**Pull request by shahiddev**
Disables hyper-v dynamic memory 

Fixes issues #2331, #2326, #1766

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot OK to test

**Comment by shahiddev** [comment]
Ah, silly mistake. 
OK, let me take another look at this

**Comment by shahiddev** [comment]
I've got a PR to add support for the flag in Docker Machine merged now.
Does the vendor directly get updated on each release automatically or as part of someones PR?

**Comment by shahiddev** [comment]
@dlorenc The latest Docker Machine now has my PR merged in it (https://github.com/docker/machine/releases/tag/v0.15.0)
How do I incorporate the updates into Minikube, are the vendor deps updated routinely as part of the release process or do I need to create a PR to do this?

**Comment by tstromberg** [comment]
I just found this PR and it looks great!

Would it be possible to resolve the conflicts and merge it? I can also recreate it in a new PR, but I would rather let you keep the credit for the change. 

Personally, I strongly prefer to disable dynamic memory by default, so that it behaves the same as other VM managers supported by minikube.

**Comment by shahiddev** [comment]
Hi @tstromberg I had tried to get the Docker Machine changes I made into the minikube project but there was some uncertainty around whether they wanted to keep on using Docker Machine, hence why things went quiet. I'd have been happy to try and surface those docker machine changes if that was settled?

**Comment by tstromberg** [comment]
shahiddev@ - minikube will continue to use Docker Machine for the foreseeable future. 

If this PR still requires a change to docker/machine, you can propose it to the fork we are using:  https://github.com/machine-drivers/machine/blob/master/drivers/hyperv/hyperv.go - I'm a maintainer there and would be happy to review your change there.

Please let me know if I can help you in any way to get this merged.

**Comment by shahiddev** [comment]
I think I managed to get my docker machine changes into the final release of Docker Machine before it went into maintenance so those should be in the fork. I'll try and get this sorted over the coming days depending on how busy Kubecon EU is :)

**Comment by tstromberg** [comment]
> I think I managed to get my docker machine changes into the final release of Docker Machine before it went into maintenance so those should be in the fork. I'll try and get this sorted over the coming days depending on how busy Kubecon EU is :)

Sounds great. Enjoy Barcelona!

**Comment by tstromberg** [comment]
I happened to be looking at 
https://github.com/machine-drivers/machine/blob/master/drivers/hyperv/hyperv.go - and it seems that DisableDynamicMemory is in fact an option.

I suggest that we disable just disable by default, as dynamically sized memory won't ever play well with Kubernetes job scheduling.

**Comment by shahiddev** [comment]
I will re-open another PR as I wanted to reset my fork to the current upstream given the majority of the changes I had in the original PR weren't required.

**Comment by shahiddev** [comment]
> I happened to be looking at
> https://github.com/machine-drivers/machine/blob/master/drivers/hyperv/hyperv.go - and it seems that DisableDynamicMemory is in fact an option.
> 
> I suggest that we disable just disable by default, as dynamically sized memory won't ever play well with Kubernetes job scheduling.

As per your suggestion @tstromberg I opted to keep it simple and just set the disable hyper-v flag I expose on Docker Machine to false (rather than adding an additional command line flag).

**Pull request merged**
