### PR TITLE
Minor docs cleanup on _index.md

### PR DESCRIPTION
**Pull request by mtoothman**

### CODE REVIEW

**Comment by mtoothman** [comment]
CCLA signed

**Review by tstromberg — APPROVED** [review]
Looks good. Thank you!

**Comment by tstromberg** [comment]
Please sign the CLA so that we can merge this. Thanks!

**Comment by spowelljr** [comment]
@mtoothman Reminding about signing CLA and rebasing

**Review by emretanriverdi — APPROVED** [review]

**Comment by priyawadhwa** [comment]
Hey @mtoothman -- this PR needs two things before we can merge:

1. A rebase to resolve merge conflicts
2. You need to sign the CLA as described [here](https://github.com/kubernetes/minikube/pull/9951#issuecomment-744063222) before we can accept this PR 

Since the PR has been quiet for a few weeks now, I'm going to temporarily close it. Please reopen whenever you have a chance to address the above!

**Comment by mtoothman** [comment]
Reopening, CLA signed.

**Pull request closed without merging**
