### PR TITLE
Update kvm2.md

### PR DESCRIPTION
**Pull request by bfotland**
Suggested missing verb.

### CODE REVIEW

**Comment by medyagh** [comment]
Thanks for improving the docs

**Comment by medyagh** [comment]
@bfotland PR looks good, only needs to sign the license.

**Comment by medyagh** [comment]
@bfotland  if you sign the CLA we could merge this contribution.

**Comment by bfotland** [comment]
I signed it

**Comment by RA489** [comment]
> I signed it

/check-cla

**Pull request merged**
