### PR TITLE
Epic Docs Site Re-Organization!

### PR DESCRIPTION
**Pull request by tstromberg**
Based on discussions with other maintainers

Preview URL: https://deploy-preview-7329--kubernetes-sigs-minikube.netlify.com/

* Handbook section added, replacing "examples" and "tasks"
* Marketing frontpage removed
* Blog removed
* Reference section removed, all content promoted up a level or moved elsewhere
* Moved /docs/overview content to /docs
* Merge marketing page content (/) with /docs
* Aliases for old URL's

## Work for follow-up PR's

* Actual content improvements (this PR focuses on organizational improvements)
* Refactoring the "Getting started" pages

### CODE REVIEW

**Comment by afbjorklund** [comment]
In the screenshot, I think one of the lines sticks out a bit (as too long):

```
Creating Kubernetes in docker container with (CPUs=2) (6 available), Memory=1989MB (1989MB
 available) ...
```

versus

```
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
```

Maybe it could made shorter "Creating docker container (CPUs=2, Memory=1989MB)"

And perhaps move the available resources to separate indented lines below the first ?

---

Also, there is some weird output at the end - like it was wrapped in `time` or so ?

30.66 real  3.24 user   1.46 sys

**Comment by afbjorklund** [comment]
> and also maybe we could make the Getting Started Page less Clicks
> (make Linux Mac And windows Tabs ?)

It probably look a bit odd, if you nested tabs within tabs though ?

* Linux
  * Installation
    * Direct
    * Debian/Ubuntu (deb)
    * Fedora/Red Hat (rpm)
  * Driver Setup
    * Docker
    * KVM
    * VirtualBox
    * None (bare-metal)
    * Podman (experimental)

* macOS
  * Installation
    * Brew
    * Direct
  * Hypervisor Setup
    * Docker
    * Hyperkit
    * VirtualBox
    * Parallels
    * VMware
    * Podman (experimental)

* Windows
  * Installation
    * Direct
    * Chocolatey
  * _(missing heading???)_
    * Docker
    * Hyper-V
    * VirtualBox

**Comment by tstromberg** [comment]
> looks good, I like the word handbook !
> there are some things that we can address in follow up PRs.
> such as updating the page about supported kuberentes versions https://deploy-preview-7329--kubernetes-sigs-minikube.netlify.com/docs/handbook/config/

Correct. I noticed this and many other pages which aren't so hot right now.

> 
> and also maybe we could make the Getting Started Page less Clicks
> (make Linux Mac And windows Tabs ?)

I don't think it will work so well as tabs, but Getting Started will be a subsequent refactor.

**Comment by tstromberg** [comment]
> In the screenshot, I think one of the lines sticks out a bit (as too long):
> 
> ```
> Creating Kubernetes in docker container with (CPUs=2) (6 available), Memory=1989MB (1989MB
>  available) ...
> ```

Agreed. I'd like to see this extra long line addressed in minikube's code.

> 
> versus
> 
> ```
> 🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
> ```
> 
> Maybe it could made shorter "Creating docker container (CPUs=2, Memory=1989MB)"

Sounds great.
> 
> And perhaps move the available resources to separate indented lines below the first ?

These haven't proved very useful - and should be moved to the logs.
> 
> Also, there is some weird output at the end - like it was wrapped in `time` or so ?
> 30.66 real 3.24 user 1.46 sys

Yeah, it's the output of `time`. I can take that out.

**Pull request merged**
