### PR TITLE
Fix Markdown rendering issue on /docs/drivers/docker

### PR DESCRIPTION
**Pull request by sahansera**
Fixes: https://github.com/kubernetes/minikube/issues/13491

**This PR:**
- Fixes bad formatting on the code panel
- Fixes `--` being rendered as `-`

**Root Cause**
The extra line break caused the Markdown renderer to insert an additional `<p>` tag within the code body. This resulted in a badly formatted view.

**Before:**
Screen Shot 2022-02-02 at 10 01 36 pm

**After:**
Screen Shot 2022-02-02 at 10 02 08 pm

### CODE REVIEW

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
@sahansera thank you for the contribution, can u plz sign the CLA so we could accept this contribution ?

**Comment by sahansera** [comment]
@medyagh Thanks for the heads up! Although I signed the CLA initially I think there was a mix up between my corporate account and personal account. I have resolved it now 🙂 Cheers

**Comment by sharifelgamal** [comment]
Thank you for your contribution!

**Pull request merged**
