### PR TITLE
Add DefaultStorageClass to admission controllers

### PR DESCRIPTION
**Pull request by jimmidyson**
As per recommended admission controllers - http://kubernetes.io/docs/admin/admission-controllers/#is-there-a-recommended-set-of-plug-ins-to-use

### CODE REVIEW

**Comment by jimmidyson** [comment]
@r2d4 @dlorenc Would like this to be in localkube 1.4.0 & 1.4.1 releases if you agree - how can we do that?

**Comment by dlorenc** [comment]
1.4.1 is easy, how much do you want 1.4.0? We'd have to cut a branch off the last 1.4 commit and cherry pick this over there.

**Comment by jimmidyson** [comment]
Personally I'm not too bothered - happy to just use 1.4.1. We can wait & only do it if a user requests it perhaps?

**Comment by r2d4** [comment]
@dlorenc since master is tracking 1.4.x, we could probably just set the jenkins job to run 
minikube @ HEAD and k8s @ v1.4.0 to rebuild the 1.4 localkube

**Pull request merged**
