### PR TITLE
Update default linux config to support ftrace, for bpf tracing, fixes #8637

### LINKED ISSUE #8637: Kernel with CONFIG_FTRACE_SYSCALLS kubectl-trace
I would like the Minikube kernel to be compiled with [CONFIG_FTRACE_SYSCALLS](https://cateee.net/lkddb/web-lkddb/FTRACE_SYSCALLS.html) (basic tracer to catch the syscall entry and exit events).

This is to be able to use kubectl-trace on Minikube.
Related issue in kubectl-trace: https://github.com/iovisor/kubectl-trace/issues/120

Symptoms:
```
$ kubectl trace run minikube -e 'tracepoint:syscalls:sys_enter_open { printf("%s %s\n", comm, str(args->filename)); }'
trace 09ecf3b8-bc53-11ea-ac93-c85b763781a4 created

$ kubectl logs kubectl-trace-09ecf3b8-bc53-11ea-ac93-c85b763781a4-4m667
if your program has maps to print, send a SIGINT using Ctrl-C, if you want to interrupt the execution send SIGINT two times
ERROR: tracepoint not found: syscalls:sys_enter_open
exit status 1
```

This is a follow-up to previous efforts to make Minikube work with BPF tools in [Inspektor Gadget](https://github.com/kinvolk/inspektor-gadget/). See issue #8556 that added CONFIG_IKHEADERS.

cc @mauriciovasquezbernal @marga-kinvolk

### PR DESCRIPTION
**Pull request by dalehamel**
This should fix #8637 

My goal here is to be able to use minikube with bpftrace / bcc.

In order to do this, they need to be able to list the available filter functions.

Prior to this change, `/sys/kernel/debug/tracing/available_filter_functions` does not exist. After this change, the file exists. I have not been able to verify end-to-end that everything works yet, but this is a good start.

These changes should be safe to merge, as all of the Linux kernel tracing features must be explicitly be enabled by a user. Almost all production systems should have these flags enabled anyways, so it's quite clear that they do not harm performance on their own.

As a side note, while preparing this PR, i believe I've found evidence that the linux config has been edited directly by users, or is otherwise somehow out of sync with the machine-generated config. I created https://github.com/kubernetes/minikube/pull/9394 to remedy this.

### CODE REVIEW

**Comment by dalehamel** [comment]
Looks like bpftrace is happy after this change:

```
$ curl https://raw.githubusercontent.com/iovisor/bpftrace/master/scripts/check_kernel_features.sh | bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   859  100   859    0     0   7953      0 --:--:-- --:--:-- --:--:--  7953
All required features present!
```

**Comment by dalehamel** [comment]
ISO build on CI seems broken?

**Comment by dalehamel** [comment]
Started a draft PR #9395 to see why the ISO build is failing

**Comment by tstromberg** [comment]
LGTM.

**Pull request merged**
