### PR TITLE
Add gcrurl env var to registry-creds addon deployment and configuration

### PR DESCRIPTION
**Pull request by Teddy-Schmitz**
Hello,

This is related to issue #1253 .  It will also require the newer version of registry-creds which I'm happy to amend to this PR when a new version is cut.  I want to make sure the other changes are OK first.

This is my first time contributing to the minikube project so please let me know if I missed something I was supposed to do.

Thanks!

### CODE REVIEW

**Comment by Teddy-Schmitz** [comment]
CLA signed.

**Comment by aaron-prindle** [comment]
@minikube-bot ok to test

**Comment by aaron-prindle** [comment]
When I run this locally I seem to get an error pulling an image from gcr (hosted at https://gcr.io)  when attempting to use the default gcr-url.  When attempting the same action on the current version of minikube/registry-creds I do not get the same error.

**Comment by Teddy-Schmitz** [comment]
Hey,
I just tested this locally and was able to pull down a image on gcr.io using the default.  Did you build a new version of the registry-creds image?  The env var doesn't do anything in the 1.7 image as checking the env var was just added to master.  I'll ask the owner when he will be able to create a new release.

**Comment by aaron-prindle** [comment]
@Teddy-Schmitz do you happen to know if the image was updated?  I think that 1.7 is still the latest pushed image.

**Comment by aaron-prindle** [comment]
Thanks for this!  A new image was pushed and we recently updated the image to 1.8.  Merging.

**Pull request merged**
