### PR TITLE
Update entrypoint and kindnetd

### PR DESCRIPTION
**Pull request by spowelljr**

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by klaases** [comment]
As a part of the PR audit procedure, I worked with @spowelljr to help review this code.

- Copy in the entry point file from kind.
- Copy in latest CNI (container network interface) version into minikube.
- minikube options: kind, celium, planel, weave

kind's kindnetd is a container image, for which are updating the version.

kicbase version bumped to coordinate with the kind entrypoint version.

**Review by klaases — APPROVED** [review]

**Pull request merged**
