### PR TITLE
containerd: use drop in config to update values

### PR DESCRIPTION
**Pull request by spowelljr**
Related https://github.com/kubernetes/minikube/issues/12358

Have containerd config exist on cluster creation. Then use drop in config to update any values that need to be changed after.

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
Build failed due to kicbase using Go 1.16 but code has 1.17 features, updated to Go 1.18

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
Flakiness of deb repositories:
```
#166 97.37 E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/armhf/catatonit_0.1.7-1_armhf.deb  404  Not Found [IP: 91.193.113.70 443]
#166 97.37 E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/armhf/conmon_2.0.30-2_armhf.deb  404  Not Found [IP: 91.193.113.70 443]
#166 97.37 E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/armhf/cri-tools_1.21.0~2_armhf.deb  404  Not Found [IP: 91.193.113.70 443]
#166 97.37 E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/armhf/criu_3.16.1-3_armhf.deb  404  Not Found [IP: 91.193.113.70 443]
#166 97.37 E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/armhf/crun_1.2-2_armhf.deb  404  Not Found [IP: 91.193.113.70 443]
#166 97.37 E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/armhf/podman-plugins_1.2.0-1_armhf.deb  404  Not Found [IP: 91.193.113.70 443]
#166 97.37 E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/armhf/containernetworking-plugins_1.0.0-1_armhf.deb  404  Not Found [IP: 91.193.113.70 443]
```
Building again

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
Build failed due to setting containerd config file before the package is installed resulting in apt not knowing how to proceed.
```
#83 34.15 Configuration file '/etc/containerd/config.toml'
#83 34.15  ==> File on system created by you or by a script.
#83 34.15  ==> File also in package provided by package maintainer.
#83 34.15    What would you like to do about it ?  Your options are:
#83 34.15     Y or I  : install the package maintainer's version
#83 34.15     N or O  : keep your currently-installed version
#83 34.15       D     : show the differences between the versions
#83 34.15       Z     : start a shell to examine the situation
#83 34.15  The default action is to keep your current version.
#83 34.15 *** config.toml (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package containerd.io (--configure):
#83 34.15  end of file on stdin at conffile prompt
#83 34.15 Setting up docker-ce-cli (5:20.10.13~3-0~ubuntu-focal) ...
#83 34.16 dpkg: dependency problems prevent configuration of docker-ce:
#83 34.16  docker-ce depends on containerd.io (>= 1.4.1); however:
#83 34.16   Package containerd.io is not configured yet.
#83 34.16 
#83 34.16 dpkg: error processing package docker-ce (--configure):
#83 34.16  dependency problems - leaving unconfigured
#83 34.16 Processing triggers for systemd (245.4-4ubuntu3.15) ...
#83 34.18 Errors were encountered while processing:
#83 34.18  containerd.io
#83 34.18  docker-ce
```
Added flags to auto resolve this conflict by not overriding existing config files.

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
Was experiencing issue where
```
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
  endpoint = ["https://registry-1.docker.io"]
```
was not present in the when running `containerd config dump` even though it was clearly included in the `config.toml` file. I found the issue to be that was importing the `containerd.conf.d/02-containerd.conf` file, and had the line `[plugins."io.containerd.grpc.v1.cri".cni]` which was actually overwriting the everything in the `[plugins."io.containerd.grpc.v1.cri".cni]` section and not just overwriting values set in the section. Going to make changes to stop this from happening.

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
KIC manually tested and working

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Review by sharifelgamal — APPROVED** [review]

**Pull request merged**
