### PR TITLE
[WIP] automate OLM catalog image updates

### PR DESCRIPTION
**Pull request by kadel**
Use `latest` image for `UpstreamCommunityOperators` to keep Operator Catalog uptodate

fixes https://github.com/kubernetes/minikube/issues/10768

### CODE REVIEW

**Review by medyagh — CHANGES_REQUESTED** [review]
@kadel for security reasons I don't agree with using :latest

however u can still use this command to specify your own image for the addon
```
minikube addons enable --images
```
meanwhile I suggest to make a PR to add a FAQ to our website https://minikube.sigs.k8s.io/docs/faq/
how to use a different image for a minikube addon

**Comment by kadel** [comment]
> @kadel for security reasons I don't agree with using :latest
> 
> however u can still use this command to specify your own image for the addon
> 
> ```
> minikube addons enable --images
> ```
> 
> meanwhile I suggest to make a PR to add a FAQ to our website https://minikube.sigs.k8s.io/docs/faq/

Every olm add-on user will always get an outdated catalog unless they manually set a new image.
This is going to be a big usability problem :-( 

Another option would be updating the image for each minikube release, to at least make sure that each new release gets a little bit more up-to-date catalog. 
Updates to community operators are happening almost every day https://github.com/operator-framework/community-operators.

**Comment by medyagh** [comment]
> dd-on user will always get an outdated catalog unless they manually set a new image.
> This is going to be a big usability problem :-(
> 
> Another option would be updating the image for each minikube release to at least make sure that each new release gets a little bit more up-to-date catalog. But it will help only a little bit.

unfortunately using :latest tag is a not gonna be acceptable in minikube security practices. but I am open to adding Automation that updates the latest OLM with with Latest SHA on each release
for example we have this hack go script to update kubernetes version
```
hack/update/kubernetes_version/update_kubernetes_version.go
```
how about changing ur PR to have a script like this

```
hack/update/addons/addons.go
```
which will for Few addons such as OLM it would get latest SHA and update it ?

would u be interested in that PR ?

**Comment by kadel** [comment]
> unfortunately using :latest tag is a not gonna be acceptable in minikube security practices. but I am open to adding Automation that updates the latest OLM with with Latest SHA on each release

That would work. I did not know that there already is a similar process where this can be done. 

I'll have a look and I'll update this PR.

Thank you for guiding me towards that.

**Comment by medyagh** [comment]
@kadel if u dont mind I close this PR and please reopen it once you are ready

**Pull request closed without merging**
