### PR TITLE
iso: enable Network Block Device support

### PR DESCRIPTION
**Pull request by pkalever**
Having NBD module support would enable some of the CSI projects to utilize
the NBD based persistent volume requests validation in their automated
testing suites.

Example, we need it at the ceph-csi project.

Signed-off-by: Prasanna Kumar Kalever \<prasanna.kalever@redhat.com\>

### CODE REVIEW

**Comment by nixpanic** [comment]
This change looks good to me :+1: I do not know why GitHub CI failed to build the test-iso, a local build worked and includes the `nbd.ko` kernel module.

/assign @sharifelgamal

**Comment by spowelljr** [comment]
@pkalever @nixpanic 
The machine being used for running the GitHub CI is pointing to a linux repository that has an out of date package and is failing on `apt-get update`. I'm currently in the middle of deleting the existing servers and creating new ones. Once I'm done I'll re-run the job.

**Comment by pkalever** [comment]
@spowelljr can we rerun now?

**Comment by spowelljr** [comment]
@pkalever Running the build now

**Comment by spowelljr** [comment]
@pkalever The build failed, it uploaded some logs you can take a look at. There was a PR that recently ran where the build was successful (https://github.com/kubernetes/minikube/runs/1864676047?check_suite_focus=true) so I'm not sure at this point if this is a server issue or caused by the PR.

**Comment by nixpanic** [comment]
Hi @spowelljr!

A local build worked fine for me. Could you restart the failed test maybe?
It would be much appreciated if this can be included in the [1.18.0 release](https://github.com/kubernetes/minikube/milestone/37].

Thanks!

**Review by nixpanic — APPROVED** [review]

**Comment by spowelljr** [comment]
@nixpanic I re-ran the build, the build succeeded this time, the tests failed, but that's a known thing I'm going to work on fixing tomorrow.

**Comment by pkalever** [comment]
@spowelljr any updates please?

**Comment by sharifelgamal** [comment]
We're in the process of overhauling our ISO testing framework, so we will retest this once that's ready.

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by pkalever** [comment]
@sharifelgamal  @spowelljr can this be taken a look please?

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by pkalever** [comment]
@sharifelgamal rebased now. Please help set the labels again.

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by pkalever** [comment]
@sharifelgamal rebased again. Please help set the labels.

A couple of months passed already, can someone please take this PR to Merged, at Ceph-csi we are eagerly waiting on these changes, please help.

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by pkalever** [comment]
@sharifelgamal @medyagh can you please tell me what are we waiting on ?

**Comment by sharifelgamal** [comment]
My apologies @pkalever, our ISO testing infrastructure is still new and silently failed while testing your ISO. It's still important to us that we test this PR, since ISO changes have bitten us in the past when they were merged untested. I'm going to rebuild this test ISO, then wait for the KVM tests to come back. If they look good, we'll merge this PR ASAP. Sorry again for the delay.

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
Quick update here, there's an issue with our ISO build that's not related to this PR. We need to fix that first, then we will retest this.

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
Alright, the tests look good. Thanks again for your patience here. Sorry it took so long.

**Pull request merged**
