### PR TITLE
Upgrade cri-dockerd to fix the socket path

### LINKED ISSUE #13545: Support docker container runtime in Kubernetes 1.24
This is a tracker for the required changes:

* https://github.com/kubernetes/minikube/pull/12102

* https://github.com/kubernetes/minikube/pull/13191

* https://github.com/kubernetes/minikube/pull/13227
* https://github.com/kubernetes/minikube/pull/13302

* https://github.com/kubernetes/minikube/pull/13563

`minikube start --kubernetes-version=v1.24.0-alpha.2 --container-runtime=docker`

Failing with minikube v1.25.1, due to the earlier confusion about the socket name

ISO (missing)
```
Failed to enable unit: Unit file cri-docker.socket does not exist.
```

KIC (outdated)
```
stat: cannot stat '/var/run/cri-dockerd.sock': No such file or directory
```

```console
docker@minikube:~$ systemctl cat cri-docker.socket 
# /lib/systemd/system/cri-docker.socket
[Unit]
Description=CRI Docker Socket for the API
PartOf=cri-docker.service

[Socket]
ListenStream=%t/cri-docker.sock
SocketMode=0660
SocketUser=root
SocketGroup=docker

[Install]
WantedBy=sockets.target
docker@minikube:~$ cri-dockerd --version
cri-dockerd 0.2.0 (HEAD)
```

* https://github.com/Mirantis/cri-dockerd/commit/50c048cb54e52cd9058f044671e309e9fbda82e4

```diff
@@ -3,7 +3,7 @@ Description=CRI Docker Socket for the API
 PartOf=cri-docker.service
 
 [Socket]
-ListenStream=%t/cri-docker.sock
+ListenStream=%t/cri-dockerd.sock
 SocketMode=0660
 SocketUser=root
 SocketGroup=docker
```

Still wrong in the upstream README, but there it is the unit and not the file.

* https://github.com/Mirantis/cri-dockerd/pull/33

### PR DESCRIPTION
**Pull request by afbjorklund**
The v0.2.0 had the socket as cri-docker.sock,
while the installer are using cri-dockerd.sock

Also fix the output of cri-dockerd --version,
to use the git commit instead of just "HEAD".

Closes #13545

### CODE REVIEW

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
@sharifelgamal : I verified this locally, using `v1.24.0-alpha.2` and local builds of KIC and ISO.

🐳  Preparing Kubernetes v1.24.0-alpha.2 on Docker 20.10.12 ...

🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default


```console
$ minikube ssh -- sudo crictl version
Version:  0.1.0
RuntimeName:  docker
RuntimeVersion:  20.10.12
RuntimeApiVersion:  1.41.0
$ minikube ssh -- sudo cri-dockerd --version
cri-dockerd 0.2.0 (a4d1895)

```

**Comment by afbjorklund** [comment]
Currently there is some confusion in the upstream documentation:

https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/

But it is being fixed:

* https://github.com/kubernetes/website/issues/30974

----

KIC output:

```
NAME       STATUS     ROLES                  AGE   VERSION           INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
minikube   NotReady   control-plane,master   6s    v1.24.0-alpha.2   192.168.49.2   <none>        Ubuntu 20.04.2 LTS   5.4.0-97-generic   docker://20.10.12
```

ISO output:

```
NAME       STATUS   ROLES                  AGE   VERSION           INTERNAL-IP      EXTERNAL-IP   OS-IMAGE              KERNEL-VERSION   CONTAINER-RUNTIME
minikube   Ready    control-plane,master   6s    v1.24.0-alpha.2   192.168.50.130   <none>        Buildroot 2021.02.4   4.19.202         docker://20.10.12
```

**Review by sharifelgamal — APPROVED** [review]

**Pull request merged**
