### PR TITLE
Add google group link to triaging doc

### LINKED ISSUE #10173: site: add calendar invite link to Triage Meeting
on our site, there should be a link to add a calendar invite for triage meeting, or we could direct the users to join a the google group so they receive the invitation on their calendar automatically 
https://minikube.sigs.k8s.io/docs/contrib/triage/

### PR DESCRIPTION
**Pull request by uhari03**
Fixes #10173

### CODE REVIEW

**Comment by uhari03** [comment]
I signed it

**Review by medyagh — CHANGES_REQUESTED** [review]
is there a way to add a Clickable Add to calendar button ?

**Comment by uhari03** [comment]
There probably is a way to get that button @medyagh but I think we need one of the admins to do it.

For example, if I go to my calendar invite and click on publish, I get:
```
<a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=N3UyaDc1Y2kxdWtrZzJoaTJqNzZyZ2k0ZXBfMjAyMTAxMjdUMTkwMDAwWiB1LmhhcmkwM0Bt&amp;tmsrc=REDACTED_MY_EMAIL&amp;scp=ALL"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_en.gif"></a>
```

I redacted it, but it had my own email in the link. Wondering if someone can give me the output if they sign in with the Group Email (if that's even possible.

**Review by priyawadhwa — APPROVED** [review]
LGTM

**Pull request merged**
