### PR TITLE
Cut v0.12.0 release

### PR DESCRIPTION
**Pull request by r2d4**
ref #737 

PTAL

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
Looks like Jenkins is having trouble talking to Github.

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by aecolley** [comment]
So where's `minikube.iso`? Its checksum is mentioned on the release page, but there's no download link.

**Comment by r2d4** [comment]
@aecolley The iso is still at v0.7 (we haven't released a new version yet, only the minikube binary itself).  We should add the download links on the release anyway. Its the same ISO as found here:

https://github.com/kubernetes/minikube/releases/download/v0.10.0/minikube-0.7.iso

Note: Minikube will fetch this ISO automatically or you can specify a URL or file URI with `minikube start --iso-url`

Note: that this is still the ISO based off of boot2docker, not the experimental buildroot-based rkt ISO. You can grab that one at https://github.com/coreos/minikube-iso/releases for now (although the code has been merged into this repo)

We need to move over those to our repo soon as well as probably rename both the buildroot-based rkt (minikube-iso.iso) and  boot2docker-based (minikube.iso) so they are more distinguishable.

**Comment by aecolley** [comment]
@r2d4 Thanks for your full explanation, as well as for your useful follow-up on #571.

**Pull request merged**
