### PR TITLE
Prepend hyper-v module name to fix cmdlet collision with vmware powercli

### LINKED ISSUE #2226: Unable to start minikube for hyperv if vmware module is present
**this is a BUG REPORT:

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):  v0.23.0
- **OS** (e.g. from /etc/os-release): Windows 10 Version 10.0.15063 Build 15063
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.6.iso
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

**What happened**:
If i try to start minikube with hyperv driver it tells me hyperv is not present when checking for the new-vm command

**What you expected to happen**: It should detect new-vm of the hyper-v module as hyper-v\new-vm works

**How to reproduce it** (as minimally and precisely as possible):
1. install the vmware module (VMware.PowerCLI)
2. make sure the hyper-v components are present.
3. check if the new-vm commands is present (get-command hyper-v\new-vm) -> note I am calling hyper-v\new-vm, otherwise it could be that the VMware.VimAutomation.Core\new-vm command is returned.
4. Start minikube with the hyperv driver

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
This is easily fixed, by checking if the **hyper-v\new-vm** command is present. It now checks for **new-vm**, Gets the first item of the returned array (in this case hyperv, and vmware), then checks the module it belongs to. If this is vmware, it fails.

Replace the new-vm powershell command with hyper-v\new-vm and check the entire array for hyper-v module to be present and this works as exepected.

### PR DESCRIPTION
**Pull request by davemay99**
Fixes #2226

When VMware PowerCLI is installed alongside Hyper-V, there are multiple command collisions which prevent the hyperv Docker machine driver from working as expected.  I fixed the underlying Docker Machine issue in https://github.com/docker/machine/pull/4404 by prepending the hyper-v module name to ensure the correct module is used.

This pull request contains the latest hyperv machine driver code from the Docker Machine repo, which also includes code to help select the correct V-Switch if one is not specified.

Signed-off-by: Dave May <dave.may@tresta.com>

### CODE REVIEW

**Comment by jimmidyson** [comment]
Looks good, but `Godeps/Godeps.json` needs updating too I think.

**Comment by davemay99** [comment]
@jimmidyson I'm not familiar with the update procedure for Godeps.json.

It doesn't appear that Comment is still relevant and/or updated.  So if my fix was committed into docker/machine at https://github.com/docker/machine/commit/15095c90d0f546419628df8eccd68c99cc2067f4, and I only changed files related to the hyperv driver, do I just need to update the Rev as follows?

```
                {
                        "ImportPath": "github.com/docker/machine/drivers/hyperv",
                        "Comment": "docs-v0.8.2-2016-09-26-292-g49dfaa70",
                        "Rev": "15095c90d0f546419628df8eccd68c99cc2067f4"
                },
```

**Comment by dlorenc** [comment]
We have some documentation here on the right way to update godeps: https://github.com/kubernetes/minikube/blob/master/docs/contributors/adding_a_dependency.md

It's a bit of a pain, so if you want I can make the change for you.

**Comment by dlorenc** [comment]
Closing in favor of #2586

**Pull request closed without merging**
