### PR TITLE
WIP Added localkube usage for no-vm in README.md

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by r2d4** [comment]
Does this actually work?  It wont change your kube context right?  I feel like there may be some hidden issues. Some of the defaults might be harmful, like looking in `/etc/kubernetes`for addons

I'm a little reluctant to support this feature officially before we iron out the issues.  Would it be easy enough to add a CI test for localkube?

**Comment by dlorenc** [comment]
> Does this actually work? It wont change your kube context right? I feel like there may be some hidden issues. Some of the defaults might be harmful, like looking in /etc/kubernetesfor addons

It won't change your kubectl, but a default context should work fine (localhost:8080 with no auth).

The other defaults are weird and we should think through them a bit. I don't think it's harmful to look there, but you won't get any addons.

**Comment by dims** [comment]
@aaron-prindle @dlorenc @r2d4 - i was toying with the generic driver from docker repo last few days and got something that seems to work reasonably well

https://github.com/dims/minikube/commit/345eda8edacd027482f861f62737bdc446e4f31f
https://github.com/dims/docker-machine-local

Please take a look and let me know if this is of any interest for the no-vm use case

**Comment by r2d4** [comment]
As far as I've understood looking at generic driver, it still assumes there's a VM present. It just is not responsible for starting/stopping/killing. 

We've been having offline talks of creating a similar driver that assumes even less about the machine, although it looks like the interfaces in libmachine may be a little too rigid to let our implementation make sense.  (Basically the fact that SSH is the method of communication)

**Comment by dims** [comment]
@r2d4 : right, that's what the implemention i pointed above does. you start a vm, download minikube binary into it and run `out/minikube start --vm-driver=local` for now it does use SSH to talk to itself to do the rest of the things needed.

**Comment by dlorenc** [comment]
@dims This is cool! It looks like you have to pass in the SSH info to the driver? Or does it have a way to figure out how to SSH into itself?

**Comment by dims** [comment]
@dlorenc : i pick the user name using `mcnutils.GetUsername()` and the ssh key using `filepath.Join(mcnutils.GetHomeDir(), ".ssh", "id_rsa")` so don't need to pass arguments in this use case.

**Comment by sharkoz** [comment]
Any reason why this is still a pending PR? I feel like I belong to the category of "Users attempting to use this for CI which are already in a VM won't be able to use Minikube as nested virtualization is typically not an option", so I find this very interesting, but I am not sure if it is a good idea to try it considering this has not been merged yet.

**Comment by r2d4** [comment]
@sharkoz there is now the `minikube --vm-driver=none` which will be able to be run on virtualized hardware (in a CI).  There are actually already instructions on our main README https://github.com/kubernetes/minikube#linux-ci-installation-which-supports-running-in-a-vm-example-w-kubectl-installation

I think @aaron-prindle can close this

**Comment by sharkoz** [comment]
Ok thanks @r2d4, my bad I didn't realise this was what these instructions were about.
Also "VirtualBox or KVM" are still listed as requirements for Linux so I was confused.

**Comment by r2d4** [comment]
Yeah, we should update the linux requirements to account for the none driver or the dockerized solution

**Pull request closed without merging**
