### PR TITLE
added localkube and dependencies

### LINKED ISSUE #7: Do not depend on localkube when released

### PR DESCRIPTION
**Pull request by ethernetdan**
Closes #7 by having Redspread contribute [localkube](https://github.com/redspread/localkube) to a Kubernetes maintained repository. The plan is currently to deprecate localkube as it's own project and focus our development efforts on minikube.

We continued using Godeps to vendor the dependencies though I am very interested in switching to Glide. In the short time I've spent maintaining localkube have found managing Kubernetes as a dependency can be challenging with Godeps.

While I added compiling the localkube binary to the build script, the minikube cli still uses the Redspread bundled version of localkube (#15).

A ported version of kube2sky is being used here as the original package does not allow external access. I am highly in favor moving to a centrally maintained when that becomes available, there is a PR in to open up access (kubernetes/kubernetes#25061).

### CODE REVIEW

**Comment by dlorenc** [comment]
Looks great! One small request though, could you update the README.md to show the change to ./out/minikube instead of ./minikube in the instructions?

I'll have to think a bit about the folder structure, but this is probably fine for now. I was hoping to have the top level "cli" folder be the code for the minikube CLI, and have other top-level folders handle other things (I'm working on one for iso/ which will contain the code to build our VM .iso file).

But this layout has some advantages too. I'll think about it a little more, but we can clean that up later.

**Comment by luxas** [comment]
Great!

A note/proposal on folder structure:
`cli` -> `pkg/minikube(/cli)`
`k8s` -> `pkg/(localkube/)dns/kube2sky`
`localkube` -> `pkg/localkube`

At least, we should keep command line parsing etc. in `cmd/` and _all logic_ in `pkg/`

**Comment by ethernetdan** [comment]
@dlorenc updated README, good catch

@luxas seems like a good approach. I'm thinking that we keep the structure as is and address that in another PR, if that sounds reasonable

**Comment by dlorenc** [comment]
> @luxas seems like a good approach. I'm thinking that we keep the structure as is and address that in another PR, if that sounds reasonable
>  Show all checks

SGTM, I like that layout as well. Getting this in unblocks some other work, so I think we should proceed and change the layout in a followup.

**Comment by luxas** [comment]
Yay! Thanks @mfburnett and @ethernetdan!
And yeah, it's better to proceed with the folder structure etc. in other PRs

**Comment by vishh** [comment]
Woot! Thanks @ethernetdan !

**Pull request merged**
