### PR TITLE
Update localkube cache images

### PR DESCRIPTION
**Pull request by kairen**
Update localkube cached images to reduce test time.

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot ok to test

**Comment by kairen** [comment]
Hi @dlorenc could you help to retest?

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by kairen** [comment]
Hi, @r2d4 I follow your suggestion added the cache to make sure that the image is cached for our tests.

**Comment by kairen** [comment]
Move to #2292.

**Pull request closed without merging**
