### PR TITLE
Add eBPF related kernel options

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

This PR permits using `minikube` 5.10 kernel to develop eBPF related feature.
It follows #12707.

I use it as my daily driver and I know developers from Polar Signals use it too.

I was able to build the images and run them:

```bash
# For x86_64
francis@pwmachine:~/Codes/kinvolk$ minikube start --driver=kvm --iso-url=file:///home/francis/Codes/kinvolk/minikube-amd64.iso    
😄  minikube v1.23.2 sur Ubuntu 20.04
✨  Utilisation du pilote kvm2 basé sur la configuration de l'utilisateur
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
🔥  Création de VM kvm2 (CPUs=2, Mémoire=6000MB, Disque=20000MB)...
🐳  Préparation de Kubernetes v1.22.2 sur Docker 20.10.16...
    ▪ Génération des certificats et des clés
    ▪ Démarrage du plan de contrôle ...
    ▪ Configuration des règles RBAC ...
🔎  Vérification des composants Kubernetes...
    ▪ Utilisation de l'image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Modules activés: storage-provisioner, default-storageclass
🏄  Terminé ! kubectl est maintenant configuré pour utiliser "minikube" cluster et espace de noms "default" par défaut.
francis@pwmachine:~/Codes/kinvolk$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ uname -a
Linux minikube 5.10.57 #1 SMP Fri Jun 10 14:03:59 UTC 2022 x86_64 GNU/Linux
$ zcat /proc/config.gz | grep BTF
CONFIG_DEBUG_INFO_BTF=y
$ ls /sys/kernel/btf/
vmlinux
``` 

```bash
# For arm64, I tested without minikube because I do not have an arm64 hardware
# For arm64:
francis@pwmachine:~/Codes/kinvolk$ wget https://releases.linaro.org/components/kernel/uefi-linaro/16.02/release/qemu64/QEMU_EFI.img.gz
# ...
francis@pwmachine:~/Codes/kinvolk$ gunzip QEMU_EFI.img.gz
# QEMU_EFI contains grub or arm64.
francis@pwmachine:~/Codes/kinvolk$ qemu-system-aarch64 -cpu cortex-a53 -M virt -m 4096 -nographic -pflash QEMU_EFI.img -hda minikube-arm64.iso
# Some systemd failures are printed:
[FAILED] Failed to listen on Docker Socket for the API.
See 'systemctl status docker.socket' for details.
[FAILED] Failed to start minikube scheduled stop.
See 'systemctl status minikube-scheduled-stop.service' for details.
[FAILED] Failed to start CRI-O Auto Update Script.
See 'systemctl status crio-wipe.service' for details.
[DEPEND] Dependency failed for Cont…ime Interface for OCI (CRI-O).
[  OK  ] Started User Login Management.

Welcome to minikube
minikube login: root
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

# uname -a
Linux minikube 5.10.57 #1 SMP PREEMPT Fri Jun 10 14:54:37 UTC 2022 aarch64 GNU/Linux
# zcat /proc/config.gz | grep BTF
CONFIG_DEBUG_INFO_BTF=y
```

The implementation of this feature is not perfect (particularly the backporting of upstream buildroot patch) but I think this is the only solution we have since some upstream patches are not part of last buildroot LTS.

Best regards and thank you in advance.

### CODE REVIEW

**Comment by medyagh** [comment]
ok-to-build-iso

**Review by spowelljr — APPROVED** [review]

**Comment by kakkoyun** [comment]
I'm ecstatic that this has been merged! Thanks a lot, @eiffel-fl, for the amazing work!

Can we just use it? Will there be a release candidate that includes new Kernel upgrades? Or is there an easy way to grab an image from the merged commits?

**Comment by victorsndvg** [comment]
Hi @all,

I'm trying to run ebpf programs with the latest minikube version (1.26.0), but it is not working. 

```shell
$ minikube ssh -- docker run --rm --privileged -v /lib/modules:/lib/modules:ro -v /usr/src:/usr/src:ro -v /etc/localtime:/etc/localtime:ro --workdir /usr/share/bcc/tools zlim/bcc ./execsnoop
chdir(/lib/modules/5.10.57/build): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/execsnoop", line 165, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 325, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
ssh: Process exited with status 1
$ minikube ssh -- uname -a
Linux minikube 5.10.57 #1 SMP Thu Jun 16 23:36:20 UTC 2022 x86_64 GNU/Linux
$ minikube ssh -- ls /lib/modules/5.10.57/
Module.symvers	modules.alias	   modules.builtin.alias.bin  modules.dep      modules.order	modules.symbols.bin
extra		modules.alias.bin  modules.builtin.bin	      modules.dep.bin  modules.softdep
kernel		modules.builtin    modules.builtin.modinfo    modules.devname  modules.symbols
``` 

I suppose it should work. Maybe, I'm missunderstunding something?

I really appreciate your help.

Thanks in advance.
Víctor.

**Comment by victorsndvg** [comment]
Thanks @eiffel-fl,

you are right, the proposed docker image is working as expected.

Sorry for bothering you, but there are a lot of old info about eBPF and I am lost ...

I will take a look to CO-RE tools.

Thanks again! :)
Víctor

**Pull request merged**
