### PR TITLE
set proxy-refresh-interval=70000 for etcd to improve CPU overhead

### LINKED ISSUE #5682: Reduce VM CPU overhead by 20%
Related to #3207 and #5398 

#3207 can probably be closed - I don't believe we are at 50% usage any longer.

### PR DESCRIPTION
**Pull request by priyawadhwa**
closes #5682 

can be reversed back to the default via command line:

```
minikube start --extra-config etcd.proxy-refresh-interval=30000
```

### CODE REVIEW

**Comment by medyagh** [comment]
@priyawadhwa the VerifyKubernetesImages test seem to be failing multiple places

**Comment by medyagh** [comment]
> @priyawadhwa the VerifyKubernetesImages test seem to be failing multiple places

never mind that was related to this https://github.com/kubernetes/minikube/issues/8859

**Comment by medyagh** [comment]
please checkout the TestRunningBinaryUpgrade failure to see if it is related:
 https://storage.googleapis.com/minikube-builds/logs/8850/1c1ac42/Docker_Linux.html#fail_TestRunningBinaryUpgrade

**Comment by priyawadhwa** [comment]
Hey @medyagh , the test passes locally so I don't think it's related to this PR:

```
$ make integration -e TEST_ARGS="-test.run TestRunningBinaryUpgrade  --cleanup=false --minikube-start-args="--driver=docker""
go test -v -test.timeout=60m ./test/integration --tags="integration container_image_ostree_stub containers_image_openpgp go_getter_nos3 go_getter_nogcs" -test.run TestRunningBinaryUpgrade  --cleanup=false --minikube-start-args=--driver=docker
Found 16 cores, limiting parallelism with --test.parallel=9
=== RUN   TestRunningBinaryUpgrade
=== PAUSE TestRunningBinaryUpgrade
=== CONT  TestRunningBinaryUpgrade
--- PASS: TestRunningBinaryUpgrade (394.90s)
    version_upgrade_test.go:90: (dbg) Run:  /var/folders/hh/dw0n4wk51cv_w3yl9h5p155h00fzsz/T/minikube-v1.9.0.345181553.exe start -p running-upgrade-20200728132338-22666 --memory=2200 --vm-driver=docker
    version_upgrade_test.go:90: (dbg) Done: /var/folders/hh/dw0n4wk51cv_w3yl9h5p155h00fzsz/T/minikube-v1.9.0.345181553.exe start -p running-upgrade-20200728132338-22666 --memory=2200 --vm-driver=docker: (2m54.138411203s)
    version_upgrade_test.go:100: (dbg) Run:  out/minikube start -p running-upgrade-20200728132338-22666 --memory=2200 --alsologtostderr -v=1 --driver=docker
    version_upgrade_test.go:100: (dbg) Done: out/minikube start -p running-upgrade-20200728132338-22666 --memory=2200 --alsologtostderr -v=1 --driver=docker: (3m15.541506118s)
    helpers_test.go:176: skipping cleanup of running-upgrade-20200728132338-22666 (--cleanup=false)
PASS
Tests completed in 6m34.903494774s (result code 0)
ok  	k8s.io/minikube/test/integration	395.397s
```

**Pull request merged**
