### PR TITLE
caching: Fix containerd, improve console messages, add integration tests

### LINKED ISSUE #3651: Add integration test for --cache-images for all container runtimes
--cache-images is in bad shape right now.

### PR DESCRIPTION
**Pull request by tstromberg**
- Change output messages to use "download" instead of "caching", for accuracy and familiarity.
- 'ctr cri load' doesn't work, use 'ctr image import' instead.
- LoadImage errors are no longer fatal, though it still outputs an error message to console.
- TestStartStop now tests caching!
- Allow integration tests to pass arguments directly to Start()

Closes #3651

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by afbjorklund** [comment]
Why did you need to use `sudo` for docker ? The default user _should_ be part of the root-equivalent group:

``` console
$ ls -l /var/run/docker.sock 
srw-rw---- 1 root docker 0 Feb 28 16:48 /var/run/docker.sock
$ id
uid=1001(docker) gid=1001(docker) groups=1001(docker),10(wheel),1000(rkt),1018(rkt-admin),1019(vboxsf)

$ docker save busybox | gzip > busybox.tar.gz
$ docker load < busybox.tar.gz 
Loaded image: busybox:latest
```

https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by tstromberg** [comment]
> Why did you need to use `sudo` for docker ? The default user _should_ be part of the root-equivalent group:
> 
> ```
> $ ls -l /var/run/docker.sock 
> srw-rw---- 1 root docker 0 Feb 28 16:48 /var/run/docker.sock
> $ id
> uid=1001(docker) gid=1001(docker) groups=1001(docker),10(wheel),1000(rkt),1018(rkt-admin),1019(vboxsf)
> 
> $ docker save busybox | gzip > busybox.tar.gz
> $ docker load < busybox.tar.gz 
> Loaded image: busybox:latest
> ```
> 
> https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

You appear to be completely correct. I put that change in a couple of weeks ago and completely forgot why I added sudo. The answer appears to be, for no reason at all. Thanks for questioning it!

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
None failure: #3873

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Pull request merged**
