### PR TITLE
Set hostname to minikubevm for xhyve driver

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by dlorenc** [comment]
Nice! cc @s-urbaniak, what hostname are you using in the new rkt iso? I think it's just "minikube", right?

**Comment by dlorenc** [comment]
LGTM

**Comment by s-urbaniak** [comment]
@dlorenc I am setting the hostname in the "buildroot" provisioner [1], hence it is controlled by minikube itself. I see in my local VM it being set to .... "minikube" ;-)

[1] https://github.com/kubernetes/minikube/pull/511/files#diff-9284c1e8907ac155cc76b06aa96535d4R124

**Comment by jimmidyson** [comment]
@s-urbaniak Hmm. I'd expect it to be `minikubeVM` then (https://github.com/kubernetes/minikube/blob/59ad726e6cb64ce2ab0b3d543a68993dd62d1765/pkg/minikube/constants/constants.go#L28)

**Comment by s-urbaniak** [comment]
@jimmidyson gah, you are right, it is "minikubeVM", it's getting late here in Europe ;-)

```
$ minikube ssh
$ hostname
minikubeVM
```

**Comment by jimmidyson** [comment]
So shall we change hostname? Can't see much harm in it personally,

**Comment by jimmidyson** [comment]
And I will update to use `constants.MachineName` once we decide.

**Comment by dlorenc** [comment]
Ah, ok. I saw this value in the buildroot config: https://github.com/coreos/minikube-iso/blob/f0b7abf42e90e5a8b47237ae4524a130647fcbf8/configs/minikube_defconfig#L6

but I guess we override that in the provisioning.

**Comment by dlorenc** [comment]
I don't really have a large preference. Whatever you prefer!

**Comment by jimmidyson** [comment]
OK so I've switched to simply minikube as discussed above.

**Pull request merged**
