### PR TITLE
fix error usage for the WaitGroup in the pkg addons

### PR DESCRIPTION
**Pull request by saltbo**
The method `Add` should out in the goroutine, because the `Wait` maybe exec before the goroutine.

### CODE REVIEW

**Comment by saltbo** [comment]
I signed it

**Comment by medyagh** [comment]
@saltbo can you please describe what issue are you trying to fix?

**Comment by saltbo** [comment]
The method Add should out in the goroutine, because the Wait maybe exec before the goroutine.

**Comment by saltbo** [comment]
I signed it

**Comment by medyagh** [comment]
> Add should out in the goroutine, because the Wait maybe exec before the goroutine.

do you have an example minikube issue that this will solve so I can test this PR before and after this PR ?

**Comment by saltbo** [comment]
https://github.com/kubernetes/minikube/blob/ad083ba7acafe4cd6018fb2fc92364e9eb148b33/pkg/addons/addons_test.go#L133

This function`Start` in Test should be called by the goroutine.  Because it is called by Goroutine in actual use.

https://github.com/kubernetes/minikube/blob/ad083ba7acafe4cd6018fb2fc92364e9eb148b33/pkg/minikube/node/start.go#L149

Then, you can found test failed. Because of the `wg.Add(1)` should be executed out of the goroutine.

**Pull request merged**
