### PR TITLE
[WIP] Make dynamic persistent volumes path readable and configurable

### PR DESCRIPTION
**Pull request by 11janci**
For #5144 & #3318

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
Change looks good, but it isn't clear to me what issue this is fixing. Can you add a description as to why this change is happening?

**Comment by 11janci** [comment]
@tstromberg It is for #5144 and #3318 (updated the PR desc). However I'm hitting a wall testing it. Can't figure out why the tests are failing, am trying to revert changes to see where it breaks. Also, I'm not able to test it locally without the minikube ISO and can't build the ISO (is failing on my mac) 😒 I should be able to get it from https://storage.googleapis.com/minikube-builds/5400/minikube-testing.iso but for that I need the tests here to pass 🤕

**Comment by medyagh** [comment]
@11janci do you mind providing examples ? maybe in the PR descrption and also add related docs in the site?

**Comment by 11janci** [comment]
@medyagh you mean examples of usage? This is a work in progress and I'd like to get it working first, however don't have the capacity to work on it right now :/

**Comment by nanikjava** [comment]
> .......... Also, I'm not able to test it locally without the minikube ISO and can't build the ISO (is failing on my mac)  I should be able to get it from https://storage.googleapis.com/minikube-builds/5400/minikube-testing.iso, but for that I need the tests here to pass

@11janci If you need help in running the testing on local machine happy to help

**Comment by tstromberg** [comment]
Need any help with this?

**Comment by 11janci** [comment]
@tstromberg, @all yeah as mentioned above, I currently don't have the capacity to work on this (for at least another 2 months). **If anybody wants to take over, feel free to pull my changes and finish it off**.

The end goal is to make the dynamic PV path 
a) readable - using the PVC's name instead of the UUID
b) configurable - sending a flag to the provisioner

I was adding and removing my changes as I was trying to test it so check out my previous commits, especially the first one.

**Comment by tstromberg** [comment]
Closing this PR until someone is ready to take a look at it again. 

Related: #6156

**Pull request closed without merging**
