### PR TITLE
Make default output of 'minikube start' consume fewer lines in the terminal

### LINKED ISSUE #4187: Shorten `minikube start` output
`minikube start` has gotten to be overly verbose in a default configuration: 15 lines of output, or 1 message for every 10 seconds of runtime.

I feel like we should be able to get down to roughly half this total (~8 lines) without degrading the user experience substantially.  Here is what head currently looks like:

```
😄  minikube v1.0.1 on linux (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.39.240
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
🚀  Launching Kubernetes v1.14.1 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
```
Here is a strawman proposal, at 7 lines:

```
😄 minikube v1.1.0 on CentOS Linux (amd64)
🔥 Creating kvm2 VM (2 CPUs, 2GB RAM, 20GB disk)
🐳 Configuring environment for Kubernetes v1.14.1 on Docker v18.03
🚜 Pulling images ...
🚀 Launching Kubernetes ... 
⌛ Waiting for: apiserver proxy etcd scheduler controller dns
🏄 Done! kubectl is now configured to use "minikube"
```

This equates to 1 message every 21 seconds of runtime, which is far less spammy.

### PR DESCRIPTION
**Pull request by dpandhi-git**
This PR fixes #4187

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
The Travis failures are just simple gofmt issues.

**Comment by tstromberg** [comment]
OSX-Hyperkit test failure seems to be an unrelated flake. CLA issue still needs to be addressed though. It seems like the first commits don't have their name/address matched to your GitHub user:

https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by dpandhi-git** [comment]
Can anyone help with latest travis build failed?

Also I might need help for cla/linux foundation error. I tried the steps mentioned in details but it does not seem to work.  My git account has two email ids one primary is E1 and other is E2 . E2 one is used when login with linux foundation to sign the CLA will that cause any issue? was checking people have faced similar issue https://github.com/cncf/foundation/issues/26#issuecomment-456842341

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
The  broken Travis build was my fault - and should not happen again.

It appears that this commit is not associated to your GitHub e-mail address:

https://github.com/kubernetes/minikube/commit/ee4e514282811a95dcc4c6bf31f3f4c868aa1890.patch

The e-mail address for this commit is dpandhi@Deepikas-MacBook-Pro-2.local

https://gist.github.com/trey/9588090 explains how to go back and fix the e-mail address for an older commit in a PR. Hope this helps! I can't wait for this change to land =)

**Comment by dpandhi-git** [comment]
> The broken Travis build was my fault - and should not happen again.
> 
> It appears that this commit is not associated to your GitHub e-mail address:
> 
> https://github.com/kubernetes/minikube/commit/ee4e514282811a95dcc4c6bf31f3f4c868aa1890.patch
> 
> The e-mail address for this commit is [dpandhi@Deepikas-MacBook-Pro-2.local](mailto:dpandhi@Deepikas-MacBook-Pro-2.local)
> 
> https://gist.github.com/trey/9588090 explains how to go back and fix the e-mail address for an older commit in a PR. Hope this helps! I can't wait for this change to land =)

Thanks for info on git. Passed CLA test. Thanks for making my first contribution to K8s successful

**Comment by tstromberg** [comment]
Thank you!

**Pull request merged**
