### PR TITLE
Move release API check from github to GCS.

### PR DESCRIPTION
**Pull request by dlorenc**
Github has rate-limiting on this URL, which causes issues for tests.
Moving to GCS also allows us to decouple Github releases from auto-updates.

### CODE REVIEW

**Comment by philips** [comment]
Can you please document the file format? I think it is just a super simplified version of the GitHub stuff but I am not sure: https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

**Comment by dlorenc** [comment]
Added the JSON Schema for this file in RELEASING.md. Let me know if you think there's a better location for it.

**Comment by luxas** [comment]
LGTM, I assume the `go-dockerclient` removal happened already in k8s core < `v1.3.0-beta.1`, and when godeps was bumped, it was unused but not removed. Until now, right?

**Comment by philips** [comment]
Fancy. A JSON schema :)

LGTM

**Comment by aaron-prindle** [comment]
LGTM

**Pull request merged**
