### PR TITLE
Updated Dockerfile to get docker version 1.11.1 for the iso file, als…

### PR DESCRIPTION
**Pull request by aaron-prindle**
…o updated README for iso testing

#135

### CODE REVIEW

**Comment by aaron-prindle** [comment]
I am running the conformance tests and will post the results in this thread.

**Comment by dlorenc** [comment]
Let's hold off on this until after the cut. But please post the conformance results when you have them.

**Comment by dlorenc** [comment]
LGTM. Once this is in I'll build and push to GCS. Can you send a PR to bump the iso url to 0.3?

**Comment by luxas** [comment]
> Can you send a PR to bump the iso url to 0.3?

So no more changes to the iso before `v0.3`? 
Or will you overwrite-push if a change is made to the iso before `v0.3`?

**Comment by dlorenc** [comment]
The ISO version and minikube version can diverge, although I agree it's a little confusing. If there are any others we could hold on, but it would be nice to get this out there to get miles on it.

@luxas do you have any concerns about the Docker update in general? If k8s 1.3 is going to run Docker 1.11 any qualifying will have to happen this week or next.

**Comment by luxas** [comment]
No special concerns if we've tested it thoroughly.
Sounds good to validate it this week

**Pull request merged**
