### PR TITLE
`minikube addons list` shows addons if cluster does not exist

### PR DESCRIPTION
**Pull request by spowelljr**
Closes https://github.com/kubernetes/minikube/issues/12736

**Before:**
```
$ minikube addons list
🤷  Profile "minikube" not found. Run "minikube profile list" to view all profiles.
👉  To start a cluster, run: "minikube start"
```

**Now:**
```
$ minikube addons list
|-----------------------------|-----------------------|
|         ADDON NAME          |      MAINTAINER       |
|-----------------------------|-----------------------|
| ambassador                  | unknown (third-party) |
| auto-pause                  | google                |
| csi-hostpath-driver         | kubernetes            |
| dashboard                   | kubernetes            |
| default-storageclass        | kubernetes            |
| efk                         | unknown (third-party) |
| freshpod                    | google                |
| gcp-auth                    | google                |
| gvisor                      | google                |
| helm-tiller                 | unknown (third-party) |
| ingress                     | unknown (third-party) |
| ingress-dns                 | unknown (third-party) |
| istio                       | unknown (third-party) |
| istio-provisioner           | unknown (third-party) |
| kubevirt                    | unknown (third-party) |
| logviewer                   | google                |
| metallb                     | unknown (third-party) |
| metrics-server              | kubernetes            |
| nvidia-driver-installer     | google                |
| nvidia-gpu-device-plugin    | unknown (third-party) |
| olm                         | unknown (third-party) |
| pod-security-policy         | unknown (third-party) |
| portainer                   | portainer.io          |
| registry                    | google                |
| registry-aliases            | unknown (third-party) |
| registry-creds              | unknown (third-party) |
| storage-provisioner         | kubernetes            |
| storage-provisioner-gluster | unknown (third-party) |
| volumesnapshots             | kubernetes            |
|-----------------------------|-----------------------|
```

### CODE REVIEW

**Comment by sharifelgamal** [comment]
LGTM. Maybe add a unit test?

**Comment by spowelljr** [comment]
> LGTM. Maybe add a unit test?

Sure, will do!

**Review by medyagh — COMMENTED** [review]
@spowelljr can u plz also paste output of --output=json I am curious what it shows for that

**Comment by medyagh** [comment]
thank you for this PR

**Pull request merged**
