### PR TITLE
Update BUILD KIT version to latest, 0.9.3.

### PR DESCRIPTION
**Pull request by klaases**
Fixes: #13102

Before:

`buildctl`

`buildctl github.com/moby/buildkit v0.9.0 c8bb937807d405d92be91f06ce2629e6202ac7a9`

After:

`buildctl`

`buildctl github.com/moby/buildkit v0.9.3 8d2625494a6a3d413e3d875a2ff7dd9b1ed1b1a9`

### CODE REVIEW

**Comment by klaases** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by klaases** [comment]
I have resolved the merge conflict with the translation file.

**Review by sharifelgamal — APPROVED** [review]

**Pull request merged**
