### PR TITLE
Update Japanese translation (Line 700-749)

### PR DESCRIPTION
**Pull request by yosshy**
This is work-in-progress for reviews by Japanese developers.
/assign @atoato88
/cc @YuikoTakada

### CODE REVIEW

**Comment by yosshy** [comment]
/hold
For japanese developers' review

**Comment by yosshy** [comment]
@atoato88 could you review this again?

**Comment by atoato88** [comment]
@yosshy 
I've left 2 comments.
Please see that.

**Comment by atoato88** [comment]
/lgtm
It looks good as Japanese reviewer.

**Comment by atoato88** [comment]
@yosshy 
Can you remove `hold` label?

**Comment by yosshy** [comment]
/unhold

@atoato88 thanks for the final review.

**Comment by yosshy** [comment]
@medyagh it’s ready to merge.

**Review by sharifelgamal — APPROVED** [review]

**Pull request merged**
