### PR TITLE
Register registry-proxy.yaml.tmpl with registry addons

### PR DESCRIPTION
**Pull request by kumarom**
Related to #4341

### CODE REVIEW

**Comment by tstromberg** [comment]
/approve /lgtm

Thank you!

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
we need documentation for this great feature,  we could have added as second option under this, (the documentation could be done in a separate PR)

https://github.com/kubernetes/minikube/blob/master/docs/reusing_the_docker_daemon.md

**Comment by medyagh** [comment]
Failing test is related to https://github.com/kubernetes/minikube/issues/4495

looks good to me

**Pull request merged**
