### PR TITLE
Remove all functions from constants.go

### PR DESCRIPTION
**Pull request by serhatcetinkaya**
This is a fix for issue described in #5374

### CODE REVIEW

**Comment by tstromberg** [comment]
Wow, that was fast! Do you mind rebasing this change? I'd like to submit it as soon as possible to avoid further merge conflicts.

Also, please ensure that `make test` passes. Thank you!

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
This can be fixed by running `goimports -w pkg/minikube/bootstrapper/bootstrapper.go` (or setting your IDE to automatically run it for you)

```
pkg/minikube/bootstrapper/bootstrapper.go:22: File is not `goimports`-ed (goimports)
Makefile:335: recipe for target 'lint-ci' failed
```

**Comment by serhatcetinkaya** [comment]
@tstromberg you are too fast :)
I hope it is better now, thanks for all the help

**Pull request merged**
