### PR TITLE
docs: fix typo in pushing.md

### PR DESCRIPTION
**Pull request by leoluk**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/minikube/7755)

### CODE REVIEW

**Comment by tstromberg** [comment]
Thank you!

**Comment by tstromberg** [comment]
When you get a chance, please fill out the CLA form: https://git.k8s.io/community/CLA.md#the-contributor-license-agreement

**Comment by leoluk** [comment]
I signed it

**Comment by leoluk** [comment]
I signed it

**Comment by tstromberg** [comment]
Need any help with the CLA?

**Comment by leoluk** [comment]
@tstromberg I'm closing this PR since the typo has been fixed. Not sure what went wrong with the CLA, my GitHub account is connected to the CNCF account, the email address on the commit matches, and a corporate CLA is attached to the account :shrug:

**Pull request closed without merging**
