### PR TITLE
Update addon files to use fully qualified name

### LINKED ISSUE #14520: Use fully qualified name in addon files
The files [deploy/addons/aliyun_mirror.json](https://github.com/kubernetes/minikube/blob/master/deploy/addons/aliyun_mirror.json) and [pkg/minikube/assets/addons.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/assets/addons.go) should be updated to use the fully qualified image names `docker.io/org/image` instead of just `org/image`.

This should be done after https://github.com/kubernetes/minikube/pull/14518 is merged to prevent merge conflicts.

### PR DESCRIPTION
**Pull request by siddhant-khisty**
Updated the files in deploy/addons/aliyun_mirror.json 
As the issue mentions files have to be changed in pkg/minikube/assets/addons.go as well, but I don't see anything that needs to be changed. Please let me know if I'm missing something.

fixes #14520

### CODE REVIEW

**Comment by spowelljr** [comment]
Hi @SiddhantKhisty, you'll need to sign the CLA as outlined in the comments above, thanks

**Comment by SiddhantKhisty** [comment]
@spowelljr hi, I just finished signing the CLA

**Review by spowelljr — CHANGES_REQUESTED** [review]
Hi @SiddhantKhisty, thanks for the PR, I think there's a slight misunderstanding.

Any of the images that ends in `.io` before the `/` should be untouched.
So all the `gcr.io`, `k8s.gcr.io`, and `quay.io` lines should be left.
All the other lines, for example `kubernetesui/dashboard` should have `docker.io/` appended to the front of it.

Hope that helps, thanks

**Comment by SiddhantKhisty** [comment]
oh ok. I got it. I'll make the changes

**Comment by SiddhantKhisty** [comment]
hi @spowelljr, I made the changes. Please have a look 😄

**Comment by spowelljr** [comment]
Hi @siddhant-khisty, thanks, this part looks great, the second part is [pkg/minikube/assets/addons.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/assets/addons.go)

If you look at the following
```
        }, false, "storage-provisioner-gluster", "", "", map[string]string{
                "Heketi":                 "heketi/heketi:10@sha256:76d5a6a3b7cf083d1e99efa1c15abedbc5c8b73bef3ade299ce9a4c16c9660f8",
                "GlusterfileProvisioner": "gluster/glusterfile-provisioner:latest@sha256:9961a35cb3f06701958e202324141c30024b195579e5eb1704599659ddea5223",
                "GlusterfsServer":        "nixpanic/glusterfs-server:pr_fake-disk@sha256:3c58ae9d4e2007758954879d3f4095533831eb757c64ca6a0e32d1fc53fb6034",
        }, map[string]string{
                "GlusterfsServer": "quay.io",
        }),
```

You can see that `GlusterfsServer` uses `quay.io` and we added it to the registry list, the Docker Hub ones should be updated, so the map would look like the following.
```
        }, map[string]string{
                "Heketi": "docker.io",
                "GlusterfileProvisioner": "docker.io",
                "GlusterfsServer": "quay.io",
        }),
```

If you have any questions let me know, thanks

**Comment by siddhant-khisty** [comment]
Hey @spowelljr, I've updated a few registreis with docker.io. However, I could not find the following ones, Please let me know what is to be done here

`docker.io/nvidia/k8s-device-plugin` - There is a driver installation addon, but no device-pluging. (line: 406)
`docker.io/cryptexlabs/minikube-ingress-dns` - I found a ingress-dns file, but it is not from cryptexlabs (line: 495)
`docker.io/jettech/kube-webhook-certgen` kube-webhook-certgen is present but from ingress-nginx repo (line: 552)

Not sure where to add `docker.io/registry ` and `docker.io/coredns/coredns`

**Comment by spowelljr** [comment]
Hi @siddhant-khisty, you need to make sure you're adding the registries to the `Registries` map.

For example you're doing:
```
"GlusterfsServer": "docker.io/gluster/gluster-centos:latest@sha256:8167034b9abf2d16581f3f4571507ce7d716fb58b927d7627ef72264f802e908",
```
But that line should be left line alone.

The nil at the end of the func should have a map with the registry in it.

Example:
```
        }, map[string]string{
                "GlusterfsServer":        "docker.io",
        }),
```

And in regard to Nvidia, it already has a registry attached to it, so no work is required on it
```
        }, false, "nvidia-gpu-device-plugin", "3rd party (Nvidia)", "https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/", map[string]string{
                "NvidiaDevicePlugin": "nvidia-gpu-device-plugin@sha256:4b036e8844920336fa48f36edeb7d4398f426d6a934ba022848deed2edbf09aa",
        }, map[string]string{
                "NvidiaDevicePlugin": "k8s.gcr.io",
        }),
```

**Comment by siddhant-khisty** [comment]
Hi @spowelljr, I made the changes as you specified. If I'm understanding this correctly, what I did earlier was edit the path of the image file? And what had to be done was to mention in the registry where the image is being pulled from. Is this correct or am I misunderstand something?

**Comment by spowelljr** [comment]
> Hi @spowelljr, I made the changes as you specified. If I'm understanding this correctly, what I did earlier was edit the path of the image file? And what had to be done was to mention in the registry where the image is being pulled from. Is this correct or am I misunderstand something?

That is correct

**Comment by siddhant-khisty** [comment]
Hey @spowelljr, I've made the recommended changes and moved the above-mentioned `KubeWebHook` files into the registry. Please have a look and let me know if anything needs to be changed

**Comment by spowelljr** [comment]
> Hey @spowelljr, I've made the recommended changes and moved the above-mentioned `KubeWebHook` files into the registry. Please have a look and let me know if anything needs to be changed

The following images that I mentioned in the previous comment still don't have registries added for them:
> `IstioOperator`, `Kong`, `KongIngress`, `Kubectl`, `Registry`, `Alpine`, `Speaker`, `Controller`, `Portainer` are missing a registry.

**Comment by siddhant-khisty** [comment]
Hey @spowelljr, Sorry about that. I misunderstood the previous comment. I have a question though. Does the Registry on line 368 refer to the Docker hub registries? 

Also, I'm not sure how I should rebase this branch. Can we look into that once you've confirmed that no changes are needed?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by spowelljr** [comment]
Hi @siddhant-khisty, yes registry if from Docker Hub (https://hub.docker.com/_/registry).

And I resolved the rebase, I helped the person with that PR so I knew what changed so I handled it for you.

**Comment by spowelljr** [comment]
Hi @siddhant-khisty, thanks for the changes! The tests have discovered that we have a bug in our code in relation to setting the `Registries` and setting custom images. I'm going to look into the issue and find a solution and then once that's resolved you're PR will be good to merge.

**Comment by siddhant-khisty** [comment]
oh cool. Is there any way I can help find what's wrong?

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

**Comment by spowelljr** [comment]
Hi @siddhant-khisty, my PR was merged, could you rebase on master and push back up, thanks.

**Comment by siddhant-khisty** [comment]
Hey @spowelljr, I synced my branch with master, but it seems that tests are still failing. Seems that the images are still not being found on the defined path.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

**Comment by spowelljr** [comment]
The tests look fine to me, the tests that are failing always fail so they're not a concern. Some of the tests environments didn't report back so I'm going to run them again.

**Review by spowelljr — APPROVED** [review]
Looks good, thanks for making all these changes

**Pull request merged**
