### PR TITLE
Fix pods not being scheduled when ingress deployment is patched

### PR DESCRIPTION
**Pull request by woodcockjosh**
This issue resolves https://github.com/kubernetes/minikube/issues/5518
Also update nginx-ingress-controller to 0.26.1 which resolves some other inconsistency issues

### CODE REVIEW

**Comment by woodcockjosh** [comment]
has same change as https://github.com/kubernetes/minikube/pull/5514

**Comment by medyagh** [comment]
@minikube-bot Ok to test.

looks good ! thank you for improving minikube

**Comment by tstromberg** [comment]
Thank you!

**Pull request merged**
