### PR TITLE
Kernel with CONFIG_IKHEADERS for BPF tools on Kubernetes

### PR DESCRIPTION
**Pull request by alban**
BCC tools need to have access to kernel headers. It can be done either
by installing linux-headers packages or by having a kernel compiled with
CONFIG_IKHEADERS so that enough information can be retrieved via
/sys/kernel/kheaders.tar.xz.

BCC tools are used in Inspektor Gadget, a collection of tools for
developers of Kubernetes applications. I would like Inspektor Gadget to
support Minikube.

Fixes https://github.com/kubernetes/minikube/issues/8556

### CODE REVIEW

**Comment by alban** [comment]
It seems to work:
```
$ ./out/minikube start --iso-url=file://$(pwd)/out/minikube.iso
$ ./out/minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ uname -a
Linux minikube 5.4.40 #1 SMP Sat Jun 27 15:36:59 UTC 2020 x86_64 GNU/Linux
$ ls -l /sys/kernel/kheaders.tar.xz
-r--r--r-- 1 root root 3438056 Jun 27 16:33 /sys/kernel/kheaders.tar.xz
$ 

```

**Comment by afbjorklund** [comment]
@alban : we don't have any packages on the minikube iso, so this could be a good alternative

3 MB doesn't seem to much to pay (size addition to the iso), for having better BPF compatibility

**Comment by alban** [comment]
Thanks for the quick review @afbjorklund! I understand we need a `/lgtm` for a lgtm label (in addition to the github review). Could you lgtm or approve the PR?

**Comment by afbjorklund** [comment]
Actually we need a merge and then a new ISO, and we are currently having some issues with it...

**Comment by afbjorklund** [comment]
But I think the configuration change looks good, maybe we need to update the docs as well ?

**Pull request merged**
