### PR TITLE
fix test for checking pods after minikube restart

### PR DESCRIPTION
**Pull request by sharifelgamal**
This test was checking for the wrong pod, for the dashboard pods instead of the user deployed busybox pod. This will catch any sort of regression like the one we had with 1.25.0, where restarting minikube erased user deployed pods on startup.

### CODE REVIEW

**Review by medyagh — COMMENTED** [review]
didnt study the PR but I am curious is this something that be improved in minikube code itself ?or the test was actually not doing the right thing?

**Comment by sharifelgamal** [comment]
the test was doing the wrong thing, it wasn't checking for the user deployed app (busybox), but for the pods from the dashboard addon, which is already checked separately in another test.

**Review by klaases — APPROVED** [review]

**Comment by klaases** [comment]
LGTM and approved, ready for merge :)

**Comment by spowelljr** [comment]
`UserAppExistsAfterStop` seems to be consistently failing

**Pull request closed without merging**
