### PR TITLE
Doc: Give an example of using kvm/kvm2 driver

### PR DESCRIPTION
**Pull request by JohnVillalovos**
Add an example usage of using the kvm and kvm2 drivers to the
documentation.

Change-Id: I280a581cf22dabd079d52d44c6cf6d1c2fd9f93d

### CODE REVIEW

**Comment by dlorenc** [comment]
@JohnVillalovos would you mind signing the CLA?

**Comment by JohnVillalovos** [comment]
Working on CLA through my employer. For some crazy reason the person in charge of it is at Kubecon! Weird right ;)

**Comment by JohnVillalovos** [comment]
Leaving a comment as supposedly my CLA is now active and it says I should leave a comment.

**Comment by JohnVillalovos** [comment]
Leaving a comment as supposedly my CLA is now active and it says I should leave a comment.

**Pull request closed without merging**
