### PR TITLE
Fix nvidia-gpu with kvm-driver

### LINKED ISSUE #6912: nvidia-driver-installer addon fails to start (driver fails to install in the container)
**The exact command to reproduce the issue**:
Following the instructions on https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/

Host: Fedora 31
Kernel: 5.5.7-200.fc31.x86_64
Cuda Drivers Host: 10.2 
Nvidia Driver Host: Driver Version: 440.64

GPUs: 
- Titan V (vfio-pci driver assigned)
- Geforce 1080TI (host GPU nvidia driver)

Minikube start:
`minikube start --vm-driver kvm2 --kvm-gpu --cpus=12 --memory=25480`

Minikube Addons:
`minikube addons enable nvidia-gpu-device-plugin` 
This will fail initially, just edit the `dc/nvidia-gpu-device-plugin` and increase the mem to `100mi` and it'll start fine. 

**The full output of the command that failed**:<details>
`minikube addons enable nvidia-driver-installer`

The container fails to start. and once you fetch teh logs, it will return:

```
Configuring kernel sources... DONE
Running Nvidia installer...
/usr/local/nvidia /
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 390.67.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

ERROR: An error occurred while performing the step: "Building kernel
       modules". See /var/log/nvidia-installer.log for details.


ERROR: An error occurred while performing the step: "Checking to see
       whether the nvidia-drm kernel module was successfully built". See
       /var/log/nvidia-installer.log for details.


ERROR: The nvidia-drm kernel module was not created.


ERROR: The nvidia-drm kernel module failed to build. This kernel module is
       required for the proper operation of DRM-KMS. If you do not need to
       use DRM-KMS, you can try to install this driver package again with
       the '--no-drm' option.


ERROR: Installation has failed.  Please see the file
       '/usr/local/nvidia/nvidia-installer.log' for details.  You may find
       suggestions on fixing installation problems in the README available
       on the Linux driver download page at www.nvidia.com.
```

</details>

**The output of the `minikube logs` command**:<details>

The minikube logs don't say much but here they are:
[minikube-logs.txt](https://github.com/kubernetes/minikube/files/4299842/minikube-logs.txt)

Logs from the nvidia-installer itself:
[nvidia-driver-installer-logs.txt](https://github.com/kubernetes/minikube/files/4299857/nvidia-driver-installer-logs.txt)
 

</details>

**The operating system version**:

### PR DESCRIPTION
**Pull request by betaboon**
hello,

took me a while to figure this out, but this fixes kvm-nvidia-gpu support for me.

this might also resolve #6912

### CODE REVIEW

**Review by medyagh — APPROVED** [review]
Thank you ver much for fixing this !

**Comment by medyagh** [comment]
[betaboon](https://github.com/betaboon) thank you for fixing this, do u mind signing the CLA

**Comment by betaboon** [comment]
just did.

FYI:
this only seems to work for `Latest Legacy GPU version (390.xx series): [390.147]`

it doesnt work for either of:
```
Latest Production Branch Version: 510.60.02
Latest New Feature Branch Version: [495.46]
```

this it seems like i can only get cuda9 here.

I'm tinkering around with getting 510 working.

if i figure that out, I'll send it in another PR tho ;)

**Comment by medyagh** [comment]
> just did.
> 
> FYI: this only seems to work for `Latest Legacy GPU version (390.xx series): [390.147]`
> 
> it doesnt work for either of:
> 
> ```
> Latest Production Branch Version: 510.60.02
> Latest New Feature Branch Version: [495.46]
> ```
> 
> this it seems like i can only get cuda9 here.
> 
> I'm tinkering around with getting 510 working.
> 
> if i figure that out, I'll send it in another PR tho ;)

Thank you for figuring it out, do u mind adding it our docs ?
https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/

and mention it currently been known to work with that specific series

I would happily review your PR if you decide to make it work with newer series,

btw I am curious what is the use case of using GPU for you if you like to share

**Comment by betaboon** [comment]
i figured out what is preventing newer drivers to work.
but I'm not yet sure how to fix this, as i am lacking the knowledge about `buildroot`.

here's the gist:
- current nvidia-drivers require `Module.symvers` to be present in the kernel-source directory.
- for `Module.symvers` to be build `CONFIG_MODVERSIONS=y` is required

here's what i tried (which lead to partial success):
- enable `CONFIG_MODVERSIONS` in [linux_defconfig](https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig)
- build and run iso (`Module.symvers` is not available in `buildroot/output/build/linux-4.19.202`, but NOT in the resulting iso)
- copy `Module.symvers` into vm using `minikube cp`
- change `nvidia-driver-installer`-daemonset to make `Module.symver` available in `/usr/src/linux-4.19.202`
- apply the `nvidia-driver-installer`-daemonset
- profit (aka driver install works with `510.60.02`)

two possible solutions:
- figure out how to include `Module.symvers` in the iso
- change the entrypoint-script of the nvidia-driver-installer to run `make modules` which should recreate it

**Comment by spowelljr** [comment]
Not sure if this is the route you want to go, but if you want an example of how to copy a file into the ISO you can look at https://github.com/kubernetes/minikube/pull/12081.

If you look at `buildkit-bin.mk` you can see how files from the repo are copied into the ISO.

**Comment by betaboon** [comment]
ok i converted this PR to a draft for now.

@spowelljr thanks for the pointers.

i just pushed a commit that fixes it for the latest nvidia-drivers.
there is a hack in there tho.

this is what it does:
- change the kernel-config to enable `CONFIG_MODVERSIONS` so that `Module.symvers`gets generated
- extend the buildroot linux-target to include `Module.symvers` in `/lib/modules/...`
- change the `command` of the `nvidia-driver-installer`-daemonset to monkeypatch `/entrypoint.sh` (this is the hack)

the hack could and should be removed, but for that the [entrypoint.sh](https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/nvidia-driver-installer/minikube/entrypoint.sh) in the upstream-package should has to be adapted.

**Comment by betaboon** [comment]
@medyagh just fyi there is something to review here now :) (dont want to hurry you tho )

**Comment by medyagh** [comment]
thank you [betaboon](https://github.com/betaboon) I look forward to see more contributions from you !

**Pull request merged**
