### PR TITLE
cni: Configure portmap plugin

### LINKED ISSUE #1987: Ingress does not work with CNI network-plugin
The ingress add-on does not work if I use the cni network plugin. This is easily reproducible, see below.

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.22.2
- **OS** (e.g. from /etc/os-release): Fedora
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.4.iso
- **Install tools**:
- **Others**:

```
#
# Infos
# ingress is enabled
#

[fabiand@tee kubevirt (ingress)]$ minikube version 
minikube version: v0.22.2

[fabiand@tee kubevirt (ingress)]$ minikube addons list
- kube-dns: enabled
- registry: disabled
- ingress: enabled
- registry-creds: disabled
- addon-manager: enabled
- dashboard: enabled
- default-storageclass: disabled
- heapster: disabled

#
# start clean
#
[fabiand@tee manifests (ingress)]$ minikube delete
Deleting local Kubernetes cluster...
Machine deleted.

#
# regular with default network plugin
#
[fabiand@tee manifests (ingress)]$ minikube start --vm-driver kvm 
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.

[fabiand@tee manifests (ingress)]$ k get --all-namespaces pods
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
kube-system   default-http-backend-p44v8       1/1       Running   0          4m
kube-system   kube-addon-manager-minikube      1/1       Running   0          4m
kube-system   kube-dns-910330662-2flv0         3/3       Running   0          4m
kube-system   kubernetes-dashboard-th8fv       1/1       Running   0          4m
kube-system   nginx-ingress-controller-fmv6j   1/1       Running   0          4m

[fabiand@tee manifests (ingress)]$ curl $(minikube ip)
default backend - 404[fabiand@tee manifests (ingress)]$ 

# Ingress works!

#
# Cleanup, start over with CNI plugin
#

[fabiand@tee manifests (ingress)]$ minikube delete
Deleting local Kubernetes cluster...
Machine deleted.

[fabiand@tee manifests (ingress)]$ minikube start --vm-driver kvm --network-plugin cni
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.

[fabiand@tee manifests (ingress)]$ k get --all-namespaces pods
NAMESPACE     NAME                             READY     STATUS    RESTARTS   AGE
kube-system   default-http-backend-8k8wz       1/1       Running   0          1m
kube-system   kube-addon-manager-minikube      1/1       Running   0          1m
kube-system   kube-dns-910330662-9m2q4         3/3       Running   0          1m
kube-system   kubernetes-dashboard-lr4c7       1/1       Running   0          1m
kube-system   nginx-ingress-controller-jqgpz   1/1       Running   0          1m

[fabiand@tee manifests (ingress)]$ curl $(minikube ip)
curl: (7) Failed to connect to 192.168.42.222 port 80: Connection refused

# Ingress does not work!
```

### PR DESCRIPTION
**Pull request by fabiand**
Previously CNI was configured to use the bridge plugin.
But to support nodePorts, the portmap plugin had to be configued as well.

With this change the CNI config is moved to a config list (as supported
by cni >= 0.3.0). In this config list there is now the bridge configuration
and an additional one for the portmap plugin.

If this config is used on minikube, then the ingress pod will also work
with CNI.

Fixes #1987

### CODE REVIEW

**Comment by fabiand** [comment]
I've tested this by manually adding the config file to a already deployed minikube VM.

What I have not tested, but a reviewer can probably help here, is if the file I am now changing will really end up in the iso and thus VM.

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by r2d4** [comment]
@minikube-bot retest this please

**Comment by webcoderz** [comment]
changed this config on running minikube, and then restarted, and it regenerated the old config but ingress was working afterwards..

**Pull request closed without merging**
