### PR TITLE
Fix: "Your cgroup does not allow setting memory"

### PR DESCRIPTION
**Pull request by kadern0**
Fixes issue #12842 

This fix seems to be working, at least for me and a few others (please see the discussion within the issue URL). So far Ubuntu, Arch and Pop!_OS are working but additional testing would be good.

### CODE REVIEW

**Comment by kadern0** [comment]
I cannot find anywhere this function is being used `func IsCgroup2UnifiedMode()`. Maybe it could be removed.

**Comment by kadern0** [comment]
@medyagh , thanks for merging. I think #12842 can be closed.  What do you think about removing the function `IsCgroup2UnifiedMode()`?

**Comment by spowelljr** [comment]
Hi @kadern0, if that function is not used anywhere then feel free to create a PR removing it. I can close #12842, just as a heads up for next time, if you put `Fixes #12842` instead of `Fixes issue #12842` it will auto close that issue on PR merge.

**Pull request merged**
