### PR TITLE
regenerate config on retry

### LINKED ISSUE #8736: --delete-on-failure does not regenerate configuration
--delete-on-failure is unable to recover from issues like #8325 because the configuration file is not regenerated.

### PR DESCRIPTION
**Pull request by sharifelgamal**
Fixes #8736

Example of 1.9 config:
```
 cat ~/.minikube/profiles/minikube/config.json 
{
        "Name": "minikube",
        "KeepContext": false,
        "EmbedCerts": false,
        "MinikubeISO": "",
        "Memory": 3892,
        "CPUs": 2,
        "DiskSize": 20000,
        "Driver": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "HypervUseExternalSwitch": false,
        "HypervExternalAdapter": "",
        "KVMNetwork": "default",
        "KVMQemuURI": "qemu:///system",
        "KVMGPU": false,
        "KVMHidden": false,
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "NoVTXCheck": false,
        "DNSProxy": false,
        "HostDNSResolver": true,
        "HostOnlyNicType": "virtio",
        "NatNicType": "virtio",
        "KubernetesConfig": {
                "KubernetesVersion": "v1.18.0",
                "ClusterName": "minikube",
                "APIServerName": "minikubeCA",
                "APIServerNames": null,
                "APIServerIPs": null,
                "DNSDomain": "cluster.local",
                "ContainerRuntime": "docker",
                "CRISocket": "",
                "NetworkPlugin": "",
                "FeatureGates": "",
                "ServiceCIDR": "10.96.0.0/12",
                "ImageRepository": "",
                "ExtraOptions": [
                        {
                                "Component": "kubeadm",
                                "Key": "pod-network-cidr",
                                "Value": "10.244.0.0/16"
                        }
                ],
                "ShouldLoadCachedImages": true,
                "EnableDefaultCNI": false,
                "NodeIP": "",
                "NodePort": 0,
                "NodeName": ""
        },
        "Nodes": [
                {
                        "Name": "m01",
                        "IP": "172.17.0.2",
                        "Port": 8443,
                        "KubernetesVersion": "v1.18.0",
                        "ControlPlane": true,
                        "Worker": true
                }
        ],
        "Addons": {
                "default-storageclass": true,
                "storage-provisioner": true
        },
        "VerifyComponents": {
                "apiserver": true,
                "system_pods": true
        }
```

What a start with retry on failure now looks like:
```
minikube start --delete-on-failure=true
😄  minikube v1.12.1 on Darwin 10.15.5
🆕  Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
❗  Node m01 failed to start, deleting and trying again.
🔥  Deleting "minikube" in docker ...
🔥  Deleting container "minikube" ...
🔥  Removing /Users/selgamal/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=3892MB) ...
🌐  Found network options:
    ▪ NO_PROXY=172.17.0.2
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
    ▪ env NO_PROXY=172.17.0.2
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
```

And the config file after the retry:
```
cat ~/.minikube/profiles/minikube/config.json 
{
        "Name": "minikube",
        "KeepContext": false,
        "EmbedCerts": false,
        "MinikubeISO": "",
        "KicBaseImage": "gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438",
        "Memory": 3892,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "",
        "Driver": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "HypervUseExternalSwitch": false,
        "HypervExternalAdapter": "",
        "KVMNetwork": "default",
        "KVMQemuURI": "qemu:///system",
        "KVMGPU": false,
        "KVMHidden": false,
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "NoVTXCheck": false,
        "DNSProxy": false,
        "HostDNSResolver": true,
        "HostOnlyNicType": "virtio",
        "NatNicType": "virtio",
        "KubernetesConfig": {
                "KubernetesVersion": "v1.18.0",
                "ClusterName": "minikube",
                "APIServerName": "minikubeCA",
                "APIServerNames": null,
                "APIServerIPs": null,
                "DNSDomain": "cluster.local",
                "ContainerRuntime": "docker",
                "CRISocket": "",
                "NetworkPlugin": "",
                "FeatureGates": "",
                "ServiceCIDR": "10.96.0.0/12",
                "ImageRepository": "",
                "LoadBalancerStartIP": "",
                "LoadBalancerEndIP": "",
                "ExtraOptions": [
                        {
                                "Component": "kubeadm",
                                "Key": "pod-network-cidr",
                                "Value": "10.244.0.0/16"
                        }
                ],
                "ShouldLoadCachedImages": true,
                "EnableDefaultCNI": false,
                "CNI": "",
                "NodeIP": "",
                "NodePort": 8443,
                "NodeName": ""
        },
        "Nodes": [
                {
                        "Name": "m01",
                        "IP": "172.17.0.3",
                        "Port": 8443,
                        "KubernetesVersion": "v1.18.0",
                        "ControlPlane": true,
                        "Worker": true
                }
        ],
        "Addons": {
                "ambassador": false,
                "dashboard": false,
                "default-storageclass": true,
                "efk": false,
                "freshpod": false,
                "gvisor": false,
                "helm-tiller": false,
                "ingress": false,
                "ingress-dns": false,
                "istio": false,
                "istio-provisioner": false,
                "kubevirt": false,
                "logviewer": false,
                "metallb": false,
                "metrics-server": false,
                "nvidia-driver-installer": false,
                "nvidia-gpu-device-plugin": false,
                "olm": false,
                "pod-security-policy": false,
                "registry": false,
                "registry-aliases": false,
                "registry-creds": false,
                "storage-provisioner": true,
                "storage-provisioner-gluster": false
        },
        "VerifyComponents": {
                "apiserver": true,
                "system_pods": true
        }
```

### CODE REVIEW

**Comment by sharifelgamal** [comment]
cc @priyawadhwa @medyagh

**Comment by sharifelgamal** [comment]
> thank you for fixing this, do you mind sharing the before after this PR output?

There's no difference to minikube output

**Comment by medyagh** [comment]
> > thank you for fixing this, do you mind sharing the before after this PR output?
> 
> There's no difference to minikube output

how about different in the config file ? before and after?

**Comment by sharifelgamal** [comment]
> > > thank you for fixing this, do you mind sharing the before after this PR output?
> > 
> > 
> > There's no difference to minikube output
> 
> how about different in the config file ? before and after?

Done. Added to PR description.

**Pull request merged**
