### PR TITLE
Bump golang support to 1.10 - Fixing "cannot use nil as type _Ctype_CFDataRef in assignment" problem

### PR DESCRIPTION
**Pull request by stantonxu**
'make test' failed on the HEAD of Jun 4, 2018, due to issue #2860 

Fixed the problem here by removing "nil" from the assignment to CFDataRef

### CODE REVIEW

**Comment by dlorenc** [comment]
We can't make changes to the vendor directory directly like this. Can you try updating the dep instead of doing this?

**Comment by stantonxu** [comment]
@dlorenc , thanks for quick review. Could you please give me more hints about how to update the dep? Where to check it?

**Comment by stantonxu** [comment]
@dlorenc I spent whole afternoon, trying to figure out how to update dep for minikube. It looks that the code structure of google/certificate-transparency-go is different than the folder in minikube. How to update the dep, could you give some hint?

**Comment by dlorenc** [comment]
The flow to update a dependency is basically the same as the one specified here:
https://github.com/kubernetes/minikube/blob/master/docs/contributors/adding_a_dependency.md

This one is a bit tricky since as you point out, certificate-transparency has changed quite a bit. You'd have to find whatever is calling the old version of it, and update that (recursively) until nothing is using that old package anymore.

**Comment by stantonxu** [comment]
@dlorenc I see the difference about the "github.com/google/certificate-transparency..." vendor content in the Godeps.json between the Kubernetes project and minikube project.

In Kubernetes, it already uses the newest version, which handle the initialization of the CFDataRef type (which caused the original issue of this PR).

`
		{
			"ImportPath": "github.com/google/certificate-transparency-go",
			"Rev": "1bec4527572c443752ad4f2830bef88be0533236"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency-go/asn1",
			"Rev": "1bec4527572c443752ad4f2830bef88be0533236"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency-go/client",
			"Rev": "1bec4527572c443752ad4f2830bef88be0533236"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency-go/client/configpb",
			"Rev": "1bec4527572c443752ad4f2830bef88be0533236"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency-go/jsonclient",
			"Rev": "1bec4527572c443752ad4f2830bef88be0533236"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency-go/tls",
			"Rev": "1bec4527572c443752ad4f2830bef88be0533236"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency-go/x509",
			"Rev": "1bec4527572c443752ad4f2830bef88be0533236"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency-go/x509/pkix",
			"Rev": "1bec4527572c443752ad4f2830bef88be0533236"
		},
`

In minikube project, it still uses the old version,

`
		{
			"ImportPath": "github.com/google/certificate-transparency/go",
			"Rev": "af98904302724c29aa6659ca372d41c9687de2b7"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency/go/asn1",
			"Rev": "af98904302724c29aa6659ca372d41c9687de2b7"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency/go/client",
			"Rev": "af98904302724c29aa6659ca372d41c9687de2b7"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency/go/x509",
			"Rev": "af98904302724c29aa6659ca372d41c9687de2b7"
		},
		{
			"ImportPath": "github.com/google/certificate-transparency/go/x509/pkix",
			"Rev": "af98904302724c29aa6659ca372d41c9687de2b7"
		},
`

Can I just simply replace the minikube vendor about it with the newest one of Kubernetes? Or maybe do a dep update in minikube for all the google/certificate-transparency deps?

**Comment by dlorenc** [comment]
> Can I just simply replace the minikube vendor about it with the newest one of Kubernetes? Or maybe do a dep update in minikube for all the google/certificate-transparency deps?

Yeah, you'll basically need to update all the deps in minikube that rely on google/certificate-transparency, then update google/certificate-transparency itself.

**Comment by stantonxu** [comment]
@dlorenc is there a way (a command or so) to check if there are other deps rely on google/certificate-transparency? Or do I need to look into the Godeps.json files for each of the vendor dep and recursively to find it out? That will be huge amount of work.

**Comment by stantonxu** [comment]
I just simply did search in whole minikube project, found out that only another dep "github.com/cloudflare/cfssl" is using "google/certificate-transparency/go". In the newest version of "github.com/cloudflare/cfssl", it is already using "google/certificate-transparency-go" instead. So I guess the task turns to update vendor dep "github.com/cloudflare/cfssl".

Working on it now.

**Comment by stantonxu** [comment]
@dlorenc , so basically it is a compatibility problem, due to https://github.com/google/certificate-transparency-go/issues/131

I see that Kubernetes has already bump `cfssl` to be compatible with Go 1.10, https://github.com/kubernetes/kubernetes/pull/60373

Do we have any plan when we will make minikube compatible with Go 1.10?

I tried to update dep `cfssl`, but ran into couple problems. I have some questions here,

1. `cfssl` at HEAD shows build failed. However `go get -u` and then `godep update` doesn't allow me to update to specific version or tag. Do I have to use `dep` for specific version? 

2. `dep` needs to init project. Will that generate extra code which I don't want to check in?

3. I tried to `go get -u` `cfssl`, it has its own vendor folder, which including `google/certificate-transparency-go` and some other deps. The vendor folder of `cfssl` shows up in my minikube project. Is it safe to manually move those `cfssl` vendor deps from minikube/vendor/github.com/cloudflare/cfssl/vendor to the root vendor folder - minikube/vendor, and overwrite the existing ones?

General question, is it safe just update all vendor deps of minikube, instead of investigating each of them one by one? That's huge amount of work.

**Comment by dlorenc** [comment]
It looks like that PR to kubernetes was merged after 1.10, so we'll need to wait until Minikube either stops vendor kubernetes (https://github.com/kubernetes/minikube/pull/2870) or until we update to k8s 1.11.

**Comment by stantonxu** [comment]
@dlorenc although we are wait until Minikube either stops vendor kubernetes (https://github.com/kubernetes/minikube/pull/2870) or until we update to k8s 1.11 per your suggestion, I am trying to update the `github.com/cloudflare/cfssl`'s dependency - `github.com/google/certificate-transparency/go`, which should be updated to `github.com/google/certificate-transparency-go`

However `godep restore ./...` under `minikube` folder always runs into some problems. I find that there are some hack scripts under `minikube/hack/godeps`, but when I tried to run them, they also ran into problems like below,
```
!!! Error in ./hack/godep-restore.sh:34
  Error in ./hack/godep-restore.sh:34. 'GOPATH="${GOPATH}:${KUBE_ROOT}/staging" godep restore "$@"' exited with status 1
Call stack:
  1: ./hack/godep-restore.sh:34 main(...)
Exiting with status 1
```

Could you please help give me some hints?

My godep is at v79, and go is at 1.9.6

**Comment by stantonxu** [comment]
@dlorenc , do you have some time to look at my latest comment above? I could use some help here to move forward. Thanks.

**Comment by dlorenc** [comment]
> @dlorenc , do you have some time to look at my latest comment above? I could use some help here to move forward. Thanks.

Hey,

I think I mentioned this earlier somewhere, but I don't think you're going to be able to update the cfssl dependency. Minikube currently vendors k8s 1.10, which is pinned to the older version of the library. We'd need to patch k8s 1.10, updated to 1.11 or just delete the vendored code.

**Comment by stantonxu** [comment]
Thanks, @dlorenc . When we have the plan to upgrade to 1.11 or delete the vendored code, please let me know. I would like to continue and follow upon this PR, either commit corresponding changes or close it.

**Comment by stantonxu** [comment]
Golang version bump up being addressed by https://github.com/kubernetes/minikube/pull/2777, closing this PR.

**Pull request closed without merging**
