### PR TITLE
Add networking validation to validateNetwork

### LINKED ISSUE #4942: proxy+VPN: apiserver: timed out waiting for the condition
Hello,

I am on a Mac HighSierra 10.13.6.  I am on a VPN.  I set up my proxy for Docker in Docker Preferences, I can connect to my remote cluster using kubectl, I use the following commands to start minikube (I used actual proxy info):

vpn-135-210-77-42:~ jo$ export HTTP_PROXY='<proxy:port>'
vpn-135-210-77-42:~ jo$ export HTTPS_PROXY='<proxy:port>'
vpn-135-210-77-42:~ jo$ export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
vpn-135-210-77-42:~ jo$ minikube start
😄  minikube v1.2.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
🌐  Found network options:
    ▪ HTTP_PROXY=http://'<proxy:port>'
    ▪ HTTPS_PROXY=https://'<proxy:port>'
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
    ▪ env HTTP_PROXY='<proxy:port>'
    ▪ env HTTPS_PROXY='<proxy:port>'
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objects passed namespace/tkuo be-system unapplych
vpn-135-210-77-42:~ jo$ minikube logs > minikube.log

Will minikube work with a VPN?  Thank you for any assistance with this error!

[minikube.log](https://github.com/kubernetes/minikube/files/3457734/minikube.log)

### LINKED ISSUE #5426: Add VPN interference check: HTTP fetch before installing Kubernetes
Here's an idea to address #4302

Add a lightweight HTTP service to our VM that unobtrusively reports system stats, such as load average. As soon as we can confirm SSH access to our VM, and the VM appears to be of the correct version, try accessing this service.

Port 8443 would be ideal for catching the issue, but lets say a nearby port to avoid conflicts.

This would kill two birds with one stone:

- A lightweight way to gather system metrics without impacting VM load (compared to ssh+uptime command)
- A way to detect connectivity issues separate from Kubernetes. 

If it fails, we could report a very clear message, such as:

`Unable to make HTTP requests to the VM (http://<ip>:port). To use minikube, please adjust your firewall or VPN to allow these connections.`

We can always add `--force` to workaround issues with it.

### PR DESCRIPTION
**Pull request by tstromberg**
Behavioral differences:

- Fail with a clear exit message if minikube is unable to make a TCP connection to the VM. This checks using the ssh port. This should always work, but may not if we're using a special ssh driver  backdoor to access the VM, and the actual virtual network is down. Fixes #4942  

- Warn if there are internet access issues from inside of a VM, such as:
  * An inability to resolve DNS addresses
  * An inability to make direct internet connections
  * An inability to make HTTPS requests 

Here is an example failure:

```
🏃  Using the running hyperkit "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
💣  minikube is unable to connect to the VM at <no value>: dial tcp 192.168.64.3:22000: connect: connection refused

This is likely due to one of two reasons:

- VPN or firewall interference
- hyperkit network configuration issue

Suggested workarounds:

- Disable your local VPN or firewall software
- Configure your local VPN or firewall to allow access to 192.168.64.3
- Restart or reinstall hyperkit
- Use an alternative --vm-driver
```

Here is an example warning:

```
⚠️  VM is unable to connect to the Kubernetes container registry: command failed: curl -x localhost:631 -sS https://k8s.gcr.io/
stdout: 
stderr: curl: (7) Failed to connect to localhost port 631: Connection refused
```

Fixes #5426 #5570

### CODE REVIEW

**Comment by medyagh** [comment]
this is great ! I wonder if we could fit this https://github.com/kubernetes/minikube/issues/5570
in this PR also ? I undrestand if that could be a different PR

**Comment by tstromberg** [comment]
> this is great ! I wonder if we could fit this #5570 ( checking if we can ping the gcr.io or the image repo that they gave us.)
> in this PR also ? I undrestand if that could be a different PR

This kind of does so already, but I'll see about updating this to take into account the specified user image repository.

**Comment by tstromberg** [comment]
> this is great ! I wonder if we could fit this #5570 ( checking if we can ping the gcr.io or the image repo that they gave us.)
> in this PR also ? I undrestand if that could be a different PR

Done.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Pull request merged**
