### PR TITLE
Added sch_htb, cls_fw, cls_matchall, act_connmark and ifb kernel modules

### LINKED ISSUE #6721: sch_htb kernel module missing for network traffic shaping
The `net_htb` module is missing. Aside from general network traffic shaping, `net_htb` is used by Chaos Engineering tools such as [Gremlin](http://gremlin.com) to simulate poor network conditions, latency, etc. This is a similar use case to #6033 and #6738.

**The full output of the command that failed**:<details>
```
$ modprobe -n net_htb
modprobe: FATAL: Module net_htb not found in directory /lib/modules/4.19.81
```
</details>

**The operating system version**:
minikube version: v1.7.2
commit: 50d543b5fcb0e1c0d7c27b1398a9a9790df09dfb

### PR DESCRIPTION
**Pull request by imilchev**
Added these modules since they allow for traffic shaping within minikube by the use of `tc`. It also allows for using certain chaos engineering tools since they rely on these modules for simulating latency by the use of HTB, for example. This also fixes #6721.

### CODE REVIEW

**Comment by imilchev** [comment]
Signed the CLA.

**Review by priyawadhwa — APPROVED** [review]
LGTM, thank you for your contribution!

Have you been able to build the ISO yourself with these changes and make sure they work for your use case?

**Comment by imilchev** [comment]
Yes, I did build the ISO and tested it. Although it took me a while to figure out that I cannot build it on a Mac even though it builds within Docker. The changes indeed solve the HTB issue mentioned and I also added a bunch of other modules related to marking and filtering packets since they are often used in such tools. I intentionally built them as modules since probably not so many people are interested in those

**Comment by medyagh** [comment]
@imilchev  thank you for this PR

**Pull request merged**
