### PR TITLE
Fixed Windows installer replacing path

### LINKED ISSUE #704: Minikube windows installer replaces Windows system PATH environment variable
BUG REPORT

**Minikube version** v0.11.0

**Environment**:
- **OS** Windows 7
- **VM Driver** n/a
- **Docker version** Docker version 1.11.1, build 5604cbe
- **Install tools**:
- **Others**:

**What happened**:
Windows installer replaced the system PATH environment variable with the minikube path. All installed applications cannot run anymore.

**What you expected to happen**:
Expected the minikube executable path to only be appended to the system PATH.

**How to reproduce it** (as minimally and precisely as possible):
Use the installer to install a fresh minikube

**Anything else do we need to know**:
This is a major bug that can be quite catastrophic for some users.

### PR DESCRIPTION
**Pull request by rodcloutier**
Fixed Windows installer replacing path (Fixes #704) by defering to a script since nsis truncates on path too long.

**Situation**
The EnvVarUpdate.nsh function is documented as not to be used when updating PATH environment variable (See header in http://nsis.sourceforge.net/Environmental_Variables:_append,_prepend,_and_remove_entries) . 

> Warning this code will replace paths rather than append if the existing path exceeds the maximum string length in the NSIS build you are using. Some setup crash can also occurs.
> Default maximum string length is 1024, see Special_Builds for a 8192 max length.

**Fix**
Added a batch script that will do the same thing without any restriction on the environment variable length.

### CODE REVIEW

**Comment by rodcloutier** [comment]
@minikube-bot yes

**Comment by dlorenc** [comment]
Thanks a lot! @aaron-prindle can you take a look at this?

**Comment by aaron-prindle** [comment]
I have tested this on my machine and it is successfully adding/removing minikube from PATH.  Thanks!

**Comment by navossoc** [comment]
I just installed minikube and I got my path truncate to 1024 characters...

Bummer...

**Pull request merged**
