### PR TITLE
Ignore localhost proxy started with scheme.

### LINKED ISSUE #8881: Shouldn't pass scheme prefixed localhost proxy environment variables.
https://github.com/kubernetes/minikube/blob/32bf4d46a7202ff0d0d7e1500ba0a49d6bf37c87/pkg/minikube/proxy/proxy.go#L156-L170

```go
strings.HasPrefix(v, "localhost") || strings.HasPrefix(v, "127.0")
```

Proxy environment variables can start with scheme like `http://`.

/kind feature

### PR DESCRIPTION
**Pull request by lingsamuel**
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>

closes #8881 

This PR adds a "default" scheme `http://` (only for `url.Parse`) to the proxy values that don't have the scheme.

Fix a wrong test. Old test never failed because `v == test.proxy` always be `false`.

### CODE REVIEW

**Comment by lingsamuel** [comment]
I don't understand the error message https://storage.googleapis.com/minikube-builds/logs/8885/bb57ae0/VirtualBox_macOS.html#fail_TestNetworkPlugins%2fgroup%2fkindnet%2fDNS

> error: invalid resource name "deployment/netcat": [may not contain '/']

https://github.com/kubernetes/minikube/blob/efa7f615d76f0babbd2c7538ffca3f58e42ce433/test/integration/net_test.go#L155-L157

**Comment by medyagh** [comment]
thank you @lingsamuel

**Pull request merged**
