### PR TITLE
K8s 1.8

### PR DESCRIPTION
**Pull request by r2d4**

### CODE REVIEW

**Comment by r2d4** [comment]
@minikube-bot retest this please

**Comment by maciaszczykm** [comment]
@r2d4 Hi, at [Kubernetes Dashboard](https://github.com/kubernetes/dashboard) we have started using minikube for our integration tests. We are in the process of migration to 1.8 and adding new resources like Cron Jobs, so it would be extremely useful for us to be able to run 1.8 on Travis. Do you have any timeframe for it? You can check our minikube startup script at: https://github.com/kubernetes/dashboard/blob/master/build/minikube.sh.

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
@maciaszczykm hopefully in the next day or so.

**Comment by r2d4** [comment]
@dlorenc PTAL

**Comment by maciaszczykm** [comment]
@dlorenc Super, thanks!

**Comment by maciaszczykm** [comment]
> @maciaszczykm hopefully in the next day or so.

@dlorenc Just to clarify, does that mean the new release is coming?

**Pull request merged**
