### PR TITLE
Kicbase: Fix modifying Docker binfmt config

### PR DESCRIPTION
**Pull request by spowelljr**
Fixes https://github.com/kubernetes/minikube/issues/17700

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Review by medyagh — APPROVED** [review]

**Comment by spowelljr** [comment]
ok-to-build-image

**Pull request merged**
