### PR TITLE
Upgrade Docker to 1.12.6.

### LINKED ISSUE #1439: Upgrade to docker 1.12
Upstream k8s has upgraded and runs tests against 1.12

https://github.com/kubernetes/kubernetes/issues/28698

### PR DESCRIPTION
**Pull request by jgoclawski**
Fixes #1439 and #1518.

Based on #1542, but without forwarding issues, as those changes are introduced in Docker 1.13+.
We've tested #1542 to use overlay2 instead of overlay (#1380) and we're seeing great performance and stability improvements.

Can one of the admins trigger the ISO build, please? We'd love to test it internally, play around and give feedback.

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot ok to test

**Comment by jgoclawski** [comment]
Thanks for running the tests. It seems that all that should work have passed :)

If anyone wants to try the upgraded Docker 1.12, here is the command:
`minikube start --iso-url https://storage.googleapis.com/minikube-builds/1658/minikube-testing.iso`

I'm running this with storage driver changed from default `overlay` to `overlay2`:
`minikube start --iso-url https://storage.googleapis.com/minikube-builds/1658/minikube-testing.iso --docker-opt storage-driver=overlay2`

So far, so good, I haven't noticed any problems.

**Comment by dlorenc** [comment]
I think we should go ahead and take this. Thanks @jgoclawski!

**Comment by jgoclawski** [comment]
Thanks!

**Pull request merged**
