### PR TITLE
Write all empty translations strings to a file

### PR DESCRIPTION
**Pull request by afbjorklund**
Useful for seeing which strings have been removed

By running a diff between the strings and the language
(since we don't have any merge or fuzzy translations)

Also works for starting translating to a new language
(easier than writing `{}` to a new translations/*.json file)

Use .txt instead of .json, to avoid including it

### CODE REVIEW

**Comment by medyagh** [comment]
could strings.txt be all_strings.json ?

**Comment by sharifelgamal** [comment]
> could strings.txt be all_strings.json ?

It really shouldn't be a json file so we don't accidentally pick it up.

**Comment by afbjorklund** [comment]
In GNU gettext, they used `.po` for the translations and `.pot` for the "template":

For details see https://www.gnu.org/software/gettext/manual/html_node/Template.html

We don't really have such a framework, so making it up as we go along...

One thing I miss is the output statistics from the compiled translations:

```
$ i18next-conv -l sv -s sv.json -t sv.po
start converting
--> reading file from: sv.json
<-- writing file to: sv.po
file written
$ msgfmt --statistics sv.po -o sv.po
34 översatta meddelanden, 604 oöversatta meddelanden.
$ LANG=C msgfmt --statistics sv.po 
34 translated messages, 604 untranslated messages.
```

That's when compiling it to the smaller machine format:
```
60K	sv.po
8.0K	sv.mo
52K	sv.json
```

That would probably not be so hard to add to _our_ output...

```
go run cmd/extract/extract.go
Compiling translation strings...
Writing to de.json
Writing to es.json
Writing to fr.json
Writing to ja.json
Writing to ko.json
Writing to pl.json
Writing to sv.json
Writing to zh-CN.json
Done!
```

> do you mind add docs to site, how to use this feature (diff the strings.txt and others)

Yeah, that is probably a good idea! We also need to update/extract the other json files

They seem to be a bit out of sync, and I'm not sure what to do with "fuzzy" messages ?

For details see https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html

Unfortunately JSON is such a silly format that it doesn't even _have_ comments ([Hjson](https://hjson.github.io/) FTW!)

**Comment by sharifelgamal** [comment]
I picked json because it was easy to marshal to/unmarshal from a map in golang, I'm not opposed to picking a different file type.

**Comment by afbjorklund** [comment]
> I picked json because it was easy to marshal to/unmarshal from a map in golang, I'm not opposed to picking a different file type.

And it works fine for that. Picking yaml would be even harder. Still: no comments.

**Comment by medyagh** [comment]
> In GNU gettext, they used `.po` for the translations and `.pot` for the "template":
> 
> For details see https://www.gnu.org/software/gettext/manual/html_node/Template.html
> 
> We don't really have such a framework, so making it up as we go along...
> 
> One thing I miss is the output statistics from the compiled translations:
> 
> ```
> $ i18next-conv -l sv -s sv.json -t sv.po
> start converting
> --> reading file from: sv.json
> <-- writing file to: sv.po
> file written
> $ msgfmt --statistics sv.po -o sv.mo
> 34 översatta meddelanden, 604 oöversatta meddelanden.
> $ LANG=C msgfmt --statistics sv.po 
> 34 translated messages, 604 untranslated messages.
> ```
> 
> That's when compiling it to the smaller machine format:
> 
> ```
> 60K	sv.po
> 8.0K	sv.mo
> 52K	sv.json
> ```
> 
> That would probably not be so hard to add to _our_ output...
> 
> ```
> go run cmd/extract/extract.go
> Compiling translation strings...
> Writing to de.json
> Writing to es.json
> Writing to fr.json
> Writing to ja.json
> Writing to ko.json
> Writing to pl.json
> Writing to sv.json
> Writing to zh-CN.json
> Done!
> ```
> 
> > do you mind add docs to site, how to use this feature (diff the strings.txt and others)
> 
> Yeah, that is probably a good idea! We also need to update/extract the other json files
> 
> They seem to be a bit out of sync, and I'm not sure what to do with "fuzzy" messages ?
> 
> For details see https://www.gnu.org/software/gettext/manual/html_node/Fuzzy-Entries.html
> 
> Unfortunately JSON is such a silly format that it doesn't even _have_ comments ([Hjson](https://hjson.github.io/) FTW!)

ok then thats fine, if plz just update the website docs how to use it,
 we could merge it

**Comment by afbjorklund** [comment]
Think this should be harmless (only updates a text file even if it is to be checked in)

But haven't gotten around to writing the required website documentation so far

**Pull request merged**
