### PR TITLE
Improve the go reportcard for minikube

### PR DESCRIPTION
**Pull request by afbjorklund**
Fix gofmt, golint, and most of gocyclo
(but not the integration tests just yet)

```
gofmt: 99%
	pkg/minikube/machine/cluster_test.go
		Line 1: warning: file is not gofmted with -s (gofmt)
golint: 99%
	pkg/minikube/tunnel/loadbalancer_patcher.go
		Line 47: warning: exported method LoadBalancerEmulator.PatchServices should have comment or be unexported (golint)
		Line 51: warning: exported method LoadBalancerEmulator.PatchServiceIP should have comment or be unexported (golint)
		Line 57: warning: exported method LoadBalancerEmulator.Cleanup should have comment or be unexported (golint)
		Line 146: warning: exported function NewLoadBalancerEmulator should have comment or be unexported (golint)
gocyclo: 99%
	cmd/minikube/cmd/delete.go
		Line 188: warning: cyclomatic complexity 20 of function deleteProfile() is high (> 15) (gocyclo)
		Line 92: warning: cyclomatic complexity 16 of function runDelete() is high (> 15) (gocyclo)
	pkg/minikube/cruntime/cruntime_test.go
		Line 228: warning: cyclomatic complexity 22 of function (*FakeRunner).docker() is high (> 15) (gocyclo)
	cmd/minikube/cmd/start.go
		Line 277: warning: cyclomatic complexity 17 of function runStart() is high (> 15) (gocyclo)
	pkg/minikube/bootstrapper/kubeadm/kubeadm.go
		Line 388: warning: cyclomatic complexity 16 of function (*Bootstrapper).UpdateCluster() is high (> 15) (gocyclo)
	pkg/minikube/image/cache.go
		Line 77: warning: cyclomatic complexity 16 of function saveToTarFile() is high (> 15) (gocyclo)
	pkg/minikube/bootstrapper/bsutil/kubelet.go
		Line 33: warning: cyclomatic complexity 16 of function NewKubeletConfig() is high (> 15) (gocyclo)
	pkg/minikube/machine/fix.go
		Line 227: warning: cyclomatic complexity 28 of function machineExists() is high (> 15) (gocyclo)
		Line 59: warning: cyclomatic complexity 21 of function fixHost() is high (> 15) (gocyclo)
```

### CODE REVIEW

**Comment by medyagh** [comment]
@afbjorklund is this a wip ? Or are you done updating it ?

**Comment by medyagh** [comment]
Code looks so much cleaner and more readable

**Comment by afbjorklund** [comment]
It was done, for now...

We need to come up with a more structured way of converting the integration tests, like changing the inline array to use separate functions and a struct instead

**Comment by medyagh** [comment]
I wonder , if TestFunctional/parallel/CertSync failure is related to this PR ?
I had not seen this before

**Comment by medyagh** [comment]
https://storage.googleapis.com/minikube-builds/logs/6959/bdbc7c0/Docker_Linux.html#fail_TestFunctional%2fparallel%2fCertSync

**Pull request merged**
