### PR TITLE
Update the 1.4 alpha branch to beta.0

### PR DESCRIPTION
**Pull request by dlorenc**
This required a manual fix, which I left in a separate commit.

### CODE REVIEW

**Comment by dlorenc** [comment]
This is failing to start with:

```shell
panic: cannot find suitable quantum for 0

goroutine 1441 [running]:
panic(0x383cf60, 0xc82039a780)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/minikube/vendor/github.com/juju/ratelimit.NewBucketWithRate(0x0, 0x1, 0xc822e5af70)
	/usr/local/google/home/dlorenc/newgopath/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/juju/ratelimit/ratelimit.go:64 +0x150
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/flowcontrol.NewTokenBucketRateLimiter(0x0, 0x1, 0x0, 0x0)
	/usr/local/google/home/dlorenc/newgopath/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/flowcontrol/throttle.go:53 +0x3d
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/controller/node.(*NodeController).monitorNodeStatus(0xc822c74d80, 0x0, 0x0)
	/usr/local/google/home/dlorenc/newgopath/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:503 +0x676
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/controller/node.(*NodeController).Run.func1()
	/usr/local/google/home/dlorenc/newgopath/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:396 +0x24
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820f8e570)
	/usr/local/google/home/dlorenc/newgopath/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:84 +0x19
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820f8e570, 0x12a05f200, 0x0, 0x1, 0xc820051740)
	/usr/local/google/home/dlorenc/newgopath/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:85 +0xb4
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc820f8e570, 0x12a05f200, 0xc820051740)
	/usr/local/google/home/dlorenc/newgopath/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x43
created by k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/controller/node.(*NodeController).Run
	/usr/local/google/home/dlorenc/newgopath/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/controller/node/nodecontroller.go:399 +0x189
```

I'll keep debugging later. Looks like a value of 0 is making it into a wait.Until somehow.

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
Cool, this should be working now. PTAL.

**Comment by luxas** [comment]
`v1.4.0-beta.0` is out! :)

**Comment by dlorenc** [comment]
@luxas nice! updating to 1.4.0-beta.0

**Comment by r2d4** [comment]
might be nice to include the corresponding 1.4 beta dashboards

https://github.com/kubernetes/dashboard/releases

**Comment by dlorenc** [comment]
Ooh, good idea. But I don't think we can do that right now, the dashboard manifest is versioned with minikube, not with localkube. We should reconsider that.

**Comment by r2d4** [comment]
Ahh yeah thats right.  LGTM

**Pull request merged**
