### PR TITLE
Upgrade Docker, from 20.10.4 to 20.10.6

### PR DESCRIPTION
**Pull request by afbjorklund**
And containerd from 1.4.3 to 1.4.4 as well

Replaces ~~PR #10860~~

### CODE REVIEW

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
@ilya-zuyev : seems like the build got broken by 65d99104883ec720ba8659b0458c2fede5a10646

```
ERROR: v1.20.0.tar.gz has wrong sha256 hash:
ERROR: expected: 76fd7543bc92d4364a11060f43a5131893a76c6e6e9d6de3a6bb6292c110b631
ERROR: got     : 792d86f0d5ba9ed5a89e7066b14dec5c6d4c5b7f11d829f3cb2b645720d1ca11
ERROR: Incomplete download, or man-in-the-middle (MITM) attack
```

**Comment by medyagh** [comment]
> @ilya-zuyev : seems like the build got broken by [65d9910](https://github.com/kubernetes/minikube/commit/65d99104883ec720ba8659b0458c2fede5a10646) (see #10975)
> 
> ```
> ERROR: v1.20.0.tar.gz has wrong sha256 hash:
> ERROR: expected: 76fd7543bc92d4364a11060f43a5131893a76c6e6e9d6de3a6bb6292c110b631
> ERROR: got     : 792d86f0d5ba9ed5a89e7066b14dec5c6d4c5b7f11d829f3cb2b645720d1ca11
> ERROR: Incomplete download, or man-in-the-middle (MITM) attack
> ```

@afbjorklund this SHA keeps flipinng, every single time we build it it complains about SHA and we keep reverting it

**Comment by afbjorklund** [comment]
> every single time we build it it complains about SHA and we keep reverting it

Please don't revert it. It got changed upstream, because they use `git archive`

**Comment by medyagh** [comment]
> > every single time we build it it complains about SHA and we keep reverting it
> 
> Please don't revert it. It got changed upstream, because they use `git archive`
> 
> But anyway, it is unrelated to upgrading Docker so let's handle it elsewhere.
> 
> Workaround: #11111 (cri-o upgrade)
> 
> Maybe should file an upstream ticket about it, see if they can remove the file...

yes plz. we had to revert it because we needed to build a New ISO for the release

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
I think this PR is probably better to be rebased

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Pull request merged**
