### PR TITLE
QEMU: add support for binfmt emulators

### PR DESCRIPTION
**Pull request by michelesr**
Adds the missing kernel compilation flag `CONFIG_BINFMT_MISC=y` that is required by the Docker runtime to run images with emulated CPU architecture. See https://docs.docker.com/build/building/multi-platform for more information.

### CODE REVIEW

**Comment by afbjorklund** [comment]
ok-to-build-image

/ok-to-test

**Comment by spowelljr** [comment]
That rebase didn't go good...

**Comment by spowelljr** [comment]
I don't have write access to https://github.com/michelesr/minikube/tree/master so I can't push his commit back onto his repo

```
commit 582472bbe86a71410d0291fcab4fd9ce792e2087 (HEAD -> michelesr/master)
Author: Michele Sorcinelli <michele.sorcinelli@citizensadvice.org.uk>
Date:   Mon Apr 17 13:19:02 2023 +0100

    Add CONFIG_BINFMT_MISC=y flag
```

Yet I was somehow able to blow away his commit without write access?

**Comment by michelesr** [comment]
> yet I was somehow able to blow away his commit without write access?

@spowelljr not sure, but there's a setting that allows edits from maintainers and I suspect it might have been enabled before the PR was closed (it shows as disabled now but maybe it changed automatically after PR closure)

**Comment by spowelljr** [comment]
This change is merged via https://github.com/kubernetes/minikube/pull/16712

**Pull request closed without merging**
