### PR TITLE
feat: make is easier to enable structured logging

### LINKED ISSUE #9268: feature: make it easier to enable JSON format for structured logging
Kubernetes 1.19 seen a big push for ensuring the Kubernetes components produce structured logs. Each components can be passed the `--logging-format` flag to tweak the output format of these structured logs. Available formats at the time of this issue are `text` and `json`, with the former being the default.

I'd like to see `minkube` support a single flag for enabling the format to be switched to JSON

`minikube --logging-format=json`, which should result in `--logging-format=json` being sent to the Kubelet, Scheduler, APIServer, and others.

### PR DESCRIPTION
**Pull request by rawkode**
Closes #9268

### CODE REVIEW

**Review by medyagh — CHANGES_REQUESTED** [review]
do you mind putting the PR description what this is trying to slove?
and I see a lot of unrelated changes to this PR do you mind making a separate PR for each seprate issue

**Comment by afbjorklund** [comment]
> do you mind putting the PR description what this is trying to slove?

Even better to make an issue about the feature, and link the PR to it

**Comment by rawkode** [comment]
@medyagh Those unrelated changes are my editor auto formatting :'(

**Comment by rawkode** [comment]
I'll aim to get this up to scratch by the weekend 👍🏻 

Issue opened too

**Review by medyagh — CHANGES_REQUESTED** [review]
do you mind sharing the output before and after this PR ?

**Comment by priyawadhwa** [comment]
Hey @rawkode are you still working on this? It needs a rebase.

**Comment by priyawadhwa** [comment]
Hey @rawkode since this PR has been quiet for a few weeks I'm going to close it temporarily -- feel free to reopen at any time whenever you have a chance to rebase/address review comments.

**Pull request closed without merging**
