### PR TITLE
Kicbase: Update base image to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by spowelljr**
Update the base image of kicbase from Ubuntu 20.04 to 22.04

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-image

**Review by afbjorklund — APPROVED** [review]

**Comment by afbjorklund** [comment]
The `xUbuntu_20.04` will also need updating.

**Comment by spowelljr** [comment]
> The `xUbuntu_20.04` will also need updating.

Good catch

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
Current issue:

With Ubuntu 22.04, `podman` is now installed via the default Ubuntu repos, one of its dependencies is `golang-github-containers-common`. `cri-o` is still installed via the `opensuse.org` repo, one of its dependencies is `containers-common`. This results in a conflict because `golang-github-containers-common` and `containers-common` both try to modify `/etc/containers/policy.json`.

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
@spowelljr can we check manually the ARM and CRIO Docker tests are normal ?
I belive our flake rate is skipping Arm and CRIO

**Comment by spowelljr** [comment]
> @spowelljr can we check manually the ARM and CRIO Docker tests are normal ? I belive our flake rate is skipping Arm and CRIO

arm64 looks good, but CRI-O does look like it's having some problems

**Comment by spowelljr** [comment]
| Run | Total Time (seconds) | CPU Usage (seconds) |
| --- | --- | --- |
| Before | 41.5376 | 4.9772 |
| After | 40.1526 | 5.0144 |
| Diff | -1.385 (-0.03%) | +0.0372 (+0.007%)

**Pull request merged**
