### PR TITLE
translations: Fix translation on wrong line

### PR DESCRIPTION
**Pull request by spowelljr**

### CODE REVIEW

**Comment by uos-ljtian** [comment]
There was a problem with the content I submitted. I'm very sorry. I will check it again next time.

**Comment by prezha** [comment]
no worries @uos-ljtian and thank you for the contribution!

you can use eg `go test ./pkg/minikube/translate -run TestTranslationFilesValid -v` for local testing

**Comment by uos-ljtian** [comment]
The modification is correct

**Review by prezha — APPROVED** [review]
@uos-ljtian thanks for confirming!

**Pull request merged**
