### PR TITLE
update to newer ubuntu_18_0_4

### PR DESCRIPTION
**Pull request by MaXinjian**
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by afbjorklund** [comment]
We use an older ubuntu image on purpose, in order to hold the libvirt version back: ~#3437~

https://packages.ubuntu.com/search?keywords=libvirt-dev

Note that there is a test for this, which will **fail** after this PR:
```
# make extra sure that we are linking with the older version of libvirt (1.3.1)
test "`strings out/docker-machine-driver-kvm2-amd64 | grep '^LIBVIRT_[0-9]' | sort | tail -n 1`" = "LIBVIRT_1.2.9"
make: *** [Makefile:638: out/docker-machine-driver-kvm2-amd64] Error 1
```

This could be documented better, for instance by specifying the version of libvirt-dev ? (< 2)

**Review by afbjorklund — CHANGES_REQUESTED** [review]
I don't think we should upgrade the kvm-build-image base

**Comment by MaXinjian** [comment]
> We use an older ubuntu image on purpose, in order to hold the libvirt version back: ~#3437~
> 
> https://packages.ubuntu.com/search?keywords=libvirt-dev
> 
> Note that there is a test for this, which will **fail** after this PR:
> 
> ```
> # make extra sure that we are linking with the older version of libvirt (1.3.1)
> test "`strings out/docker-machine-driver-kvm2-amd64 | grep '^LIBVIRT_[0-9]' | sort | tail -n 1`" = "LIBVIRT_1.2.9"
> make: *** [Makefile:638: out/docker-machine-driver-kvm2-amd64] Error 1
> ```
> 
> This could be documented better, for instance by specifying the version of libvirt-dev ? (< 2)

Thanks for kindly review. I will close this PR

**Comment by afbjorklund** [comment]
Thanks for contributing! We might revisit next year (2021), when 16.04 LTS goes of of support

**Pull request closed without merging**
