### PR TITLE
Upgrade Docker, from 17.06 to 17.09

### PR DESCRIPTION
**Pull request by afbjorklund**

### CODE REVIEW

**Comment by afbjorklund** [comment]
17.12.0 seems to fail horribly, will try with 17.09.0 instead

**Comment by dlorenc** [comment]
Thanks!

**Comment by afbjorklund** [comment]
The reason that 17.12.0 didn't work was because DOCKER_RAMDISK stopped working in containerd:
https://github.com/moby/moby/pull/35957

It has been fixed in the 18.02 release, so we will be able to upgrade to 18.03.0-ce once it comes out.
Meanwhile, we _could_ upgrade to 17.09.0 to 17.09.1 - and remove the checksum for 17.12.0 perhaps.

**Comment by karser** [comment]
I just compiled ISO locally - it seems to be working
```
sha256 1270dce1bd7e1838d62ae21d2505d87f16efc1d9074645571daaefdfd0c14054  docker-17.12.1-ce.tgz
DOCKER_BIN_VERSION = 17.12.1-ce
```

**Comment by afbjorklund** [comment]
@karser : sure, that would work too...

**Comment by afbjorklund** [comment]
@karser : added a PR, we'll see how it goes..
Docker 18.03 is currently on RC3, I believe ?
So might as well wait for 18.03.1-ce, it seems
(good ole "always wait for Service Pack 1" rule)

**Comment by karser** [comment]
18.03.0-ce has been released

**Comment by afbjorklund** [comment]
@karser : and yet, only 17.03 is _supported_: (by `kubeadm`)

https://kubernetes.io/docs/setup/independent/install-kubeadm/#installing-docker
> On each of your machines, install Docker. Version v1.12 is recommended, but v1.11, v1.13 and 17.03 are known to work as well. Versions 17.06+ might work, but have not yet been tested and verified by the Kubernetes node team.

Think we should rest on 17.12, at least for a month or so ?

https://docs.docker.com/install/#time-based-release-schedule
> * Docker CE Stable releases generally happen quarterly, with patch releases as needed.
> * A given Docker CE Stable release receives patches and updates for one month after the next Docker CE Stable release.

---
Still cleaning up after the 1.12.6 to 1.13.1 rebase on CentOS...
Upgrading for the sake of upgrading is highly overrated, I think.

**Comment by karser** [comment]
>only 17.03 is supported
Ugh, that's an ancient one

>for the sake of upgrading
For me, it's not like that. 17.12 allows to copy a folder and set the ownership in one step, e.g: `COPY --chown=user:user . ./`

**Comment by afbjorklund** [comment]
The 17.12.1-ce release should _already_ be the default: cc965e37930e2e8ebe9e9de8afe5fdd3d81bda69

But since there hasn't been a new ISO/distro release, you will need to compile your own buildroot...

@r2d4: Maybe it is time to bump the ISO_VERSION to `v0.25.2` ?

I guess some people use the minikube docker as their main docker, and thus need newer versions.

**Pull request merged**
