### PR TITLE
Stop applying the beta.kubernetes.io/os and arch

### PR DESCRIPTION
**Pull request by pacoxu**
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

### CODE REVIEW

**Comment by pacoxu** [comment]
Are the failed test cases related to the change? I think not.

**Comment by spowelljr** [comment]
> Are the failed test cases related to the change? I think not.

No, these are unrelated to the change

**Review by spowelljr — APPROVED** [review]
Looks good to me, thanks for the PR

**Pull request merged**
