### PR TITLE
Update buildkit to v0.11.0

### PR DESCRIPTION
**Pull request by kushmansingh**
Before:
`buildctl github.com/moby/buildkit v0.10.3`

After:
`buildctl github.com/moby/buildkit v0.11.0`

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by afbjorklund** [comment]
Changed the title, because it sounded like a go dependency update (next to the other firehose of updates)

**Review by spowelljr — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
