### PR TITLE
Updating upstream spf13/pflag and using StringArrayVar for docker-env flag

### PR DESCRIPTION
**Pull request by spk83**
Fixes issue #811 by updating upstream spf13/pflag and using StringArrayVar in place of StringSliceVar for docker-env flag

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot OK to test

**Comment by dlorenc** [comment]
Could you sign the CLA?

**Comment by spk83** [comment]
Working on it

**Comment by spk83** [comment]
@dlorenc Done signing CLAs - Google and LinuxFoundation.

**Comment by jimmidyson** [comment]
@spk83 Need to run `make gendocs` to generate updated docs - looks like updated pflag changes output slightly.

**Comment by spk83** [comment]
@jimmidyson Having some issue running make on MacOSX with docker-machine. docker-machine is mounting empty minikube directory as volume. will generate the updated docs as soon as I can.

**Comment by dlorenc** [comment]
You might need to make sure your GOPATH is in /Users, so the volume gets mounted into the VM correctly.

**Comment by spk83** [comment]
@dlorenc yes, GOPATH requires to be under /Users. Issue was with docker-machine-driver-xhyve not mounting nfs correctly. docker-machine-nfs fixed it.

**Comment by spk83** [comment]
thanks @r2d4!

**Pull request merged**
