### PR TITLE
WIP: Upgrade kindbase to later version and ubuntu:20.04

### LINKED ISSUE #8250: Upgrade kicbase to Ubuntu 20.04 LTS
We should upgrade the kind base image, and ubuntu from 19.10 to 20.04

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #8250 #8766 #8767

### CODE REVIEW

**Comment by afbjorklund** [comment]
> is possible to push it to a public registry and change the image to your -snapshot in the code so we can see the integration results ?

It would be better to fix the code so that you could run a local snapshot _without_ having to push it to some registry, but I suppose we can

**Comment by afbjorklund** [comment]
Unfortunately I think the current release procedure is off-limits to anyone without the gcr.io credentials, so I can't push _any_ type of images. Not the build images, not the storage-provisioner, not this one...

**Comment by afbjorklund** [comment]
Hmm, today it seems like `--base-image` actually works ? Wonder what was the issue yesterday...

`Successfully tagged gcr.io/k8s-minikube/kicbase:v0.0.10-snapshot`

`--base-image gcr.io/k8s-minikube/kicbase:v0.0.10-snapshot`

```
😄  [kicbase] minikube v1.10.1 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node kicbase in cluster kicbase
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.8 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "kicbase"
```

```
docker@kicbase:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

And I guess I need to bump the version too, to something like `v0.0.11` - or maybe `v0.1.1` ?

**Comment by afbjorklund** [comment]
@medyagh : try `afbjorklund/kicbase:v0.0.10-snapshot`

`v0.0.10-snapshot: digest: sha256:729f74899c8619d817011cc365927a774be0d2f009a0ed1182dcd8d6a74db241 size: 4908`

Based on `kindest/base:v20200513-fd490400`
In turn is based on `ubuntu:focal-20200423`

----

```
REPOSITORY                                                         TAG                                IMAGE ID            CREATED             SIZE
ubuntu                                                             20.04                              1d622ef86b13        4 weeks ago         73.9MB
kindest/base                                                       v20200513-fd490400                 c4b19ed8c9eb        9 days ago          284MB
gcr.io/k8s-minikube/kicbase                                        v0.0.10-snapshot                   4755e5c58e15        4 hours ago         942MB
```

Note that the digest are different, even though the contents are the same

**Comment by medyagh** [comment]
> `afbjorklund/kicbase:v0.0.10-snapshot`
> 
> `v0.0.10-snapshot: digest: sha256:729f74899c8619d817011cc365927a774be0d2f009a0ed1182dcd8d6a74db241 size: 4908`

@afbjorklund can you please put that in the types.go in kic package so it triggers a test using that image? once it is good I will push it to gcr

**Comment by afbjorklund** [comment]
>  once it is good I will push it to gcr

But when you push it to gcr, it changes ?

**Comment by afbjorklund** [comment]
But you mean like do a separate PR, where changing the image ? Like a throwaway

**Comment by afbjorklund** [comment]
> is possible to push it to a public registry and change the image to your -snapshot in the code so we can see the integration results ?

Trying something out in #8262

**Comment by afbjorklund** [comment]
> it isn't clear to me on how I can see the test results.

me neither (a problem?), it seemed to work locally though

**Comment by afbjorklund** [comment]
It shouldn't be needed to downgrade podman anymore, can move to 1.9.3 instead

**Comment by medyagh** [comment]
as discussed in the office hours, I rather we combine this PR with Ruben's PR and make a consolidate change for the beta

**Comment by afbjorklund** [comment]
I don't think there were any major changes in #7884, besides forking/copying the entrypoint and trying to pin the package versions (something that we have shown that it _doesn't work_, a couple of times)

We didn't really come to a decision about #7788 on the meeting, there were some minor space savings to be had from it and we could clean up our Dockerfile by using the kindbase `clean-install` script.

But if we want to go that route, I could join the changes from it here: https://github.com/kubernetes/minikube/compare/master...afbjorklund:kicbase

I still used the previous version of ubuntu (19.10) and the previous entrypoint, in that other discussion

**Comment by medyagh** [comment]
> I don't think there were any major changes in #7884, besides forking/copying the entrypoint and trying to pin the package versions (something that we have shown that it _doesn't work_, a couple of times)
> 
> We didn't really come to a decision about #7788 on the meeting, there were some minor space savings to be had from it and we could clean up our Dockerfile by using the kindbase `clean-install` script.
> 
> But if we want to go that route, I could join the changes from it here: [master...afbjorklund:kicbase](https://github.com/kubernetes/minikube/compare/master...afbjorklund:kicbase)
> 
> I still used the previous version of ubuntu (19.10) and the previous entrypoint, in that other discussion

I think we should move off kindbase so we install lastet version of containerd instead of nightly build

**Comment by medyagh** [comment]
plz update the version in the types.go to
```
// Version is the current version of kic
    Version = "v0.0.11"
    // SHA of the kic base image
    baseImageSHA = "742264bf43555709cfa141878b643de58961801ddf778e3cde8713495dd7bfec"
```

**Comment by afbjorklund** [comment]
> plz update the version in the types.go to
> 
> ```
> // Version is the current version of kic
>     Version = "v0.0.11"
>     // SHA of the kic base image
>     baseImageSHA = "742264bf43555709cfa141878b643de58961801ddf778e3cde8713495dd7bfec"
> ```

Ok

**Comment by afbjorklund** [comment]
> I think we should move off kindbase so we install lastet version of containerd instead of nightly build so lets brings those changes here

This image will still install the old containerd (as a docker requirement), so it's more a question of making the image a little smaller

**Comment by afbjorklund** [comment]
Will try to upgrade podman and cri-o, for the next version... Might have to build it from source:

https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable:cri-o:1.18/cri-o?rev=4

**Comment by afbjorklund** [comment]
https://dl.bintray.com/afbjorklund/cri-o/pool/main/c/cri-o/:cri-o_1.18.1~1_amd64.deb

> Using the command line, add the following to your /etc/apt/sources.list system config file:
>
> `echo "deb https://dl.bintray.com/afbjorklund/cri-o {distribution} {components}" | sudo tee -a /etc/apt/sources.list`

**Comment by afbjorklund** [comment]
Added some cleanup from the kindbase installs, rather than forking the files and entrypoint.

```Dockerfile
RUN rm \
    /etc/crictl.yaml \
    /etc/systemd/system/multi-user.target.wants/containerd.service \
    /opt/cni/bin/host-local \
    /opt/cni/bin/loopback \
    /opt/cni/bin/portmap \
    /opt/cni/bin/ptp \
    /usr/local/bin/containerd \
    /usr/local/bin/containerd-shim \
    /usr/local/bin/containerd-shim-runc-v2 \
    /usr/local/bin/crictl \
    /usr/local/bin/ctr \
    /usr/local/sbin/runc
```

The end result doesn't seem _that_ much worse, it's even smaller than the current kicbase ?

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
kindbase            latest              9aab24e656fc        37 minutes ago      132MB
kicbase             latest              3200008055a0        About a minute ago  925MB
```

This is because I used the `clean-install` script, rather than copy/pasting it in several steps.

**Comment by tstromberg** [comment]
Do you mind resolving the conflicts?

**Comment by medyagh** [comment]
closing in favor of https://github.com/kubernetes/minikube/pull/8869

**Pull request closed without merging**
