### PR TITLE
Add auto pause on arm64 image

### PR DESCRIPTION
**Pull request by medyagh**

### CODE REVIEW

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Review by ilya-zuyev — APPROVED** [review]
lgtm

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Pull request merged**
