### PR TITLE
Upgrade Docker, from 20.10.4 to 20.10.5

### PR DESCRIPTION
**Pull request by afbjorklund**
/hold

This goes in after PR #10647

### CODE REVIEW

**Comment by afbjorklund** [comment]
/unhold

ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Pull request closed without merging**
