### PR TITLE
ISO/Kicbase: Update cri-dockerd from 0.3.0 to 0.3.1

### PR DESCRIPTION
**Pull request by spowelljr**
Used some code from @afbjorklund's https://github.com/kubernetes/minikube/pull/14827

Also updated automation to auto update hash files

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Review by medyagh — APPROVED** [review]
look good to me

**Pull request merged**
