### PR TITLE
Wait for crictl version after the socket is up

### LINKED ISSUE #10355: Race condition in containerd restart when using --container-runtime=containerd and containerd was previously initialized
I'm running minikube on SLES 12.5 on bare-metal machine, and I'm aware of the warning that containerd with --driver=none is experimental. However, it seemed to work once, but not anymore with 1.17.1. There seems to be a race condition where crictl command is called before containerd is fully started. Following command is ran as root user, hence no sudo (I'm fully aware of the issues that may arise).

```
KUBERNETES_VERSION=v1.20.2
SERVER_ADDRESS=redacted

minikube start --driver=none --apiserver-ips="${SERVER_ADDRESS}" --apiserver-port=6443 \
               --embed-certs=true --install-addons=false --kubernetes-version="${KUBERNETES_VERSION}" \
               --container-runtime=containerd --cni=calico
```

**Full output of `minikube start` command used, if not already included:**

```
😄  minikube v1.17.1 on Suse 12.5
✨  Using the none driver based on user configuration
❗  Using the 'containerd' runtime with the 'none' driver is an untested configuration!
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=8, Memory=64159MB, Disk=40962MB) ...
ℹ️  OS release is SUSE Linux Enterprise Server 12 SP5
📦  Preparing Kubernetes v1.20.2 on containerd 1.4.3 ...

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: get cri info: sudo crictl info: exit status 1
stdout:

stderr:
time="2021-02-03T10:14:44+01:00" level=fatal msg="getting status of runtime: rpc error: code = Unknown desc = server is not initialized yet"


😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

If I run `sudo crictl info`, I get the JSON output the command expects. So there seems to be a race condition between writing a containerd.toml file, restarting containerd and issuing crictl command to get the cgroup driver.

I have found out that this happens when containerd is previously initialized in /var/lib/containerd and has lots of data. If I wipe all containerd data, containerd will start up much faster, and the same command will succeed.

```
😄  minikube v1.17.1 on Suse 12.5
✨  Using the none driver based on user configuration
❗  Using the 'containerd' runtime with the 'none' driver is an untested configuration!
✅  Using image repository reg-hrpap.app.corpintra.net/infrastructure
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=8, Memory=64159MB, Disk=40962MB) ...
ℹ️  OS release is SUSE Linux Enterprise Server 12 SP5
📦  Preparing Kubernetes v1.20.2 on containerd 1.4.3 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring Calico (Container Networking Interface) ...
🤹  Configuring local host environment ...

❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl and minikube configuration will be stored in /root
❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🔎  Verifying Kubernetes components...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

### PR DESCRIPTION
**Pull request by afbjorklund**
As there are no guarantees that the CRI socket actually _works_,
just because it has been made available by the container runtime.

Closes #10355

----

Now looks something like this:

```
I0303 21:08:28.291806 3918982 ssh_runner.go:149] Run: sudo systemctl restart containerd
I0303 21:08:28.372919 3918982 start.go:322] Will wait 60s for socket path /run/containerd/containerd.sock
I0303 21:08:28.372999 3918982 ssh_runner.go:149] Run: stat /run/containerd/containerd.sock
I0303 21:08:28.376748 3918982 start.go:347] Will wait 60s for crictl info
I0303 21:08:28.376806 3918982 ssh_runner.go:149] Run: sudo crictl version
I0303 21:08:28.401981 3918982 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo crictl version: Process exited with status 1
stdout:

stderr:
time="2021-03-03T20:08:28Z" level=fatal msg="getting the runtime version failed: rpc error: code = Unknown desc = server is not initialized yet"
I0303 21:08:39.448960 3918982 ssh_runner.go:149] Run: sudo crictl version
I0303 21:08:39.495437 3918982 start.go:356] Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  1.4.3
RuntimeApiVersion:  v1alpha2
I0303 21:08:39.495593 3918982 ssh_runner.go:149] Run: containerd --version
I0303 21:08:39.546331 3918982 out.go:119] 📦  Preparing Kubernetes v1.20.2 on containerd 1.4.3 ...

```

### CODE REVIEW

**Comment by medyagh** [comment]
the tests don't look very good on docker but looks better on Containerd

**Comment by afbjorklund** [comment]
> the tests don't look very good on docker but looks better on Containerd

I could only see Mac errors, not sure if there was anything related ?

The code doesn't actually do anything, unless running CRI

```go
       if socket == "" || socket == "/var/run/dockershim.sock" {
               return nil
       }

```

**Review by medyagh — APPROVED** [review]

**Pull request merged**
