### PR TITLE
InAccel FPGA Operator addon

### PR DESCRIPTION
**Pull request by eliaskoromilas**
# Simplifying FPGA management in Minikube

[asciicast](https://asciinema.org/a/457556)

### CODE REVIEW

**Comment by spowelljr** [comment]
Hi @eliaskoromilas, would it be possible to add an integration test to `test/integration/addons_test.go`?

**Comment by eliaskoromilas** [comment]
@spowelljr Sure, but it's going to be platform specific (e.g. AWS F1 instances).

**Comment by eliaskoromilas** [comment]
rebase

**Comment by eliaskoromilas** [comment]
Amazon EC2 / **f1.2xlarge**:

```
$ env TEST_ARGS="-minikube-start-args=--driver=none -test.run TestAddons" make integration
go test -ldflags="-X k8s.io/minikube/pkg/version.version=v1.24.0 -X k8s.io/minikube/pkg/version.isoVersion=v1.24.0 -X k8s.io/minikube/pkg/version.gitCommitID="8379487c018053849e1d95461e49fe953ac433c8" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v5" -v -test.timeout=90m ./test/integration --tags="integration " -minikube-start-args=--driver=none -test.run TestAddons 2>&1 | tee "./out/testout_8379487c0.txt"
Found 8 cores, limiting parallelism with --test.parallel=4
=== RUN   TestAddons
=== RUN   TestAddons/Setup
    addons_test.go:78: (dbg) Run:  out/minikube start -p minikube --wait=true --memory=4000 --alsologtostderr --addons=registry --addons=metrics-server --addons=olm --addons=volumesnapshots --addons=csi-hostpath-driver --addons=gcp-auth --driver=none --addons=inaccel --addons=helm-tiller
    addons_test.go:78: (dbg) Done: out/minikube start -p minikube --wait=true --memory=4000 --alsologtostderr --addons=registry --addons=metrics-server --addons=olm --addons=volumesnapshots --addons=csi-hostpath-driver --addons=gcp-auth --driver=none --addons=inaccel --addons=helm-tiller: (2m5.454064543s)
=== RUN   TestAddons/parallel
=== RUN   TestAddons/parallel/Registry
    addons_test.go:284: registry stabilized in 13.800826ms
    addons_test.go:286: (dbg) TestAddons/parallel/Registry: waiting 6m0s for pods matching "actual-registry=true" in namespace "kube-system" ...
    helpers_test.go:343: "registry-sgn6h" [88a65e03-106f-4aed-8532-952269d7a639] Running
    addons_test.go:286: (dbg) TestAddons/parallel/Registry: actual-registry=true healthy within 5.014616796s
    addons_test.go:289: (dbg) TestAddons/parallel/Registry: waiting 10m0s for pods matching "registry-proxy=true" in namespace "kube-system" ...
    helpers_test.go:343: "registry-proxy-x57jp" [4b47b890-3755-41d9-8239-52fa9ef0cf37] Running
    addons_test.go:289: (dbg) TestAddons/parallel/Registry: registry-proxy=true healthy within 5.009350156s
    addons_test.go:294: (dbg) Run:  kubectl --context minikube delete po -l run=registry-test --now
    addons_test.go:299: (dbg) Run:  kubectl --context minikube run --rm registry-test --restart=Never --image=busybox -it -- sh -c "wget --spider -S http://registry.kube-system.svc.cluster.local"
    addons_test.go:299: (dbg) Done: kubectl --context minikube run --rm registry-test --restart=Never --image=busybox -it -- sh -c "wget --spider -S http://registry.kube-system.svc.cluster.local": (1.945409795s)
    addons_test.go:313: (dbg) Run:  out/minikube -p minikube ip
2021/11/30 15:29:49 [DEBUG] GET http://172.31.85.102:5000
    addons_test.go:342: (dbg) Run:  out/minikube -p minikube addons disable registry --alsologtostderr -v=1
=== RUN   TestAddons/parallel/Ingress
    addons_test.go:155: skipping: ingress not supported
=== RUN   TestAddons/parallel/MetricsServer
    addons_test.go:361: metrics-server stabilized in 15.11042ms
    addons_test.go:363: (dbg) TestAddons/parallel/MetricsServer: waiting 6m0s for pods matching "k8s-app=metrics-server" in namespace "kube-system" ...
    helpers_test.go:343: "metrics-server-77c99ccb96-b7cnf" [3a176bf3-b482-47d0-a74b-c2b1b39f5039] Running
    addons_test.go:363: (dbg) TestAddons/parallel/MetricsServer: k8s-app=metrics-server healthy within 5.014181846s
    addons_test.go:369: (dbg) Run:  kubectl --context minikube top pods -n kube-system
    addons_test.go:386: (dbg) Run:  out/minikube -p minikube addons disable metrics-server --alsologtostderr -v=1
=== RUN   TestAddons/parallel/HelmTiller
    addons_test.go:410: tiller-deploy stabilized in 2.740345ms
    addons_test.go:412: (dbg) TestAddons/parallel/HelmTiller: waiting 6m0s for pods matching "app=helm" in namespace "kube-system" ...
    helpers_test.go:343: "tiller-deploy-64b546c44b-m2r7b" [8d4fbbbf-eb56-4b3d-bfa6-37b1a8a0f49b] Running
    addons_test.go:412: (dbg) TestAddons/parallel/HelmTiller: app=helm healthy within 5.009216954s
    addons_test.go:427: (dbg) Run:  kubectl --context minikube run --rm helm-test --restart=Never --image=alpine/helm:2.16.3 -it --namespace=kube-system -- version
    addons_test.go:427: (dbg) Done: kubectl --context minikube run --rm helm-test --restart=Never --image=alpine/helm:2.16.3 -it --namespace=kube-system -- version: (3.415687587s)
    addons_test.go:444: (dbg) Run:  out/minikube -p minikube addons disable helm-tiller --alsologtostderr -v=1
=== RUN   TestAddons/parallel/Olm
    addons_test.go:456: (dbg) Run:  kubectl --context minikube wait --for=condition=ready --namespace=olm pod --selector=app=catalog-operator --timeout=90s
    addons_test.go:459: catalog-operator stabilized in 95.809477ms
    addons_test.go:461: (dbg) Run:  kubectl --context minikube wait --for=condition=ready --namespace=olm pod --selector=app=olm-operator --timeout=90s
    addons_test.go:464: olm-operator stabilized in 176.431089ms
    addons_test.go:466: (dbg) Run:  kubectl --context minikube wait --for=condition=ready --namespace=olm pod --selector=app=packageserver --timeout=90s
    addons_test.go:469: packageserver stabilized in 271.157326ms
    addons_test.go:471: (dbg) Run:  kubectl --context minikube wait --for=condition=ready --namespace=olm pod --selector=olm.catalogSource=operatorhubio-catalog --timeout=90s
    addons_test.go:474: operatorhubio-catalog stabilized in 362.666346ms
    addons_test.go:477: (dbg) Run:  kubectl --context minikube create -f testdata/etcd.yaml
    addons_test.go:477: (dbg) Done: kubectl --context minikube create -f testdata/etcd.yaml: (1.247706211s)
    addons_test.go:484: (dbg) Run:  kubectl --context minikube get csv -n my-etcd
    addons_test.go:489: kubectl --context minikube get csv -n my-etcd: unexpected stderr: No resources found in my-etcd namespace.
    addons_test.go:484: (dbg) Run:  kubectl --context minikube get csv -n my-etcd
    addons_test.go:489: kubectl --context minikube get csv -n my-etcd: unexpected stderr: No resources found in my-etcd namespace.
    addons_test.go:484: (dbg) Run:  kubectl --context minikube get csv -n my-etcd
    addons_test.go:489: kubectl --context minikube get csv -n my-etcd: unexpected stderr: No resources found in my-etcd namespace.
    addons_test.go:484: (dbg) Run:  kubectl --context minikube get csv -n my-etcd
    addons_test.go:484: (dbg) Run:  kubectl --context minikube get csv -n my-etcd
=== RUN   TestAddons/parallel/CSI
    addons_test.go:515: csi-hostpath-driver pods stabilized in 8.354087ms
    addons_test.go:518: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/pvc.yaml
    addons_test.go:518: (dbg) Done: kubectl --context minikube create -f testdata/csi-hostpath-driver/pvc.yaml: (1.123747133s)
    addons_test.go:523: (dbg) TestAddons/parallel/CSI: waiting 6m0s for pvc "hpvc" in namespace "default" ...
    helpers_test.go:393: (dbg) Run:  kubectl --context minikube get pvc hpvc -o jsonpath={.status.phase} -n default
    addons_test.go:528: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/pv-pod.yaml
    addons_test.go:533: (dbg) TestAddons/parallel/CSI: waiting 6m0s for pods matching "app=task-pv-pod" in namespace "default" ...
    helpers_test.go:343: "task-pv-pod" [0c1e4041-4f56-4f3a-8e28-3a5a41ae6efb] Pending
    helpers_test.go:343: "task-pv-pod" [0c1e4041-4f56-4f3a-8e28-3a5a41ae6efb] Pending / Ready:ContainersNotReady (containers with unready status: [task-pv-container]) / ContainersReady:ContainersNotReady (containers with unready status: [task-pv-container])
    helpers_test.go:343: "task-pv-pod" [0c1e4041-4f56-4f3a-8e28-3a5a41ae6efb] Running
    addons_test.go:533: (dbg) TestAddons/parallel/CSI: app=task-pv-pod healthy within 19.006914254s
    addons_test.go:538: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/snapshot.yaml
    addons_test.go:543: (dbg) TestAddons/parallel/CSI: waiting 6m0s for volume snapshot "new-snapshot-demo" in namespace "default" ...
    helpers_test.go:418: (dbg) Run:  kubectl --context minikube get volumesnapshot new-snapshot-demo -o jsonpath={.status.readyToUse} -n default
    helpers_test.go:418: (dbg) Run:  kubectl --context minikube get volumesnapshot new-snapshot-demo -o jsonpath={.status.readyToUse} -n default
    addons_test.go:548: (dbg) Run:  kubectl --context minikube delete pod task-pv-pod
    addons_test.go:554: (dbg) Run:  kubectl --context minikube delete pvc hpvc
    addons_test.go:560: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/pvc-restore.yaml
    addons_test.go:565: (dbg) TestAddons/parallel/CSI: waiting 6m0s for pvc "hpvc-restore" in namespace "default" ...
    helpers_test.go:393: (dbg) Run:  kubectl --context minikube get pvc hpvc-restore -o jsonpath={.status.phase} -n default
    addons_test.go:570: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/pv-pod-restore.yaml
    addons_test.go:575: (dbg) TestAddons/parallel/CSI: waiting 6m0s for pods matching "app=task-pv-pod-restore" in namespace "default" ...
    helpers_test.go:343: "task-pv-pod-restore" [ed2b205d-0ed9-44df-b46c-42e0b36c5078] Pending
    helpers_test.go:343: "task-pv-pod-restore" [ed2b205d-0ed9-44df-b46c-42e0b36c5078] Pending / Ready:ContainersNotReady (containers with unready status: [task-pv-container]) / ContainersReady:ContainersNotReady (containers with unready status: [task-pv-container])
    helpers_test.go:343: "task-pv-pod-restore" [ed2b205d-0ed9-44df-b46c-42e0b36c5078] Running
    addons_test.go:575: (dbg) TestAddons/parallel/CSI: app=task-pv-pod-restore healthy within 15.007180446s
    addons_test.go:580: (dbg) Run:  kubectl --context minikube delete pod task-pv-pod-restore
    addons_test.go:580: (dbg) Done: kubectl --context minikube delete pod task-pv-pod-restore: (1.569928172s)
    addons_test.go:584: (dbg) Run:  kubectl --context minikube delete pvc hpvc-restore
    addons_test.go:588: (dbg) Run:  kubectl --context minikube delete volumesnapshot new-snapshot-demo
    addons_test.go:592: (dbg) Run:  out/minikube -p minikube addons disable csi-hostpath-driver --alsologtostderr -v=1
    addons_test.go:592: (dbg) Done: out/minikube -p minikube addons disable csi-hostpath-driver --alsologtostderr -v=1: (6.666361604s)
    addons_test.go:596: (dbg) Run:  out/minikube -p minikube addons disable volumesnapshots --alsologtostderr -v=1
=== RUN   TestAddons/parallel/InAccel
    addons_test.go:729: (dbg) Run:  kubectl --context minikube create --filename testdata/inaccel.yaml
    addons_test.go:734: (dbg) Run:  kubectl --context minikube wait --for condition=ready --timeout -1s pod/inaccel-vadd
    addons_test.go:734: (dbg) Done: kubectl --context minikube wait --for condition=ready --timeout -1s pod/inaccel-vadd: (3m5.383374573s)
    addons_test.go:738: (dbg) Run:  kubectl --context minikube logs --follow pod/inaccel-vadd
    addons_test.go:738: (dbg) Done: kubectl --context minikube logs --follow pod/inaccel-vadd: (6.179247542s)
    addons_test.go:747: (dbg) Run:  kubectl --context minikube delete pod/inaccel-vadd
=== RUN   TestAddons/serial
=== RUN   TestAddons/serial/GCPAuth
    addons_test.go:607: (dbg) Run:  kubectl --context minikube create -f testdata/busybox.yaml
    addons_test.go:607: (dbg) Done: kubectl --context minikube create -f testdata/busybox.yaml: (1.078477636s)
    addons_test.go:613: (dbg) TestAddons/serial/GCPAuth: waiting 8m0s for pods matching "integration-test=busybox" in namespace "default" ...
    helpers_test.go:343: "busybox" [7fc707ed-47b5-493d-9e18-b8711b2c33b4] Pending / Ready:ContainersNotReady (containers with unready status: [busybox]) / ContainersReady:ContainersNotReady (containers with unready status: [busybox])
    helpers_test.go:343: "busybox" [7fc707ed-47b5-493d-9e18-b8711b2c33b4] Running
    addons_test.go:613: (dbg) TestAddons/serial/GCPAuth: integration-test=busybox healthy within 7.015933761s
    addons_test.go:619: (dbg) Run:  kubectl --context minikube exec busybox -- /bin/sh -c "printenv GOOGLE_APPLICATION_CREDENTIALS"
    addons_test.go:632: (dbg) Run:  kubectl --context minikube exec busybox -- /bin/sh -c "cat /google-app-creds.json"
    addons_test.go:656: (dbg) Run:  kubectl --context minikube exec busybox -- /bin/sh -c "printenv GOOGLE_CLOUD_PROJECT"
    addons_test.go:669: (dbg) Run:  out/minikube -p minikube addons disable gcp-auth --alsologtostderr -v=1
    addons_test.go:669: (dbg) Done: out/minikube -p minikube addons disable gcp-auth --alsologtostderr -v=1: (6.386943971s)
=== RUN   TestAddons/StoppedEnableDisable
    addons_test.go:136: (dbg) Run:  out/minikube stop -p minikube
    addons_test.go:136: (dbg) Done: out/minikube stop -p minikube: (10.653090312s)
    addons_test.go:140: (dbg) Run:  out/minikube addons enable dashboard -p minikube
    addons_test.go:144: (dbg) Run:  out/minikube addons disable dashboard -p minikube
=== CONT  TestAddons
    helpers_test.go:176: Cleaning up "minikube" profile ...
    helpers_test.go:179: (dbg) Run:  out/minikube delete -p minikube
    helpers_test.go:179: (dbg) Done: out/minikube delete -p minikube: (4.788245892s)
--- PASS: TestAddons (444.74s)
    --- PASS: TestAddons/Setup (125.46s)
    --- PASS: TestAddons/parallel (288.39s)
        --- PASS: TestAddons/parallel/Registry (12.75s)
        --- SKIP: TestAddons/parallel/Ingress (0.00s)
        --- PASS: TestAddons/parallel/MetricsServer (5.45s)
        --- PASS: TestAddons/parallel/HelmTiller (8.78s)
        --- PASS: TestAddons/parallel/Olm (21.40s)
        --- PASS: TestAddons/parallel/CSI (47.22s)
        --- PASS: TestAddons/parallel/InAccel (192.78s)
    --- PASS: TestAddons/serial (15.19s)
        --- PASS: TestAddons/serial/GCPAuth (15.19s)
    --- PASS: TestAddons/StoppedEnableDisable (10.92s)
PASS
Tests completed in 7m24.745081222s (result code 0)
ok  	k8s.io/minikube/test/integration	444.847s
```

**Comment by eliaskoromilas** [comment]
@spowelljr PTAL

**Comment by eliaskoromilas** [comment]
/remove-lifecycle stale

@spowelljr An integration test is added. Could you please take another look?

**Comment by eliaskoromilas** [comment]
rebase

**Comment by sharifelgamal** [comment]
Hey, it seems like one of our unit tests is failing. Could you take a look and fix it? Once that's fixed and the tests are rerun, we can go ahead and get this merged.

**Comment by eliaskoromilas** [comment]
> Hey, it seems like one of our unit tests is failing. Could you take a look and fix it? Once that's fixed and the tests are rerun, we can go ahead and get this merged.

@sharifelgamal In `TestAddonsList/NonExistingClusterJSON` there is a temp buffer that needs to be large enough to fit the JSON addons list. I just allocated 15 more bytes for the new entry (`\"inaccel\":{},`), it should be fine now (but we could consider an one time fix, check also https://github.com/kubernetes/minikube/commit/67f748fc9ea26ccfa414e66d852cdbfd3b8033cf).

**Comment by eliaskoromilas** [comment]
rebase

**Comment by eliaskoromilas** [comment]
Amazon EC2 / **f1.2xlarge**:

```
$ env TEST_ARGS="-minikube-start-args=--driver=none -test.run TestAddons" make integration
go test -ldflags="-X k8s.io/minikube/pkg/version.version=v1.26.0-beta.1 -X k8s.io/minikube/pkg/version.isoVersion=v1.26.0-1652998508-14153 -X k8s.io/minikube/pkg/version.gitCommitID="6364518066f0b59081be7e3e269fae24b6e5a948" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v5" -v -test.timeout=90m ./test/integration --tags="integration " -minikube-start-args=--driver=none -test.run TestAddons 2>&1 | tee "./out/testout_636451806.txt"
Found 8 cores, limiting parallelism with --test.parallel=4
=== RUN   TestAddons
=== RUN   TestAddons/Setup
    addons_test.go:77: (dbg) Run:  out/minikube start -p minikube --wait=true --memory=4000 --alsologtostderr --addons=registry --addons=metrics-server --addons=volumesnapshots --addons=csi-hostpath-driver --addons=gcp-auth --driver=none --addons=inaccel --addons=helm-tiller
    addons_test.go:77: (dbg) Done: out/minikube start -p minikube --wait=true --memory=4000 --alsologtostderr --addons=registry --addons=metrics-server --addons=volumesnapshots --addons=csi-hostpath-driver --addons=gcp-auth --driver=none --addons=inaccel --addons=helm-tiller: (44.03978862s)
=== RUN   TestAddons/parallel
=== RUN   TestAddons/parallel/Registry
    addons_test.go:283: registry stabilized in 9.599293ms
    addons_test.go:285: (dbg) TestAddons/parallel/Registry: waiting 6m0s for pods matching "actual-registry=true" in namespace "kube-system" ...
    helpers_test.go:342: "registry-sm64v" [509fd4fc-f218-4bb3-91b4-ba31b711cedf] Running
    addons_test.go:285: (dbg) TestAddons/parallel/Registry: actual-registry=true healthy within 5.008611607s
    addons_test.go:288: (dbg) TestAddons/parallel/Registry: waiting 10m0s for pods matching "registry-proxy=true" in namespace "kube-system" ...
    helpers_test.go:342: "registry-proxy-crtdv" [7d2b748c-441d-4edb-b396-8606e09891cb] Running
    addons_test.go:288: (dbg) TestAddons/parallel/Registry: registry-proxy=true healthy within 5.010031039s
    addons_test.go:293: (dbg) Run:  kubectl --context minikube delete po -l run=registry-test --now
    addons_test.go:298: (dbg) Run:  kubectl --context minikube run --rm registry-test --restart=Never --image=gcr.io/k8s-minikube/busybox -it -- sh -c "wget --spider -S http://registry.kube-system.svc.cluster.local"
    addons_test.go:298: (dbg) Done: kubectl --context minikube run --rm registry-test --restart=Never --image=gcr.io/k8s-minikube/busybox -it -- sh -c "wget --spider -S http://registry.kube-system.svc.cluster.local": (3.885868251s)
    addons_test.go:312: (dbg) Run:  out/minikube -p minikube ip
2022/05/26 08:20:42 [DEBUG] GET http://172.31.88.36:5000
    addons_test.go:341: (dbg) Run:  out/minikube -p minikube addons disable registry --alsologtostderr -v=1
=== RUN   TestAddons/parallel/Ingress
    addons_test.go:154: skipping: ingress not supported
=== RUN   TestAddons/parallel/MetricsServer
    addons_test.go:360: metrics-server stabilized in 2.561304ms
    addons_test.go:362: (dbg) TestAddons/parallel/MetricsServer: waiting 6m0s for pods matching "k8s-app=metrics-server" in namespace "kube-system" ...
    helpers_test.go:342: "metrics-server-bd6f4dd56-bmfvp" [ec3a9048-2536-4fde-9610-66247b625986] Running
    addons_test.go:362: (dbg) TestAddons/parallel/MetricsServer: k8s-app=metrics-server healthy within 5.0087142s
    addons_test.go:368: (dbg) Run:  kubectl --context minikube top pods -n kube-system
    addons_test.go:385: (dbg) Run:  out/minikube -p minikube addons disable metrics-server --alsologtostderr -v=1
=== RUN   TestAddons/parallel/HelmTiller
    addons_test.go:409: tiller-deploy stabilized in 2.960187ms
    addons_test.go:411: (dbg) TestAddons/parallel/HelmTiller: waiting 6m0s for pods matching "app=helm" in namespace "kube-system" ...
    helpers_test.go:342: "tiller-deploy-6d67d5465d-ttgnd" [a126a203-c236-4806-b21b-1f7ee9275b97] Running
    addons_test.go:411: (dbg) TestAddons/parallel/HelmTiller: app=helm healthy within 5.009746627s
    addons_test.go:426: (dbg) Run:  kubectl --context minikube run --rm helm-test --restart=Never --image=alpine/helm:2.16.3 -it --namespace=kube-system -- version
    addons_test.go:426: (dbg) Done: kubectl --context minikube run --rm helm-test --restart=Never --image=alpine/helm:2.16.3 -it --namespace=kube-system -- version: (3.876973454s)
    addons_test.go:443: (dbg) Run:  out/minikube -p minikube addons disable helm-tiller --alsologtostderr -v=1
=== RUN   TestAddons/parallel/Olm
    addons_test.go:451: Skipping OLM addon test until https://github.com/operator-framework/operator-lifecycle-manager/issues/2534 is resolved
=== RUN   TestAddons/parallel/CSI
    addons_test.go:514: csi-hostpath-driver pods stabilized in 7.266171ms
    addons_test.go:517: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/pvc.yaml
    addons_test.go:522: (dbg) TestAddons/parallel/CSI: waiting 6m0s for pvc "hpvc" in namespace "default" ...
    helpers_test.go:392: (dbg) Run:  kubectl --context minikube get pvc hpvc -o jsonpath={.status.phase} -n default
    addons_test.go:527: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/pv-pod.yaml
    addons_test.go:532: (dbg) TestAddons/parallel/CSI: waiting 6m0s for pods matching "app=task-pv-pod" in namespace "default" ...
    helpers_test.go:342: "task-pv-pod" [67604232-80ab-4844-b1a7-e0a109f9c6dc] Pending
    helpers_test.go:342: "task-pv-pod" [67604232-80ab-4844-b1a7-e0a109f9c6dc] Pending / Ready:ContainersNotReady (containers with unready status: [task-pv-container]) / ContainersReady:ContainersNotReady (containers with unready status: [task-pv-container])
    helpers_test.go:342: "task-pv-pod" [67604232-80ab-4844-b1a7-e0a109f9c6dc] Running
    addons_test.go:532: (dbg) TestAddons/parallel/CSI: app=task-pv-pod healthy within 11.006956817s
    addons_test.go:537: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/snapshot.yaml
    addons_test.go:542: (dbg) TestAddons/parallel/CSI: waiting 6m0s for volume snapshot "new-snapshot-demo" in namespace "default" ...
    helpers_test.go:417: (dbg) Run:  kubectl --context minikube get volumesnapshot new-snapshot-demo -o jsonpath={.status.readyToUse} -n default
    helpers_test.go:417: (dbg) Run:  kubectl --context minikube get volumesnapshot new-snapshot-demo -o jsonpath={.status.readyToUse} -n default
    addons_test.go:547: (dbg) Run:  kubectl --context minikube delete pod task-pv-pod
    addons_test.go:553: (dbg) Run:  kubectl --context minikube delete pvc hpvc
    addons_test.go:559: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/pvc-restore.yaml
    addons_test.go:564: (dbg) TestAddons/parallel/CSI: waiting 6m0s for pvc "hpvc-restore" in namespace "default" ...
    helpers_test.go:392: (dbg) Run:  kubectl --context minikube get pvc hpvc-restore -o jsonpath={.status.phase} -n default
    addons_test.go:569: (dbg) Run:  kubectl --context minikube create -f testdata/csi-hostpath-driver/pv-pod-restore.yaml
    addons_test.go:574: (dbg) TestAddons/parallel/CSI: waiting 6m0s for pods matching "app=task-pv-pod-restore" in namespace "default" ...
    helpers_test.go:342: "task-pv-pod-restore" [b3c379e7-c7da-40a9-8e76-86d0ce40c9e3] Pending
    helpers_test.go:342: "task-pv-pod-restore" [b3c379e7-c7da-40a9-8e76-86d0ce40c9e3] Pending / Ready:ContainersNotReady (containers with unready status: [task-pv-container]) / ContainersReady:ContainersNotReady (containers with unready status: [task-pv-container])
    helpers_test.go:342: "task-pv-pod-restore" [b3c379e7-c7da-40a9-8e76-86d0ce40c9e3] Running
    addons_test.go:574: (dbg) TestAddons/parallel/CSI: app=task-pv-pod-restore healthy within 16.008651545s
    addons_test.go:579: (dbg) Run:  kubectl --context minikube delete pod task-pv-pod-restore
    addons_test.go:579: (dbg) Done: kubectl --context minikube delete pod task-pv-pod-restore: (1.496589616s)
    addons_test.go:583: (dbg) Run:  kubectl --context minikube delete pvc hpvc-restore
    addons_test.go:587: (dbg) Run:  kubectl --context minikube delete volumesnapshot new-snapshot-demo
    addons_test.go:591: (dbg) Run:  out/minikube -p minikube addons disable csi-hostpath-driver --alsologtostderr -v=1
    addons_test.go:591: (dbg) Done: out/minikube -p minikube addons disable csi-hostpath-driver --alsologtostderr -v=1: (6.535659705s)
    addons_test.go:595: (dbg) Run:  out/minikube -p minikube addons disable volumesnapshots --alsologtostderr -v=1
=== RUN   TestAddons/parallel/InAccel
    addons_test.go:728: (dbg) Run:  kubectl --context minikube create --filename testdata/inaccel.yaml
    addons_test.go:733: (dbg) Run:  kubectl --context minikube wait --for condition=ready --timeout -1s pod/inaccel-vadd
    addons_test.go:733: (dbg) Done: kubectl --context minikube wait --for condition=ready --timeout -1s pod/inaccel-vadd: (2.339062155s)
    addons_test.go:737: (dbg) Run:  kubectl --context minikube logs --follow pod/inaccel-vadd
    addons_test.go:737: (dbg) Done: kubectl --context minikube logs --follow pod/inaccel-vadd: (3.554292361s)
    addons_test.go:746: (dbg) Run:  kubectl --context minikube delete pod/inaccel-vadd
=== RUN   TestAddons/serial
=== RUN   TestAddons/serial/GCPAuth
    addons_test.go:606: (dbg) Run:  kubectl --context minikube create -f testdata/busybox.yaml
    addons_test.go:612: (dbg) TestAddons/serial/GCPAuth: waiting 8m0s for pods matching "integration-test=busybox" in namespace "default" ...
    helpers_test.go:342: "busybox" [6f711959-84e6-49a0-9765-9bfaaed88ef3] Pending
    helpers_test.go:342: "busybox" [6f711959-84e6-49a0-9765-9bfaaed88ef3] Pending / Ready:ContainersNotReady (containers with unready status: [busybox]) / ContainersReady:ContainersNotReady (containers with unready status: [busybox])
    helpers_test.go:342: "busybox" [6f711959-84e6-49a0-9765-9bfaaed88ef3] Running
    addons_test.go:612: (dbg) TestAddons/serial/GCPAuth: integration-test=busybox healthy within 8.008634301s
    addons_test.go:618: (dbg) Run:  kubectl --context minikube exec busybox -- /bin/sh -c "printenv GOOGLE_APPLICATION_CREDENTIALS"
    addons_test.go:631: (dbg) Run:  kubectl --context minikube exec busybox -- /bin/sh -c "cat /google-app-creds.json"
    addons_test.go:655: (dbg) Run:  kubectl --context minikube exec busybox -- /bin/sh -c "printenv GOOGLE_CLOUD_PROJECT"
    addons_test.go:668: (dbg) Run:  out/minikube -p minikube addons disable gcp-auth --alsologtostderr -v=1
    addons_test.go:668: (dbg) Done: out/minikube -p minikube addons disable gcp-auth --alsologtostderr -v=1: (5.476207357s)
=== RUN   TestAddons/StoppedEnableDisable
    addons_test.go:135: (dbg) Run:  out/minikube stop -p minikube
    addons_test.go:135: (dbg) Done: out/minikube stop -p minikube: (10.593515674s)
    addons_test.go:139: (dbg) Run:  out/minikube addons enable dashboard -p minikube
    addons_test.go:143: (dbg) Run:  out/minikube addons disable dashboard -p minikube
=== CONT  TestAddons
    helpers_test.go:175: Cleaning up "minikube" profile ...
    helpers_test.go:178: (dbg) Run:  out/minikube delete -p minikube
    helpers_test.go:178: (dbg) Done: out/minikube delete -p minikube: (4.101684951s)
--- PASS: TestAddons (148.76s)
    --- PASS: TestAddons/Setup (44.04s)
    --- PASS: TestAddons/parallel (75.00s)
        --- PASS: TestAddons/parallel/Registry (14.39s)
        --- SKIP: TestAddons/parallel/Ingress (0.00s)
        --- PASS: TestAddons/parallel/MetricsServer (5.40s)
        --- PASS: TestAddons/parallel/HelmTiller (9.16s)
        --- SKIP: TestAddons/parallel/Olm (0.00s)
        --- PASS: TestAddons/parallel/CSI (39.44s)
        --- PASS: TestAddons/parallel/InAccel (6.61s)
    --- PASS: TestAddons/serial (14.74s)
        --- PASS: TestAddons/serial/GCPAuth (14.74s)
    --- PASS: TestAddons/StoppedEnableDisable (10.87s)
PASS
Tests completed in 2m28.764698942s (result code 0)
ok  	k8s.io/minikube/test/integration	148.863s
```

**Review by sharifelgamal — APPROVED** [review]

**Pull request merged**
