### PR TITLE
Cleanup ssh tunnels on cancel

### LINKED ISSUE #10752: SSH tunnels left open after sending SIGINT to `minikube tunnel`
**Steps to reproduce the issue:** 
Minikube running with docker driver on macOS Catalina

1. `minikube tunnel`
2. On another terminal: `kill -INT <PID_OF_THE_PREVIOUS_COMMAND>`
3. `ps aux | grep minikube`

**Full output of failed command:** 
The `ps` command will show multiple ssh tunnels still open, outliving the parent process.

**Details**
In **pkg/minikube/tunnel/kic/ssh_tunnel.go** the interrupt signal is caught and it stops the LoadBalancerEmulator. However, it assumes that the interrupt will also propagate to the children ssh tunnels, which are running in a goroutine inside `startConnections`.
The interrupt, however, kills the goroutine and the blocking call which waits for the child process to finish. This leaves the ssh tunnels dangling.
On the other hand, if `CTRL + C` is sent on the same terminal as `minikube tunnel` and the clean-up routine included killing all ssh tunnels, the OS would error with "process already finished".

**Related issues**
https://github.com/kubernetes/minikube/issues/8511
https://github.com/kubernetes/minikube/issues/3647

### PR DESCRIPTION
**Pull request by m-lima**
**Details**
In **pkg/minikube/tunnel/kic/ssh_tunnel.go** the interrupt signal is caught and it stops the LoadBalancerEmulator. However, it assumes that the interrupt will also propagate to the children ssh tunnels, which are running in a goroutine inside `startConnections`.
The interrupt, however, kills the goroutine and the blocking call which waits for the child process to finish. This leaves the ssh tunnels dangling.
On the other hand, if `CTRL + C` is sent on the same terminal as `minikube tunnel` and the clean-up routine included killing all ssh tunnels, the OS would error with "process already finished".

This leads to accumulation of processes and is likely to happen. Since `minikube tunnel` is a blocking command, users will tend to detach it from the terminal and kill it with a `SIGINT` (as proposed in https://github.com/kubernetes/minikube/issues/3647).

**Approaches**
There are two proposed approaches. This PR takes the approach of having the tunnel know if is running or not. The second approach is to have the parent of all connections managed and know which processes should be killed.

The first approach, proposed with this PR, also addresses https://github.com/kubernetes/minikube/issues/8511, by letting the process owner hold the knowledge if the process is running or not. Since the ssh tunnels are started inside `startAndWait()` on **pkg/minikube/tunnel/kic/ssh_conn.go**, and a blocking call to `Wait()` is made, the owner can know when the process is started, finished, or killed.

The second approach is more oriented towards the cleaning up of the ssh tunnels, and isolates changes to only **pkg/minikube/tunnel/kic/ssh_tunnel.go**. However it relies on `sync`. The second approach can be seen here: https://github.com/m-lima/minikube/tree/issue/10752-managed-kill

**Output**
With this PR, users will be notified of connections being closed (as opposed to the silent death that happens now). E.g:
```
$ minikube tunnel
🏃  Starting tunnel for service serviceA.
🏃  Starting tunnel for service serviceB.
🏃  Starting tunnel for service serviceC.
^C✋  Tunnel for service serviceB.
✋  Tunnel for service serviceA stopped.
✋  Tunnel for service serviceC stopped.
```

Also, when detaching from the terminal, all ssh tunnels will be reaped, also outputting to the terminal (if not redirected by the user). E.g:
```
$ minikube tunnel
🏃  Starting tunnel for service serviceA.
🏃  Starting tunnel for service serviceB.
🏃  Starting tunnel for service serviceC.
```
On another terminal:
```
kill -INT <PID>
```
Main terminal:
```
✋  Stopping tunnel for service serviceA.
✋  Stopping tunnel for service serviceB.
✋  Stopping tunnel for service serviceC.
```

fixes #10752

### CODE REVIEW

**Comment by m-lima** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
>     * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
>     * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> 
>     * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> 
>     * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Revalidate CLA

**Comment by m-lima** [comment]
Revalidate CLA

**Comment by m-lima** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
>     * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
>     * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> 
>     * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> 
>     * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Revalidate CLA

**Comment by medyagh** [comment]
@m-lima thanks for this PR, do u mind checking if the Email u are using in the terminal is the same on that is Signed CLA in 
https://identity.linuxfoundation.org/projects/cncf

**Comment by m-lima** [comment]
> @m-lima thanks for this PR, do u mind checking if the Email u are using in the terminal is the same on that is Signed CLA in
> https://identity.linuxfoundation.org/projects/cncf

I used my github account to sign the CLA. Got an email confirmation on my email and it all looked good.
I assume that by checking my email in the terminal, you mean to check that the commits were made with the same email that was used for CLA, right? I just double checked that and it is correct.
I assumed that the problem with the CLA not validating was because of the migration that the linux foundation was reporting..

**Comment by medyagh** [comment]
@m-lima 
thats possible how rebasing the PR and force push the commits ? maybe that would help ?

**Comment by m-lima** [comment]
> 
> 
> @m-lima
> thats possible how rebasing the PR and force push the commits ? maybe that would help ?

Sure I'll try that

**Pull request closed without merging**
