### PR TITLE
Remove duplicate setting field in config

### PR DESCRIPTION
**Pull request by theVDude**
Quick fix for issue #5516

### CODE REVIEW

**Comment by theVDude** [comment]
Dropping a comment now that I've registered with CNCF and signed CLA.

**Comment by tstromberg** [comment]
The commit appears to have been written by rbruceSV - which has not signed the CLA. Do you mind editing the commit to appear from theVDude, or having rbruceSV sign the CLA?

**Comment by tstromberg** [comment]
Still needs to have the commit attributed to the correct user. This can be fixed by:

```
git config --global user.email example@email.com
git commit --amend --reset-author --no-edit
git push -f
```

**Comment by theVDude** [comment]
Whoops, sorry about the CLA/author mix up there! I didn't realize what account I was logged into on my PC.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
Looks good!

**Pull request merged**
