### PR TITLE
Add hyperv support

### LINKED ISSUE #465: Support for Hyper-V on Windows
I have Hyper-V enabled on my Windows for Docker. When I try to run minkube cluster, it says that I have to disable Hyper-V for VirtualBox to work or use Hyper-V as the driver but Hyper-V is not supported by minikube.
```
Starting local Kubernetes cluster...
E0809 14:08:01.300772    8324 start.go:78] Error starting host:  Error creating. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"
```

I purpose that Hyper-V be supported by minikube as the default driver for Windows.

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #465

@raeesbhatti Would you be willing to try this branch out locally & see if hyperv support works for you? Would be much appreciated if you could.

### CODE REVIEW

**Comment by raeesbhatti** [comment]
@jimmidyson Can you please guide me to the build process.

**Comment by dlorenc** [comment]
LGTM, but let's hold off until someone has a chance to test. @aaron-prindle has a Windows machine he can test with too.

**Comment by aaron-prindle** [comment]
I am having issues using hyperv with minikube, here is a gist showing the steps I took and the error that I am getting when running `minikube start`:

https://gist.github.com/aaron-prindle/4454d0941cfb095f23408c6f3035990f

**Comment by aaron-prindle** [comment]
I am getting this same error when simply using docker-machine with the hyperv driver

**Comment by cosminilie** [comment]
I wanted to share some finding, maybe they can help you debug.

I also tested today with the PR. With docker machine when you enable connection sharing i was able to make it work (docker-machine version 0.8) http://www.packet6.com/allowing-windows-8-1-hyper-v-vm-to-work-with-wifi/ (this is mentioned in the hyper-v driver documentation -https://github.com/docker/machine/blob/8141874120abdc5c9056b6dbeb09bfb76a3eb290/docs/drivers/hyper-v.md). With minikube it remains stuck at:

Starting local Kubernetes cluster...
Waiting for SSH to be available...
E0817 06:50:21.093893    6956 start.go:81] Error starting host: Error configuring auth on host: Too many retries waiting
 for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
Waiting for SSH to be available...

Manually i'm able to SSH into the boot2docker vm using the minikube key(C:\Users\user\.minikube\machines\minikubeVM\id_rsa). 

One thing i noticed is that the boot2docker image for machine is version 1.12 while the minikube one is 1.11. It might not help but figured it might.

**Comment by raeesbhatti** [comment]
Is anyone still working on this?

**Comment by jimmidyson** [comment]
I'm back next week to try to get this in. Would love feedback on any info on how to get this working.

**Comment by aaron-prindle** [comment]
I am looking into getting the hyperv driver working with minikube.  Right
now there is an issue where once minikube provisions the vm through
libmachine it is not able to ssh into the machine.

**Comment by aaron-prindle** [comment]
Hey @jimmidyson,
In investigating the issue with minikube not being able to ssh into the minikubeVM there seems to be an issue was with using SetConfigFromFlags.  We do not call SetConfigFromFlags in minikube so the d.SSHUser="docker" call is not being run and as such d.SSHUser actually being set to "root".  I believe the fix for this is to append this line to createHypervHost in cluster_windows.go:
d.SSHUser = "docker"

**Comment by jimmidyson** [comment]
@aaron-prindle Thanks! Updated.

**Comment by dlorenc** [comment]
LGTM

**Comment by raeesbhatti** [comment]
Having some problems with this, I've attached the log file. Please take a look. I stopped and started again, even deleted and created the vm again but the results were same.
[minikube.zip](https://github.com/kubernetes/minikube/files/435390/minikube.zip)

**Comment by jimmidyson** [comment]
That's an IPv6 address. Perhaps the hyperv driver doesn't support IPv6?

**Comment by jimmidyson** [comment]
@raeesbhatti Try https://github.com/docker/machine/issues/1203

**Comment by dlorenc** [comment]
@aaron-prindle had some trouble with ipv6 as well

**Comment by raeesbhatti** [comment]
Yes, I changed the DockerNAT network interface type to public and bridged it to my WiFi and it has started working. Thanks.

However, it seems that only Administrator can create or start the minikube VM.

**Comment by aaron-prindle** [comment]
I believe this is because by default only the Administrator account has
access to hyperv.  It looks like you can add non-administrators to
the Hyper-V Administrators account, as shown here:
https://blogs.msdn.microsoft.com/virtual_pc_guy/2014/06/11/allowing-non-administrators-to-control-hyper-vupdated/

From this article though it appears that there might be issues in doing
this with Windows 10.  It seems that Windows 8 works correctly though.

**Comment by raeesbhatti** [comment]
It doesn't work with Windows 10 but thanks :+1:

**Comment by raeesbhatti** [comment]
Found another problem. No, host directory is being shared in the VM, not event the Users directory. I think its the same as [the xhyve problem](https://github.com/kubernetes/minikube/issues/423). Should be easy to fix.

**Comment by dlorenc** [comment]
Could you open a separate bug to track that fix? It might be more work depending on the hyper-v driver.

**Comment by raeesbhatti** [comment]
@jimmidyson can you please take a look at https://github.com/kubernetes/minikube/issues/518

**Pull request merged**
