### PR TITLE
Fix typo in drivers documentation

### PR DESCRIPTION
**Pull request by AlekSi**
VirtualBox is a regular Virtual Machine, not "FVM"

### CODE REVIEW

**Comment by sharifelgamal** [comment]
Thanks for the contribution @AlekSi! We just need to you sign the CLA so that we can merge your PR.

**Comment by AlekSi** [comment]
I tried to do that, and the experience was traumatizing. identity.linuxfoundation.org thinks I'm "AlekSi 2" (so I think there is another my account somewhere), that CLA was sent to my email (but I received nothing), etc. I used a contact form and checked "Send yourself a copy" checkbox, but again did not receive anything, including a copy.

**Comment by medyagh** [comment]
@AlekSi thank you for this contrubition, please sing the CLA so we can merge this.

**Comment by AlekSi** [comment]
Still trying to do that, see above…

**Comment by medyagh** [comment]
@AlekSi are you still interested to figure out the CLA ?

**Comment by AlekSi** [comment]
Yes, send halp

**Comment by priyawadhwa** [comment]
Hey @AlekSi are you still working on this?

**Comment by AlekSi** [comment]
@priyawadhwa merge conflicts resolved

**Review by priyawadhwa — APPROVED** [review]
Thank you!

**Comment by priyawadhwa** [comment]
Hey @AlekSi it won't let me merge because of the CLA. Could you try going through the steps one more time?

**Comment by AlekSi** [comment]
image

There are no steps I can take other than requesting help (I did that) and sending emails "hey, please look into it" (I did that too).

**Comment by priyawadhwa** [comment]
Hey @AlekSi from the CLA guidelines:

>If you haven't yet, post a comment ("I signed it") to the PR—this is needed for the system to recheck your contribution authorization.

Could you try commenting "I signed it" to this PR?

**Comment by AlekSi** [comment]
I signed it

**Comment by RA489** [comment]
@AlekSi Are you still facing problem while signing the CLA? You can check our KubeCon EU talk https://youtu.be/xdoOmSSCxo8 for more detail on CLA.

**Comment by priyawadhwa** [comment]
Hey @AlekSi -- it seems that this has been fixed in another PR so I'm going to close this one. Sorry this wasn't able to be merged -- some guesses around why the CLA isn't working:

1. If any of the commits have been signed by a different email address, the CLA check won't go through

It would be great if you'd be interested in contributing again. Perhaps consider opening a support ticket as suggested [here](https://identity.linuxfoundation.org/projects/cncf) to get to the bottom of this?

**Pull request closed without merging**
