### PR TITLE
kic: Use SSHRunner by default (20% faster startup)

### LINKED ISSUE #6891: Remove need to pass Node into Bootstrapper
Right now we need to pass into the appropriate node into `cluster.Bootstrapper` since the command runner needs to know which machine to ssh into. This is an abstraction error, since the bootstrapper shouldn't have to care about nodes, it's bootstrapping the *cluster*.

We should find a way to decouple command runner and bootstrapper.

### PR DESCRIPTION
**Pull request by tstromberg**
The TL;DR is that ssh is faster than docker for command-execution and file copies, as it benefits from connection reuse.

Fixes #6891 and #7573

* Ensure that Copy() closes sessions on completion
* Minor refactor so that the bootstrapper doesn't have to create it's own runner (slow)
* Remove duplicate `commandRunner` function
* Add session/client retry to ensure robustness

This reduces start latency with Docker for macOS by ~20% (9 seconds)

### CODE REVIEW

**Comment by sharifelgamal** [comment]
the none test failures all seem related to deleting minikube: 

```
-- stdout --
	* Uninstalling Kubernetes v1.18.0 using kubeadm ...
-- /stdout --
** stderr ** 
	* 
	X Error getting host: machine "minikube" does not exist
	* 
	* minikube is exiting due to an error. If the above message is not useful, open an issue:
	  - https://github.com/kubernetes/minikube/issues/new/choose
** /stderr **
```

**Comment by tstromberg** [comment]
> the none test failures all seem related to deleting minikube:
> 
> ```
> -- stdout --
> 	* Uninstalling Kubernetes v1.18.0 using kubeadm ...
> -- /stdout --
> ** stderr ** 
> 	* 
> 	X Error getting host: machine "minikube" does not exist
> 	* 
> 	* minikube is exiting due to an error. If the above message is not useful, open an issue:
> 	  - https://github.com/kubernetes/minikube/issues/new/choose
> ** /stderr **
> ```

**Comment by tstromberg** [comment]
Oof. I forgot to close the ssh session, so some integration tests ran out of open files :(

**Comment by medyagh** [comment]
I wonder if this PR will break the hac/preload geneator script

**Comment by tstromberg** [comment]
> I wonder if this PR will break the hac/preload geneator script

It does not appear to.

```
I0410 14:52:13.332386   21333 kic.go:153] Creating ssh key for kic: /Users/tstromberg/.minikube/machines/generate-preloaded-images-tar/id_rsa...
I0410 14:52:13.332529   21333 kic_runner.go:174] docker (temp): /Users/tstromberg/.minikube/machines/generate-preloaded-images-tar/id_rsa.pub --> /home/docker/.ssh/authorized_keys (381 bytes)
I0410 14:52:13.523837   21333 kic_runner.go:91] Run: chown docker:docker /home/docker/.ssh/authorized_keys
v1.11.10: Pulling from kube-proxy-amd64
39fafc05754f: Pulling fs layer
db3f71d0eb90: Pulling fs layer
c697db36e22b: Pulling fs layer
db3f71d0eb90: Verifying Checksum
```

**Comment by medyagh** [comment]
what happened ! the failures bumped up daramticly !
Jenkins: completed with 11 / 68 failures in 27.60 minute(s).

**Comment by medyagh** [comment]
so I think your latest update on the PR broke kic
```
	* 
	* minikube is exiting due to an error. If the above message is not useful, open an issue:
	  - https://github.com/kubernetes/minikube/issues/new/choose
	I0410 14:43:07.268980   22312 exit.go:58] WithError(failed to start node)=startup failed: apply kic overlay: cmd: sudo /var/lib/minikube/binaries/v1.18.0/kubectl create --kubeconfig=/var/lib/minikube/kubeconfig -f - output: 
	** stderr ** 
	error: no objects passed to create
	
	** /stderr **: sudo /var/lib/minikube/binaries/v1.18.0/kubectl create --kubeconfig=/var/lib/minikube/kubeconfig -f -: Process exited with status 1
	stdout:
	
	stderr:
	error: no objects passed to create
	 called from:
	goroutine 1 [running]:
```
I think the kic overlay is pasted into the std input
and seems like the ssh runner is not handling it correctly

**Comment by medyagh** [comment]
### my test summary (in progress)
- https://storage.googleapis.com/minikube-builds/logs/7591/6ddb934/Docker_Linux.html#fail_TestErrorSpam
error_spam_test.go:57: unexpected stderr line: "* Restarting the docker service may improve performance."

**Pull request merged**
