### PR TITLE
Allow running docker driver with force on 1 CPU

### LINKED ISSUE #15608: Possibility to override NumCPU with --force for docker (engine) driver
Currently there is an extra hard-coded check for Docker, that makes it fail even if it passes the first hurdle.

```console
ubuntu $ minikube start --force
😄  minikube v1.28.0 on Ubuntu 20.04 (amd64)
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
✨  Automatically selected the docker driver. Other choices: podman, none, ssh

⛔  Requested cpu count 2 is greater than the available cpus of 1


⛔   has less than 2 CPUs available, but Kubernetes requires at least 2 to be available

🛑  The "docker" driver should not be used with root privileges. If you wish to continue as root, use --force.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/

🧯  The requested memory allocation of 1983MiB does not leave room for system overhead (total system memory: 1983MiB). You may face stability issues.
💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=1983mb'

📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.25.3 preload ...
    > preloaded-images-k8s-v18-v1...:  385.44 MiB / 385.44 MiB  100.00% 158.94 
    > gcr.io/k8s-minikube/kicbase:  386.27 MiB / 386.27 MiB  100.00% 33.49 MiB 
    > gcr.io/k8s-minikube/kicbase:  0 B [________________________] ?% ? p/s 12s
🔥  Creating docker container (CPUs=2, Memory=1983MB) ...

⛔  Exiting due to RSRC_INSUFFICIENT_CORES: Docker has less than 2 CPUs available, but Kubernetes requires at least 2 to be available
```

It would make the sense, if the behaviour was similar for the "none" driver and for the "docker" driver ?

There is an `exit.Fatal` in "advice", that doesn't use the exitIfNotForced logic used in all other places...

### PR DESCRIPTION
**Pull request by afbjorklund**
For running on killercoda

Closes #15608

----

https://killercoda.com/examples/scenario/ubuntu-simple

`minikube start --driver=docker`

### CODE REVIEW

**Comment by medyagh** [comment]
@afbjorklund does this replace the other PR ? https://github.com/kubernetes/minikube/pull/15610/files

**Comment by spowelljr** [comment]
> @afbjorklund does this replace the other PR ? https://github.com/kubernetes/minikube/pull/15610/files

One is for none driver and one is for docker driver

**Comment by afbjorklund** [comment]
I'm not sure why it was checked in two (or three?) different places

**Comment by spowelljr** [comment]
This doesn't seem to be working for me
```
$ ./out/minikube start --driver docker --force
😄  minikube v1.28.0 on Darwin 13.1 (arm64)
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
✨  Using the docker driver based on user configuration
- Ensure your docker daemon has access to enough CPU/memory resources.
- Docs https://docs.docker.com/docker-for-mac/#resources

⛔  Requested cpu count 2 is greater than the available cpus of 1


⛔  Docker Desktop has less than 2 CPUs configured, but Kubernetes requires at least 2 to be available
💡  Suggestion: 

    1. Click on "Docker for Desktop" menu icon
    2. Click "Preferences"
    3. Click "Resources"
    4. Increase "CPUs" slider bar to 2 or higher
    5. Click "Apply & Restart"
📘  Documentation: https://docs.docker.com/docker-for-mac/#resources

📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...

⛔  Exiting due to RSRC_DOCKER_CORES: Docker Desktop has less than 2 CPUs configured, but Kubernetes requires at least 2 to be available
💡  Suggestion: 

    1. Click on "Docker for Desktop" menu icon
    2. Click "Preferences"
    3. Click "Resources"
    4. Increase "CPUs" slider bar to 2 or higher
    5. Click "Apply & Restart"
📘  Documentation: https://docs.docker.com/docker-for-mac/#resources
```

**Comment by spowelljr** [comment]
Oh, this is only for Linux specifically?

**Comment by afbjorklund** [comment]
It was only meant for killercoda

**Comment by afbjorklund** [comment]
It can run `kind` today, since they disable the "preflight" phase

**Comment by spowelljr** [comment]
> It was only meant for [killercoda](https://killercoda.com/playgrounds) "ubuntu"
> 
> But Docker Desktop has 2 vCPU by default, right ?
> 
> > **CPUs.** By default, Docker Desktop is set to use half the number of processors available on the host machine.
> 
> It does need the other patch, for kubeadm

I just tried setting it to one core for testing purposes

**Review by medyagh — APPROVED** [review]

**Pull request merged**
