### PR TITLE
Kubernetes v1.7 alpha 2 update.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Windows had some test failures, going to retest to make sure it was a flake.

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
Pushed this as a branch called k8s-v1.7. Deleting the PR.

**Pull request closed without merging**
