### PR TITLE
wip: Improve minikube tunnel output

### PR DESCRIPTION
**Pull request by RA489**
Improve minikube tunnel output
fixes https://github.com/kubernetes/minikube/issues/6309

### CODE REVIEW

**Comment by RA489** [comment]
@medyagh Before output was following:

```
Status:
		machine: minikube
		pid: 22890
		route: 10.96.0.0/12 -> 10.0.7.230
		minikube: Running
		services: []
	    errors:
			minikube: no errors
			router: no errors
			loadbalancer emulator: no errors
```

**Comment by RA489** [comment]
After this PR output was following:
```
Status:
		machine: minikube
		pid: 22890
		route: 10.96.0.0/12 -> 10.0.7.230
		minikube: Running
		services: []
	    errors:
			minikube: no errors
			router: no errors
			loadbalancer emulator: Get https://10.0.7.230:8443/api/v1/services: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by tstromberg** [comment]
We have some change-detector unit tests that you will need to update before we can merge this PR. Please run `make test` and take a look.

**Comment by medyagh** [comment]
@RA489 the output should not show any errors if there is no errors.

**Comment by RA489** [comment]
@medyagh Currently in this PR if there is no error in all three like below it will skip printing below output.


```
errors:
			minikube: no errors
			router: no errors
			loadbalancer emulator: no error
```

**Comment by RA489** [comment]
> @RA489 the output should not show any errors if there is no errors. this PR needs more work I will mark this as WIP

It is currently not printing anything if `minikube: no errors  router: no errors loadbalancer emulator: no error` in all three.

Do you want me to show some msg instead?

**Comment by sharifelgamal** [comment]
@RA489 You should just suppress the `errors` portion of the output if there are no errors.

**Pull request closed without merging**
