### PR TITLE
Add option to use icons instead of emojis

### PR DESCRIPTION
**Pull request by afbjorklund**
Make it possible to use icons from "Nerd Fonts",
instead of using the regular emojis from Unicode.

See https://www.nerdfonts.com/font-downloads for
the required fonts in order to display properly.

For #5734

### CODE REVIEW

**Comment by afbjorklund** [comment]
Choosing names instead of icons, made it harder to compare with emojis.
Could keep it as an alternative for later (?), used raw `rune` literals for now:

```
''
const human rune = '\uf7e5'
```

**Comment by afbjorklund** [comment]
Here is a short summary of styles (emojis, icons, enums):  [nerdfonts.txt](https://github.com/kubernetes/minikube/files/3965152/nerdfonts.txt)

**Comment by medyagh** [comment]
that is cool ! do you have a screenshot how it looks like ?

**Comment by afbjorklund** [comment]
@medyagh : see https://github.com/kubernetes/minikube/issues/5734#issuecomment-564599519

**Comment by tstromberg** [comment]
Are you sending this PR out because it's possible, or because you think it is the right thing to do?

**Comment by afbjorklund** [comment]
@tstromberg : I thought I would send it in because I ended up writing it (just to see what it looked like)

I didn't know about the availability of this font, even though I had seen powerlines and Font Awesome individually. I'm not sure what the original plan was, maybe Medya only wanted to change one emoji ?

My finding was that changing just one emoji for one icon ended up looking _worse_ than keeping it. So it is better to change **all** of them in that case. The icons being monochrome is a pro and a con, I guess.

There is a lot of hidden complexity in this feature (i.e. telling users how to use it, maintaining two sets)

So I am OK with closing it, unless it grows a following. I'll keep the branch around, for a while.

It also got me thinking about using color for minikube, but I think I will leave that can of worms closed...

**Pull request closed without merging**
