### PR TITLE
fix(localkube): Read path to install localkube from env variable

### PR DESCRIPTION
**Pull request by ramaganapa**
Support installing localkube to a user specified folder. Fixes issue #2348

### CODE REVIEW

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by dlorenc** [comment]
The code looks fine, but can you explain the use-case a bit more? We might want to add this to the documentation.

**Comment by ramaganapa** [comment]
Few flavors of linux like Container Linux from CoreOS mounts "/usr/" as readonly. Because it simplifies applying OS updates. On it updates are applied just by swapping the mount point at "/usr/" with updated partition. Not even root user can add or edit files under "/usr/".
Reference: https://coreos.com/os/docs/latest/sdk-disk-partitions.html

So, minikube should provide ability to install localkube to a place other than "/usr/local/". I prefer "/opt/localkube/" when starting it using none driver.

**Comment by dlorenc** [comment]
> Few flavors of linux like Container Linux from CoreOS mounts "/usr/" as readonly. Because it simplifies applying OS updates. On it updates are applied just by swapping the mount point at "/usr/" with updated partition. Not even root user can add or edit files under "/usr/".

How are you using localkube on Container Linux?

**Comment by ramaganapa** [comment]
I haven't started using Container Linux yet. But, had similar issues with a customized Linux Distro used at work where /usr/local folder is readonly. Thought of submitting PR after seeing #2348. @khs1994 could you explain your experience with Container Linux?

**Pull request closed without merging**
