### PR TITLE
[Trival] beta.kubernetes.io/os is already deprecated since v1.14, are  targeted for removal in v1.18

### PR DESCRIPTION
**Pull request by wawa0210**
/kind cleanup

Ref: kubernetes/kubernetes#89477

/assign @tstromberg

### CODE REVIEW

**Comment by tstromberg** [comment]
I'm curious if this breaks dashboard for --kubernetes-version=v1.11.x users.

**Comment by tstromberg** [comment]
I did some local testing, and this PR does break dashboard deployments to Kubernetes versions older than v1.14 - versions that minikube currently supports.

Let's revisit this when Kubernetes v1.19 ships without this node selector. We can then consider whether to restrict the `dashboard` command to Kubernetes v1.14 releases and newer, or if we should search and replace the node selector based on the Kubernetes release.

**Comment by wawa0210** [comment]
> I did some local testing, and this PR does break dashboard deployments to Kubernetes versions older than v1.14 - versions that minikube currently supports.
> 
> Let's revisit this when Kubernetes v1.19 ships without this node selector. We can then consider whether to restrict the `dashboard` command to Kubernetes v1.14 releases and newer, or if we should search and replace the node selector based on the Kubernetes release.

Sorry, I thought minikube was always the latest dashboard, because I just changed this in the dashboard project https://github.com/kubernetes/dashboard/pull/5045

If minikube needs to adapt to versions below 1.14, I think this pr can also be closed first, and then observed later

**Pull request closed without merging**
