### PR TITLE
Add additional modules for IPVS

### LINKED ISSUE #1894: Add additional ipvs modules
**Is this a FEATURE REQUEST?** :

If this is a FEATURE REQUEST, please:
Right now only the CONFIG_IP_VS module is available. This is not enough.
Please enable the additional list of modules. Without this modules is not possible to configure ipvs

```console
#
# IPVS
#
CONFIG_IP_VS=m
CONFIG_IP_VS_IPV6=m
# CONFIG_IP_VS_DEBUG=m
CONFIG_IP_VS_TAB_BITS=12

#
# IPVS transport protocol load balancing support
#
CONFIG_IP_VS_PROTO_TCP=y
CONFIG_IP_VS_PROTO_UDP=m
CONFIG_IP_VS_PROTO_AH_ESP=m
CONFIG_IP_VS_PROTO_ESP=m
CONFIG_IP_VS_PROTO_AH=m
CONFIG_IP_VS_PROTO_SCTP=m

#
# IPVS scheduler
#
CONFIG_IP_VS_RR=m
CONFIG_IP_VS_WRR=m
CONFIG_IP_VS_LC=m
CONFIG_IP_VS_WLC=m
CONFIG_IP_VS_FO=m
CONFIG_IP_VS_OVF=m
CONFIG_IP_VS_LBLC=m
CONFIG_IP_VS_LBLCR=m
CONFIG_IP_VS_DH=m
CONFIG_IP_VS_SH=m
CONFIG_IP_VS_SED=m
CONFIG_IP_VS_NQ=m

#
# IPVS SH scheduler
#
CONFIG_IP_VS_SH_TAB_BITS=8

#
# IPVS application helper
#
CONFIG_IP_VS_FTP=m
CONFIG_IP_VS_NFCT=m
```

### PR DESCRIPTION
**Pull request by r2d4**
Fixes #1894 
Can you verify these are exhaustive @aledbf?

You can grab an ISO after the jenkins cross build finishes at 

https://storage.googleapis.com/minikube-builds/1897/minikube-testing.iso

### CODE REVIEW

**Comment by aledbf** [comment]
@r2d4 how I can test this change?
I can start a new cluster with the iso but the docker.service it's missing so minikube start ends with errors

**Comment by r2d4** [comment]
Ah you'll need to run a version from this PR

https://storage.googleapis.com/minikube-builds/1897/minikube-linux-amd64

**Comment by aledbf** [comment]
@r2d4 it's working now

*Create a dummy service*
```console
$ kubectl create -f https://raw.githubusercontent.com/kubernetes/ingress/master/examples/http-svc.yaml
service "http-svc" created
replicationcontroller "http-svc" created
```

*Create the configuration configmap*
```console
$ echo "
apiVersion: v1
kind: ConfigMap
metadata:
  name: vip-configmap
data:
  192.168.99.200: default/http-svc
" | kubectl create -f -
```

*Create the keepalived rc:*
```console
$ kubectl create -f https://raw.githubusercontent.com/aledbf/kube-keepalived-vip/master/vip-rc.yaml
replicationcontroller "kube-keepalived-vip" created


```console
$ kubectl get pods
NAME                        READY     STATUS              RESTARTS   AGE
http-svc-pdjqk              0/1       ContainerCreating   0          8s
kube-keepalived-vip-sk94p   0/1       ContainerCreating   0          2s
```console

*Check the logs:*
```console
$ kubectl logs -f kube-keepalived-vip-sk94p
ERROR: logging before flag.Parse: I0830 21:41:06.961457       1 main.go:201] Creating API server client for https://10.0.0.1:443
ERROR: logging before flag.Parse: I0830 21:41:06.964877       1 keepalived.go:187] cleaning ipvs configuration
ERROR: logging before flag.Parse: I0830 21:41:06.965834       1 main.go:125] starting LVS configuration
ERROR: logging before flag.Parse: I0830 21:41:07.582862       1 utils.go:150] network interfaces: [{Index:2 MTU:1500 Name:eth0 HardwareAddr:08:00:27:ba:9d:60 Flags:up|broadcast|multicast} {Index:3 MTU:1500 Name:eth1 HardwareAddr:08:00:27:a7:48:b8 Flags:up|broadcast|multicast} {Index:4 MTU:1480 Name:sit0 HardwareAddr: Flags:0}]
ERROR: logging before flag.Parse: I0830 21:41:07.585661       1 main.go:135] starting keepalived to announce VIPs
Wed Aug 30 21:41:07 2017: Starting Keepalived v1.3.5 (unknown)
Wed Aug 30 21:41:07 2017: Opening file '/etc/keepalived/keepalived.conf'.
Wed Aug 30 21:41:07 2017: Starting Healthcheck child process, pid=18
Wed Aug 30 21:41:07 2017: Starting VRRP child process, pid=19
Wed Aug 30 21:41:07 2017: Opening file '/etc/keepalived/keepalived.conf'.
Wed Aug 30 21:41:07 2017: Registering Kernel netlink reflector
Wed Aug 30 21:41:07 2017: Registering Kernel netlink command channel
Wed Aug 30 21:41:07 2017: Registering gratuitous ARP shared channel
Wed Aug 30 21:41:07 2017: Opening file '/etc/keepalived/keepalived.conf'.
Wed Aug 30 21:41:07 2017: Using LinkWatch kernel netlink reflector...
ERROR: logging before flag.Parse: I0830 21:41:08.968378       1 keepalived.go:160] reloading keepalived
Wed Aug 30 21:41:08 2017: Opening file '/etc/keepalived/keepalived.conf'.
Wed Aug 30 21:41:08 2017: Got SIGHUP, reloading checker configuration
Wed Aug 30 21:41:08 2017: Opening file '/etc/keepalived/keepalived.conf'.
Wed Aug 30 21:41:08 2017: Initializing ipvs
Wed Aug 30 21:41:08 2017: Activating healthchecker for service [172.17.0.4]:tcp:8080 for VS [192.168.99.200]:tcp:80
Wed Aug 30 21:41:08 2017: Registering Kernel netlink reflector
Wed Aug 30 21:41:08 2017: Registering Kernel netlink command channel
Wed Aug 30 21:41:08 2017: Registering gratuitous ARP shared channel
Wed Aug 30 21:41:08 2017: Opening file '/etc/keepalived/keepalived.conf'.
Wed Aug 30 21:41:08 2017: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Wed Aug 30 21:41:08 2017: Using LinkWatch kernel netlink reflector...
Wed Aug 30 21:41:08 2017: VRRP_Instance(vips) Entering BACKUP STATE
Wed Aug 30 21:41:12 2017: VRRP_Instance(vips) Transition to MASTER STATE
Wed Aug 30 21:41:13 2017: VRRP_Instance(vips) Entering MASTER STATE
Wed Aug 30 21:41:13 2017: VRRP_Instance(vips) using locally configured advertisement interval (1000 milli-sec)
```


*Test the service:*
```console
$ curl -v http://192.168.99.200:80
* Rebuilt URL to: http://192.168.99.200:80/
*   Trying 192.168.99.200...
* TCP_NODELAY set
* Connected to 192.168.99.200 (192.168.99.200) port 80 (#0)
> GET / HTTP/1.1
> Host: 192.168.99.200
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 30 Aug 2017 21:46:08 GMT
< Content-Type: text/plain
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: echoserver
< 


Hostname: http-svc-pdjqk

Pod Information:
	node name:	kk
	pod name:	http-svc-pdjqk
	pod namespace:	default
	pod IP:	172.17.0.4

Server values:
	server_version=nginx: 1.13.3 - lua: 10008

Request Information:
	client_address=192.168.99.1
	method=GET
	real path=/
	query=
	request_version=1.1
	request_uri=http://192.168.99.200:8080/

Request Headers:
	accept=*/*
	host=192.168.99.200
	user-agent=curl/7.52.1

Request Body:
	-no body in request-

* Curl_http_done: called premature == 0
* Connection #0 to host 192.168.99.200 left intact
```

**Comment by aledbf** [comment]
@r2d4 @dlorenc thanks for this PR!

**Comment by r2d4** [comment]
Awesome, thanks for verifying.

**Pull request merged**
