### PR TITLE
wip: testing kic build image

### PR DESCRIPTION
**Pull request by medyagh**

### CODE REVIEW

**Comment by medyagh** [comment]
OK to build image

**Comment by medyagh** [comment]
OK to build image

**Comment by medyagh** [comment]
OK to build image

**Comment by medyagh** [comment]
OK to build image

**Comment by sharifelgamal** [comment]
New image is available at gcr.io/k8s-minikube/kicbase:v0.0.17-1611688068 with a sha of 1cd2e039ec9d418e6380b2fa0280503a72e5b282adea674ee67882f59f4f546e

**Pull request closed without merging**
