### PR TITLE
Specifying control plane IP in kubeadm config template

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Comment by medyagh** [comment]
"TestDockerFlags" fails consistently on all 3 docker tests (ubuntu 16, ubuntu 18) and jenkins docker linux

**Comment by medyagh** [comment]
and on a hyperkit driver, I can not do ssh

 $ ./out/minikube ssh
ssh: dial tcp 192.168.64.48:22: connect: connection refused

**Comment by medyagh** [comment]
to replicate locally I tried this : 
```
./out/minikube start --cache-images=false --install-addons=false --wait=false --docker-env=FOO=BAR --docker-env=BAZ=BAT --docker-opt=debug --docker-opt=icc=true --alsologtostderr -v=5
```

and you will see

```
I0222 10:23:23.908801   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:27.926582   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:31.930985   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:35.936583   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:39.941502   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:43.949684   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:47.957392   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:51.963299   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:55.965575   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:23:59.975435   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:24:03.984332   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:24:07.998939   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:24:12.002965   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
I0222 10:24:16.008500   61319 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.51:22: connect: connection refused
```

**Comment by sharifelgamal** [comment]
All of that worked locally for me, so I'm not sure what's going on

**Comment by medyagh** [comment]
> All of that worked locally for me, so I'm not sure what's going on

ah!  I think I found the problem

I tried again I with docker driver, ( I think the ssh problem I mentioned was irrelaevent)


"this is where the test fails !

docker@minikube:~$ systemctl show docker --property=Environment --no-pager
Failed to connect to bus: No such file or directory

but it passes with sudo

docker@minikube:~$ sudo systemctl show docker --property=Environment --no-pager
Environment=FOO=BAR BAZ=BAT

**Comment by sharifelgamal** [comment]
that also works fine for me:
```out/minikube -p minikube ssh "systemctl show docker --property=ExecStart --no-pager" 
ExecStart={ path=/usr/bin/dockerd ; argv[]=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=hyperkit --insecure-registry 10.96.0.0/12 --debug --icc=true ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }```

also I'm not sure what that has to do with my change.

**Comment by medyagh** [comment]
> that also works fine for me:
> 
> ```
> out/minikube -p minikube ssh "systemctl show docker --property=ExecStart --no-pager" 
> ExecStart={ path=/usr/bin/dockerd ; argv[]=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=hyperkit --insecure-registry 10.96.0.0/12 --debug --icc=true ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
> ```
> 
> also I'm not sure what that has to do with my change.

you are right ...it seems to be a docker-driver only thing. we could do sudo in a different PR for docker driver. lets merge this

**Pull request merged**
