### PR TITLE
fix kubeadm join error: "Found multiple CRI sockets"

### LINKED ISSUE #11179: kubeadm join error: "Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock"
kubeadm join will fail with this error if multiple CRI sockets exist (eg, both docker and crio are started at the same time)

/assign

### PR DESCRIPTION
**Pull request by prezha**
fixes #11179

### CODE REVIEW

**Review by afbjorklund — CHANGES_REQUESTED** [review]
There is already a check for this when generating the join command, but it doesn't add any configuration when using the (previously default) dockershim.

```go
        if cc.KubernetesConfig.CRISocket != "" {
                joinCmd = fmt.Sprintf("%s --cri-socket %s", joinCmd, cc.KubernetesConfig.CRISocket)
        }
```

We have yet another hack in DeleteCluster, which has the right code:

```go
        sp := cr.SocketPath()
        if sp == "" {
                sp = kconst.DefaultDockerCRISocket
        }

```

**Comment by prezha** [comment]
> There is already a check for this when generating the join command, but it doesn't add any configuration when using the (previously default) dockershim.
> 
> ```go
>         if cc.KubernetesConfig.CRISocket != "" {
>                 joinCmd = fmt.Sprintf("%s --cri-socket %s", joinCmd, cc.KubernetesConfig.CRISocket)
>         }
> ```
> 
> We have yet another hack in DeleteCluster, which has the right code:
> 
> ```go
>         sp := cr.SocketPath()
>         if sp == "" {
>                 sp = kconst.DefaultDockerCRISocket
>         }
> ```

instead of those (now 3) hacks, wouldn't it be then maybe better to set it at the beginning - eg, in cmd.generateClusterConfig right after https://github.com/kubernetes/minikube/blob/d1b09893e7eaa93383870bfcb3c546a310a99ab8/cmd/minikube/cmd/start_flags.go#L272-L275 ?

**Comment by prezha** [comment]
> There is already a check for this when generating the join command, but it doesn't add any configuration when using the (previously default) dockershim.
> 
> ```go
>         if cc.KubernetesConfig.CRISocket != "" {
>                 joinCmd = fmt.Sprintf("%s --cri-socket %s", joinCmd, cc.KubernetesConfig.CRISocket)
>         }
> ```
> 
> We have yet another hack in DeleteCluster, which has the right code:
> 
> ```go
>         sp := cr.SocketPath()
>         if sp == "" {
>                 sp = kconst.DefaultDockerCRISocket
>         }
> ```

@afbjorklund agree, i've used the 'right code' to fix the existing join cmd in #11209 

i'll close this one in favour of #11209
/close

**Pull request closed without merging**
