### PR TITLE
Update Skaffold link

### PR DESCRIPTION
**Pull request by MichaelBitard**

### CODE REVIEW

**Comment by MichaelBitard** [comment]
I signed it

**Comment by medyagh** [comment]
Thanks for fixing this

**Comment by MichaelBitard** [comment]
You're welcome!

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by MichaelBitard** [comment]
I think the `KVM_Linux` and `VirtualBox_Linux` tests failures are not related to my PR

**Pull request merged**
