### PR TITLE
CI: Cut down log noise by just showing problems by default

### PR DESCRIPTION
**Pull request by tstromberg**
Based on feedback by @medyagh in #5760

### CODE REVIEW

**Comment by medyagh** [comment]
hopefully we still have some flaky test to see it in action on this PR itself 
that one time you Hope for a test failure to happen :D

**Comment by medyagh** [comment]
something is wrong the linux kvm timed out ! 
```
panic: test timed out after 1h0m0s
```

**Comment by tstromberg** [comment]
Looks like this PR is  doing the right thing now. Will ask for more test feedback though.

**Pull request merged**
