### PR TITLE
remove trailing `\` in the shell command

### PR DESCRIPTION
**Pull request by goodwillcoding**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Thanks for the PR.  LGTM, thanks!

**Comment by aaron-prindle** [comment]
You will need to sign the CLA before we can merge this in.  /To sign the CLA follow the instructions the bot posted and then we can merge.

**Comment by goodwillcoding** [comment]
The CLA form is RIDICULOUSLY broken. I used github login setup, it created an account without a password. Tried the password reset link which requires a current LF password without the current password which was never set. This is most complicated process I've seen yet.

**Comment by goodwillcoding** [comment]
Oh I guess the checks passed.

**Comment by aaron-prindle** [comment]
Sorry about that, it seems that it is passing now.  Thanks for submitting this!

**Comment by goodwillcoding** [comment]
Thanks, sorry for the frustration, it was just a pretty painful process. Thanks for accepting the PR.

**Pull request merged**
