### PR TITLE
Update docker_registry.md

### PR DESCRIPTION
**Pull request by stoffen01**
Need to use docker deamon from Minikube for this method to work.

### CODE REVIEW

**Comment by stoffen01** [comment]
CLA added

**Comment by afbjorklund** [comment]
The whole point of that document is to _avoid_ using the master docker daemon, but instead push the image from a local dockerd to the registry...

**Comment by tstromberg** [comment]
LGTM, but needs CLA approval. Let me know if you need help getting it sorted out.

**Comment by medyagh** [comment]
@tstromberg I think this PR is wrong ! the registery is an alternative to docker-env ! 

if u want to do docker-env u dont need to use registery.

**Comment by priyawadhwa** [comment]
Hey @stoffen01 are you still working on this?

**Comment by afbjorklund** [comment]
Thanks for contributing, open another PR if you find any issues with the minikube registry

**Pull request closed without merging**
