### PR TITLE
clean up go mod

### PR DESCRIPTION
**Pull request by medyagh**
trying to remove two replaces that might not be needed anymore

### CODE REVIEW

**Review by afbjorklund — CHANGES_REQUESTED** [review]
Please don't revert the cpuid renaming that was done previously.

* https://github.com/minikube-machine/machine/pull/4

If it needs to be done, it should go in minikube-machine properly...

https://github.com/minikube-machine/machine/blob/main/drivers/virtualbox/vtx_intel.go

**Comment by medyagh** [comment]
> Please don't revert the cpuid renaming that was done previously.
> 
> * [Organization of github.com/intel-go/cpuid changed minikube-machine/machine#4](https://github.com/minikube-machine/machine/pull/4)
> 
> If it needs to be done, it should go in minikube-machine properly...
> 
> https://github.com/minikube-machine/machine/blob/main/drivers/virtualbox/vtx_intel.go

good call thank you, yes I rather get rid of as many replaces as I can :)  I will do that on minikube-machine fist then

**Comment by medyagh** [comment]
made a PR https://github.com/minikube-machine/machine/pull/5

**Pull request closed without merging**
