### PR TITLE
Use temp file for cached downloads & rename to handle interrupted downloads gracefully

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by r2d4** [comment]
Should we also do this for the iso download?

**Comment by jimmidyson** [comment]
Yeah. I'd also like to add in progress bars (already done in minishift so proven) & checksum validation (if we've not already done that - can't remember).

Let me add in at least ISO download temp/rename & do the rest in a separate PR.

**Comment by r2d4** [comment]
Awesome, SGTM

dlorenc added checksum validation for localkube in https://github.com/kubernetes/minikube/pull/624

**Comment by jimmidyson** [comment]
Added download temp/rename for ISO download & refactored the ISO checksum validation to calculate during download.

**Comment by jimmidyson** [comment]
Mergin as approved, although hyperv build still not completed.

**Comment by r2d4** [comment]
It doesn't look like the windows CI server is functional yet.  I've turned off the hyper-v presubmit check until then to avoid confusion

**Pull request merged**
