### PR TITLE
wip: Adding name.minikube.sigs.k8s.io label to the docker network

### PR DESCRIPTION
**Pull request by imrajdas**
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>

closes- https://github.com/kubernetes/minikube/issues/12635

Changes
Adding name.minikube.sigs.k8s.io  label to the docker network create and delete function

Logs: 
[tmp.txt](https://github.com/kubernetes/minikube/files/7272798/tmp.txt)

### CODE REVIEW

**Comment by rajdas98** [comment]
Hi @spowelljr , Can you approve the pipelines to run?

**Comment by spowelljr** [comment]
Hi @rajdas98, we don't have a test that would catch this issue, could you please add a test to this that starts two instances and then deletes one of them and then checks if the network for the other instance still exists.

**Comment by medyagh** [comment]
@rajdas98 
this PR makes this label

$ docker network inspect minikube
```
...
        "Labels": {
            "created_by.minikube.sigs.k8s.io": "true,name.minikube.sigs.k8s.io=minikube"
        }
...

```
but we should create a separate label so it be like

        "Labels": {
            "created_by.minikube.sigs.k8s.io": "true",
           "name.minikube.sigs.k8s.io" : "minikube"
        }

**Review by medyagh — CHANGES_REQUESTED** [review]
this breaks the `minikube delete--all` when the minikube home folder is deleted (orpahned minikbue networks)

to reporoduce do this with this PR binary try:


minikube start -p minikube
and then
minikube start -p p1

$ docker ps
CONTAINER ID   IMAGE                                                         COMMAND                  CREATED         STATUS         PORTS                                                                                                                                  NAMES
ad0722292fae   gcr.io/k8s-minikube/kicbase-builds:v0.0.27-1633027942-12081   "/usr/local/bin/entr…"   2 minutes ago   Up 2 minutes   127.0.0.1:53901->22/tcp, 127.0.0.1:53902->2376/tcp, 127.0.0.1:53904->5000/tcp, 127.0.0.1:53905->8443/tcp, 127.0.0.1:53903->32443/tcp   p2
7294cc27418e   gcr.io/k8s-minikube/kicbase-builds:v0.0.27-1633027942-12081   "/usr/local/bin/entr…"   3 minutes ago   Up 3 minutes   127.0.0.1:53491->22/tcp, 127.0.0.1:53492->2376/tcp, 127.0.0.1:53489->5000/tcp, 127.0.0.1:53490->8443/tcp, 127.0.0.1:53493->32443/tcp   minikube
8d5d6fb25fb2   docker/getting-started                                        "/docker-entrypoint.…"   4 hours ago     Up 4 hours     0.0.0.0:80->80/tcp                                                                                                                     affectionate_wu

$ docker ps
(get the container ids)
delete the two containers manually
$ docker rm -fv ad0722292fae
ad0722292fae

$ docker rm -fv 7294cc27418e

# remove the minikube home folder
$ rm -rf ~/.minikube

$ docker ps


$ docker network ls
NETWORK ID     NAME       DRIVER    SCOPE
cfd291543106   bridge     bridge    local
a4cf62200f82   host       host      local
5b63de4ceba9   minikube   bridge    local
28c81f724c0f   none       null      local
0643600935e1   p2         bridge    local
17:24:24 medya/workspace/minikube
add-label-docker-net ✓

add-label-docker-net ✓
$ mk delete --all --alsologtostderr
I1206 17:24:45.069639   91984 out.go:298] Setting OutFile to fd 1 ...
I1206 17:24:45.069793   91984 out.go:350] isatty.IsTerminal(1) = true
I1206 17:24:45.069797   91984 out.go:311] Setting ErrFile to fd 2...
I1206 17:24:45.069801   91984 out.go:350] isatty.IsTerminal(2) = true
I1206 17:24:45.069877   91984 root.go:313] Updating PATH: /Users/medya/.minikube/bin
W1206 17:24:45.069957   91984 root.go:291] Error reading config file at /Users/medya/.minikube/config/config.json: open /Users/medya/.minikube/config/config.json: no such file or directory
W1206 17:24:45.070404   91984 delete.go:158] 'error loading profiles in minikube home "/Users/medya/.minikube": open /Users/medya/.minikube/profiles: no such file or directory
I1206 17:24:45.070469   91984 delete.go:124] deleting containers and volumes ...
I1206 17:24:45.070508   91984 cli_runner.go:115] Run: docker ps -a --filter label=created_by.minikube.sigs.k8s.io=true --format {{.Names}}
I1206 17:24:45.224561   91984 volumes.go:79] trying to delete all docker volumes with label created_by.minikube.sigs.k8s.io=true
I1206 17:24:45.224718   91984 cli_runner.go:115] Run: docker volume ls --filter label=created_by.minikube.sigs.k8s.io=true --format {{.Name}}
I1206 17:24:45.355755   91984 cli_runner.go:115] Run: docker volume rm --force minikube
I1206 17:24:45.730349   91984 cli_runner.go:115] Run: docker volume rm --force p2
I1206 17:24:46.122506   91984 volumes.go:101] trying to prune all docker volumes with label created_by.minikube.sigs.k8s.io=true
I1206 17:24:46.122788   91984 cli_runner.go:115] Run: docker volume prune -f --filter label=created_by.minikube.sigs.k8s.io=true
I1206 17:24:46.272514   91984 delete.go:120] skipping deleteContainersAndVolumes for podman: exec: "podman": executable file not found in $PATH
I1206 17:24:46.272544   91984 delete.go:229] DeleteProfiles
I1206 17:24:46.290381   91984 out.go:177] 🔥  Successfully deleted all profiles
🔥  Successfully deleted all profiles
17:24:46 medya/workspace/minikube
add-label-docker-net ✓
$ docker network ls
NETWORK ID     NAME       DRIVER    SCOPE
cfd291543106   bridge     bridge    local
a4cf62200f82   host       host      local
5b63de4ceba9   minikube   bridge    local
28c81f724c0f   none       null      local
0643600935e1   p2         bridge    local

we can see the two networks p2 and minikbue are still there

**Comment by medyagh** [comment]
I suggest trying to add two separate labels so it doesnt interfere with the abandoned network clean up

**Comment by medyagh** [comment]
@rajdas98 are u still working on this

**Comment by rajdas98** [comment]
> @rajdas98 are u still working on this

Apologies for the late update. I've pushed the name.minikube.sigs.k8s.io as a separate label.

 But the unit test case part is left as requested here- https://github.com/kubernetes/minikube/pull/12644#issuecomment-936714561
 
 I can raise a  seperate PR for the unit test case if you want this PR urgently.

**Comment by spowelljr** [comment]
Hi @rajdas66, just following up on this PR, are you still working on this?

If you are, are you able to implement https://github.com/kubernetes/minikube/pull/12644#issuecomment-936714561?

**Comment by spowelljr** [comment]
This PR has been open for while with no update so I'm going to close it for now. If you come back to it feel free to reopen it, thanks!

**Pull request closed without merging**
