### PR TITLE
Support CRI-O runtime with Rootless Docker driver (`--driver=docker --container-runtime=cri-o`)

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Follow-up to PR #12359 (containerd runtime with Rootless Docker driver).

Usage (needs [cgroup v2](https://rootlesscontaine.rs/getting-started/common/cgroup2/)):
```
dockerd-rootless-setuptool.sh install
docker context use rootless
minikube start --driver=docker --container-runtime=cri-o
```

See `site/content/en/docs/drivers/includes/docker_usage.inc`

---

Tested on Ubuntu 21.10 host, Rootless Docker 20.10.10

```console
$ kubectl get nodes -o wide
NAME       STATUS   ROLES                  AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
minikube   Ready    control-plane,master   104s   v1.22.3   192.168.49.2   <none>        Ubuntu 20.04.2 LTS   5.13.0-20-generic   cri-o://1.22.0

$ kubectl get pods -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
kube-system   coredns-78fcd69978-kpsfg           1/1     Running   0             79s
kube-system   etcd-minikube                      1/1     Running   0             85s
kube-system   kindnet-546zq                      1/1     Running   0             79s
kube-system   kube-apiserver-minikube            1/1     Running   0             93s
kube-system   kube-controller-manager-minikube   1/1     Running   0             92s
kube-system   kube-proxy-w45xb                   1/1     Running   0             79s
kube-system   kube-scheduler-minikube            1/1     Running   0             86s
kube-system   storage-provisioner                1/1     Running   1 (48s ago)   89s
```

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @giuseppe FYI

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
thank you very much @AkihiroSuda for this contribution :) look forward to see more of your great work

**Pull request merged**
