### PR TITLE
Provisioner code

### PR DESCRIPTION
**Pull request by r2d4**
Since it vendors client-go, it will be very difficult to vendor this
code in and keep client-go, apimachinery, and apiserver in check.  We
will most definitely have breaking changes that we need to fix.

The solution I've proposed here is to bring this code in tree.  There are some extra vendor changes, because of the `controller_test.go` file which needs a few `client-go/kubernetes/fake` imports

### CODE REVIEW

**Comment by r2d4** [comment]
agreed that might be a better solution

**Comment by dlorenc** [comment]
Is the rebasing issue something that glide might help with?

**Comment by r2d4** [comment]
No, unfortunately. The real issue is that when we upgrade, we have to use the corresponding versions of client-go, apimachinery, and apiserver. Since those packages have a lot of breaking changes, we make "manual changes" in our code. 

The code that the provisioner vendors in from kubernetes-incubator will also need these changes. And since it's vendored, it would be hacky to edit it.

**Comment by r2d4** [comment]
By bringing that code in tree, we can make the required client-go changes, but it will make upgrading more of a pain as we have more code to check for compatibility.

**Pull request closed without merging**
