### PR TITLE
bump lint

### PR DESCRIPTION
**Pull request by medyagh**
### bumped lint version :)

- bump golang-ci version
- bump go version to latest available
- putting a comment to specify where we can find latest available golang for kuberentes project
- remove un-needed replaces 

### didn't bump kubernetes version :(
tried to bump kubernetes version but I faced this issue https://github.com/kubernetes/minikube/issues/7638 till that is solved will not bump kubernets version which has nice nice new features such as passing context to client-go calls

### CODE REVIEW

**Comment by afbjorklund** [comment]
Would it be possible to do this in two _separate_ PRs instead ? Hard to review/test with all-in-one.

**Comment by medyagh** [comment]
> Would it be possible to do this in two _separate_ PRs instead ? Hard to review/test with all-in-one.

the golang bump didnt invoke any code change, this PR is basicly bumping lint + golang (golang could be easily deleted as one line change)

**Comment by medyagh** [comment]
if it helps to review, most of them are un-needed fmt.Sprtinf("simple string")

**Pull request closed without merging**
