### PR TITLE
Simplify, and remove all un-used minikube error codes

### LINKED ISSUE #11786: Replace InternalEnable and InternalDisable with InternalAddonEnable, and InternalAddonDisable
At the moment, we have InternalEnable, InternalDisable, and InternalAddonEnable. We should simplify and only have InternalAddonEnable and InternalAddonDisable.

### PR DESCRIPTION
**Pull request by mahalrs**
This PR replaces InternalEnable and InternalDisable error codes with InternalAddonEnable and InternalAddonDisable, respectively; and removed all un-used minikube error codes.

fixes #11786

### CODE REVIEW

**Comment by mahalrs** [comment]
@andriyDev let me know if this looks good!

**Review by medyagh — CHANGES_REQUESTED** [review]
thank you @mahalrs  as part of this PR we should remove the un-used other Reasons and use only the new ones

**Comment by mahalrs** [comment]
> thank you @mahalrs as part of this PR we should remove the un-used other Reasons and use only the new ones

@medyagh Thanks for the review. I have already removed InternalEnable and InternalDisable reasons. If you mean to remove other un-used reasons (such as WrongBinaryM1, InternalFlagSet, InternalLogtostderrFlag, etc.) please let me know.

**Comment by mahalrs** [comment]
> thank you @mahalrs as part of this PR we should remove the un-used other Reasons and use only the new ones

@medyagh Done ✅

**Review by medyagh — APPROVED** [review]

**Comment by andriyDev** [comment]
@mahalrs #11773 was merged and broke this, do you mind rebasing onto master after pulling? Hopefully merging isn't too difficult, I'm unsure how your "git-fu" is :P

**Comment by mahalrs** [comment]
@andriyDev properly rebased!

**Comment by andriyDev** [comment]
@mahalrs Awesome! Looks great, we'll merge this as soon as we can (release stuff is in progress)!

/approve

**Pull request merged**
