### PR TITLE
Allow some `minikube start` flags to be set by config file

### PR DESCRIPTION
**Pull request by r2d4**
This allows some of the common `minikube start` options to be passed in by either config file or environment variables.  

Unfortunately, viper does not handle string slices correctly spf13/viper/issues/200 and it doesn't look like theres much activity around fixing this.  

I might add an example config file to minikube after we finalize some more of the commands that can be configured by one.  I didn't add any additional tests here, because the viper behavior is tested pretty extensively in cmd/minikube/cmd/root_test.go but I can add some additional ones if anyone feels strongly.

### CODE REVIEW

**Comment by dlorenc** [comment]
I'm making some Jenkins improvements, so you get to be the guinea pig :)
@minikube-bot test this please

**Comment by dlorenc** [comment]
One more try:

@minikube-bot test this please

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
LGTM. Could you squash commits, then I'll merge?

**Comment by r2d4** [comment]
squashed

**Pull request merged**
