### PR TITLE
Exit non-zero when state isn't running

### PR DESCRIPTION
**Pull request by pnegahdar**

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot ok to test

**Comment by dlorenc** [comment]
Hey, I think this is a reasonable change to make. Unfortunately it breaks our start_stop_delete.go integration test becase we run "minikube status" there and error if the return code is non zero. I think you can just change the test utility function here: https://github.com/kubernetes/minikube/blob/master/test/integration/util/util.go#L86 to not check for an error (switch the true to false).

You can run the integration test with:

`go test ./test/integration --tags=integration --run=TestStartStop`

**Comment by jimmidyson** [comment]
> Unfortunately it breaks our start_stop_delete.go integration test

Seems to have passed integration tests? Is this something that should have broken & if so does it highlight a problem with the integration tests?

**Comment by jimmidyson** [comment]
Or are we not running integration tests as part of CI yet?

**Comment by dlorenc** [comment]
They're running but not blocking submit yet. The failure shows up in the in the link.

**Comment by dlorenc** [comment]
They're running but not blocking submit yet. The failure shows up in the in the link.

**Comment by pnegahdar** [comment]
Will address soon

**Comment by jimmidyson** [comment]
@dlorenc OK I'll look at logs before approving PRs from now on then - would be good to trust the status checks green ticks soon though :)

**Comment by jimmidyson** [comment]
@pnegahdar Is this PR still active? Can you update the integration tests as @dlorenc suggested so we can merge?

**Comment by dlorenc** [comment]
Ping @pnegahdar, any idea if you'll be able to finish this up soon?

**Comment by dlorenc** [comment]
Please re-open if you'd like!

**Pull request closed without merging**
