### PR TITLE
Update Dashboard UI to version v1.1.1

### PR DESCRIPTION
**Pull request by bryk**
Release tag: https://github.com/kubernetes/dashboard/releases/tag/v1.1.1

Release issue: kubernetes/dashboard#1078

### CODE REVIEW

**Comment by jimmidyson** [comment]
LGTM will merge on green

**Comment by jimmidyson** [comment]
@minikube-bot ok to test

**Comment by jimmidyson** [comment]
@dlorenc What's the magic incantation to get @minikube-bot to run integration tests? Or do I not have karma to do so (would be good if I did please)?

**Comment by jimmidyson** [comment]
@minikube-bot test this

**Comment by dlorenc** [comment]
It's
@minikube-bot ok to test

You weren't an admin, but you should be now.

**Comment by dlorenc** [comment]
LGTM, thanks @bryk

**Pull request merged**
