### PR TITLE
Revamp minikube website footer

### PR DESCRIPTION
**Pull request by sandipanpanda**
Fixes: #18055

### CODE REVIEW

**Comment by spowelljr** [comment]
@sandipanpanda I know it's in draft so if you're aware and still working on this ignore this, but I'm not seeing your change in the footer

https://deploy-preview-18062--kubernetes-sigs-minikube.netlify.app/

**Comment by sandipanpanda** [comment]
> Here's link to the Hugo config
> 
> https://www.zerostatic.io/docs/hugo-shard/global-config/footer/

@spowelljr I was following the documentation for the footer you shared in the issue. I think it is for a custom hugo theme, not the one minikube uses.

**Comment by sandipanpanda** [comment]
Changes seem to work now: https://deploy-preview-18062--kubernetes-sigs-minikube.netlify.app/docs/

**Comment by spowelljr** [comment]
Great work! Could you also style it to white so it matches the rest of the footer?

**Comment by sandipanpanda** [comment]
Done!

**Comment by spowelljr** [comment]
Awesome @sandipanpanda, this looks great! One last request if you're willing, to match the rest of the links on our site it would be nice if it changed color on hover to help the users know it's a link. I was thinking something around `#b5b1b1` maybe?

**Comment by sandipanpanda** [comment]
@spowelljr what do you think about keeping them the default blue to indicate they are clickable links?

**Comment by sandipanpanda** [comment]
@spowelljr @medyagh how can I push this forward?

**Comment by spowelljr** [comment]
> @spowelljr what do you think about keeping them the default blue to indicate they are clickable links?

I don't think the contrast of the blue on a gray background is visually goes together. I think having them change shade on hover would be enough.

**Comment by medyagh** [comment]
@sandipanpanda do you mind addressing steven's review so we could merge this pr

**Comment by sandipanpanda** [comment]
/cc @medyagh @spowelljr 
PTAL

**Review by spowelljr — APPROVED** [review]
Looks good, thanks for the PR!

**Pull request merged**
