### PR TITLE
hyperv: Use 'Get-Wmiobject HyperVisorPresent' instead of 'Get-WindowsOptionalFeature'

### LINKED ISSUE #7789: Make Hyper-V usable by members of Hyper-V admins group
This would require moving from `Get-WindowsOptionalFeature` to `HypervisorPresent`, as mentioned here:

https://github.com/code-ready/crc/blob/0f91698f533fd4f4079f8cb5b61f951e91e1b95e/pkg/crc/preflight/preflight_checks_windows.go#L44

@gbraad  mentioned that perhaps we should just call all of the checks here before trying to use the Hyper-V driver.

### PR DESCRIPTION
**Pull request by regulskimichal**
May fix #7789

### CODE REVIEW

**Comment by regulskimichal** [comment]
The CLA has been signed

**Comment by tstromberg** [comment]
PR tests fine locally. 

There are still a few restrictions with the hyperv libmachine driver that require PowerShell to be called from an Administrative context, but this check keeps minikube from blocking, and appears to be much faster than the previous check.

Thank you!

**Pull request merged**
