### PR TITLE
Add env variable to configure force-systemd

### PR DESCRIPTION
**Pull request by priyawadhwa**
Also add an integration test for the env variable

Rel #6404

### CODE REVIEW

**Comment by priyawadhwa** [comment]
## Docker_Linux
**TestFunctional/parallel/ComponentHealth - 0.16s**
#7807 
**TestFunctional/parallel/ServiceCmd - 53.31s**
#7765 
**TestStartStop/group/containerd - 238.64s**
#7704 
**TestStartStop/group/embed-certs - 824.01s**
#7921 

## Hyperkit
**TestFunctional/parallel/TunnelCmd** 
https://github.com/kubernetes/minikube/issues/7809

## Virtualbox_Linux
**TestErrorSpam**
https://github.com/kubernetes/minikube/issues/7760

**Comment by medyagh** [comment]
@priyawadhwa 
```
TestFunctional/parallel/ServiceCmd - 53.31s
#7765
```
that issue was closed

this one's error is 
```
functional_test.go:712: get failed: GET http://172.17.0.3:30602 giving up after 5 attempts
resp: <nil>
```

that closed issue was a different error
```
:Get http://127.0.0.1:10251/healthz: dial tcp 127.0.0.1:10251: connect: connection refused Error:}]}
```

I recommend creating a new issue for this

**Comment by priyawadhwa** [comment]
@medyagh thanks, opened those issues and updated my comment.

**Pull request merged**
