### PR TITLE
Switch from .gopath to _gopath to be consistent with kubernetes.

### PR DESCRIPTION
**Pull request by dlorenc**
cc @luxas.

This makes it so we can reuse the boilerplate.py and other hack/ scripts easier.

ref #35

### CODE REVIEW

**Comment by luxas** [comment]
Want to add the boilerplate scripts to `hack/boilerplate` at the same time to fix #35?

**Comment by dlorenc** [comment]
There's a bit more work to do there still, but I'll add that shortly.

**Comment by dlorenc** [comment]
OK, this should be ready. I was trying to do something fancy to avoid having to vendor the boilerplate code, but it didn't work. This is fine for now, and matches what kubernetes/contrib does.

**Comment by luxas** [comment]
LGTM

**Pull request merged**
