### PR TITLE
Cache: don't use ssh runner for the none driver

### LINKED ISSUE #4438: Ubuntu: error for minikube cache add images
**The exact command to reproduce the issue**:
$ minikube cache add ubuntu:16.04

**The full output of the command that failed**:
$ minikube cache add ubuntu:16.04

💣  Failed to cache and load images: Error creating new ssh host from driver: Error getting ssh host name for driver: driver does not support ssh commands

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:
None
**The operating system version**:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #4438

### CODE REVIEW

**Comment by medyagh** [comment]
I am curious does this also fix this issue ? https://github.com/kubernetes/minikube/issues/4132
Currently if you start minikube with none driver and then repeat the start command, it fails on waiting for SSH

**Comment by andrewjcouzens** [comment]
@medyagh I just tried compiling this and attempting to use vmdriver=none and I can confirm this patch doesn't fix it, at least not for me.

> 1031 15:49:51.248712   12005 main.go:110] libmachine: Waiting for SSH to be available...
I1031 15:49:51.248732   12005 main.go:110] libmachine: Getting to WaitForSSH function...
I1031 15:49:51.248750   12005 main.go:110] libmachine: Error getting ssh command 'exit 0' : driver does not support ssh commands

**Comment by medyagh** [comment]
@andrewjcouzens did you compile against HEAD ? if yes, that would be a bug ! we could create an issue to track it, or re-open the other one

**Comment by andrewjcouzens** [comment]
@medyagh Yes I compiled against HEAD.  Do you mean re-open 4132?  If so, it was already open and so I left a comment showing my results.  If there is another ticket regarding this issue please let me know and I can also share there.  Thank you.

**Pull request merged**
