### PR TITLE
Only reset docker/podman env if set by minikube

### LINKED ISSUE #7420: Support external DOCKER_HOST from inside WSL
**Steps to reproduce the issue:** 
1. I have Docker for Windows installed. I also have Ubuntu installed in WSL. I am able to connect to the Docker daemon from my Ubuntu shell:
```
ashoknn@ashoknn-yoga:~$ docker ps
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                                                                           NAMES
ashoknn@ashoknn-yoga:~$
```
2. If I try to create a cluster using minikube from within my Ubuntu shell, it fails to connect to the Docker daemon:
```ashoknn@ashoknn-yoga:~$ minikube start --driver=docker --alsologtostderr
W0404 19:52:48.033354   14510 root.go:248] Error reading config file at /home/ashoknn/.minikube/config/config.json: open /home/ashoknn/.minikube/config/config.json: no such file or directory
I0404 19:52:48.038441   14510 notify.go:125] Checking for updates...
I0404 19:52:48.445060   14510 start.go:262] hostinfo: {"hostname":"ashoknn-yoga","uptime":15431,"bootTime":1586039737,"procs":21,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"4.4.0-18362-Microsoft","virtualizationSystem":"","virtualizationRole":"","hostid":"20d448e0-882e-40b0-80bc-ed502a1eca7b"}
I0404 19:52:48.446325   14510 start.go:272] virtualization:
😄  minikube v1.9.2 on Ubuntu 18.04
I0404 19:52:48.450545   14510 driver.go:245] Setting default libvirt URI to qemu:///system
✨  Using the docker driver based on existing profile
I0404 19:52:48.586065   14510 start.go:310] selected driver: docker
I0404 19:52:48.586490   14510 start.go:656] validating driver "docker" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: Memory:4000 CPUs:2 DiskSize:20000 Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.0 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: ExtraOptions:[{Component:kubeadm Key:pod-network-cidr Value:10.244.0.0/16}] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:0 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.18.0 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0404 19:52:48.587629   14510 start.go:662] status for docker: {Installed:true Healthy:false Error:exit status 1 Fix:Docker is not running or is responding too slow. Try: restarting docker desktop. Doc:}

❗  'docker' driver reported an issue: exit status 1
💡  Suggestion: Docker is not running or is responding too slow. Try: restarting docker desktop.

I0404 19:52:48.590447   14510 start.go:1100] auto setting extra-config to "kubeadm.pod-network-cidr=10.244.0.0/16".
I0404 19:52:48.726483   14510 start.go:1004] Using suggested 4000MB memory alloc based on sys=16180MB, container=0MB
I0404 19:52:48.727148   14510 start.go:1210] Wait components to verify : map[apiserver:true system_pods:true]
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
I0404 19:52:48.729744   14510 cache.go:104] Beginning downloading kic artifacts
I0404 19:52:48.730338   14510 preload.go:81] Checking if preload exists for k8s version v1.18.0 and runtime docker
I0404 19:52:48.730964   14510 cache.go:106] Downloading gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81 to local daemon
I0404 19:52:48.731451   14510 image.go:84] Writing gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81 to local daemon
I0404 19:52:48.731233   14510 preload.go:97] Found local preload: /home/ashoknn/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4
I0404 19:52:48.732895   14510 cache.go:46] Caching tarball of preloaded images
I0404 19:52:48.734157   14510 preload.go:123] Found /home/ashoknn/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0404 19:52:48.734763   14510 cache.go:49] Finished downloading the preloaded tar for v1.18.0 on docker
I0404 19:52:48.737874   14510 profile.go:138] Saving config to /home/ashoknn/.minikube/profiles/minikube/config.json ...
E0404 19:52:49.383329   14510 cache.go:114] Error downloading kic artifacts:  error loading image: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
💣  Unable to get machine status: state: "docker inspect -f {{.State.Status}} minikube" failed: exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #7420

### CODE REVIEW

**Comment by medyagh** [comment]
the high failure rate in docker driver looks a bit concerning. I am not sure if it is related though. could it be ? @afbjorklund

**Comment by afbjorklund** [comment]
> the high failure rate in docker driver looks a bit concerning. I am not sure if it is related though. could it be ? @afbjorklund

It should not keep anything that wasn't there already... Do you set DOCKER_HOST in this Jenkins environment, or is it blank ?

**Comment by medyagh** [comment]
> > the high failure rate in docker driver looks a bit concerning. I am not sure if it is related though. could it be ? @afbjorklund
> 
> It should not keep anything that wasn't there already... Do you set DOCKER_HOST in this Jenkins environment, or is it blank ?

It must be blank, the test failures are a bit alarming, I am not sure if we should merge this, unless we make sure the root cause of the test failure. do you mind taking a look?

**Comment by afbjorklund** [comment]
> It must be blank, the test failures are a bit alarming, I am not sure if we should merge this, unless we make sure the root cause of the test failure. do you mind taking a look?

That was actually a question I had, why you set it (to "") rather than unset it (remove it) ?

https://golang.org/pkg/os/#Unsetenv

**Comment by afbjorklund** [comment]
> the offline tests seem scary, do you mind pulling master to see if that was a flake ?

Rebased and squashed (Unsetenv)

**Comment by medyagh** [comment]
on both commits of this PR all the offline docker tests fail... that makes me beleive it is related to this change
https://storage.googleapis.com/minikube-builds/logs/8164/165f7bb/Docker_Linux.html
https://storage.googleapis.com/minikube-builds/logs/8164/391e4f7/Docker_Linux.html

**Comment by afbjorklund** [comment]
So the test was relying on minikube to clean up after it ? Maybe add the unset to the test instead ?

**Comment by priyawadhwa** [comment]
Hey @afbjorklund would you mind rebasing on master? I'm curious to see which tests pass/fail

**Comment by medyagh** [comment]
@afbjorklund 
for this PR to be meregd we need to update the TestsOffline to be mindful of this new behaviour

**Comment by afbjorklund** [comment]
The only change here was to clear the variables if it was minikube that set them, not otherwise...
And to remove them from the environment instead of setting empty values like DOCKER_HOST=""

It doesn't restore the previous value, if you happened to be using one and not running locally.
I'm not sure where we would keep that old state, do we need to save it to a file in ~/.minikube ?

**Comment by tstromberg** [comment]
Something looks funny about this test result: https://storage.googleapis.com/minikube-builds/logs/8164/de1063e/none_Linux.html

`docker info` appears to be panic'ing? Will re-run tests.

**Comment by afbjorklund** [comment]
I'm OK with closing this PR, and letting somebody else have a go

**Pull request closed without merging**
