### PR TITLE
Add fscrypt kernel options

### PR DESCRIPTION
**Pull request by irq0**
Enables filesystem encryption support in the minikube kernel. Allows
users to use file level encryption on ext4.

Signed-off-by: Marcel Lauhoff <marcel.lauhoff@suse.com>

### CODE REVIEW

**Comment by nixpanic** [comment]
I don't think my review counts for much, but this looks good to me.

/lgtm

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by reylejano** [comment]
re-applying lgtm
/lgtm

**Review by spowelljr — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
