### PR TITLE
ISO: Update cni-plugins v1.4.1 SHAs

### PR DESCRIPTION
**Pull request by spowelljr**
ISO builds now fail with the following error:
```
22:23:50 ERROR: while checking hashes from /home/jenkins/go/src/k8s.io/minikube/deploy/iso/minikube-iso/arch/x86_64/package/cni-plugins-latest//cni-plugins-latest.hash
22:23:50 ERROR: cni-plugins-linux-amd64-v1.4.1.tgz has wrong sha256 hash:
22:23:50 ERROR: expected: 1511f6c003ace805eafeb1132727791326283cff88a923d76329e1892bba7a10
22:23:50 ERROR: got     : 2a0ea7072d1806b8526489bcd3b4847a06ab010ee32ba3c3d4e5a3235d3eb138
22:23:50 ERROR: Incomplete download, or man-in-the-middle (MITM) attack
```

Based on https://github.com/containernetworking/plugins/issues/1038 and https://github.com/containernetworking/plugins/issues/1019#issuecomment-2110355250 this is a legitimate change.

Updated the SHAs to match the new files

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Review by medyagh — APPROVED** [review]
looks good to me, hyperv failures seems to normal flakes

**Pull request merged**
