### PR TITLE
Remove extra `github.com/pborman/uuid` dependency

### PR DESCRIPTION
**Pull request by Juneezee**
Currently we have two UUID packages as dependencies:

1. `github.com/pborman/uuid`
2. `github.com/google/uuid`

`github.com/pborman/uuid` is no longer being actively maintained (last release was 2019). In addition, `github.com/pborman/uuid` uses `github.com/google/uuid` internally, so it is safe to replace.

image

### CODE REVIEW

**Review by liangyuanpeng — COMMENTED** [review]
/lgtm

/kind cleanup

**Comment by Juneezee** [comment]
friendly ping @spowelljr

**Comment by Juneezee** [comment]
@spowelljr friendly ping

**Review by spowelljr — APPROVED** [review]
Sorry for the late review @Juneezee, great work with the find and thank you for your PR!

**Pull request merged**
