### PR TITLE
Replace duration chart with total duration of tests -line

### LINKED ISSUE #12015: Remove duration chart and add total duration to total test count chart
Context: https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux

### PR DESCRIPTION
**Pull request by andriyDev**
fixes #12015.

Since no gopogh reports have been uploaded containing the root job id, all job ids are set to 0, so we currently have no averaged data and only a single instance per day. As new master integration tests complete, this chart should become more accurate.

image

### CODE REVIEW

**Comment by andriyDev** [comment]
After merging, we need to run hack/jenkins/test-flake-chart/collect_data_manual.sh

**Comment by medyagh** [comment]
> After merging, we need to run hack/jenkins/test-flake-chart/collect_data_manual.sh

What will this do for old data ?

**Comment by medyagh** [comment]
Will it generate chart for old tests ?

**Review by medyagh — APPROVED** [review]

**Pull request merged**
