### PR TITLE
Remove obsoleted docs/ directory

### LINKED ISSUE #7543: docs/networking.md points to non-existing URL
**Steps to reproduce the issue:** 
`cat docs/networking.md`
it points to https://minikube.sigs.k8s.io/docs/reference/networking/ which does not exist any more. 

**Full output of failed command:** 
`Not found 
Oops! This page doesn't exist. Try going back to our home page.`

**Proposed Solution:**
Because *networking* section has gone from minikube.sigs.k8s.io/ we probably should remove the docs/networking.md.

### PR DESCRIPTION
**Pull request by radeksm**
The only content of docs/networking.md is an URL to non-existing page
https://minikube.sigs.k8s.io/docs/reference/networking/

fixes #7543

### CODE REVIEW

**Comment by medyagh** [comment]
@radeksm  do you mind looking throught the old version of the site ( before thomas refactors the website) and check what was that content ?

**Comment by medyagh** [comment]
here is the link to that PR https://github.com/kubernetes/minikube/pull/7479

**Comment by medyagh** [comment]
oops that was wrong PR I linked, but if you go through the commit historyu will find it

**Comment by afbjorklund** [comment]
The new page is here: https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/

They were squashed in e9e1a77fecd2fef6ce1f75ee37ed3e2ed00b94bf

```
 site/content/en/docs/Reference/Networking/_index.md |  10 --
 site/content/en/docs/Reference/Networking/dns.md   |  58 --------
 site/content/en/docs/Reference/Networking/proxy.md | 109 --------------
 site/content/en/docs/Reference/Networking/vpn.md   |  23 ---
```

**Comment by afbjorklund** [comment]
We should probably delete the entire `docs/` directory, since it is now empty anyway.

**Comment by radeksm** [comment]
> We should probably delete the entire docs/ directory, since it is now empty anyway.
> Since 7559952

@afbjorklund, @medyagh how about converting all files from docs/ directory into one file where we can put all the links from individual files?

**Comment by tstromberg** [comment]
I'm OK with deleting the entire docs/ directory at this point.

**Comment by radeksm** [comment]
> I'm OK with deleting the entire docs/ directory at this point.

I will update my pull requests. I see some existing references to docs/ directory in main Makefile.
Need to check if there are some other places too.

**Comment by medyagh** [comment]
@radeksm can you also change all the links that are Full path to 
```
 [docker-env]({{< ref "/docs/commands/docker-env" >}}
```

this will make sure the website works when you run in it locally
more info here https://github.com/kubernetes/minikube/issues/7540

**Pull request merged**
