### PR TITLE
Add documentation for minikube CLI commands

### LINKED ISSUE #4271: Document all "start" options on the minikube website
So that our options are more discoverable.

### PR DESCRIPTION
**Pull request by blueelvis**
Fixes #4271 

This is the first pass on documenting the options, commands and flags available in the `minikube` CLI.

I went ahead and added for all the commands and not only the `start` command as mentioned in the issue.

/assign tstromberg

### CODE REVIEW

**Comment by afbjorklund** [comment]
These are very likely to get out of date, due to the duplication of information...

Could we use something automated, similar to `help2man`, to generate it ?

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
I agree with afbjorklund@ - these docs are great, but will get stale very fast. The command-line framework we are using, Cobra, allows automatic generation of markdown docs.

https://github.com/spf13/cobra/blob/master/doc/md_docs.md

By auto-generating docs, we can guarantee that users who are using `--help` get the same rich help as those using our doc website. Here's an example using Cobra's VisitAll() that we could emulate  - though my preference would be that each command gets it's own markdown file:

https://github.com/GoogleContainerTools/skaffold/blob/68fe5670b38a19cc5f689040ad2088c5bdeea779/cmd/skaffold/man/man.go#L38

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by blueelvis** [comment]
@afbjorklund @tstromberg - Agreed. Let me try using Cobra's auto generation and get back.

**Comment by tstromberg** [comment]
I thought about this some more: lets not let perfect be the enemy of good, particularly when it comes to documentation. Let's start with this so that we have something up for command documentation,  and replace it with automation as soon as possible.

Thank you!

**Comment by blueelvis** [comment]
@tstromberg @afbjorklund - This looks really promising. I generated the attached ([start.txt](https://github.com/kubernetes/minikube/files/3356727/start.txt)) markdown file for the `start` command. After a couple of tweaks, it could look really good!

The `cobra.Command` accepts a lot of parameters which can be filled with Examples and other documentation! That would flesh out the documentation automatically.

Let me know if you are open to merge this PR now and I can work on another one meanwhile to integrate this with all of our commands and have something automated?

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by blueelvis** [comment]
ping @tstromberg

**Comment by tstromberg** [comment]
Happy to merge this one now while we work out how to automate it. Thank you for writing this up!

**Pull request merged**
