### PR TITLE
Add more description in node add --worker option to inform adding control plane nodes is not available

### PR DESCRIPTION
**Pull request by kimsehwan96**
fixes: #17680

This changes are related with minikube's document and command line options.

### CODE REVIEW

**Review by medyagh — APPROVED** [review]

**Comment by kimsehwan96** [comment]
@medyagh 이 PR이 병합되지 않는 이유가 있나요? 테스트 실패가 원인일 수 있다고 생각합니다.

이 테스트 실패에 대해 더 확인해야 할 사항이 있나요?

감사합니다!

**Comment by prezha** [comment]
with pr #17909 we aim to enable support for multi-control-plane (ie, ha) topology, incl. `--control-plane` flag for adding more control-plane nodes to an existing ha cluster

**Comment by kimsehwan96** [comment]
@prezha It looks greate. Thank you for your supporting to enable this feature :). 

Then, I will not do nothing about this PR then. :) When It's flag really works then this PR should be closed.

**Comment by caerulescens** [comment]
this is awesome! thank you

**Pull request closed without merging**
