### PR TITLE
Fix TestProxy 

### PR DESCRIPTION
**Pull request by medyagh**
To address this issue https://github.com/kubernetes/minikube/issues/4339. 
and making sure minikube is deleted before/after test  avoid #4132

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
Turns out the issue for this test is related to https://github.com/kubernetes/minikube/issues/4132
the root cause is, when the None driver integration test starts an already started minikube, it fails with Waiting SSH ...

the root cause needs to be address in ttps://github.com/kubernetes/minikube/issues/4132 meanwhile we can make sure the TestProxy doesn't start an already started minikube for this test

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Pull request merged**
