### PR TITLE
Fix for issue #3044 - mounted timestamps incorrect with windows host

### PR DESCRIPTION
**Pull request by ngoozeff**
Test cases & resolution for #3044.

Original Behavior:
```
go test ./test/integration --tags integration -binary c:\programdata\chocolatey\bin\minikube.exe --minikube-start-args "--vm-driver hyperv" -run TestFunctional/Mounting --minikube-mount-args "--ip 192.168.128.103" -v
=== RUN   TestFunctional
=== RUN   TestFunctional/Mounting
=== PAUSE TestFunctional/Mounting
=== CONT  TestFunctional/Mounting
--- FAIL: TestFunctional (7.82s)
    --- FAIL: TestFunctional/Mounting (25.03s)
        mount_test.go:131: Invalid access time
              File: /mount-9p/fromhost
              Size: 5           Blocks: 1          IO Block: 65536  regular file
            Device: 10008eh/1048718d    Inode: 7           Links: 1
            Access: (0666/-rw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
            Access: 1970-01-01 00:00:00.000000000 +0000
            Modify: 1970-01-01 00:00:00.000000000 +0000
            Change: 1970-01-01 00:00:00.000000000 +0000
             Birth: -
FAIL
FAIL    k8s.io/minikube/test/integration        33.428s
```

With this fix:
```
go test ./test/integration --tags integration -binary ..\..\out\minikube-windows-amd64.exe --minikube-start-args "--vm-driver hyperv" -run TestFunctional/Mounting --minikube-mount-args "--ip 192.168.128.103" -v
=== RUN   TestFunctional
=== RUN   TestFunctional/Mounting
=== PAUSE TestFunctional/Mounting
=== CONT  TestFunctional/Mounting
--- PASS: TestFunctional (7.61s)
    --- PASS: TestFunctional/Mounting (26.89s)
PASS
ok      k8s.io/minikube/test/integration        35.102s
```

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by ngoozeff** [comment]
@tstromberg I've managed to reproduce these failures on my linux box. I think it might be related to the msize default for the mount command being too large for the tests. I'm currently investigating.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
Do you mind addressing the merge conflict? I'd like to see about merging this if it's still viable. My apologies for the unnecessarily long delay in reviewing this PR.

**Comment by ngoozeff** [comment]
Will do - I'll take a look over the weekend.

**Pull request merged**
