### PR TITLE
fixes(#8301): --help: bool flags which default to 'false' yield confusing output

### PR DESCRIPTION
**Pull request by Xcalizorz**
Adds the help-text mentioned in [#8301 (comment)](https://github.com/kubernetes/minikube/issues/8301#issuecomment-635582825)

### CODE REVIEW

**Comment by tstromberg** [comment]
Do you mind removing the translations/ file changes? They are auto-generated.

**Comment by Xcalizorz** [comment]
@tstromberg Please check again - thanks!

**Review by priyawadhwa — APPROVED** [review]
Looks good! Thank you for improving this.

**Pull request merged**
