### PR TITLE
Feature: `xhyve` driver: Allow setting up multiple Virtio9p shares on `minikube start`

### PR DESCRIPTION
**Pull request by huguesalary**
Note: This PR is dependent on the merging of a PR in the `xhyve`'s driver project: https://github.com/zchee/docker-machine-driver-xhyve/pull/194

Once https://github.com/zchee/docker-machine-driver-xhyve/pull/194 is merged, this PR will give the opportunity to `minikube` users to share multiple Host folders inside the `minikube` Guest using `virtio9p`

### CODE REVIEW

**Comment by r2d4** [comment]
@minikub-bot ok to test

**Comment by r2d4** [comment]
@huguesalary can we close #1803 and merge this one?

**Comment by huguesalary** [comment]
@r2d4 yes! Not sure why I did this.

(although when you merge this one, the other one will probably be closed automatically)

**Comment by huguesalary** [comment]
Just rebased this on master. Any chance of merging it? Or should I change a few things?

**Comment by huguesalary** [comment]
Indeed, good catch.

I've been tinkering but really can't think of any solution. There's nothing in the `xhyve` code that would allow for minikube to do a version check.

The only, really ugly, solution I can think of would be adding some sort of `--compatibility` flag that, if switched on, would make minikube talk to `xhyve` with the old API. But it complicates the code and is really ugly, and, of course next time another breaking change happens in `xhyve`, we'd run into the same issue all over again.

Vendoring `xhyve` would be another solution, but I supposed it's been looked into before and hasn't been done, so there must be a few roadblocks?

**Comment by r2d4** [comment]
What do you think about reverting the `Virtio9p` flag and adding the list of shares as `Virtio9pShares`?

It's maybe a little odd to keep a boolean flag only for 9p, but that wouldn't break existing users, as the default for `Virtio9pShares` could just be the default `/Users` mount.

Then you'd have set of flags like

```golang
NFSShares     []string
NFSSharesRoot string
Virtio9pRoot  string
Virtio9pShares []string
Virtio9p bool // Toggles virtio9p on or off
```

cc @dlorenc @zchee

**Comment by huguesalary** [comment]
I think it's a good idea. I also tried thinking of other solutions this morning; I had one but it really wasn't much better.

But now, I gave it even more thoughts, and, I'm not sure what the compatibility promises are for the `minikube` project, but, is it unreasonable to break compatibility?

The next minikube release could say "`minikube` expects the `xhyve` driver to be of version `strictly > 0.3.3`".

My rationale here being that it's going to be really hard to have both project stay compatible with each other.

It would make sense to have compatibility promises if those 2 projects were 1 project under the same umbrella, but they're not. Ultimately, it even seems like `minikube` will always be subjected to incompatible changes happening in the drivers it uses, with not much recourse.

**Pull request closed without merging**
