### PR TITLE
remove static ip in docker and podman

### LINKED ISSUE #13729: Can't start minikube inside docker network
### What Happened?

I'm trying to start minikube on ubuntu 18.04 inside nginx proxy manager docker network in order to setup some kubernetes services and manage the domain names and the proxy hosts in the nginx proxy manager platform.

so I have `nginxproxymanager_default` docker network and when I run `minikube start --network=nginxproxymanager_default` I get

> Exiting due to GUEST_PROVISION: Failed to start host: can't create with that IP, address already in use

what might I been doing wrong?

### Attach the log file

🤷  The control plane node "" does not exist.
👉  To start a cluster, run: "minikube start"

### Operating System

_No response_

### Driver

_No response_

### PR DESCRIPTION
**Pull request by zhan9san**
fix #13729 

Would yo kindly review this PR?

### CODE REVIEW

**Comment by medyagh** [comment]
@zhan9san would u plz state the reason u want to remove this ? this will make the driver less stable

**Comment by zhan9san** [comment]
Hi @medyagh 

If we remove the static IP, docker daemon will assign an available IP to `minikube` container automatically.

Currently, if the driver is `docker` or `podman`, it's some sort of hard-code in `minikube` container IP, https://github.com/kubernetes/minikube/blob/3f25d3ec4ff86f089f3771e01cba8c52830620f1/pkg/drivers/kic/kic.go#L101-L107

In other words, it always passes the first IP in the subnet to `minikube` container, no matter it is available or not.

This issue exists in both two scenarios. Both of them would fail.

### For `minikube` bridge network

1. `minikube start --driver=docker`
2. `minikube stop`
3. `docker run --rm -d --network minikube nginx`
4. `minikube start --driver=docker`

### For `non-minikube` bridge network

1. `docker network create non-minikube`
2. `docker run --rm -d --network minikube nginx`
3. `minikube start --driver=docker --network non-minikube`


```
❯ docker network ls
NETWORK ID     NAME                        DRIVER    SCOPE
5850e3b88677   bridge                      bridge    local
9901496684c6   host                        host      local
e1a5f17161a7   jenkins-in-docker_default   bridge    local
6c0240901aa0   knboard_default             bridge    local
5a9da0551e18   minikube                    bridge    local
a93741be50ae   none                        null      local
~                                                                                                                     09:14:28
❯ docker run -d --network minikube nginx
563f26651be44c5a10901671e71607abf9ab2308e4132098c3863cf20b0b803a
~                                                                                                                     09:15:07
❯ minikube start --driver=docker
😄  minikube v1.25.2 on Darwin 11.4
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🤦  StartHost failed, but will try again: provision: get ssh host-port: unable to inspect a not running container to get SSH port
🔄  Restarting existing docker container for "minikube" ...
😿  Failed to start docker container. Running "minikube delete" may fix it: provision: get ssh host-port: unable to inspect a not running container to get SSH port

❌  Exiting due to GUEST_PROVISION_CONTAINER_EXITED: Docker container exited prematurely after it was created, consider investigating Docker's performance/health.

~ 14s                                                                                                                 09:15:32
❯ docker stop 563f26651be44c5a10901671e71607abf9ab2308e4132098c3863cf20b0b803a
563f26651be44c5a10901671e71607abf9ab2308e4132098c3863cf20b0b803a
~                                                                                                                     09:16:08
❯ minikube start --driver=docker
😄  minikube v1.25.2 on Darwin 11.4
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
🔎  Verifying Kubernetes components...
💡  After the addon is enabled, please run "minikube tunnel" and your ingress resources would be available at "127.0.0.1"
    ▪ Using image registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5
    ▪ Using image registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v1.1.1
    ▪ Using image registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.1.1
    ▪ Using image registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.1.1
🔎  Verifying ingress addon...
🌟  Enabled addons: storage-provisioner, default-storageclass, ingress
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

**Comment by zhan9san** [comment]
Besides, if someone expects to use specific static IP address, it's better to implement it like below.

`minikube start --driver=docker --extra-opt=ip=192.168.50.2`.

This follows how docker does, `dhcp by default` whereas `--ip string IPv4 address (e.g., 172.30.100.104)` for specific scenario.

**Comment by medyagh** [comment]
I would rather this PR be implemented as a feature https://github.com/kubernetes/minikube/pull/13050

**Pull request closed without merging**
