### PR TITLE
Add support for FOU tunnels in the linux kernel.

### PR DESCRIPTION
**Pull request by Cellebyte**
The CNI [https://github.com/cybozu-go/coil](https://github.com/cybozu-go/coil) needs fou for egress traffic.
```log
kubectl logs -f -n internet egress-5df7854f55-cqsgb                                                                                                          1 ↵
{"level":"info","ts":1619562448.0290525,"logger":"setup","msg":"detected local IP addresses","ipv4":"169.254.0.2","ipv6":"<nil>"}
{"level":"info","ts":1619562448.5414793,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
Error: failed to load fou module: modprobe fou failed with exit status 1: modprobe: FATAL: Module fou not found in directory /lib/modules/4.19.171

failed to load fou module: modprobe fou failed with exit status 1: modprobe: FATAL: Module fou not found in directory /lib/modules/4.19.171

```
 Also some other apps will benefit from it. It makes developing with the CNI easier when it runs on minikube.

### CODE REVIEW

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
The build failure is related to cri-o checksums (again)

**Comment by Cellebyte** [comment]
@afbjorklund is there a good documentation for those CONFIG flags for the kernel? So that I can make sure this is working?

**Comment by afbjorklund** [comment]
Kernel config flags ? Those are documented at kernel.org (the other ones at buildroot.org)

https://www.kernel.org/doc/html/latest/kbuild/kconfig-language.html

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by Cellebyte** [comment]
@medyagh could we try another build of the iso?

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by Cellebyte** [comment]
@spowelljr anything happening with that build? It is still not reporting a status back. Aprecciate investigation or clarfication.

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by Cellebyte** [comment]
@spowelljr is there a way to test the build-iso on my own?

**Comment by afbjorklund** [comment]
@Cellebyte : https://minikube.sigs.k8s.io/docs/contrib/building/iso/

**Comment by Cellebyte** [comment]
@afbjorklund I tried but have issues with glibc locally. I think ArchLinux is to new.

```console
$ git/minikube (patch-1) » make out/minikube.iso
docker run --rm --workdir /mnt --volume /home/cellebyte/git/minikube:/mnt  \
	--user 1000:987 --env HOME=/tmp --env IN_DOCKER=1 \
	gcr.io/k8s-minikube/buildroot-image /usr/bin/make out/minikube.iso
/usr/bin/make minikube_iso
make[1]: Entering directory '/mnt'
echo v1.21.0-1624660371-11688 > deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/VERSION
if [ ! -d ./out/buildroot ]; then \
	mkdir -p ./out; \
	git clone --depth=1 --branch=2021.02.3 https://github.com/buildroot/buildroot ./out/buildroot; \
fi;
/usr/bin/make BR2_EXTERNAL=../../deploy/iso/minikube-iso minikube_defconfig -C ./out/buildroot
make[2]: Entering directory '/mnt/out/buildroot'
Makefile:1021: recipe for target 'minikube_defconfig' failed
make[2]: Leaving directory '/mnt/out/buildroot'
/mnt/out/buildroot/output/build/buildroot-config/conf: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /mnt/out/buildroot/output/build/buildroot-config/conf)
make[2]: *** [minikube_defconfig] Error 1
Makefile:275: recipe for target 'minikube_iso' failed
make[1]: Leaving directory '/mnt'
make[1]: *** [minikube_iso] Error 2
Makefile:300: recipe for target 'out/minikube.iso' failed
make: *** [out/minikube.iso] Error 2
make: *** [Makefile:302: out/minikube.iso] Error 2
```

**Comment by spowelljr** [comment]
Hi @Cellebyte, I'm very sorry for the delayed response, but since the ISO has been build through our CI the ISO is in a bucket and the code in the following commit is now pointing to use the ISO in the bucket.
https://github.com/kubernetes/minikube/pull/11218/commits/84695329fc69494d85fa1803b3ceeb2fde70145c

So all you have to do is pull in the that commit and run `make` and it will build using the ISO that has your requested changes in it and you can do your testing locally.

**Pull request closed without merging**
