### PR TITLE
add BR2_PACKAGE_LIBFUSE  addresses  #12426

### PR DESCRIPTION
**Pull request by schwichtgit**
Minikube 1.23+ does not provide the openvmtools anymore causing mounts to fail using the vmware driver (as tested with VMWare Fusion on MacOS).

As  the openvmtools package (https://github.com/buildroot/buildroot/blob/2021.02.x/package/openvmtools/openvmtools.mk)  requires libfuse to work, this PR adds  BR2_PACKAGE_LIBFUSE to minikube_defconfig resulting into a minikube.iso with a functional openvmtools including the hgfs driver.

### CODE REVIEW

**Comment by medyagh** [comment]
CC: @spowelljr

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by schwichtgit** [comment]
Hello  @medyagh I am not sure if this PR waits for an action on my side, please let me know what exactly is expected.

**Comment by schwichtgit** [comment]
@spowelljr @medyagh bump ...
Anything I can do to progress this PR?

**Review by afbjorklund — APPROVED** [review]

**Pull request merged**
