### PR TITLE
Fix invalid build result comparison in the cross build script

### PR DESCRIPTION
**Pull request by tstromberg**
Also apply http://google.github.io/styleguide/shell.xml and http://sipb.mit.edu/doc/safe-shell

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by balopat** [comment]
@minikube-bot OK to test

**Pull request merged**
