### PR TITLE
Upgrade to Docker 17.06-ce

### LINKED ISSUE #1518: Update docker version in minikube iso - possible?
**Is this a BUG REPORT or FEATURE REQUEST?**: 
FEATURE REQUEST

**Minikube version** :
 v0.19.0

**Environment**: linux
- **OS** : debian jessie
- **VM Driver** : virtualbox
- **ISO version** : minikube-v0.18.0.iso
- **Install tools**: debian installer
- **Others**: N/A

**What happened**:
Am using the new [multistage build in docker](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) but this does not work on the minikube iso as it is running docker v1.11.1.

It is in the edge docker release so not expecting this to be implemented in a minikube release anytime soon, but would it be possible to upgrade docker in the minikube-iso to ^17.05?

Have newer versions of docker been tested? 
Worry that would be quite the jump...

### PR DESCRIPTION
**Pull request by bryanlarsen**
This is an attempt to address #1518.   It does actually fix #1518, but breaks much of Kubernetes.   :)   Don't merge this, I'm just creating a PR that people can play with if they're interested in taking it further.

### CODE REVIEW

**Comment by bryanlarsen** [comment]
It would be nice if a reviewer released this to CI so that an ISO is created that others can play with.

**Comment by bryanlarsen** [comment]
One reason it doesn't work:  https://github.com/kubernetes/kubernetes/issues/40182.   There are probably others.

**Comment by dlorenc** [comment]
@minikube-bot ok to test

Just to make sure our tests catch the failures :)

**Comment by bryanlarsen** [comment]
Jenkins put the ISO URL at https://storage.googleapis.com/minikube-builds/1542/minikube-testing.iso if anybody wants to try this without compiling it.

**Comment by bryanlarsen** [comment]
It's actually working fairly well for me now.

**Comment by imkin** [comment]
@bryanlarsen any updates on this one?

**Comment by dlorenc** [comment]
We're not going to be able to take this until Kubernetes upstream is tested and verified against Docker 17.05. The current highest is 1.12.6: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information

**Comment by kilianc** [comment]
If you are stuck with this, you can preview the custom ISO with:

    $ minikube start --iso-url=https://storage.googleapis.com/minikube-builds/1542/minikube-testing.iso

Works perfectly for me! 🍻

**Comment by bryanlarsen** [comment]
I've upgraded this PR to use 17.06-ce rather than 17.05-ce since that's long term stable.   I also merged in master to get Kube 1.7.

Unfortunately, this now requires using a new minikube executable as well as using a new ISO.   Does Jenkins stash the minikube executable somewhere convenient for others to access, in a manner similar to how it stashes the iso at https://storage.googleapis.com/minikube-builds/1542/?

**Comment by dlorenc** [comment]
> Unfortunately, this now requires using a new minikube executable as well as using a new ISO. Does Jenkins stash the minikube executable somewhere convenient for others to access, in a manner similar to how it stashes the iso at https://storage.googleapis.com/minikube-builds/1542/?

Yeah all the exe's should be in that same location:
```shell
$ gsutil ls gs://minikube-builds/1542/
gs://minikube-builds/1542/build_iso.sh
gs://minikube-builds/1542/common.sh
gs://minikube-builds/1542/e2e-darwin-amd64
gs://minikube-builds/1542/e2e-linux-amd64
gs://minikube-builds/1542/e2e-windows-amd64.exe
gs://minikube-builds/1542/linux_integration_tests_kvm.sh
gs://minikube-builds/1542/linux_integration_tests_kvm_alt.sh
gs://minikube-builds/1542/linux_integration_tests_none.sh
gs://minikube-builds/1542/linux_integration_tests_virtualbox.sh
gs://minikube-builds/1542/localkube
gs://minikube-builds/1542/minikube-darwin-amd64
gs://minikube-builds/1542/minikube-linux-amd64
gs://minikube-builds/1542/minikube-testing.iso
gs://minikube-builds/1542/minikube-testing.iso.sha256
gs://minikube-builds/1542/minikube-windows-amd64.exe
gs://minikube-builds/1542/minikube.iso
gs://minikube-builds/1542/minikube.iso.sha256
gs://minikube-builds/1542/minikube_cross_build_and_upload.sh
gs://minikube-builds/1542/minikube_set_pending.sh
gs://minikube-builds/1542/osx_integration_tests_virtualbox.sh
gs://minikube-builds/1542/osx_integration_tests_xhyve.sh
gs://minikube-builds/1542/print-debug-info.sh
gs://minikube-builds/1542/release_build_and_upload.sh
gs://minikube-builds/1542/release_github_page.sh
gs://minikube-builds/1542/release_update_installers.sh
gs://minikube-builds/1542/release_update_releases_json.sh
gs://minikube-builds/1542/windows_integration_test_hyperv.ps1
gs://minikube-builds/1542/testdata/
```

**Comment by derailed** [comment]
Hi - any updates on this issue? We need to run docker multistage and kind of stuck at the moment.

**Comment by bryanlarsen** [comment]
We don't use this PR any more.   What we do is we create a VM manually, install the docker 17.06 and then install minikube with --vm-driver=None

**Comment by derailed** [comment]
Thanks for the prompt reply Brian!

I am not sure how to make this work?I have tried using the custom iso and
minikube listed on the PR but
running into errors on minikube starts.

I am trying out a multistage build on OSX using xhyve. Not sure how to
update docker on this vm. Any suggestions?

**Comment by pondohva** [comment]
> https://storage.googleapis.com/minikube-builds/1542/minikube-testing.iso

this ISO doesn't work for me because of ExecStart string in /usr/lib/systemd/system/docker.service. It tries to run "docker daemon" command, but it needs to use dockerd instead.

**Comment by medyagh** [comment]
any plan to support multistage build in minikube anytime soon ? does anyone know?

**Comment by dlorenc** [comment]
Once we get k8s 1.8 merged we should be able to upgrade Docker. Old versions of k8s did not support the versions of docker that have multi-stage builds.

**Comment by medyagh** [comment]
@dlorenc thanks do you have the link for the PR so I can watch it ? 
and also do you know if that means the new docker in minikube will only work for kuberentes 1.8 ? could I have k8s 1.7 and new version of docker?

**Comment by r2d4** [comment]
Hope you don't mind but I resolved the merge conflicts since they were basically a no-op.  I would like to get this merged soon now that we are on 1.8

**Comment by centromere** [comment]
At this point, why not use 17.09?

**Comment by r2d4** [comment]
@centromere we only like to use the versions that are official vetted by k8s.  I don't think 17.09 is fully tested against 1.8 clusters yet.  However, it might be useful to expose some functionality to fetch arbitrary docker versions.

**Pull request merged**
