### PR TITLE
Upgrade CNI config version to 0.3.0

### LINKED ISSUE #4406: Running containers with podman doesn't work
We install the `podman` tool into the VM, to do things such as loading or building OCI images.

But currently there are some issues with the CNI configuration, if you try to use it for _running_:

``` console
$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ sudo podman run -it busybox
Trying to pull docker.io/library/busybox...Getting image source signatures
Copying blob 53071b97a884 done
Copying config 64f5d945ef done
Writing manifest to image destination
Storing signatures
Error: error parsing CNI plugin result "IP4:{IP:{IP:10.1.0.7 Mask:ffff0000} Gateway:10.1.0.1 Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.1.0.1}]}, DNS:{Nameservers:[] Domain: Search:[] Options:[]}": cannot convert version ["" "0.1.0" "0.2.0"] to 0.4.0: cannot convert version ["" "0.1.0" "0.2.0"] to 0.4.0
```

Even though it is not the **primary** use-case (normally use crictl/crio), this should work...

Maybe we can get the standard minikube CNI configuration compatible with Podman ?

### PR DESCRIPTION
**Pull request by afbjorklund**
Was using the default version of 0.2.0, didn't load with 0.4.0

For #4406

### CODE REVIEW

**Comment by medyagh** [comment]
The none driver test is faling for trying to SSH while it shouldn't SSH, different issue

**Comment by medyagh** [comment]
Looks good to me. I will merge this tomorrow after rerunning the tests

**Comment by medyagh** [comment]
the two failing test are not related to this PR

https://github.com/kubernetes/minikube/issues/4418
and 
https://github.com/kubernetes/minikube/issues/4489

**Comment by afbjorklund** [comment]
Hmm, closing stories in commit messsages never work very well.

This was only a _part_ of #4406

**Pull request merged**
