### PR TITLE
Fixed version typo in windows installer

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by r2d4** [comment]
Any idea why the xhyve test is failing?

```
+ bash -x out/osx_integration_tests_xhyve.sh
bash: out/osx_integration_tests_xhyve.sh: No such file or directory
Build step 'Execute shell' marked build as failure
```

**Comment by aaron-prindle** [comment]
No, I am not sure what could have caused that.  I don't think it's related.

**Comment by r2d4** [comment]
gsutil being weird
Running on jenkins

```
Operation completed over 15 objects/406.3 Mi
```

Running locally
```        
Operation completed over 18 objects/406.3 MiB.
```

**Comment by dlorenc** [comment]
Yeah we might need to switch that to a hardcoded list. GCS's consistency model doesn't guarantee that "list" operations will return all objects, but fetching a specific object will always work if the write succeeded.

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Pull request merged**
