### PR TITLE
add buildroot based minikube-iso build infrastructure

### LINKED ISSUE #571: Switch to the rkt iso by default
Ref #168 #570

### PR DESCRIPTION
**Pull request by s-urbaniak**
This moves all files from https://github.com/coreos/minikube-iso to minikube itself.

One can build the minikub-iso image directly from the top-level directory using

```
$ make minikube-iso
```

Partially fixes #571

### CODE REVIEW

**Comment by s-urbaniak** [comment]
Note that I included the history from the old project, so I assume, that quite some CLAs are missing.

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by r2d4** [comment]
@minikube-bot add to whitelist

**Comment by dlorenc** [comment]
Thanks! It looks like the cla bot is complaining that you (@s-urbaniak) need to sign, and it also says "4 other problems). Not sure how to find out what those are...

**Comment by s-urbaniak** [comment]
@dlorenc my commits are sur@coreos.com which implicitely has CLA signed. But the minikube-iso surely had some contributors which may have not signed it. If you want, I can squash the complete history, the only downside would be, that we would lose it.

**Comment by dlorenc** [comment]
I think that would go against the point of the checks, we'll have to reach out to the authors and get them to sign.

Any idea why it thinks you haven't signed yet though? I had to register my email even though I've implicitly signed through my employer.

**Comment by s-urbaniak** [comment]
I went through the history, and some commits from me use the email sergiusz.urbaniak@gmail.com, let me fix that. I hope that at least for me the CLA goes away.

**Comment by s-urbaniak** [comment]
@iaguis @ryanj Can I kindly ask you to sign the CLA with the email addresses iago@kinvolk.io, and ryan.jarvinen@gmail.com

**Comment by philips** [comment]
cc @ethernetdan

**Comment by iaguis** [comment]
I signed the CLA as a corporation under Kinvolk GmbH:

```
Agreement	            Name	        Date Signed
Google Corporate CLA	Kinvolk GmbH	Feb 08, 2016 11:22 PST
```

**Comment by ryanj** [comment]
I couldn't figure out how to sign the latest corporate CLA form, and I didn't want to block this issue, so I signed as an individual contributor (short term).  
I'll update with corporate CLA info as soon as I can get that form to submit correctly.

**Comment by s-urbaniak** [comment]
@ryanj @iaguis Thanks a lot!!! :-)

@dlorenc I guess we are complete then :-) I looked through the history and all the other authors should have the CLA signed.

**Comment by iaguis** [comment]
In mine it says:

> CLAs are signed, but unable to verify author consent

😕

**Comment by dlorenc** [comment]
> In mine it says:

@iaguis I did some digging and it looks like the issue is that the CLA bot can't confirm that you are the same person that authored the commit. Do you have both email addresses added to your github account?

It looks like this error is OK for us to override if we've manually verified that you've given consent, so if we can't figure it out we can still move forward :)

**Comment by dlorenc** [comment]
Hmm, this still says @s-urbaniak needs a CLA. Any idea what's up?

**Comment by s-urbaniak** [comment]
Sorry, I don't really have clue :-( Maybe the bot is overwhelmed, because I took over the whole history. Since all parties agreed on the CLA, can we somehow merge it manually?

I'd address https://github.com/kubernetes/minikube/pull/692#discussion_r83527169 in a separate PR.

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
Yeah, I'll kick off one more round of tests (something seems up there) then merge.

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
Merging. The xhyve failure is a test infra issue.

**Pull request merged**
