### PR TITLE
Pin docker images to commit hash

### PR DESCRIPTION
**Pull request by acumino**
Pin docker images to commit hash
Part of #17808 
#SecuritySlam

### CODE REVIEW

**Comment by afbjorklund** [comment]
@acumino : pinning an old minor release, will make the images _less_ up-to-date

```diff
-FROM ubuntu:20.04
+FROM ubuntu:20.04@sha256:f5c3e53367f142fab0b49908550bdcdc4fb619d2f61ec1dfa60d26e0d59ac9e7
```

ubuntu:focal-20231128

```
ubuntu                                                20.04            f78909c2b360   2 days ago      72.8MB
ubuntu                                                focal            f78909c2b360   2 days ago      72.8MB
ubuntu                                                focal-20231211   f78909c2b360   2 days ago      72.8MB
ubuntu                                                focal-20231128   83a4bf3bb050   2 weeks ago     72.8MB
```

**Comment by afbjorklund** [comment]
These are mostly builder images, it seems. The kicbase should already be pinned: `ubuntu:jammy-20231128`

**Review by afbjorklund — CHANGES_REQUESTED** [review]
The commit message is misleading, since image digest != commit hash

Also I am not convinced pinning all the builder images is the way to go...

**Comment by acumino** [comment]
> @acumino : pinning an old minor release, will make the images _less_ up-to-date
> 
> ```diff
> -FROM ubuntu:20.04
> +FROM ubuntu:20.04@sha256:f5c3e53367f142fab0b49908550bdcdc4fb619d2f61ec1dfa60d26e0d59ac9e7
> ```
> 
> ubuntu:focal-20231128
> 
> ```
> ubuntu                                                20.04            f78909c2b360   2 days ago      72.8MB
> ubuntu                                                focal            f78909c2b360   2 days ago      72.8MB
> ubuntu                                                focal-20231211   f78909c2b360   2 days ago      72.8MB
> ubuntu                                                focal-20231128   83a4bf3bb050   2 weeks ago     72.8MB
> ```

Openssf suggested to use `f5c3e53367f142fab0b49908550bdcdc4fb619d2f61ec1dfa60d26e0d59ac9e7 ` hash, Now I pulled the image locally `docker pull ubuntu:20.04` and it leads to hash `f2034e7195f61334e6caff6ecf2e965f92d11e888309065da85ff50c617732b8`. 
Should I updated hash to `f2034e7195f61334e6caff6ecf2e965f92d11e888309065da85ff50c617732b8` then?

**Comment by afbjorklund** [comment]
You will need to update it all the time, if you pin an older release instead of using a "latest" tag like the "20.04"

**Comment by acumino** [comment]
> You will need to update it all the time, if you pin an older release instead of using a "latest" tag like the "20.04"

In that case, should I close this PR?
I opened the based on below warning by openssf checks - 
```
"Warn: containerImage not pinned by hash: deploy/addons/auto-pause/Dockerfile:1: pin your Docker image by updating golang:1.21.5 to golang:1.21.5@sha256:2ff79bcdaff74368a9fdcb06f6599e54a71caf520fd2357a55feddd504bcaffb","Warn: containerImage not pinned by hash: deploy/gvisor/Dockerfile:16: pin your Docker image by updating alpine:3 to alpine:3@sha256:51b67269f354137895d43f3b3d810bfacd3945438e94dc5ac55fdac340352f48","Warn: containerImage not pinned by hash: deploy/iso/minikube-iso/Dockerfile:15: pin your Docker image by updating ubuntu:20.04 to ubuntu:20.04@sha256:f5c3e53367f142fab0b49908550bdcdc4fb619d2f61ec1dfa60d26e0d59ac9e7","Warn: containerImage not pinned by hash: deploy/kicbase/Dockerfile:24","Warn: containerImage not pinned by hash: deploy/kicbase/Dockerfile:42","Warn: containerImage not pinned by hash: deploy/prow/Dockerfile:18: pin your Docker image by updating debian:bullseye to debian:bullseye@sha256:ab2b95aa8d7d6d54866b92c322cf0693933c1ae8038652f24ddfda1d1763a45a","Warn: containerImage not pinned by hash: installers/linux/kvm/Dockerfile.amd64:15: pin your Docker image by updating gcr.io/gcp-runtimes/ubuntu_20_0_4 to gcr.io/gcp-runtimes/ubuntu_20_0_4@sha256:666805a878d9cd58ce9dfd6f423e2d0e3bdf01eea0cddd2be3a88244c1d4dfa5","Warn: containerImage not pinned by hash: installers/linux/kvm/Dockerfile.arm64:15: pin your Docker image by updating ubuntu:20.04 to ubuntu:20.04@sha256:f5c3e53367f142fab0b49908550bdcdc4fb619d2f61ec1dfa60d26e0d59ac9e7",
```

**Comment by afbjorklund** [comment]
You could add a digest to the more "permanent" tags, if you feels that it adds value.

I'm not sure if go issues another image for the same go version, when they update the OS ?
`golang:1.21.5` uses debian:bookworm (+scm), so it would inherit all the issues from that

But if they don't, the same would apply even there. You would pin the go version, but also the OS...

**Comment by afbjorklund** [comment]
Tradeoffs are described here:

https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
> Pinned dependencies reduce several security risks: [...]
...
> However, pinning dependencies can inhibit software updates,

Also, we don't pin the package version (an even bigger hassle) so it is void after running `apt`

**Comment by acumino** [comment]
> You could add a digest to the more "permanent" tags, if you feels that it adds value.
> 
> I'm not sure if go issues another image for the same go version, when they update the OS ? `golang:1.21.5` uses debian:bookworm (+scm), so it would inherit all the issues from that
> 
> But if they don't, the same would apply even there. You would pin the go version, but also the OS...



> golang:1.21.5

Let's keep it as it is, instead of pinning.
/close

**Comment by afbjorklund** [comment]
It is interesting that GCP adds some packages, compared to the Docker Hub originals:

```
@@ -8,3 +8,5 @@
 Package: bzip2
+Package: ca-certificates
 Package: coreutils
+Package: curl
 Package: dash
@@ -25,2 +27,3 @@
 Package: libapt-pkg6.0
+Package: libasn1-8-heimdal
 Package: libattr1
@@ -29,2 +32,3 @@
 Package: libblkid1
+Package: libbrotli1
 Package: libbz2-1.0
@@ -35,2 +39,3 @@
 Package: libcrypt1
+Package: libcurl4
 Package: libdb5.3
@@ -45,4 +50,17 @@
 Package: libgpg-error0
+Package: libgssapi3-heimdal
+Package: libgssapi-krb5-2
+Package: libhcrypto4-heimdal
+Package: libheimbase1-heimdal
+Package: libheimntlm0-heimdal
 Package: libhogweed5
+Package: libhx509-5-heimdal
 Package: libidn2-0
+Package: libk5crypto3
+Package: libkeyutils1
+Package: libkrb5-26-heimdal
+Package: libkrb5-3
+Package: libkrb5support0
+Package: libldap-2.4-2
+Package: libldap-common
 Package: liblz4-1
@@ -53,2 +71,3 @@
 Package: libnettle7
+Package: libnghttp2-14
 Package: libp11-kit0
@@ -61,2 +80,7 @@
 Package: libprocps8
+Package: libpsl5
+Package: libroken18-heimdal
+Package: librtmp1
+Package: libsasl2-2
+Package: libsasl2-modules-db
 Package: libseccomp2
@@ -67,3 +91,6 @@
 Package: libsmartcols1
+Package: libsqlite3-0
 Package: libss2
+Package: libssh-4
+Package: libssl1.1
 Package: libstdc++6
@@ -75,2 +102,3 @@
 Package: libuuid1
+Package: libwind0-heimdal
 Package: libzstd1
@@ -83,2 +111,4 @@
 Package: ncurses-bin
+Package: netbase
+Package: openssl
 Package: passwd
```

Not sure I am a big fan of wiping the timestamp, but it does give reproducible images:

```
ubuntu                                                20.04            f78909c2b360   3 days ago      72.8MB
gcr.io/gcp-runtimes/ubuntu_20_0_4                     latest           857718b87420   53 years ago    88.2MB
```

**Pull request closed without merging**
