### PR TITLE
Add DOCKER_API_VERSION to docker-env command

### LINKED ISSUE #474: Update docker-env to export DOCKER_API_VERSION
If you've got a different docker client to that in minikube's boot2docker.iso, any docker commands return the dreaded:

    Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)

If we export the `DOCKER_API_VERSION` env var in `docker-env` with the appropriate API version then this error won't be thrown. Docker seems to work fine too...

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #474

### CODE REVIEW

**Comment by dlorenc** [comment]
Nice. Looks like Travis failed but it was probably a flake.

I assume the DOCKER_API_VERSION env var doesn't work forever, but it gives us a wider range of support.

Could you poke travis to see if that repros?

**Comment by zoidbergwill** [comment]
Would love to see this merged, so we can go ahead with switching from hyperkube to minikube where I work.

**Comment by dlorenc** [comment]
I can't figure out how to make travis re-run this without amending. @jimmidyson could you poke it so it re-runs?

**Comment by danmikita** [comment]
@dlorenc I would love to get this merged in ASAP too. Having to manually downgrade my client docker is a pain. Have you tried this? http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by jimmidyson** [comment]
Kicked via Travis site

**Comment by dlorenc** [comment]
Nice, passed this time.

**Comment by dlorenc** [comment]
LGTM

**Pull request merged**
