### PR TITLE
[wip] kicbase: disable docker service

### PR DESCRIPTION
**Pull request by ilya-zuyev**
This PR disables docker service in kicbase image by default 
This main reason is to make start of kicbase with non-docker container runtimes faster - on test machine starting of docker.service takes about 10 seconds and later we stop and disable it from minikube anyway

### CODE REVIEW

**Comment by ilya-zuyev** [comment]
ok-to-build-image

**Comment by ilya-zuyev** [comment]
ok-to-build-image

**Comment by ilya-zuyev** [comment]
ok-to-build-image

**Comment by ilya-zuyev** [comment]
ok-to-build-image

**Comment by ilya-zuyev** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
> **kvm2 driver with docker runtime**
> 
> ```
> +----------------+----------+---------------------+
> |    COMMAND     | MINIKUBE | MINIKUBE (PR 11596) |
> +----------------+----------+---------------------+
> | minikube start | 47.5s    | 47.6s               |
> | enable ingress | 40.7s    | 37.2s               |
> +----------------+----------+---------------------+
> ```
> 
> **docker driver with docker runtime**
> 
> ```
> +----------------+----------+---------------------+
> |    COMMAND     | MINIKUBE | MINIKUBE (PR 11596) |
> +----------------+----------+---------------------+
> | minikube start | 21.7s    | 30.0s               |
> | enable ingress | 33.5s    | 35.4s               |
> +----------------+----------+---------------------+
> ```
> 
> **docker driver with containerd runtime**
> 
> ```
> +----------------+----------+---------------------+
> |    COMMAND     | MINIKUBE | MINIKUBE (PR 11596) |
> +----------------+----------+---------------------+
> | minikube start | 41.8s    | 45.8s               |
> | enable ingress |          |                     |
> +----------------+----------+---------------------+
> ```

this makes docker drier with docker runtime 9 seconds slower

**Pull request closed without merging**
