### PR TITLE
Remove docker requirement for none driver

### LINKED ISSUE #10908: None driver should take care of --container-runtime parameter
**Steps to reproduce the issue:** 

This is the current behavior regarding initizliation with none driver with containerd runtime.

```
# minikube start --driver=none --container-runtime='containerd'
😄  minikube v1.18.1 on Ubuntu 20.04 (amd64)
✨  Using the none driver based on user configuration

🤷  Exiting due to PROVIDER_NONE_NOT_FOUND: The 'none' provider was not found: exec: "docker": executable file not found in $PATH
💡  Suggestion: Install docker
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

root@minikube:~# minikube start -h | grep provider
root@minikube:~# minikube start --driver=none --container-runtime='containerd'
😄  minikube v1.18.1 on Ubuntu 20.04 (amd64)
✨  Using the none driver based on user configuration

🤷  Exiting due to PROVIDER_NONE_NOT_FOUND: The 'none' provider was not found: exec: "docker": executable file not found in $PATH
💡  Suggestion: Install docker
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/none/
```

Since Docker is no longer *default* runtime, I think even none driver should consider the runtime option if specified.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

### PR DESCRIPTION
**Pull request by staticdev**
* Removed docker validation on none driver. This validation does not make sense since it run for all other container-runtimes, even when not using docker. It is also redundant with the same validation on docker runtime side.

### CODE REVIEW

**Comment by afbjorklund** [comment]
This check _should_ be removed, but the underlying issue still needs to be fixed. It will still fail, just somewhat later.

So while I support removing it, it will **not** fix the issue where running the "none" driver requires a fake `docker` binary

**Review by afbjorklund — APPROVED** [review]

**Comment by staticdev** [comment]
You are right @afbjorklund. I removed the fixed #10908 from this PR. Maybe I follow up with another PR as the discussion in the issue evolves.

**Comment by staticdev** [comment]
@prasadkatti
@sharifelgamal
LGTM?

**Comment by sharifelgamal** [comment]
/ok-to-test

makes sense to me, let's make sure the tests don't complain, not that they should.

**Review by sharifelgamal — APPROVED** [review]

**Pull request merged**
