### PR TITLE
Adds dm-crypt support

### PR DESCRIPTION
**Pull request by vasyl-purchel**
Adds crypt target support in kernel for device mapper
Adds XTS support, AES cipher algorithms and User-space interface for
symmetric key cipher algorithms in kernel

This change is needed to make it possible to encrypt rbd images in ceph-csi with LUKS

Signed-off-by: Vasyl Purchel vasyl.purchel@workday.com
Signed-off-by: Andrea Baglioni andrea.baglioni@workday.com

### CODE REVIEW

**Comment by medyagh** [comment]
Thanks for creating this PR ! would you mind giving some examples that this PR would be useful ?
and also an example that the current minikube does not support it ? myabe be output and logs?

**Comment by vasyl-purchel** [comment]
With the change I have created containers from https://github.com/ceph/ceph-csi/pull/697/files and then inside csi-rbdplugin container (`kubectl exec -it csi-rbdplugin-hn2bc -c csi-rbdplugin bash`) I have created an rbd image in ceph, mapped it and then was able to encrypt it with LUKS:
```shell
[root@minikube /]# echo 'hellopassphrase' | cryptsetup luksFormat --hash sha256 /dev/rbd0 -d /dev/stdin
[root@minikube /]# echo $?
0
[root@minikube /]# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
rbd0   251:0    0     1G  0 disk
sr0     11:0    1 143.4M  0 rom
sda      8:0    0  19.5G  0 disk
`-sda1   8:1    0  19.5G  0 part /var/lib/kubelet/plugins
[root@minikube /]# echo 'hellopassphrase' | cryptsetup luksOpen /dev/rbd0 luks-encr-test -d /dev/stdin
[root@minikube /]# lsblk
NAME             MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
rbd0             251:0    0     1G  0 disk
`-luks-encr-test 252:0    0  1020M  0 crypt
sr0               11:0    1 143.4M  0 rom
sda                8:0    0  19.5G  0 disk
`-sda1             8:1    0  19.5G  0 part  /var/lib/kubelet/plugins
```

While with the latest version I was getting:
```shell
[root@minikube /]# echo 'hellopassphrase' | cryptsetup -q luksFormat --hash sha256 /dev/rbd0 -d /dev/stdin          
device-mapper: reload ioctl on   failed: Invalid argument
Failed to setup dm-crypt key mapping for device /dev/rbd0.
Check that kernel supports aes-xts-plain64 cipher (check syslog for more info).
```

Also from cryptsetup documentation:
> Before using cryptsetup, always make sure the dm_crypt kernel module is loaded.

without change you get:
```shell
[root@minikube /]# modprobe dm_crypt
modprobe: FATAL: Module dm_crypt not found.
```

after the change:
```shell
[root@minikube /]# modprobe dm-crypt
[root@minikube /]# echo $?
0
```

**Comment by RA489** [comment]
@vasyl-purchel  Do you have any issue while signing the cla?

**Comment by tstromberg** [comment]
Diff was difficult to parse at first, but change looks good. Thank you!

**Pull request merged**
