### PR TITLE
upgrade Dashboard addon from v2.5.1 to v2.6.0, MetricsScraper from v1.0.7 to v1.0.8

### PR DESCRIPTION
**Pull request by ziyi-xie**
This PR fixed the version of Dashboard to v2.6.0, and MetricsScraper to v1.0.8 in minikube.
https://github.com/kubernetes/dashboard/releases
https://github.com/kubernetes-sigs/dashboard-metrics-scraper/releases

### CODE REVIEW

**Comment by shu-mutou** [comment]
Thanks for updating dashboard!
Not to be confused in updating in the future, could you change versions to `vX.X.X` in following comments?
https://github.com/kubernetes/minikube/blob/919e0da7ba87852d366e269278e11fac410a5447/test/integration/start_stop_delete_test.go#L451

**Comment by ziyi-xie** [comment]
> Thanks for updating dashboard! Not to be confused in updating in the future, could you change versions to `vX.X.X` in following comments?
> 
> https://github.com/kubernetes/minikube/blob/919e0da7ba87852d366e269278e11fac410a5447/test/integration/start_stop_delete_test.go#L451

I just modified the version of dashboard in that file and thank you so much for your comments!

**Review by spowelljr — APPROVED** [review]

**Pull request merged**
