### PR TITLE
Bump Dashboard to v2.0.1

### PR DESCRIPTION
**Pull request by maciaszczykm**

### CODE REVIEW

**Comment by sharifelgamal** [comment]
Can you update the `dashboardFrontend` and `dashboardMetrics` functions in `pkg/minikube/bootstrapper/images/images.go` to the new versions as well? That'll make the currently failing tests pass.

**Comment by maciaszczykm** [comment]
@sharifelgamal Sure, done.

**Comment by medyagh** [comment]
@maciaszczykm the unit tests are failing, you can run the unit test locally by `make test` command

**Comment by maciaszczykm** [comment]
I hope this will fix the tests.

**Comment by maciaszczykm** [comment]
I am not sure what fails atm.

**Comment by maciaszczykm** [comment]
It is bumping two things that are coupled. Scraper is a tool that is created to be used by Dashboard and I think both of them should be updated together in the current situation.

Since I am not sure what is failing and I am not able to reproduce it as I don't have access to any Windows env you can change this pull request if you want or create two separate ones with changes that I did.

**Comment by maciaszczykm** [comment]
@priyawadhwa Yes, thank you for the tip!

**Comment by maciaszczykm** [comment]
Thank you too :)

**Pull request merged**
