### PR TITLE
RELEASING: Add simplified Homebrew Cask update directions

### PR DESCRIPTION
**Pull request by adidalal**
Hey there,

We have a script that makes bumping the version super easy - it will automatically pull down the version you specify, update the shasum and appcast, and create a PR with the changes and issue template correctly filled out.

Feel free to close this PR and use whatever wording is appropriate, just figured a PR would be easier that opening up an issue.

### CODE REVIEW

**Comment by dlorenc** [comment]
Thanks! This looks awesome. @r2d4 could you take a look here and merge after?

**Comment by r2d4** [comment]
Hey @adidalal thanks for the tip, this will definitely make upgrading easier.  One small request, can you sign the CLA first so that I can merge this in?  Thanks again

**Comment by adidalal** [comment]
Apologies, don't have a Google account that I'd want linked to my Github. I understand the legal necessity for a CLA, though, so I will go ahead and close this PR. Consider it a friendly tip :)

**Comment by jimmidyson** [comment]
It doesn't have to be a Google account, whatever you use for github is fine.

**Pull request closed without merging**
