### PR TITLE
Add config parameter for the cri socket path

### LINKED ISSUE #3153: Kubernetes v1.11 doesn't respect alternative container-runtime (cri-o)
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

Please provide the following details:

**Environment**:

- **Minikube version** (use `minikube version`):
v0.28.2-dirty
- **OS** (e.g. from /etc/os-release):
Ubuntu
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
kvm2
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
v0.28.1-dirty
- **Install tools**:

**What happened**:

Still used dockerd

**What you expected to happen**:

Use crio instead

**How to reproduce it** (as minimally and precisely as possible):

`minikube start --kubernetes-version=v1.11.0 --network-plugin=cni --container-runtime=cri-o --extra-config=kubelet.container-runtime=remote --extra-config=kubelet.container-runtime-endpoint=/var/run/crio/crio.sock --extra-config=kubelet.image-service-endpoint=/var/run/crio/crio.sock`

**Output of `minikube logs` (if applicable)**:

```
[preflight] Some fatal errors occurred:
	[ERROR Service-Docker]: docker service is not active, please run 'systemctl start docker.service'
	[ERROR SystemVerification]: failed to get docker info: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

**Anything else do we need to know**:

Worked OK with `v1.10.0`

Apparently there is some new cri socket config added, that is still pointing to the wrong thing.

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #3153

### CODE REVIEW

**Comment by dlorenc** [comment]
Looks like some failing tests in travis:
```shell
    	kubeadm_test.go:245: actual config does not match expected.  actual:
```

**Comment by afbjorklund** [comment]
It seems that it inserted a newline, so I suppose the template needs to be modified slightly...

**Comment by afbjorklund** [comment]
Note that `kubeadm` chokes on `unix://` since it is "not an absolute path"...

**Comment by RA489** [comment]
@afbjorklund this PR needs rebase.

**Pull request merged**
