### PR TITLE
Add link to minikube repository for Void Linux

### PR DESCRIPTION
**Pull request by dan-santana**

### CODE REVIEW

**Comment by dan-santana** [comment]
Do I **really** need to sign a CLA for this single line added to README.md?

**Comment by dlorenc** [comment]
Yes, unfortunately we can't take any PRs without the CLA signature.

**Comment by dan-santana** [comment]
Signed.

**Comment by dan-santana** [comment]
It still shows as `cncf-cla: no`, is there any action I should take?

**Pull request merged**
