### PR TITLE
Add an integration run with the new ISO.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by dlorenc** [comment]
ref #571

**Comment by jimmidyson** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
Just rebased onto the other PR. This should get closer to passing now :)

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
Cool, this is passing now :)

**Pull request merged**
