### PR TITLE
WIP: Save info logs to ~/.minikube/logs by default

### PR DESCRIPTION
**Pull request by RA489**
Save info logs to ~/.minikube/logs by default.
fixes https://github.com/kubernetes/minikube/issues/5581

### CODE REVIEW

**Comment by tstromberg** [comment]
Have you tested this?

make test says:

```
k8s.io/minikube/pkg/minikube/logs imports

	github.com/golang/klog: cannot find module providing package github.com/golang/klog
```

**Comment by RA489** [comment]
I will check it again about test failures.

**Comment by priyawadhwa** [comment]
Hey @RA489 looks like travis failed due to a lint error:

```
pkg/minikube/logs/logs.go:30: File is not `goimports`-ed (goimports)
	"k8s.io/klog"
```

**Comment by tstromberg** [comment]
I don't think this PR does quite enough. To fulfill the issue, this PR would need to move all of the log statements, not just in the logs module.

**Pull request closed without merging**
