### PR TITLE
WIP: Add minikube support for the "generic" VM driver

### PR DESCRIPTION
**Pull request by afbjorklund**
This driver connects to an already existing virtual machine,
using the provided IP address and SSH user/key/port parameters.

On this machine, libmachine will provision the docker daemon
and minikube will bootstrap the kubernetes cluster (as usual).

Implements #4733

### CODE REVIEW

**Comment by medyagh** [comment]
could you provide an example with the PR so we have a context ?

**Comment by medyagh** [comment]
I am thinking if we could use this in the VM-free model too, maybe if the generic driver supports exec-ing into a docker container ?

**Comment by afbjorklund** [comment]
Typical, seems like the generic install (https://get.docker.com) is more strict about security...

```
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker vagrant

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.

```

That doesn't really work, since minikube normally assumes that user has group access:

```Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.39/version: dial unix /var/run/docker.sock: connect: permission denied```

**Comment by afbjorklund** [comment]
Added the user to the group, but doesn't work with vagrant since it only uses one IP (i.e. 127.0.0.1)

`The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?`

**Comment by afbjorklund** [comment]
I think I will split this PR

**Comment by afbjorklund** [comment]
This PR is not going to be merged (it keeps on breaking!), so mostly using it for testing...

**Pull request closed without merging**
