### PR TITLE
Allow users to skip pod health checks with --wait=false

### PR DESCRIPTION
**Pull request by tstromberg**
This saves about 1 minute of run time, and will be useful for integrating with other applications which may do their own health checking. This flag behaves the same as the similarly named flag in `kind`, with one important difference: we leave the default as `true` for a more predictable start-up sequence, at the expense of startup latency. This was also the behavior in minikube up until v1.0.

This PR also sets `--wait=false` to all tests where it's possible to begin testing without all of the services online, such as CoreDNS or etcd. As a result, this PR decreases integration testing time by ~9 minutes.

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by afbjorklund** [comment]
If you change your mind (or your cluster is acting weird), can you run the health checks afterwards ?

**Comment by tstromberg** [comment]
> If you change your mind (or your cluster is acting weird), can you run the health checks afterwards ?

Not yet, but you bring a good point. We should extend `status` to have the same model of pod healthiness as `start`. I'd prefer to introduce that as a second PR though, as it does pose some challenges to how the status command is currently implemented.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

The one failure here appears to be #4418 - just looking for more test data:

```
--- FAIL: TestVersionUpgrade (143.72s)
    util.go:130: Error running command: start --vm-driver=none  --v=10 --logtostderr --...
          - error: failed to create listener: failed to listen on 0.0.0.0:8443: listen tcp 0.0.0.0:8443: bind: address already in use
```

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
PTAL - passes all tests, amazingly.

**Pull request merged**
