### PR TITLE
Upgrade the list of images for 1.12 and 1.13

### PR DESCRIPTION
**Pull request by afbjorklund**
Getting tired of downloading newer etcd again

### CODE REVIEW

**Comment by tstromberg** [comment]
Thanks!

In the future, I think we need to rethink this process a bit. It should be possible to get decent caching behavior without manually maintaining an image list between each update.

**Comment by afbjorklund** [comment]
There's still some oddness going on with the "-amd64", but didn't want to break anything.

**Comment by tstromberg** [comment]
Test failures look OK. Feel free to merge when you are comfortable with it.

**Pull request merged**
