### PR TITLE
Add cross compile Makefile target, including building for Windows

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by luxas** [comment]
LGTM

**Comment by dlorenc** [comment]
Nice! Have you tested the windows build yet? We should add it to the releasing.md doc once it's actually ready to send to users.

**Comment by jimmidyson** [comment]
I haven't tested on Windows yet - was just getting out an old dusty Windows VM I had tucked away for stuff like this. Let's wait for merge until I have (or someone else has!) tested. Can't see any problems with it though.

**Comment by dlorenc** [comment]
I don't mind merging now, this makes it easier for others to start testing on Windows.

**Pull request merged**
