### PR TITLE
Make KIC start message shorter

### PR DESCRIPTION
**Pull request by afbjorklund**
Don't show the host info any more (available),
since we don't show it for the VM host either.

### CODE REVIEW

**Comment by medyagh** [comment]
Can you please post before and after?

**Comment by afbjorklund** [comment]
Before:

```
✨  Using the docker driver based on user configuration
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
🔥  Creating Kubernetes in docker container with (CPUs=2) (4 available), Memory=2
200MB (7800MB available) ...
```

After:

```
✨  Using the docker driver based on user configuration
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=2200MB, Disk=138379MB) ...
```

----

Compare:
```
👍  Starting control plane node m01 in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
```

```
✨  Using the none driver based on user configuration
👍  Starting control plane node  in cluster minikube
🤹  Running on localhost (CPUs=4, Memory=7800MB, Disk=138379MB) ...
ℹ️  OS release is Ubuntu 16.04.6 LTS
```

**Comment by tstromberg** [comment]
I tried this on macOS and got:

`pkg/drivers/kic/oci/info.go:42:26: invalid operation: int64(fs.Blocks) * fs.Bsize (mismatched types int64 and uint32)`

Using `int64(fs.Bsize)` made it work properly.

**Comment by afbjorklund** [comment]
I’m not even sure the disk size is accurate on the VM-based Docker ?

**Comment by afbjorklund** [comment]
https://docs.docker.com/docker-for-mac/space/

`~/Library/Containers/com.docker.docker/Data/vms/0/data/Docker.raw`

https://docs.docker.com/docker-for-windows/install/

`C:\Users\Public\Documents\Hyper-V\Virtual hard disks\DockerDesktop.vhdx`

So the values above are **only** valid for Linux. :-(

----

The problem with `docker system df -v` is that it takes _forever_ to run... (like 15s or so)

And it only shows how much is used, not how much the total is or how much is available.

**Comment by afbjorklund** [comment]
> Using `int64(fs.Bsize)` made it work properly.

golangci-lint had a different opinion, though...

```
pkg/drivers/kic/oci/info.go:42:33: unnecessary conversion (unconvert)
	return int64(fs.Blocks) * int64(fs.Bsize) / 1024 / 1024
	                               ^
```

**Comment by tstromberg** [comment]
OK. Switch it back so the tests work. We can sort out any platform specific quirks afterwards.

```
pkg/drivers/kic/oci/info.go:42:33: unnecessary conversion (unconvert)
	return int64(fs.Blocks) * int64(fs.Bsize) / 1024 / 1024
```

**Comment by medyagh** [comment]
I was thinking how about to keep the available somehow ?
Sometimes its nice to see it user had to give 2gb memory because available was 3 gb...


And also for disk size I was thinking for kic it makes more sense to use docker machine disk size not the system disk size. What do you think ?

**Comment by tstromberg** [comment]
> I was thinking how about to keep the available somehow ?
> Sometimes its nice to see it user had to give 2gb memory because available was 3 gb...

So far, I personally haven't found avail to be useful.

> And also for disk size I was thinking for kic it makes more sense to use docker machine disk size not the system disk size. What do you think ?

I believe this PR does that.

**Comment by afbjorklund** [comment]
The easiest short-term solution is to remove the disk size. Or show the config ?
(sort of implies that there is a check to see that you actually can use the 20G)

**Comment by medyagh** [comment]
> t-term solution is to remove the disk size. Or show the config ?

what do u think about this

🔥  Creating Kubernetes in docker container with (CPUs=2) (2 available), Memory=4000MB (7964MB available) ...

become like the kubernetes optiopns
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16

so it will be:

🔥  Creating Kubernetes in docker container 
         ▪  CPUs=2 (2 available)
         ▪  Memory=4000MB (7964MB available) 
         ▪  Disk=20000MB (10000MB available)

**Comment by afbjorklund** [comment]
I don't fully understand why we need to show the word "Kubernetes" twice.

The end goal was to make the start output more similar for different drivers:

`🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...`

`🔥  Creating docker container (CPUs=2, Memory=2200MB, Disk=20000MB) ...`

**Comment by medyagh** [comment]
> I don't fully understand why we need to show the word "Kubernetes" twice.
> 
> The end goal was to make the start output more similar for different drivers:
> 
> `🔥 Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...`
> 
> `🔥 Creating docker container (CPUs=2, Memory=2200MB, Disk=20000MB) ...`

I agree that looks much better

**Comment by medyagh** [comment]
> I don't fully understand why we need to show the word "Kubernetes" twice.
> 
> The end goal was to make the start output more similar for different drivers:
> 
> `🔥 Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...`
> 
> `🔥 Creating docker container (CPUs=2, Memory=2200MB, Disk=20000MB) ...`

what do u think about using multi lines
🔥  Creating docker container
    ▪  CPUs=2 (2 available)
    ▪  Memory=4000MB (7964MB available) 
    ▪  Disk=20000MB (10000MB available)

**Comment by afbjorklund** [comment]
> what do u think about using multi lines so we can still keep the availables

Sure, but then you should show host info for all drivers (not just docker)

**Comment by afbjorklund** [comment]
Note that I wanted to show the disk info for the docker driver as well.

Just fell a bit short, when it comes to implementing it (cross-platform)

Maybe something similar. but using `ssh df` ?

But very hard to test this, on the VM platforms.

**Comment by medyagh** [comment]
I would like to see that info for all of them. If not possible for a platform for now. We can just skip

**Comment by afbjorklund** [comment]
> I would like to see that info for all of them. If not possible for a platform for now. We can just skip

Should open a new issue, for getting docker disk information on those platforms...
I'm not sure if we have `ssh` access, or if we know how those disk images work ?

For the Minikube VM and SSH, it is easy enough to connect to the virtual machine.
But for the Docker VM, it depends on what is implemented and what is accessible ?

**Comment by medyagh** [comment]
> > I would like to see that info for all of them. If not possible for a platform for now. We can just skip
> 
> Should open a new issue, for getting docker disk information on those platforms...
> I'm not sure if we have `ssh` access, or if we know how those disk images work ?
> 
> For the Minikube VM and SSH, it is easy enough to connect to the virtual machine.
> But for the Docker VM, it depends on what is implemented and what is accessible ?

sure we can do it in a separate PR

**Pull request merged**
