### PR TITLE
Make kicbase copy auto-pause binary instead of auto-pause folder

### LINKED ISSUE #11823: auto-pause not working - kubectl hangs/fails to connect
Start minikube with auto-pause, kubectl commands all hang indefinitely or fails to connect.

### PR DESCRIPTION
**Pull request by andriyDev**
fixes #11823.

### CODE REVIEW

**Comment by sharifelgamal** [comment]
cc @medyagh

**Review by medyagh — CHANGES_REQUESTED** [review]
aah it seems that I broke this when I added arm64 to kicbase
```
COPY --from=0 /src/cmd/auto-pause /bin/auto-pause
```
this needs to be changed to 
```
COPY --from=0 /src/cmd/auto-pause/auto-pause /bin/auto-pause

```

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by andriyDev** [comment]
ok-to-build-image

**Comment by andriyDev** [comment]
ok-to-build-image

**Review by medyagh — APPROVED** [review]

**Pull request merged**
