### PR TITLE
Adding cephfs kernel module to minikube iso

### PR DESCRIPTION
**Pull request by kokhang**
Fix https://github.com/kubernetes/minikube/issues/1668

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot ok to test

**Comment by dlorenc** [comment]
You should be able to sanity test your built iso (to make sure ceph works) at this URL: http://storage.googleapis.com/minikube-builds/1669/minikube.iso

I'm running a few tests on it now.

**Comment by dlorenc** [comment]
```shell
$ cat /proc/config.gz | gunzip | grep CEPH
CONFIG_CEPH_LIB=y
# CONFIG_CEPH_LIB_PRETTYDEBUG is not set
# CONFIG_CEPH_LIB_USE_DNS_RESOLVER is not set
CONFIG_CEPH_FS=m
CONFIG_CEPH_FS_POSIX_ACL=y
```

**Comment by dlorenc** [comment]
@kokhang can you ack that the ceph stuff you need works in this ISO? I'll merge after that and then push out a new build.

**Comment by kokhang** [comment]
@dlorenc It works. The module does get included.
`$ find /lib/modules/$(uname -r)/kernel/fs -type f -name '*.ko' | grep -E 'ceph'
/lib/modules/4.9.13/kernel/fs/ceph/ceph.ko`

Also my test script worked. I was able to mount a ceph FS with this minikube ISO.
Thank you!

**Pull request merged**
