### PR TITLE
Update kubernetes to v1.3.0-beta.1

### PR DESCRIPTION
**Pull request by dlorenc**
No manual changes needed. Integration tests passing:
```shell
$ make integration
go test -v k8s.io/minikube/test/integration --tags=integration
=== RUN   TestAddons
--- PASS: TestAddons (101.59s)
=== RUN   TestDashboard
--- PASS: TestDashboard (5.95s)
=== RUN   TestClusterDNS
--- PASS: TestClusterDNS (14.08s)
=== RUN   TestClusterEnv
--- PASS: TestClusterEnv (1.24s)
=== RUN   TestClusterLogs
--- PASS: TestClusterLogs (1.06s)
=== RUN   TestClusterSSH
--- PASS: TestClusterSSH (1.14s)
=== RUN   TestClusterStatus
Component: scheduler, Healthy: True.
Component: controller-manager, Healthy: True.
Component: etcd-0, Healthy: True.
--- PASS: TestClusterStatus (0.87s)
=== RUN   TestStartStop
--- PASS: TestStartStop (125.55s)
PASS
ok  	k8s.io/minikube/test/integration	251.557s
```

### CODE REVIEW

**Comment by luxas** [comment]
Have you run conformance tests?

**Comment by luxas** [comment]
@dlorenc ping on conformance test results...
Otherwise LGTM, but I think we want the stable `v1.3` for the next release as well

**Comment by dlorenc** [comment]
Sorry, running them now. I had some trouble getting them built last night.

**Comment by dlorenc** [comment]
Results are good (no changes):
```shell
Summarizing 2 Failures:

[Fail] [k8s.io] DNS [It] should provide DNS for services [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:204

[Fail] [k8s.io] Networking [It] should function for intra-pod communication [Conformance]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:133
```

**Pull request merged**
