### PR TITLE
made the default status of addons false

### LINKED ISSUE #15710: `minikube addons list` outputs wrong state for default addons
**Reproduce:**
```
$ minikube start --install-addons=false
😄  minikube v1.28.0 on Darwin 13.2 (arm64)
✨  Using the docker driver based on user configuration
📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
🐳  Preparing Kubernetes v1.25.3 on Docker 20.10.22 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

# no storage provisioner
$ kubectl get pods -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-565d847f94-hvhfh           1/1     Running   0          5m59s
kube-system   etcd-minikube                      1/1     Running   0          6m12s
kube-system   kube-apiserver-minikube            1/1     Running   0          6m12s
kube-system   kube-controller-manager-minikube   1/1     Running   0          6m12s
kube-system   kube-proxy-tvr7g                   1/1     Running   0          5m59s
kube-system   kube-scheduler-minikube            1/1     Running   0          6m12s

# incorrectly states addons are enabled
$ minikube addons list
|-----------------------------|----------|--------------|--------------------------------|
|         ADDON NAME          | PROFILE  |    STATUS    |           MAINTAINER           |
|-----------------------------|----------|--------------|--------------------------------|
| ambassador                  | minikube | disabled     | 3rd party (Ambassador)         |
| auto-pause                  | minikube | disabled     | Google                         |
| cloud-spanner               | minikube | disabled     | Google                         |
| csi-hostpath-driver         | minikube | disabled     | Kubernetes                     |
| dashboard                   | minikube | disabled     | Kubernetes                     |
| default-storageclass        | minikube | enabled ✅   | Kubernetes                     |
| efk                         | minikube | disabled     | 3rd party (Elastic)            |
| freshpod                    | minikube | disabled     | Google                         |
| gcp-auth                    | minikube | disabled     | Google                         |
| gvisor                      | minikube | disabled     | Google                         |
| headlamp                    | minikube | disabled     | 3rd party (kinvolk.io)         |
| helm-tiller                 | minikube | disabled     | 3rd party (Helm)               |
| inaccel                     | minikube | disabled     | 3rd party (InAccel             |
|                             |          |              | [info@inaccel.com])            |
| ingress                     | minikube | disabled     | Kubernetes                     |
| ingress-dns                 | minikube | disabled     | Google                         |
| istio                       | minikube | disabled     | 3rd party (Istio)              |
| istio-provisioner           | minikube | disabled     | 3rd party (Istio)              |
| kong                        | minikube | disabled     | 3rd party (Kong HQ)            |
| kubevirt                    | minikube | disabled     | 3rd party (KubeVirt)           |
| logviewer                   | minikube | disabled     | 3rd party (unknown)            |
| metallb                     | minikube | disabled     | 3rd party (MetalLB)            |
| metrics-server              | minikube | disabled     | Kubernetes                     |
| nvidia-driver-installer     | minikube | disabled     | Google                         |
| nvidia-gpu-device-plugin    | minikube | disabled     | 3rd party (Nvidia)             |
| olm                         | minikube | disabled     | 3rd party (Operator Framework) |
| pod-security-policy         | minikube | disabled     | 3rd party (unknown)            |
| portainer                   | minikube | disabled     | 3rd party (Portainer.io)       |
| registry                    | minikube | disabled     | Google                         |
| registry-aliases            | minikube | disabled     | 3rd party (unknown)            |
| registry-creds              | minikube | disabled     | 3rd party (UPMC Enterprises)   |
| storage-provisioner         | minikube | enabled ✅   | Google                         |
| storage-provisioner-gluster | minikube | disabled     | 3rd party (Gluster)            |
| volumesnapshots             | minikube | disabled     | Kubernetes                     |
|-----------------------------|----------|--------------|--------------------------------|
```

The addon list should show all addons as disabled

### PR DESCRIPTION
**Pull request by swastik959**
1. made the default status of addons false
2. it fixes #15710 
3.I simply changed the default status of the sevices as false
4. if any discrepancy is there feel free to point out

### CODE REVIEW

**Review by spowelljr — CHANGES_REQUESTED** [review]
We don't want the the storage provisioner addons to be disabled by default, we just want them to show as correctly disabled when `minikube profile list` is ran.

**Comment by swastik959** [comment]
@spowelljr can you please let me know where to look for this problem

**Comment by spowelljr** [comment]
@shubhbapna is assigned the issue https://github.com/kubernetes/minikube/issues/15710, if they don't have any activity on the issue by the end of this week then we can unassign the issue and you can take it.

**Comment by shubhbapna** [comment]
@spowelljr sorry for the delay. I have opened a PR:
* https://github.com/kubernetes/minikube/pull/15762

**Pull request closed without merging**
