### PR TITLE
Use cri-dockerd instead of dockershim where needed

### LINKED ISSUE #12099: Start cri-docker service automatically, if using docker and kubernetes version >= 1.24
As mentioned in ~#9868~, using docker requires CRI starting from kubernetes **1.24** up:

https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2221-remove-dockershim

It is being casually updated by Mirantis, for use in their commercial products:

https://www.mirantis.com/blog/the-future-of-dockershim-is-cri-dockerd/

https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/

We should make sure to include `cri-dockerd`, and switch to `/var/run/cri-docker.sock`

----

Most things should be prepared in the cruntime already.

~~Unfortunately it seems upstream doesn't provide binaries ?~~

~~> There is a Makefile with a few targets. `make deb` or `make rpm` will probably have you covered, and you can install the packages as normal. If you’re using a different distribution, `make static` will give you raw binaries you can invoke.~~

~~https://github.com/mirantis/cri-dockerd~~

### PR DESCRIPTION
**Pull request by afbjorklund**
Starting with Kubernetes version 1.24, the CRI socket
for Docker is handled externally instead of internally.

See https://www.mirantis.com/blog/the-future-of-dockershim-is-cri-dockerd/

I added a feature to start the socket/service, transparently to the casual user...

For the power user giving their own CRI socket, they get to maintain it as well.

Closes #12099

----

Note: needs `cri-dockerd` installed, for testing (see #12103).

Also tweak the version check, when to not use dockershim:

`KubernetesVersion.GTE(semver.Version{Major: 1, Minor: 24})`

i.e. If you want to try it out, _before_ Kubernetes 1.24 is available.

EDIT: The dockershim removal was delayed again, from 1.23 to 1.24

### CODE REVIEW

**Comment by medyagh** [comment]
I am excited about this PR

**Comment by afbjorklund** [comment]
I tested with the alpha, and it doesn't work because minikube passes "0.0.0" for the kubernetes version.

**Comment by afbjorklund** [comment]
dockershim is still included, in alpha 1 as well

**Comment by afbjorklund** [comment]
Need to change the k8s version (1.24.0-alpha.**1**), and need to change the cri socket path (cri-docker**d**.sock).

**Comment by afbjorklund** [comment]
Related PR, for `kubeadm`:

* https://github.com/kubernetes/kubernetes/pull/107317

**Comment by medyagh** [comment]
thank you for this PR :)

**Review by medyagh — APPROVED** [review]

**Pull request merged**
