### PR TITLE
cri-dockerd 0.2.6

### PR DESCRIPTION
**Pull request by afbjorklund**
* go1.19

* Use cni by default on Linux, too

----

Note: needs fix for `--network-plugin` to go in first:

* #14703

### CODE REVIEW

**Comment by afbjorklund** [comment]
@spowelljr : it was not _entirelly_ obvious how to kick off the build of the new binaries, so just updated version and checksums

**Comment by afbjorklund** [comment]
Need to cherry-pick: `460da8ef84e7d2781ee275907543764b6a77c5ff`

* #14789

**Comment by spowelljr** [comment]
> @spowelljr : it was not _entirelly_ obvious how to kick off the build of the new binaries, so just updated version and checksums

No worries, I just ran the job

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by cdeeran** [comment]
Commenting to subscribe to the PR. I really need this to go through in order to advance on my project.

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-image

**Pull request closed without merging**
