### PR TITLE
Add checkpointing support with cri-o for x86

### PR DESCRIPTION
**Pull request by mh4ck-Thales**
Checkpointing a Kubernetes Pod have been introduced as an alpha feature in Kubernetes 1.25 (see [here](https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/) and [here](https://kubernetes.io/docs/reference/node/kubelet-checkpoint-api/)). Checkpointing was not working out of the box for minikube due to missing options. This PR enable the possibility to test checkpointing on minikube by adding the necessary binaries, upgrades and options in the Linux kernel within the minikube iso buildroot configuration.

## Detailed changes 
 
- https://github.com/kubernetes/minikube/commit/28a5044797002ce9a1f9897552aae43d6e5419ae : update the cri-o version, PR is pending at https://github.com/kubernetes/minikube/pull/16493, there was other multiple PRs which were all closed. In this PR https://github.com/kubernetes/minikube/pull/15972#issuecomment-1455874304 I mentioned that in order to update cri-o we need to update also crictl. For info checkpointing requires cri-o >= 1.25 and crictl >= 1.25.
- https://github.com/kubernetes/minikube/commit/41433ee5cbcc41b45667de0ca54a2acb4b2eaf4b updating crictl for the point explained above (cri-o >= 1.25.0 needs it). 
- https://github.com/kubernetes/minikube/commit/413d2e3426499b3bc27a08b133fac8299189d52e : this adds the [criu](https://criu.org/Main_Page) binary to the buildroot config. This is the binary needed to do the actual checkpointing.
- https://github.com/kubernetes/minikube/commit/4ccde9dd5482a3fee9b223361a00bb5e0198d045 : This enables the additional librairies needed by criu within the buildroot configuration. It also add some kernel options in order for criu to be able to do its job. The needed kernel options are listed [here](https://criu.org/Linux_kernel) and the dependencies for criu [here](https://criu.org/Installation#Installing_build_dependencies).
- https://github.com/kubernetes/minikube/commit/db6205b74b6ea08e1271c2db1def7f11fd0fbb99 : modification of the default embedded cri-o config in order to enable checkpointing support with cri-o.
- https://github.com/kubernetes/minikube/commit/c2d8075e9555c15c37734904b25ddb3d285b8ebc : add needed dependencies to the buildroot Dockerfile.

### Before the PR

Starting the minikube cluster with the cri-o runtime (the only one supporting checkpointing) and enabling the feature gate : 

```
$ minikube start --container-runtime cri-o --feature-gates "ContainerCheckpoint=true"
[minikube starting...]
```

Creating privileged service account and getting token for API authentication : 

```
$ kubectl create serviceaccount checkpoint-api
serviceaccount/checkpoint-api created
$ kubectl create clusterrolebinding checkpoint-api-sa-admin --clusterrole=cluster-admin --serviceaccount=default:checkpoint-api
clusterrolebinding.rbac.authorization.k8s.io/checkpoint-api-sa-admin created
$ TOKEN=$(kubectl create token checkpoint-api)
$ echo "$TOKEN"
eYJ...
```

Creating the demo container to checkpoint and waiting for deployment :

```
$ kubectl create deployment nginx --image bitnami/nginx
deployment.apps/nginx created
$ kubectl rollout status deployment nginx
Waiting for deployment "nginx" rollout to finish: 0 of 1 updated replicas are available...
deployment "nginx" successfully rolled out
```

And try checkpointing the container : 

```
$ curl -k -X POST -H "Authorization: Bearer $TOKEN" "https://$(minikube ip):10250/checkpoint/default/$(kubectl get pods -o jsonpath='{.items[0].metadata.name}')/nginx"
checkpointing of default/nginx-747764db4-mb7sd/nginx failed (rpc error: code = Unimplemented desc = unknown method CheckpointContainer for service runtime.v1.RuntimeService)
```

The checkpointing is failing because cri-o < 1.25 doesn't implement checkpointing support. Just upgrading and configuring cri-o will give another error as the `criu` binary needed to checkpoint is not present on the minikube VM. 

### After the PR

Starting minikube using the `minikube-amd64.iso` image generated using the PR changes (don't forget clean before with `minikube delete` if you're doing the tests back-to-back):

```
$ minikube start --container-runtime cri-o --feature-gates "ContainerCheckpoint=true" --iso-url file://$(pwd)/minikube-amd64.iso
[minikube starting...]
```

Repeat the steps above up until the checkpointing step. With the PR modifications, when trying to checkpoint :

```
$ curl -k -X POST -H "Authorization: Bearer $TOKEN" "https://$(minikube ip):10250/checkpoint/default/$(kubectl get pods -o jsonpath='{.items[0].metadata.name}')/nginx"
{"items":["/var/lib/kubelet/checkpoints/checkpoint-nginx-747764db4-wcf7h_default-nginx-2023-05-23T15:09:56Z.tar"]}
```

You see that the checkpoint have succeeded and is available on the minikube VM. You can `minikube ssh` to look at it and scp it on your own machine to examine it further.

## Additional infos 
- This is tested and confirmed to work with minikube v1.29.0. I rebased my branch and didn't test again. I didn't see any potential problem in the release notes for v1.30 though.
- At the moment checkpointing is only working with cri-o (and will stay like this as long as https://github.com/containerd/containerd/pull/6965 is not merged). Once this is done simply upgrading containerd should allow it to be used for checkpointing in minikube as well.
- There is an ugly hack in the criu configuration file [here](https://github.com/ThalesGroup/minikube/blob/c2d8075e9555c15c37734904b25ddb3d285b8ebc/deploy/iso/minikube-iso/arch/x86_64/package/criu/criu.mk#L15]). That's the only way I found to be able to build criu within the buildroot building process. I don't know why it's not working without manually changing the compile flags. If you have an idea on how to build in a more "buildroot philosophy" way, feel free to comment. Otherwise it can just be merged as is, as it is working and doesn't impact the rest of the project. Changes are explained into the comments above the hacky line.
- I put criu in the x86_64 directory as I only tested the changes on x86 hardware and I don't know if criu and the Kubernetes checkpoining is even supposed to work on ARM architectures.

### CODE REVIEW

**Comment by medyagh** [comment]
@mh4ck-Thales do you mind sharing example of using this feature Before and After this PR ? in the PR description output

**Comment by mh4ck-Thales** [comment]
Hello, I've rebased this PR and signed the CLA, is it possible to review it ?

**Comment by mh4ck-Thales** [comment]
Any news for a review ?

**Comment by medyagh** [comment]
@mh4ck-Thales thanks for your patience on this review, I ordered an image bulid and we will see tests are normal
and also the PR still says has a merge conflict

**Comment by mh4ck-Thales** [comment]
Hi @medyagh, thanks for launching the tests. I just fixed the merge conflict, it should be mergeable now.

**Comment by mh4ck-Thales** [comment]
@medyagh I rebased again, waiting for your input.

**Comment by mh4ck-Thales** [comment]
Rebased and fixed conflicts again.

**Pull request closed without merging**
