### PR TITLE
Upgrade Headlamp version to 0.19.1

### PR DESCRIPTION
**Pull request by joaquimrocha**
Upgrade Headlamp version to 0.19.1
  cc: @joaquimrocha

### CODE REVIEW

**Comment by joaquimrocha** [comment]
Couldn't do it yesterday in the end. But rebased now against the latest upstream master. Hopefully it's fine.

**Review by spowelljr — APPROVED** [review]
Works now, thanks!

**Comment by joaquimrocha** [comment]
> Works now, thanks!

Thank you!

**Pull request merged**
