### PR TITLE
test k8s v1.27.2

### PR DESCRIPTION
**Pull request by prezha**
do not merge: this pr is for testing the latest k8s ~v1.27.0-rc.0~ v1.27.1

local TestMultiNode with docker/docker passed:
[TestMultiNode-k8s-1.27.0-rc-0.log](https://github.com/kubernetes/minikube/files/11057409/TestMultiNode-k8s-1.27.0-rc-0.log)

### CODE REVIEW

**Comment by prezha** [comment]
got TestFunctional with docker/containerd failed different sub-tests (flake?)
[TestFunctional-k8s-1.27.0-rc-0 - fail.log](https://github.com/kubernetes/minikube/files/11057591/TestFunctional-k8s-1.27.0-rc-0.-.fail.log)

**Comment by prezha** [comment]
ingress tests failing (eg, [this](https://storage.googleapis.com/minikube-builds/logs/16145/28465/Docker_Linux.html#fail_TestAddons%2fparallel%2fIngress) one) because the latest k8s v1.27.0-rc.0 returns `27+` for the minor version:
```
14:05 $ kubectl version -ojson
{
  "clientVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.3",
    "gitCommit": "9e644106593f3f4aa98f8a84b23db5fa378900bd",
    "gitTreeState": "clean",
    "buildDate": "2023-03-15T13:40:17Z",
    "goVersion": "go1.19.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "27+",
    "gitVersion": "v1.27.0-rc.0",
    "gitCommit": "cf60ee25590ac79334f823b7f03cf33105a442c1",
    "gitTreeState": "clean",
    "buildDate": "2023-03-23T18:59:06Z",
    "goVersion": "go1.20.2",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

**Comment by afbjorklund** [comment]
It is supposed to use semver, so that looks broken.

**Comment by prezha** [comment]
perhaps we did not test an `-rc` version recently or it was simply missed (usually not sticking around for a long time), but in any case, it's not compliant with the semver spec, so probably should not return that

**Comment by afbjorklund** [comment]
It is passed down through the linker flags:

`-X 'k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitMajor=1' -X 'k8s.io/kubernetes/vendor/k8s.io/component-base/version.gitMajor=1' -X 'k8s.io/client-go/pkg/version.gitMajor=1' -X 'k8s.io/component-base/version.gitMajor=1' -X 'k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitMinor=26+' -X 'k8s.io/kubernetes/vendor/k8s.io/component-base/version.gitMinor=26+' -X 'k8s.io/client-go/pkg/version.gitMinor=26+'`

But it has been added on purpose:

```shell
      if [[ "${KUBE_GIT_VERSION}" =~ ^v([0-9]+)\.([0-9]+)(\.[0-9]+)?([-].*)?([+].*)?$ ]]; then
        KUBE_GIT_MAJOR=${BASH_REMATCH[1]}
        KUBE_GIT_MINOR=${BASH_REMATCH[2]}
        if [[ -n "${BASH_REMATCH[4]}" ]]; then
          KUBE_GIT_MINOR+="+"
        fi
      fi
```

**Comment by prezha** [comment]
good catch, thanks @afbjorklund !

issue: #16157, pr: #16158

i'll also "patch" this test pr so we can move on with testing k8s v1.27

**Comment by prezha** [comment]
closing as resolved via https://github.com/kubernetes/minikube/pull/16528

**Pull request closed without merging**
