### PR TITLE
metallb addon: fix docker.io dependency and move to quay.io

### PR DESCRIPTION
**Pull request by boeboe**
Fixes https://github.com/kubernetes/minikube/issues/16053 as per https://github.com/metallb/metallb/issues/696#issuecomment-714652624

### CODE REVIEW

**Comment by boeboe** [comment]
Referencing https://github.com/kubernetes/minikube/pull/16055

**Review by medyagh — COMMENTED** [review]
thank you for this PR, do you mind building minikube locally and paste the outpute of


make
./out/minikube delete 
./out/minikube start 
./out/minikube addons enable metallb

and then

kubectl get pods -A

so we could see the changes work?

**Comment by boeboe** [comment]
At your service.

```
~/Git/boeboe/minikube (metallb-quay-io) $ make
go build  -tags "" -ldflags="-X k8s.io/minikube/pkg/version.version=v1.29.0 -X k8s.io/minikube/pkg/version.isoVersion=v1.29.0-1678210391-15973 -X k8s.io/minikube/pkg/version.gitCommitID="f0e0e69dc18db6ea0a802435c9a958d9c2c0ce2a" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v5" -o out/minikube k8s.io/minikube/cmd/minikube
~/Git/boeboe/minikube (metallb-quay-io) $ ./out/minikube start
😄  minikube v1.29.0 on Ubuntu 22.04
✨  Automatically selected the docker driver. Other choices: kvm2, qemu2, virtualbox, ssh
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.26.2 preload ...
    > preloaded-images-k8s-v18-v1...:  396.97 MiB / 396.97 MiB  100.00% 16.97 M
    > gcr.io/k8s-minikube/kicbase...:  373.16 MiB / 373.16 MiB  100.00% 6.09 Mi
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
🐳  Preparing Kubernetes v1.26.2 on Docker 23.0.1 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
~/Git/boeboe/minikube (metallb-quay-io) $ ./out/minikube addons enable metallb
❗  metallb is a 3rd party addon and is not maintained or verified by minikube maintainers, enable at your own risk.
❗  metallb does not currently have an associated maintainer.
    ▪ Using image quay.io/metallb/speaker:v0.9.6
    ▪ Using image quay.io/metallb/controller:v0.9.6
🌟  The 'metallb' addon is enabled
~/Git/boeboe/minikube (metallb-quay-io) $ kubectl get pods -n metallb-system controller-56986fbff6-gttfx -o yaml | grep image
    image: quay.io/metallb/controller:v0.9.6@sha256:6932cf255dd7f06f550c7f106b9a206be95f847ab8cb77aafac7acd27def0b00
    imagePullPolicy: IfNotPresent
    image: quay.io/metallb/controller@sha256:6932cf255dd7f06f550c7f106b9a206be95f847ab8cb77aafac7acd27def0b00
    imageID: docker-pullable://quay.io/metallb/controller@sha256:6932cf255dd7f06f550c7f106b9a206be95f847ab8cb77aafac7acd27def0b00
~/Git/boeboe/minikube (metallb-quay-io) $ kubectl get daemonset -n metallb-system speaker -o yaml | grep image
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"metallb","component":"speaker"},"name":"speaker","namespace":"metallb-system"},"spec":{"selector":{"matchLabels":{"app":"metallb","component":"speaker"}},"template":{"metadata":{"annotations":{"prometheus.io/port":"7472","prometheus.io/scrape":"true"},"labels":{"app":"metallb","component":"speaker"}},"spec":{"containers":[{"args":["--port=7472","--config=config"],"env":[{"name":"METALLB_NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"METALLB_HOST","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}}],"image":"quay.io/metallb/speaker:v0.9.6@sha256:7a400205b4986acd3d2ff32c29929682b8ff8d830837aff74f787c757176fa9f","imagePullPolicy":"IfNotPresent","name":"speaker","ports":[{"containerPort":7472,"name":"monitoring"}],"resources":{"limits":{"cpu":"100m","memory":"100Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"add":["NET_ADMIN","NET_RAW","SYS_ADMIN"],"drop":["ALL"]},"readOnlyRootFilesystem":true}}],"hostNetwork":true,"nodeSelector":{"kubernetes.io/os":"linux"},"serviceAccountName":"speaker","terminationGracePeriodSeconds":0,"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"}]}}}}
        image: quay.io/metallb/speaker:v0.9.6@sha256:7a400205b4986acd3d2ff32c29929682b8ff8d830837aff74f787c757176fa9f
        imagePullPolicy: IfNotPresent
~/Git/boeboe/minikube (metallb-quay-io) $ kubectl get pods -A
NAMESPACE        NAME                               READY   STATUS    RESTARTS      AGE
kube-system      coredns-787d4945fb-2z2mh           1/1     Running   0             68s
kube-system      etcd-minikube                      1/1     Running   0             82s
kube-system      kube-apiserver-minikube            1/1     Running   0             83s
kube-system      kube-controller-manager-minikube   1/1     Running   0             82s
kube-system      kube-proxy-vb9p8                   1/1     Running   0             69s
kube-system      kube-scheduler-minikube            1/1     Running   0             82s
kube-system      storage-provisioner                1/1     Running   1 (38s ago)   81s
metallb-system   controller-56986fbff6-gttfx        1/1     Running   0             59s
metallb-system   speaker-22mxb                      1/1     Running   0             59s

```

**Pull request merged**
