### PR TITLE
Add an integration test to make sure the dashboard works after a rest…

### PR DESCRIPTION
**Pull request by dlorenc**
…art.

This should fail until we finish and merge #320.

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
Nice, got the correct failure this time:

```
=== RUN   TestAddons
--- PASS: TestAddons (153.49s)
=== RUN   TestDashboard
--- PASS: TestDashboard (26.08s)
=== RUN   TestClusterDNS
--- PASS: TestClusterDNS (8.80s)
=== RUN   TestClusterEnv
--- PASS: TestClusterEnv (1.08s)
=== RUN   TestClusterLogs
--- PASS: TestClusterLogs (0.84s)
=== RUN   TestClusterSSH
--- PASS: TestClusterSSH (1.00s)
=== RUN   TestClusterStatus
Component: controller-manager, Healthy: True.
Component: scheduler, Healthy: True.
Component: etcd-0, Healthy: True.
--- PASS: TestClusterStatus (1.20s)
=== RUN   TestPersistence
--- FAIL: TestPersistence (132.58s)
	persistence_test.go:94: Dashboard pod is not healthy: Dashboard pod not healthy. Healthy: False. Reason: ContainersNotReady
=== RUN   TestStartStop
--- PASS: TestStartStop (194.89s)
```

**Comment by jimmidyson** [comment]
Yay #320 seems to have worked! LGTM

**Pull request merged**
