### PR TITLE
added missing 's' in github issues link

### PR DESCRIPTION
**Pull request by TG-KK**

### CODE REVIEW

**Comment by TG-KK** [comment]
I signed the CLA after submitting the PR. How do I get the CLA check to pass/re-trigger ?
Email address is same in github & CLA.

**Comment by uthark** [comment]
I submitted PR for that one yesterday. See [pr#4048](https://github.com/kubernetes/minikube/pull/4048)

**Comment by tstromberg** [comment]
Thank you for fixing this!

**Comment by afbjorklund** [comment]
This issue seems to have been prematurely closed.

**Pull request closed without merging**
