### PR TITLE
Update Japanese translation (Line 800-850)

### PR DESCRIPTION
**Pull request by yosshy**
/hold for japanese developer's review
/assign @atoato88
/cc @YuikoTakada @t-inu

### CODE REVIEW

**Comment by medyagh** [comment]
@yosshy @atoato88 is this PR ready to be merged ?

**Comment by atoato88** [comment]
/lgtm
@yosshy Thank you to update.
@medyagh It's ready to merge.

**Comment by yosshy** [comment]
/unhold
@medyagh it's ready to merge.

**Comment by yosshy** [comment]
@atoato88 thanks for your review.
/assign @prezha

**Pull request merged**
