### PR TITLE
linux steps are for without VM

### PR DESCRIPTION
**Pull request by kmova**
The steps indicate minikube is getting installed without VM
sudo -E ./minikube start --vm-driver=none

### CODE REVIEW

**Comment by afbjorklund** [comment]
Confusingly, I think the comment was alluding to the fact that running `minikube` this way allows ("supports" ?) running it _inside_ another VM, referred to as "nested virtualization" further down on the page...

> none (Linux-only) - this driver can be used to run the Kubernetes cluster components on the host instead of in a VM. This can be useful for CI workloads which do not support nested virtualization.

Would be good with some extra clarification.

**Comment by kmova** [comment]
I see what you mean @afbjorklund 

Though, I must say, I find this mode (vmdriver=none) useful for non-CI workload scenarios as well.

**Comment by afbjorklund** [comment]
Yeah, that is another documentation need... Especially with the addition of kubeadm bootstrapper.

**Comment by dlorenc** [comment]
I think this initially was intended to mean that you can run it inside a VM, but this seems slightly more clear. We probably want to reword it more though.

**Pull request merged**
