### PR TITLE
Fix the Makefile so a phantom "minikube" linked directory isn't creat…

### PR DESCRIPTION
**Pull request by dlorenc**
…ed anymore.

### CODE REVIEW

**Comment by dlorenc** [comment]
@k8s-bot retest this please

**Comment by jimmidyson** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
Sorry, this is a jenkins issue. One more try:

@minikube-bot retest this please

**Comment by jimmidyson** [comment]
:+1: btw

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
There we go, running now. For some reason jenkins decided to start building this job on the Mac Mini instead of the linux host.

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by jimmidyson** [comment]
LGTM

**Comment by jimmidyson** [comment]
Noticed that this shows branch must be up to date to merge. I think it's safe to disable that in protected branches config as Travis tests PRs merged against target branch. Otherwise I can see even more merge commits as PRs are brought up to date with target branch before merging - sure none of us are keen on that.

**Comment by jimmidyson** [comment]
@dlorenc Do you think you could remove the `Merge branch 'master' into make` commit & disable the `Require branches to be up to date before merging` in protected branches?

**Comment by dlorenc** [comment]
There we go. Thanks for the pointer on how to remove that merge check.

**Comment by jimmidyson** [comment]
Nice. LGTM

**Pull request merged**
