### PR TITLE
V1.6.0 beta.2

### PR DESCRIPTION
**Pull request by r2d4**

### CODE REVIEW

**Comment by dlorenc** [comment]
Looks like all the tests failed :( Any idea what's up?

**Comment by r2d4** [comment]
Been debugging this the last day.  The apiserver and etcd aren't coming up, and the log messages aren't helpful.  

My first thought was that the upgraded etcd (3.0.14 -> 3.0.17) was the issue, however, I was able to run 1.5.3 with etcd 3.0.17 fine.  

I think the root of the problem is in the changes to the kube-apiserver options.  The struct was reorganized pretty significantly and its possible that I'm not setting it up correctly anymore.  

Additionally, etcd also fails to come up, which should be independent of the apiserver.

**Comment by dims** [comment]
@r2d4 @dlorenc : Throwing this comment here in addition to slack for the record. Server.StartAll() is never called so etcd is not even started. The reason is the if condition with `cache.WaitForCacheSync` in lines 51,52,53 https://github.com/kubernetes/kubernetes/blame/00c0c8332f33a5ff057be4f4477cd743e9e2f963/pkg/proxy/config/api.go#L51 was introduced recently. If i comment that out we do go to Server.StartAll() but other things fail. 

I believe we should setup etcd and start it, before we try to start the rest of the servers, that would help i think given when i see in the traceback:
http://pastebin.com/raw/iT01hye8

**Comment by dims** [comment]
@r2d4 @dlorenc - just starting the etcd first seems to be enough to get everything up and running (http://paste.openstack.org/show/602403/)

**Comment by r2d4** [comment]
Yep I'm gonna spend some time today starting up (and setting up) the servers in the right order.

**Comment by r2d4** [comment]
Looks like the provisioning test is the only one still failing - looking into it

`FAIL: TestFunctional/Provisioning (26.73s)`

**Comment by r2d4** [comment]
As far as I got over the weekend was that we aren't going into this conditional https://github.com/r2d4/external-storage/blob/master/lib/controller/controller.go#L390-L395

Maybe the provisioning annotations have changed slightly

**Comment by dlorenc** [comment]
> As far as I got over the weekend was that we aren't going into this conditional https://github.com/r2d4/external-storage/blob/master/lib/controller/controller.go#L390-L395

Not sure if this is helpful, but the annotation is supposed to be added by an admission controller, DefaultStorageClass.

**Comment by dlorenc** [comment]
This looks relevant: https://github.com/kubernetes/kubernetes/commit/7ae4152712e7257bb1b492118de45cd5b9db8bf8

**Comment by r2d4** [comment]
I actually commented on the PR yesterday and found a bug where one of the annotations wasn't properly promoted from beta to v1, but I don't think that was the issue.  However, the underlying issue is probably still somewhere in that PR

https://github.com/kubernetes/kubernetes/pull/40088#discussion_r105567300

**Comment by r2d4** [comment]
Linux-KVM and OSX-Virtualbox passing
Linux-Virtualbox (Persistence) and OSX-Xhyve (DNS) failing

@minikube-bot retest this please

**Comment by r2d4** [comment]
this turned into a rebase, so since all tests passed except windows i'll force push to k8s-v1.6

**Comment by r2d4** [comment]
this is now the k8s-v1.6 branch

**Pull request closed without merging**
