### PR TITLE
Use kernel 5.10 for minikube.iso.

### PR DESCRIPTION
**Pull request by eiffel-fl**
Hi.

With this PR, I jumped the kernel version in `minikube.iso` to 5.10.
Jumping the actual version of the kernel is something needed by the community (*e.g.* #10501 or #8556).
The following shows the result:
```
francis@machine:~/Codes/kinvolk/minikube-git$ minikube start --driver=kvm2 --iso-url=file://$(pwd)/out/minikube.iso                        
😄  minikube v1.23.2 sur Debian 11.1
✨  Utilisation du pilote kvm2 basé sur la configuration de l'utilisateur
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
🔥  Création de VM kvm2 (CPUs=2, Mémoire=2048MB, Disque=20000MB)...
🐳  Préparation de Kubernetes v1.22.2 sur Docker 20.10.8...
    ▪ Génération des certificats et des clés
    ▪ Démarrage du plan de contrôle ...
    ▪ Configuration des règles RBAC ...
🔎  Vérification des composants Kubernetes...
    ▪ Utilisation de l'image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Modules activés: storage-provisioner, default-storageclass
🏄  Terminé ! kubectl est maintenant configuré pour utiliser "minikube" cluster et espace de noms "default" par défaut.
francis@machine:~/Codes/kinvolk/minikube-git$ minikube ssh                                                 francis/upstream/use-kernel-5.10 % u=
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ uname -a
Linux minikube 5.10.57 #4 SMP Wed Oct 13 15:51:53 UTC 2021 x86_64 GNU/Linux
$ docker run -t --rm hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete 
Digest: sha256:37a0b92b08d4919615c3ee023f7ddb068d12b8387475d64c622ac30f45c29c51
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```
However, I would like to test it more because there are a lot of parameters and I cannot ensure everything work fine.
Also, #8187 (I gathered inspiration from this once, particularly for `CONFIG_PCI`) was removed after some tests failed to pass.

I understand this PR goes maybe in an opposite direction to [this](https://github.com/kubernetes/minikube/blob/f567893cdbb8e98a0348c1d93455af71cf6ce12c/enhancements/proposed/20201230-standard-distro/standard-distro.md) `minikube` enhancement process.
So, I am open to discussion in the hope to find a solution which suits everyone.

Best regards.

### CODE REVIEW

**Comment by eiffel-fl** [comment]
Thank you for your quick answer.

How can I use the Ubuntu based image you are talking?
Because I got the following with the default image:
```
minikube start --driver=kvm2
...
Téléchargement de l'image de démarrage de la VM...
    > minikube-v1.23.1.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.23.1.iso: 225.22 MiB / 225.22 MiB  100.00% 332.18 MiB p/s 900
...
minikube ssh 'uname -a'
Linux minikube 4.19.202 #1 SMP Thu Sep 16 17:44:03 UTC 2021 x86_64 GNU/Linux
```

**Comment by eiffel-fl** [comment]
Hi.

I am not familiar with `vagrant`, I just know it by name and know it can be used to run VM.
I will take a look to it then! Thank you for the pointers.


Best regards.

**Comment by kakkoyun** [comment]
@eiffel-fl @afbjorklund Hey, it would be amazing to have this. Any progress?

**Comment by eiffel-fl** [comment]
Hi.

@kakkoyun This is not merged for the moment, but I am using this image (plus some options) as my daily minikube image.
If you want to use it, you can clone `https://github.com/kinvolk/minikube.git` and jump on branch `francis/upstream/use-kernel-5.10` (there are others branches based on 5.10 kernel with specific `CONFIG_` enabled).
Then run the following to build the iso:

```bash
make buildroot-image
make out/minikube.iso
```

Please be patient because this process involves [buildroot](https://buildroot.org/) which fetches all the software sources present in the image and compiles them on your machine, so it can take time (half a day depending on your machine, I would advise you to run it during the night or weekend).
The final instruction executed by the `Makefile` should be:

```bash
mv ./out/buildroot/output/images/rootfs.iso9660 ./out/minikube.iso
```

You should normally end with the image in `out/minikube.iso`, just use it like this:

```bash
minikube start --driver kvm --iso-url=file://$(pwd)/out/minikube.iso
# To test if kernel 5.10 is used, test the following:
minikube ssh 'uname -r'
5.10.57
```

If `5.10.57` is printed, you are all good and using kernel 5.10 as minikube kernel!
Please, do not use this in production, as I cannot guarantee it is bugless and OK regarding security.

Best regards.

**Comment by eiffel-fl** [comment]
@k8s-ci-robot Please, add back the "cncf-cla: yes" flag because I already signed this document.

**Comment by kakkoyun** [comment]
Hey @eiffel-fl, I'm trying to build an image on https://github.com/kinvolk/minikube/commit/686450fe392ead176710c7f1cdcb4b7b648e59fb and it's failing with the following error:
```
Failed to generate BTF for vmlinux
Try to disable CONFIG_DEBUG_INFO_BTF
make[3]: *** [vmlinux] Error 1
Makefile:1179: recipe for target 'vmlinux' failed
make[3]: Leaving directory '/mnt/out/buildroot/output/build/linux-5.10.57'
make[2]: *** [/mnt/out/buildroot/output/build/linux-5.10.57/.stamp_built] Error 2
package/pkg-generic.mk:247: recipe for target '/mnt/out/buildroot/output/build/linux-5.10.57/.stamp_built' failed
make[2]: Leaving directory '/mnt/out/buildroot'
make[1]: *** [minikube_iso] Error 2
Makefile:286: recipe for target 'minikube_iso' failed
make[1]: Leaving directory '/mnt'
Makefile:326: recipe for target 'out/minikube.iso' failed
make: *** [out/minikube.iso] Error 2
make: *** [Makefile:328: out/minikube.iso] Error 2
```
Do you have any pointers? I'd appreciate it.
Also, do you happen to have a prebuilt version of this image in somewhere public? It would be even more awesome to validate if things actually work for me? Happy to invest further to push this forward.

**Comment by eiffel-fl** [comment]
Hi @kakkoyun!

Your error is "normal", you want to compile with `CONFIG_DEBUG_INFO_BTF` but you need `pahole` and buildroot does not know about `pahole`.
In branch [`alban/kernel-5.10-options`](https://github.com/kinvolk/minikube/commits/alban/kernel-5.10-options), I added more commits to have a "BPF ready" kernel.
Sorry, I should have shared with you this branch sooner but I shared the "generic" one.

Regarding the image, sadly, I do not have it published "ready to use" somewhere...
As it is a big file, I do not really know where I can publish this, but I will discuss this internally!

If you have problem testing this, do not hesitate to ask for help.

Best regards.

**Comment by eiffel-fl** [comment]
@kakkoyun I uploaded the image here:
https://github.com/eiffel-fl/minikube/releases/tag/v42-prerelease

**Comment by kakkoyun** [comment]
@eiffel-fl Amazing! Thanks for the help. I'll check it out. 

And I'm looking forward to having a completely BPF enabled image in the main branch. We don't have any alternatives to `minikube` to test eBPF based programs.

Let me know if I can help in any way.

cc @afbjorklund

**Comment by eiffel-fl** [comment]
Hi @kakkoyun.

I think we are on the same wave length regarding having a "cutting-edge" BPF ready kernel in default `minikube` image.
Nonetheless, this does not depend on me and I would accept if `minikube` maintainers do not want such a feature to be included.
Also, we can still maintain such a feature somewhere.

When you would have tried the ISO, I would be happy to add a line like this to my commit message:

```
Tested-by: kakkoyun_real_name <kakkoyun_real_mail@provider.earth>
```

Best regards.

**Comment by kakkoyun** [comment]
The ISO works perfectly. I was able to load the BTF enabled eBPF program and made it work with `minikube`. I will continue further tests and let you know if anything emerges. Thanks again @eiffel-fl. Your work is much appreciated.

**Comment by eiffel-fl** [comment]
You are welcome :D
I needed to do this modification, better to publish it so it can empower the community!

**Comment by eiffel-fl** [comment]
Hi.

For people who would be interested to have a "BPF ready kernel" for `minikube`, patches to add [`pahole`](https://git.buildroot.net/buildroot/commit/?id=ddba0ef6b1e8e407c44bb1036a75aecaeb89da92) to `buildroot` were merged on Friday.
Thus, when `minikube` will update its release of `buildroot`, adding `BTF` debug info would just be matter of enabling [`CONFIG_DEBUG_INFO_BTF`](https://git.buildroot.net/buildroot/commit/?id=2da2f359dba50aafef1202edda34374d99b77a14).

Best regards.

**Comment by eiffel-fl** [comment]
Hi!

I will present this work at the [Rejekt conference](https://cfp.cloud-native.rejekts.io/cloud-native-rejekts-eu-valencia-2022/talk/T7PWMZ/).
Before writing my slides, I decided to test it again and sadly, it did not compile.

The problem comes from `sysdig` which version 0.23.1 does not compile with recent kernel, to be honst I do not know how I ws able to compile this when I first worked on it...
So, I bumped its version and add dependency to fix this problem and some others.
Note that, this problem also occurs in upstream buildroot, so a fix was sent to the [mailing list](https://lore.kernel.org/buildroot/20220407182425.194001-1-flaniel@linux.microsoft.com/T/#t).

Regarding eBPF, I rebased `alban/kernel-5.10-options` on top of this change:

```bash
$ minikube start --driver=kvm --iso-url=file:///home/francis/Codes/kinvolk/azure-minikube/minikube.iso
😄  minikube v1.23.2 sur Ubuntu 20.04
✨  Utilisation du pilote kvm2 basé sur la configuration de l'utilisateur
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
🔥  Création de VM kvm2 (CPUs=2, Mémoire=6000MB, Disque=20000MB)...
🐳  Préparation de Kubernetes v1.22.2 sur Docker 20.10.8...
    ▪ Génération des certificats et des clés
    ▪ Démarrage du plan de contrôle ...
    ▪ Configuration des règles RBAC ...
🔎  Vérification des composants Kubernetes...
    ▪ Utilisation de l'image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Modules activés: storage-provisioner, default-storageclass
🏄  Terminé ! kubectl est maintenant configuré pour utiliser "minikube" cluster et espace de noms "default" par défaut.
francis@pwmachine:~/Codes/kinvolk$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ uname -a
Linux minikube 5.10.57 #1 SMP Fri Apr 8 11:52:11 UTC 2022 x86_64 GNU/Linux
$ zcat /proc/config.gz | grep BTF
CONFIG_DEBUG_INFO_BTF=y
$ lsmod | grep vbox
vboxsf                 36864  0
vboxguest              40960  1 vboxsf
$ sudo sysdig | head  
1 12:40:30.045232000 0 container:2648ce97a633 (-1) > container json={"container":{"Mounts":[],"cpu_period":100000,"cpu_quota":0,"cpu_shares":2,"cpuset_cpu_count":0,"created_time":1649421585,"env":[],"full_id":"2648ce97a633d65b9abd16ae9028dad1eaab2e0c1dbd7e9a3b22ea1777c888c7","id":"2648ce97a633","image":"k8s.gcr.io/pause:3.5","imagedigest":"sha256:1ff6c18fbef2045af6b9c16bf034cc421a29027b800e4f9b68ae9b1cb3e9ae07","imageid":"ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459","imagerepo":"k8s.gcr.io/pause","imagetag":"3.5","ip":"0.0.0.0","is_pod_sandbox":true,"labels":{"annotation.kubeadm.kubernetes.io/etcd.advertise-client-urls":"https://192.168.39.220:2379","annotation.kubernetes.io/config.hash":"5810d034a80a963bfbd9f66fb0bf7a86","annotation.kubernetes.io/config.seen":"2022-04-08T12:39:44.650194642Z","annotation.kubernetes.io/config.source":"file","component":"etcd","io.kubernetes.container.name":"POD","io.kubernetes.docker.type":"podsandbox","io.kubernetes.pod.name":"etcd-minikube","io.kubernetes.pod.namespace":"kube-system","io.kubernetes.pod.uid":"5810d034a80a963bfbd9f66fb0bf7a86","tier":"control-plane"},"lookup_state":1,"memory_limit":0,"metadata_deadline":0,"name":"k8s_POD_etcd-minikube_kube-system_5810d034a80a963bfbd9f66fb0bf7a86_0","port_mappings":[],"privileged":false,"swap_limit":0,"type":0}}
...
```

I will publish the eBPF ready image and update this comment with a link.

Regarding the contribution itself, is it possible to get some feedback from maintainers (ping @sharifelgamal)?
I saw there are some projects to use kernel 5.15 to port `minikube` to arm, so we can maybe help each other?


Best regards!

**Comment by afbjorklund** [comment]
We will do a kernel upgrade as part of the Buildroot 2022.02.x OS upgrade, but the plan was to complete the UEFI (and ARM) work first

**Comment by eiffel-fl** [comment]
> We will do a kernel upgrade as part of the Buildroot 2022.02.x OS upgrade, but the plan was to complete the UEFI (and ARM) work first

Thank you for your quick answer!
I will take a look to UEFI and arm port.
When you will do the OS upgrade, feel free to ping me to get tests, reviews, codes, etc.

**Comment by afbjorklund** [comment]
> When you will do the OS upgrade, feel free to ping me to get tests, reviews, codes, etc.

This will probably not happen until after the release of Ubuntu 22.04 LTS, but that's soon too.

Haven't decided on which kernel to use for Buildroot, it does support all the long-term ones...

Ubuntu | Linux
--- | ---
18.04 LTS | 4.15
19.04 | 5.0
20.04 LTS | 5.4 lts
21.04 | 5.11
22.04 LTS | 5.15 lts

The available ones in Buildroot are all the long term support releases, from 4.19 up to 5.15

```
# From https://www.kernel.org/pub/linux/kernel/v5.x/sha256sums.asc
sha256  cca7d6e053e33f44af1b39f7becec73a387911d81ede5a84ecf671692533138f  linux-5.16.16.tar.xz
sha256  254ea2fe08f0aa07e4f7fffe95d12463df7fa6ff8a9ba72f321da15e50fa7132  linux-5.15.30.tar.xz
sha256  c467c3077946370fb26c9277313b601d6c48bb557abc889f4892caf627fcdfea  linux-5.10.107.tar.xz
sha256  61f7cd24cb8a38d41891d9066c1dfd14a688a9dff7f485922e385654ea8b39b9  linux-5.4.186.tar.xz
# From https://www.kernel.org/pub/linux/kernel/v4.x/sha256sums.asc
sha256  35017bb40b604e0b577fc2b87e727632b46608a2ba3a4f5858b9177f58f376b3  linux-4.4.302.tar.xz
sha256  47470f83aa64e0098830a53176c959740742973663fead7ca7cc7b84e1f9d0f7  linux-4.9.307.tar.xz
sha256  9b6178099cf33c534c971f3f065c0debe92788f0f504d54badb2f8c2ee089d69  linux-4.14.272.tar.xz
sha256  530c5ac848111bbf7d1ad407a4ce8173ef8f9a4554477a32c695c5a4eaf02598  linux-4.19.235.tar.xz
```

**Comment by eiffel-fl** [comment]
At the time of this writing, the default version of buildroot is [5.15.3](https://github.com/buildroot/buildroot/blob/1fe5029122c8d6aba0194d6b9b0ddcd1fde2ee8d/linux/Config.in#L128).
Also, I tried to upstream as much as possible the [fix](https://marc.info/?l=buildroot&m=164935627001286&w=2) I proposed here.
So, bumping buildroot to "latest" version and using kernel 5.15 should not add a lot of extra work.

**Comment by afbjorklund** [comment]
Latest **LTS**, was the idea (as usual).

We back-revved the kernel to 2019.02.x

**Comment by eiffel-fl** [comment]
Hi.

I rebased the PR to remove the conclift regarding falco.
The updated image is available [here](https://github.com/eiffel-fl/minikube/releases/download/v42-prerelease/minikube.iso).
Note that, upstreaming of falco/sysdig is [in progress](https://marc.info/?l=buildroot&m=165090502310913&w=1).

Best regards.

P.S.: If you want to come at [Rejekt conference](https://cloud-native.rejekts.io/) here is a discount code: Rejekts_SpeakerGuestEU2022

**Comment by javierhonduco** [comment]
Thanks so much for working on this!! Very excited about the very necessary kernel upgrade as well as the arm image!

**Comment by afbjorklund** [comment]
> Note that, upstreaming of falco/sysdig is [in progress](https://marc.info/?l=buildroot&m=165090502310913&w=1).

Sounds great, minikube really should to try upstream some of the packages as well.

Currently many are just either forks of system packages or downloads of vendor binaries.

But some are actually useful, and should be available to everyone in the upstream distribution.

**Comment by eiffel-fl** [comment]
Hi.


As promised, I uploaded the image [here](https://github.com/eiffel-fl/minikube/releases/tag/v42-prerelease):
* `minikube.iso` is the amd64 eBPF ready 5.10 image.
* `minikube-arm64` is the arm64 eBPF ready 5.10 image.


Best regards.

**Comment by sharifelgamal** [comment]
Hey @eiffel-fl, thanks for all the work on this! I'd love to test this out, but we need you to sign the CLA before any testing can get underway.

**Comment by spowelljr** [comment]
> Hey @eiffel-fl, thanks for all the work on this! I'd love to test this out, but we need you to sign the CLA before any testing can get underway.

It looks like one of your commits has a separate user (probably just from another computer), if you fix up that commit that should fix the CLA

https://github.com/kubernetes/minikube/pull/12707/commits/86359a037d1922f899abb09861896d4c020d4fdf

**Comment by sharifelgamal** [comment]
Ah, looks like our bot doesn't have access to push to this PR, which is totally fine.

Could you run
```
sed -i 's/ISO_VERSION ?= .*/ISO_VERSION ?= v1.26.0-1654280115-12707/' Makefile
sed -i 's|isoBucket := .*|isoBucket := "minikube-builds/iso/12707"|' pkg/minikube/download/iso.go
```

and push up the changes? That way we can run our test suites with your ISOs.

**Comment by eiffel-fl** [comment]
It seems some tests are not passing, is there a way for me to run the test locally it would be easier to debug them?

**Comment by sharifelgamal** [comment]
Truthfully, a lot of our tests are flaky (and some just outright fail), it's something we're working on but is definitely an issue. This test run actually looks quite good comparatively. Since your change only affects the VM ISO, the docker driver test failures are entirely unrelated. I apologize for the confusion this causes.

If you'd still like to run the tests locally, you can run 

```
env TEST_ARGS='-minikube-start-args=--driver=kvm' make integration 
```

and you can supply any go test argument in that test arg env var, e.g. `-test.run TestFunctional`. 

With the change I asked to make above, your ISO is the default ISO to run minikube against, so that's easy. We're actually going to keep it that way when we merge.

If you're comfortable having this merged, (and so is @afbjorklund), we'll do so today.

**Comment by sharifelgamal** [comment]
If you're talking about 

```
05:54:14 E0608 12:54:15.341885    7971 cert_rotation.go:168] key failed with : open /home/jenkins/minikube-integration/linux-amd64-kvm2--master-4282-454816a908381ccb58510a3f451030729acc1aa8/.minikube/profiles/old-k8s-version-20220608124631-7971/client.crt: no such file or directory
```

then don't worry about it. It has something to with cert rotation in our tests and it's completely harmless, just annoying since it clogs up the logs.

**Review by sharifelgamal — APPROVED** [review]
This change looks good to me. Thanks again for sticking with this!

**Comment by eiffel-fl** [comment]
Hi!


Thank you for the approval!
<details>
  <summary>Just for information, here are the failed tests when I ran them on my machine:</summary>
  
```bash
francis@pwmachine:~/Codes/kinvolk/minikube-git$ grep 'FAIL:' out/testout_c0a0f4542.txt
--- FAIL: TestAddons (43.66s)
    --- FAIL: TestAddons/Setup (42.73s)
--- FAIL: TestErrorSpam (45.71s)
    --- FAIL: TestErrorSpam/setup (30.69s)
--- FAIL: TestFunctional (139.45s)
    --- FAIL: TestFunctional/serial (87.83s)
        --- FAIL: TestFunctional/serial/CopySyncFile (0.00s)
        --- FAIL: TestFunctional/serial/StartWithProxy (47.83s)
        --- FAIL: TestFunctional/serial/MinikubeKubectlCmdDirectly (0.95s)
        --- FAIL: TestFunctional/serial/LogsCmd (0.71s)
        --- FAIL: TestFunctional/serial/LogsFileCmd (0.70s)
    --- FAIL: TestFunctional/parallel (0.00s)
        --- FAIL: TestFunctional/parallel/ConfigCmd (0.24s)
        --- FAIL: TestFunctional/parallel/MountCmd (3.35s)
            --- FAIL: TestFunctional/parallel/MountCmd/any-port (1.84s)
            --- FAIL: TestFunctional/parallel/MountCmd/specific-port (1.50s)
        --- FAIL: TestFunctional/parallel/FileSync (1.26s)
        --- FAIL: TestFunctional/parallel/PersistentVolumeClaim (6.26s)
        --- FAIL: TestFunctional/parallel/CertSync (2.26s)
        --- FAIL: TestFunctional/parallel/CpCmd (0.54s)
        --- FAIL: TestFunctional/parallel/UpdateContextCmd (0.00s)
            --- FAIL: TestFunctional/parallel/UpdateContextCmd/no_changes (0.07s)
            --- FAIL: TestFunctional/parallel/UpdateContextCmd/no_clusters (0.07s)
            --- FAIL: TestFunctional/parallel/UpdateContextCmd/no_minikube_cluster (0.06s)
        --- FAIL: TestFunctional/parallel/MySQL (1.37s)
        --- FAIL: TestFunctional/parallel/ImageCommands (12.94s)
            --- FAIL: TestFunctional/parallel/ImageCommands/ImageBuild (0.45s)
--- FAIL: TestIngressAddonLegacy (667.98s)
    --- FAIL: TestIngressAddonLegacy/serial (581.08s)
        --- FAIL: TestIngressAddonLegacy/serial/ValidateIngressAddons (554.34s)
--- FAIL: TestErrorJSONOutput (0.17s)
--- FAIL: TestMultiNode (491.63s)
    --- FAIL: TestMultiNode/serial (488.87s)
        --- FAIL: TestMultiNode/serial/DeployApp2Nodes (1.74s)
        --- FAIL: TestMultiNode/serial/PingHostFrom2Pods (1.34s)
        --- FAIL: TestMultiNode/serial/CopyFile (6.01s)
--- FAIL: TestSkaffold (40.97s)
--- FAIL: TestKVMDriverInstallOrUpdate (0.00s)
--- FAIL: TestCertExpiration (257.26s)
--- FAIL: TestStartStop (2631.35s)
    --- FAIL: TestStartStop/group (0.00s)
        --- FAIL: TestStartStop/group/no-preload (495.62s)
            --- FAIL: TestStartStop/group/no-preload/serial (495.48s)
                --- FAIL: TestStartStop/group/no-preload/serial/DeployApp (2.12s)
        --- FAIL: TestStartStop/group/embed-certs (450.46s)
            --- FAIL: TestStartStop/group/embed-certs/serial (450.29s)
                --- FAIL: TestStartStop/group/embed-certs/serial/DeployApp (2.31s)
        --- FAIL: TestStartStop/group/old-k8s-version (568.11s)
            --- FAIL: TestStartStop/group/old-k8s-version/serial (567.96s)
                --- FAIL: TestStartStop/group/old-k8s-version/serial/DeployApp (2.08s)
        --- FAIL: TestStartStop/group/default-k8s-different-port (459.77s)
            --- FAIL: TestStartStop/group/default-k8s-different-port/serial (459.61s)
                --- FAIL: TestStartStop/group/default-k8s-different-port/serial/DeployApp (2.13s)
--- FAIL: TestNetworkPlugins (2685.92s)
    --- FAIL: TestNetworkPlugins/group (0.00s)
        --- FAIL: TestNetworkPlugins/group/auto (1851.77s)
            --- FAIL: TestNetworkPlugins/group/auto/NetCatPod (1800.28s)
        --- FAIL: TestNetworkPlugins/group/custom-flannel (0.18s)
            --- FAIL: TestNetworkPlugins/group/custom-flannel/Start (0.00s)
        --- FAIL: TestNetworkPlugins/group/false (0.18s)
            --- FAIL: TestNetworkPlugins/group/false/Start (0.00s)
        --- FAIL: TestNetworkPlugins/group/enable-default-cni (0.18s)
            --- FAIL: TestNetworkPlugins/group/enable-default-cni/Start (0.00s)
        --- FAIL: TestNetworkPlugins/group/flannel (0.20s)
            --- FAIL: TestNetworkPlugins/group/flannel/Start (0.00s)
        --- FAIL: TestNetworkPlugins/group/bridge (0.18s)
            --- FAIL: TestNetworkPlugins/group/bridge/Start (0.00s)
        --- FAIL: TestNetworkPlugins/group/kubenet (0.18s)
            --- FAIL: TestNetworkPlugins/group/kubenet/Start (0.00s)
        --- FAIL: TestNetworkPlugins/group/kindnet (1874.34s)
            --- FAIL: TestNetworkPlugins/group/kindnet/NetCatPod (1800.31s)
        --- FAIL: TestNetworkPlugins/group/calico (1906.93s)
            --- FAIL: TestNetworkPlugins/group/calico/NetCatPod (1800.33s)
        --- FAIL: TestNetworkPlugins/group/cilium (1929.92s)
            --- FAIL: TestNetworkPlugins/group/cilium/NetCatPod (1800.71s)
```
  
</details>

Best regards.

**Comment by eiffel-fl** [comment]
Thank you a lot for the merge :D

**Pull request merged**
