### PR TITLE
Added flag to allow the number of CPU's to be specified

### PR DESCRIPTION
**Pull request by stevesloka**
Allows the number of CPU's to be specified as command line argument. Happy to discuss naming and change around.

//cc @philips (Saw you had a TODO on this as well)

### CODE REVIEW

**Comment by dlorenc** [comment]
Thanks @stevesloka! This looks great. I'm in the middle of cutting the 0.4.0 release now, do you mind if I merge this after that goes out?

**Comment by stevesloka** [comment]
Yup no problem @dlorenc don't let this hold up the release unless you think it's helpful to include.

**Comment by dlorenc** [comment]
Sorry, I think you'll have to regen the help text to fix a merge conflict now.

**Comment by stevesloka** [comment]
Ok I redid the docs and also rebased in my 2 commits into a single.

**Comment by dlorenc** [comment]
LGTM.  Thanks!

**Pull request merged**
