### PR TITLE
download.Binary: Mock downloads for testing

### LINKED ISSUE #6751: Running unit tests downloads kubernetes binaries
It would be nice if `TestCacheBinariesForBootstrapper` could mock the actual downloads...

 Downloading the `v1.16.0` can take a long time, and wastes space in the minikube cache.

`--- PASS: TestCacheBinariesForBootstrapper (183.97s)`

`418M	/home/anders/.minikube/cache/v1.16.0/`

### PR DESCRIPTION
**Pull request by nkprince007**
fixes #6751

### CODE REVIEW

**Comment by tstromberg** [comment]
Something is weird about the checksum URL being generated in this PR:

`https://storage.googleapis.com/kubernetes-release/release/v1.11.10/bin/linux/amd64/kubeadm?checksum=file:https://stora
ge.googleapis.com/kubernetes-release/release/v1.11.10/bin/linux/amd64/kubeadm.sha1`

**Comment by nkprince007** [comment]
> I appreciate the clarity of this solution, but don't love that it leaks the implementation detail of go-getter being used underneath.
> 
> What do you think about an alternative approach like the downloads package having a `downloads.Getter`:
> 
> ```
> var (
>   Getter = getter.FileGetter{}
>   FileGetter = getter.FileGetter{}
>   MockGetter = getter.MockGetter{}
> )
> ```
> 
> then tests can set: `download.Getter = download.MockGetter`
> 
> The advantages I see are:
> 
>     * This would now mock out all types of downloads (ISO, Binaries, Preload)
> 
>     * Callers won't have to know about getters
> 
> 
> The disadvantages I see are:
> 
>     * Global state can be confusing if tests are run in parallel (we currently don't do this)
> 
>     * Introduces a public package variable
> 
> 
> It's unlikely that unit tests will be toggling back between getters, however.
> 
> Thoughts?

Global state is a point of concern though.

**Comment by tstromberg** [comment]
Seems reasonable. Go ahead and rebase, but remove the uri.Parse bit. It doesn't seem to be doing the right thing with the URL in this case.

**Comment by nkprince007** [comment]
Alright, I'll update it :)

**Comment by nkprince007** [comment]
> Seems reasonable. Go ahead and rebase, but remove the uri.Parse bit. It doesn't seem to be doing the right thing with the URL in this case.

@tstromberg, `Get` function requires a `*url.URL` parameter.

**Comment by tstromberg** [comment]
PR is still broken:

```
# k8s.io/minikube/pkg/minikube/download
pkg/minikube/download/binary.go:76:23: cannot use url (type string) as type *url.URL in argument to gtr.GetFile
```

**Comment by tstromberg** [comment]
Closing until this PR can be revisited. Please re-open it when it's ready for review again.

**Pull request closed without merging**
