### PR TITLE
Add new VMware unified driver to supported list

### PR DESCRIPTION
**Pull request by frapposelli**
This PR adds the new VMware unified driver to the supported list, the driver now supports Fusion *and* Workstation across Windows, Linux and macOS.

A deprecation note has been added for the bundled `vmwarefusion` driver.

Ref: #2118 #2526 machine-drivers/discussion#5 machine-drivers/docker-machine-driver-vmware#1

Fixes: machine-drivers/docker-machine-driver-vmware#1 #2118

### CODE REVIEW

**Comment by dlorenc** [comment]
We shouldn't really add this to an officially supported list until we get automated integration testing for it.

@minikube-bot OK to test

**Comment by frapposelli** [comment]
@dlorenc we’re working on getting a CI environment to test integration under the driver repo.

**Comment by gbraad** [comment]
@frapposelli glad to hear about that last part... :-D

**Comment by frapposelli** [comment]
@dlorenc @gbraad it’s going to take some time to have the environment provisioned, in the meantime, this driver is fixing several issues with our platforms, and extending support to Windows and Linux.

Adding support for this and deprecating the docker-machine builtin one should be a priority in order to have better supportability and timely fixes.

**Comment by dlorenc** [comment]
@frapposelli I definitely understand that, but I'm going to have to stay firm on this one. The vmware fusion driver shouldn't have been added without CI tests in the first place, and it's much harder to delete something once it's been merged in.

Once we get CI running, we can add this driver.

**Comment by gbraad** [comment]
I also understand, but have to agree with @dlorenc.

**Comment by frapposelli** [comment]
Understand, let's leave this open and I'll try to speed up with the CI infra on our side.

**Comment by dlorenc** [comment]
Any updates on getting this into the test infrastructure?

**Comment by frapposelli** [comment]
@dlorenc we’re still waiting on the capacity we requested. Shouldn’t take long

**Comment by frapposelli** [comment]
Yes, we have secured the capacity and we're working on setting up CI, this week there's Kubecon (pretty much our the entire team is here) so I would expect to have something ready by end of next week.

**Comment by fenos** [comment]
What's the progress on this?

**Comment by frapposelli** [comment]
Unfortunately the CI work was re-prioritized a few times, we’re now working to have the vSphere capacity added to the tide pool, after that is done we can run tests and merge this.

**Comment by fenos** [comment]
@frapposelli Thanks for the update! 
No worries it happens! I Can't wait for having VMWare fusion working properly on minikube, at the current state it doesn't even start a cluster on it 😭 

Keep up the great job 🎉

**Comment by smebberson** [comment]
Any news on this?

**Comment by frapposelli** [comment]
Sorry guys, this is taking a little longer than expected.

/cc @akutz FYI

**Comment by RA489** [comment]
@frapposelli This PR needs rebase.

**Comment by tstromberg** [comment]
Do you mind addressing the merge conflicts? I'd like to see about merging this if it's still viable. My apologies for the unnecessarily long delay in reviewing this PR.

**Comment by frapposelli** [comment]
@tstromberg thanks, let me look into it

**Comment by frapposelli** [comment]
@tstromberg the original fork was deleted, created #3534 as a follow up from this PR, which I'm closing

**Pull request closed without merging**
