### PR TITLE
[Addon] Update Kong Ingress Controller Addon to 2.9.x/Kong 3.2.x

### PR DESCRIPTION
**Pull request by gAmUssA**
Updated existing Kong Ingress Controller addon to the latest versions.

### CODE REVIEW

**Comment by gAmUssA** [comment]
@sharifelgamal, it's me again (Viktor from #13326 )
I updated the kong addon to the latest version. Kindly allow to test

**Comment by gAmUssA** [comment]
Also, how can I assign myself as the official maintainer of this addon?

**Comment by gAmUssA** [comment]
> Also, how can I assign myself as the official maintainer of this addon?

thanks @shaneutt for this comment. 
the reason I brought this up is when one does enable addons minikube says 

```
❱ minikube addons enable kong
❗  kong is a 3rd party addon and is not maintained or verified by minikube maintainers, enable at your own risk.
❗  kong does not currently have an associated maintainer.
```

so I would love to give some assurance that this addon is maintained.

Hope it does make sense. Thank you

**Comment by spowelljr** [comment]
Hi @gAmUssA, thanks for updating the addon!

Just a heads up that @sharifelgamal no longer actively works on the minikube project.

As for adding yourself as the maintainer for the kong addon:

https://github.com/kubernetes/minikube/blob/795b706adf130af265a0daf8ba2b2a2d5ca45d9c/pkg/minikube/assets/addons.go#L296

You can put your GitHub username in the empty string after `3rd party (Kong HQ)`.

Thanks for nominating yourself as the maintainer for the addon!

After you make the maintainer change I'll run the tests against your PR

**Comment by gAmUssA** [comment]
@spowelljr awesome, thank you! 
it's done

**Comment by gAmUssA** [comment]
are those flaky tests or something is required from me to fix it?

**Comment by spowelljr** [comment]
> are those flaky tests or something is required from me to fix it?

All the failed tests are flaky, PR looks good to me

**Comment by spowelljr** [comment]
I just tried to enable the addon on my machine (amd64 macOS) and the kong pods aren't coming up
```
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
kong          ingress-kong-668c4bd5bb-jpvcm      0/1     Running   0             2m10s
kong          proxy-kong-6dfdc945-4tmc2          0/1     Running   1 (59s ago)   2m10s
kong          proxy-kong-6dfdc945-79l7q          0/1     Running   1 (59s ago)   2m10s
```

```
  Type     Reason             Age                From               Message
  ----     ------             ----               ----               -------
  Normal   Scheduled          104s               default-scheduler  Successfully assigned kong/proxy-kong-6dfdc945-79l7q to minikube
  Normal   Pulling            104s               kubelet            Pulling image "docker.io/kong:3.2@sha256:f5f51af49fa1f5a7600e60bb51ebd760b16fd020bb16bba2b70d36a54f3d6ac8"
  Normal   Pulled             97s                kubelet            Successfully pulled image "docker.io/kong:3.2@sha256:f5f51af49fa1f5a7600e60bb51ebd760b16fd020bb16bba2b70d36a54f3d6ac8" in 7.077919212s (7.078009254s including waiting)
  Normal   Killing            64s                kubelet            Container proxy failed liveness probe, will be restarted
  Warning  FailedPreStopHook  62s                kubelet            PreStopHook failed
  Normal   Created            33s (x2 over 96s)  kubelet            Created container proxy
  Normal   Started            33s (x2 over 96s)  kubelet            Started container proxy
  Normal   Pulled             33s                kubelet            Container image "docker.io/kong:3.2@sha256:f5f51af49fa1f5a7600e60bb51ebd760b16fd020bb16bba2b70d36a54f3d6ac8" already present on machine
  Warning  Unhealthy          4s (x10 over 84s)  kubelet            Readiness probe failed: Get "http://10.244.0.2:8100/status": dial tcp 10.244.0.2:8100: connect: connection refused
  Warning  Unhealthy          4s (x6 over 84s)   kubelet            Liveness probe failed: Get "http://10.244.0.2:8100/status": dial tcp 10.244.0.2:8100: connect: connection refused
```

**Comment by spowelljr** [comment]
Looks like that resolved it:
```
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
kong          ingress-kong-668c4bd5bb-ghnds      1/1     Running   0             55s
kong          proxy-kong-6dfdc945-cq8kb          1/1     Running   0             55s
```

**Review by spowelljr — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
