### PR TITLE
docs: fix link to kubernetes 'pull-image-private-registry'

### PR DESCRIPTION
**Pull request by jpoikela**

### CODE REVIEW

**Comment by prasadkatti** [comment]
@jpoikela - Can you please sign the CLA using the instructions in the comment above?

**Comment by RA489** [comment]
/check-cla

Rest LGTM.

**Comment by jpoikela** [comment]
the CLA should be ok now.

**Comment by RA489** [comment]
> the CLA should be ok now.

/lgtm

**Comment by RA489** [comment]
> the CLA should be ok now.

/check-cla

**Comment by RA489** [comment]
@jpoikela CLA issue still exists. Do you have any issue signing CLA?

**Comment by medyagh** [comment]
@jpoikela we are still wainting for the CLA to be signed, plz make sure the CLA is signed.  https://identity.linuxfoundation.org/projects/cncf

**Pull request merged**
