### PR TITLE
README: add rkt instructions

### PR DESCRIPTION
**Pull request by s-urbaniak**

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@dlorenc I added a few instructions in the readme on how to enable rkt, PTAL.

/cc @jonboulle

**Comment by jonboulle** [comment]
LGTM

**Comment by jonboulle** [comment]
Should we have a separate issue for making this the default ISO..?

**Comment by dlorenc** [comment]
LGTM. Opened #571 to track making this default.

**Pull request merged**
