### PR TITLE
Add CIFS-utils to minikube iso

### PR DESCRIPTION
**Pull request by r2d4**

### CODE REVIEW

**Comment by r2d4** [comment]
fixes #1197

**Comment by r2d4** [comment]
@minikube-bot retest this please

**Comment by jmalobicky** [comment]
@r2d4 I loaded the iso from the build `minikube start --vm-driver=virtualbox --iso-url=https://storage.googleapis.com/minikube-builds/1198/minikube-testing.iso`

I now get the following error when running `kubectl describe pods`

```
Output: mount error: cifs filesystem not supported by the system
mount error(19): No such device
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

**Comment by r2d4** [comment]
Did you make sure to delete and start?  The iso changes won't take effect unless you minikube delete first

**Comment by jmalobicky** [comment]
Yes, I did `minikube stop` then `minikube delete` followsed by `rm -rf ~/.minikube` to ensure the environment was cleansed. I noticed that running `minikube version` didnt state that is was unstable or a something other than 0.16.0.

**Comment by jmalobicky** [comment]
I haven't dug deeper into it lately as i just used the hostPath instead. I will give it a shot though to see if it works.

**Comment by msnelling** [comment]
I imagine this will also require the CIFS kernel module instatalled? https://wiki.samba.org/index.php/LinuxCIFSKernel

**Pull request merged**
