### PR TITLE
clarify that Windows install commands are powershell-based

### PR DESCRIPTION
**Pull request by carehart**
Someone reading this line could presume it should work at the regular Windows command line (and the curl would), but of course the 2nd and 3rd lines will not.

And if someone who may approve this might want to also revise the line after step 2 here (or move to here its point about running as admin), that would of course make sense. I just didn't want to presume to do that in this simpler commit.

### CODE REVIEW

**Comment by carehart** [comment]
I believe I did just successfully sign the CLA. First-time contributor to this project.

**Review by spowelljr — CHANGES_REQUESTED** [review]
Hi @carehart, thanks for creating this PR! This looks good, the only thing is line 450 has the same string as well, could you change it there as well please, thanks!

**Review by medyagh — CHANGES_REQUESTED** [review]

**Comment by medyagh** [comment]
closing in favor of https://github.com/kubernetes/minikube/pull/12397

**Comment by spowelljr** [comment]
@carehart #12397 is merged and is now live on the site

**Pull request closed without merging**
