### PR TITLE
virtualbox: improve solution message -> ensure it is in the path #8453

### LINKED ISSUE #8453: virtualbox: improve solution message -> ensure it is in the path
**重现问题所需的命令**：
minikube start --driver=virtualbox

**失败的命令的完整输出**：<details>
😄  Debian 8.0 上的 minikube v1.11.0
✨  根据用户配置使用 virtualbox 驱动程序

❗  'virtualbox' 驱动程序报告了一个问题： /usr/bin/VBoxManage list hostinfo failed:

💡  建议：Install the latest version of VirtualBox
📘  文档：https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

💣  Failed to validate 'virtualbox' driver

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
No LSB modules are available.
Distributor ID:	Deepin
Description:	Deepin 15.5 Professional
Release:	15.5
Codename:	camel

### PR DESCRIPTION
**Pull request by Ajitesh13**
fixes #8453

### CODE REVIEW

**Comment by tstromberg** [comment]
Thank you!

**Comment by tstromberg** [comment]
BTW, you will need to sign the CLA agreement before we are allowed to merge this PR: https://git.k8s.io/community/CLA.md#the-contributor-license-agreement 

Thank you for understanding - please let me know if you need any help.

**Comment by medyagh** [comment]
@Ajitesh13  please ensure sign the CLA

**Pull request merged**
