### PR TITLE
Pass --kubernetes-version to 'kubeadm init' to avoid external HTTP request

### LINKED ISSUE #3242: Propagate HTTP proxy config into VM
**BUG REPORT**

**Minikube version** (use `minikube version`): v0.30.0
- **OS** (e.g. from /etc/os-release): Windows
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.30.0

**What happened**:
`minikube start --kubernetes-version v1.10.8 --docker-env HTTP_PROXY=xxx --docker-env HTTPS_PROXY=xxx --docker-env NO_PROXY=xxx` is failing in timeout during kubeadm command execution

```
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

.: Process exited with status 1
```
**What you expected to happen**:
minikube starts normally

**Anything else do we need to know**:
The faulty command is `kubeadm alpha phase addon kube-dns`. I replayed it inside the minikube VM to have more logs : 
```
$ sudo kubeadm alpha phase addon kube-dns
unable to get URL "https://dl.k8s.io/release/stable-1.10.txt": Get https://dl.k8s.io/release/stable-1.10.txt: dial tcp 23.236.58.218:443: getsockopt: connection timed out
```
kubeadm is trying to download a file (that actually contains the exact version of kubernetes) but since HTTP proxy settings are not set in VM (they are only set for docker engine through `--docker-env` parameters), this is failing. I found that if you add `--kubernetes-version`, no download is done and the command succeeds:
```
$ sudo kubeadm alpha phase addon kube-dns --kubernetes-version v1.10.8
[addons] Applied essential addon: kube-dns
```
So a fix could be to propagate the `--kubernetes-version` passed to `minikube start` to `kubeadm alpha phase addon kube-dns` command.

### PR DESCRIPTION
**Pull request by cvila84**
this is my proposal to fix #3242

### CODE REVIEW

**Comment by cvila84** [comment]
I signed it

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
PR looks good - I need to dig into the --vm-driver=none integration test failure before I can comfortably approve it though.

I believe the OSX integration test failures are due to a known unrelated issue: https://github.com/kubernetes/minikube/issues/3203

**Comment by cvila84** [comment]
This PR is probably covered by https://github.com/kubernetes/minikube/pull/3247 as kubeadm config file passed to kubeadm alpha command contains kubernetes version

**Comment by tstromberg** [comment]
Is this PR obsolete now that kubeadm no longer specifies an addon command?

**Pull request closed without merging**
