### PR TITLE
Add a design doc for "minikube tunnel".

### PR DESCRIPTION
**Pull request by dlorenc**
Still need to fill in more on the load balancer implementation.

Signed-off-by: dlorenc <dlorenc@google.com>

### CODE REVIEW

**Comment by r2d4** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
Updated with some more info. I think this is ready for review.

**Comment by AmazingTurtle** [comment]
@dlorenc i see you're documenting the `minikube tunnel` command, but it doesn't even exist. What's the point?

**Comment by dlorenc** [comment]
This is meant to be a design document for a command we're going to implement :)

**Comment by AmazingTurtle** [comment]
@dlorenc so can I reference this one? https://github.com/kubernetes/minikube/issues/2834
Lacking functionality for this one made me mad, that's why I opened this issue - all the other issues regarding LoadBalancer support are closed...

**Pull request closed without merging**
