### PR TITLE
Upgrade Headlamp version to 0.15.0

### PR DESCRIPTION
**Pull request by joaquimrocha**
Upgrade Headlamp version to 0.15.0
  cc: @yolossn

### CODE REVIEW

**Comment by joaquimrocha** [comment]
We've had some issues related to having migrated the org where we had `headlamp` (from `kinvolk` to `headlamp-k8s`).
It should be good to test now. Sorry for the inconvenience.

**Review by spowelljr — CHANGES_REQUESTED** [review]
The image is not able to be pulled
```
Warning  Failed     6m31s (x4 over 8m)      kubelet            Failed to pull image "ghcr.io/headlamp-k8s/headlamp:v0.15.0@sha256:a797a472cb8133e543b7bcacd255500ae37357d11fe5c99a2e54c3f882a3d9fc": rpc error: code = Unknown desc = Error response from daemon: Get "https://ghcr.io/v2/headlamp-k8s/headlamp/manifests/sha256:a797a472cb8133e543b7bcacd255500ae37357d11fe5c99a2e54c3f882a3d9fc": unauthorized
```

**Comment by joaquimrocha** [comment]
Closing since we have a new bug fix version coming (0.15.1 already released, PR coming soon).

**Pull request closed without merging**
