### PR TITLE
K8s v1.9.4

### PR DESCRIPTION
**Pull request by PeterSun15629150864**

### CODE REVIEW

**Comment by dlorenc** [comment]
This would ahve to essentially be a 0.25.2 release, but minikube is currently at 0.27.0.

Is there a reason you can't upgrade to 27.0, which uses a k8s 1.10 build?

**Comment by secat** [comment]
@dlorenc on my side, I am working on windows 10 using virtualbox and there is the following issues open: https://github.com/kubernetes/minikube/issues/2818
-

**Comment by dlorenc** [comment]
I think I'm still missing the goal here. You can already use any version of kubernetes (well, most of them) with any version of minikube using the --kubernetes-version flag. Why doesn't that work for your use case?

**Comment by dlorenc** [comment]
I'm going to close this for now. Please open up an issue if you'd like with more detailed use-cases.

**Pull request closed without merging**
