### PR TITLE
Add addon support for portainer

### PR DESCRIPTION
**Pull request by balasu**
Portainer is a free, open source toolset for managing containerized applications. It works with Kubernetes, Docker, Docker Swarm, Azure ACI in both data centres and at the edge.

Portainer removes the complexity associated with orchestrators so developers can deploy apps quickly, easily and accurately. In addition to managing apps, it can be used to observe the behavior of containers, manage the underlying platform and provide the security and governance necessary for organization to deploy containers widely.
This add-on service will be enabled on nodeport 30777 and internally runs on 9000 port.

### CODE REVIEW

**Comment by sharifelgamal** [comment]
Hi there! Thanks for contributing to minikube! Can you explain what the portainer addon is for in your PR description?

You will also need to sign the CLA before we go forward with testing.

**Comment by balasu** [comment]
> 
> 
> Hi there! Thanks for contributing to minikube! Can you explain what the portainer addon is for in your PR description?
> 
> You will also need to sign the CLA before we go forward with testing.
Hi Description is included and CLA is signed

**Comment by ncresswell** [comment]
Hi, please note i have signed the CLA for Portainer.io and Bala is a nominated member of our Org.

**Comment by andriyDev** [comment]
Is your org the maintainer of the images being used? If so, can you add your org's name in the string after the addon name?

**Comment by balasu** [comment]
> 
> 
> Is your org the maintainer of the images being used? If so, can you add your org's name in the string after the addon name?

Hi updated organization name,  its pulling latest image from  dockerhub repo and image update is maintained by portainer. users can raise the  issues  or queries related to add-on on portainer github or portainer community slack
https://github.com/portainer/portainer/issues

**Pull request merged**
