### PR TITLE
Fix the addons_test to work with xhyve.

### PR DESCRIPTION
**Pull request by dlorenc**
When you run with the xhyve driver, the addon-manager has a different
name.

### CODE REVIEW

**Comment by jimmidyson** [comment]
That's interesting. I'm not sure I understand why it would have a different name?

**Comment by dlorenc** [comment]
The machine hostname is set to boot2docker when run inside xhyve for some reason. The pod comes up with:

kube-addon-mnanager-boot2docker
instead of:
kube-addon-manager-minikubevm

**Comment by jimmidyson** [comment]
Ah interesting. Wonder if that is a bug in xhyve driver or in our use of it?

**Comment by jimmidyson** [comment]
https://github.com/zchee/docker-machine-driver-xhyve/issues/114

**Comment by dlorenc** [comment]
Ah, nice find.

**Comment by dlorenc** [comment]
Any concerns with getting this in until we get get the fix in upstream? I sent another fix that hasn't seen any movement on that repo: https://github.com/zchee/docker-machine-driver-xhyve/pull/127

So it might take a little while.

**Comment by jimmidyson** [comment]
:+1:

**Pull request merged**
