### PR TITLE
Enable kernel support for transparent huge pages with madvise fixes #5765

### LINKED ISSUE #5765: run containers that need madvise enabled to inspect transparent huge pages availability status
**The exact command to reproduce the issue**:
```
minikube ssh
docker pull pull cambridgesemantics/anzograph:latest
docker run -d -p 443:8443 -p 80:8080 -p 5600:5600 -p 5700:5700 cambridgesemantics/anzograph:latestdocker run -d -p 443:8443 -p 80:8080 -p 5600:5600 -p 5700:5700 cambridgesemantics/anzograph:latest
docker logs anzo
```
**The full output of the command that failed**:<details>
(...)
2019-10-29 13:38:06.771723Z: [37:56] cmd: /opt/anzograph/bin/azg -node 0 -time 625671486 -errpipe /tmp/sbxbooterr.np0 -internal /opt/anzograph/internal -pidfile /tmp/azgpids.log
2019-10-29 13:38:06.806463Z: [37:41]
  -----------------------------------------------
  error:     Database did not start
             System error. Contact Cambridge Semantics Support. Reference: startup: Process did not succeed - System error. Contact Cambridge Semantics Support. Reference: 0 == madvise(base, acquireSize_, MADV_ACQUIRE): Invalid argument
  code:      1029
  entity:    detected startup failed
  location:  quiet_dbstart() in gsysmgrd.cpp:854
  time:      625671486806341
  pid:       37
  thread:    56
  -----------------------------------------------
(...)

a fully grown kernel will offer
/sys/kernel/mm/transparent_hugepage/enabled
```
[always] madvise never
```

applications use the madvise function to figure out what the kernel is set to do.

see
http://man7.org/linux/man-pages/man2/madvise.2.html
```
MADV_HUGEPAGE (since Linux 2.6.38)
              Enable Transparent Huge Pages (THP) for pages in the range
              specified by addr and length.  Currently, Transparent Huge
              Pages work only with private anonymous pages (see mmap(2)).
              The kernel will regularly scan the areas marked as huge page
              candidates to replace them with huge pages.  The kernel will
              also allocate huge pages directly when the region is naturally
              aligned to the huge page size (see posix_memalign(2)).

              This feature is primarily aimed at applications that use large
              mappings of data and access large regions of that memory at a
              time (e.g., virtualization systems such as QEMU).  It can very
              easily waste memory (e.g., a 2 MB mapping that only ever
              accesses 1 byte will result in 2 MB of wired memory instead of
              one 4 KB page).  See the Linux kernel source file
              Documentation/admin-guide/mm/transhuge.rst for more details.

              The MADV_HUGEPAGE and MADV_NOHUGEPAGE operations are available
              only if the kernel was configured with
              CONFIG_TRANSPARENT_HUGEPAGE.
```

I understand that you configure the kernel support here:
https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig

macOS 1.15 (Catalina)
minikube version: v0.28.2
VMware fusion 8 or VirtualBox (does not matter)

```
minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.144.214
```
```
minikube config view
- vm-driver: vmwarefusion
- WantReportError: true
- memory: 16384
```
I attach the minikube logs as well, but the issues in there are related to k8s .. this is a kernel issue
[minikube.log](https://github.com/kubernetes/minikube/files/3783874/minikube.log)

would you consider to support madvise?

### PR DESCRIPTION
**Pull request by schwichtgit**
After this PR the kernel supports

``cat /sys/kernel/mm/transparent_hugepage/enabled``
```always [madvise] never```

### CODE REVIEW

**Comment by schwichtgit** [comment]
I signed it

**Comment by tstromberg** [comment]
Please ensure that the e-mail used for your CLA matches the e-mail used for your GitHub ID.

/ok-to-test

**Comment by schwichtgit** [comment]
> Please ensure that the e-mail used for your CLA matches the e-mail used for your GitHub ID.
@tstromberg  could you please try to validate the CLA one more time?
I signed my company and obviously used my  company email for that, my github account had that email as secondary. I swapped github primary/secondary email. I hope the CLA check works now.

**Comment by schwichtgit** [comment]
I signed it

I am still not sure why the CLA could not be verified.

**Pull request merged**
