### PR TITLE
Update Makefile for version 1.4.1

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
I hate this PR, let's open a new identical one and that will hopefully have less terrible CI.

**Pull request closed without merging**
