### PR TITLE
Revert "Warn if hyperkit version is old"

### PR DESCRIPTION
**Pull request by medyagh**
Reverts kubernetes/minikube#4691

### CODE REVIEW

**Comment by sharifelgamal** [comment]
This seems to be making our Travis CI flaky.

**Comment by josedonizetti** [comment]
@medyagh do you have the URL for one of those failing builds? I can look into it.

**Comment by medyagh** [comment]
> @medyagh do you have the URL for one of those failing builds? I can look into it.

https://travis-ci.org/kubernetes/minikube/jobs/562334274

**Comment by medyagh** [comment]
it doesn't seem to be related to your PR at all, it seems to be about  golangci-lint
we might not need to do this rervert

```

goroutine 13461 [runnable]:
github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll.func1(0xc0b3ad3ea0)
	/home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:290
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker.execAll
	/home/travis/gopath/src/github.com/golangci/golangci-lint/pkg/golinters/goanalysis/checker/checker.go:297 +0x11b
```

**Comment by medyagh** [comment]
I wonder if updating travis to use latest golang would fix it

**Comment by josedonizetti** [comment]
`make lint` run fine locally. Do you think was a bad build only? Maybe running it again it will be fine?

**Pull request closed without merging**
