### PR TITLE
Reset all secrets during cluster startup.

### LINKED ISSUE #288: minikube dashboard doesn't display in browser
I installed minikube version: v0.5.0 yesterday.  

when I type ```minikube dashboard``` it starts a browser tab as expected at http://192.168.99.100:30000/

however, the dashboard just hangs and nothing displays.

any ideas?

thanks

### PR DESCRIPTION
**Pull request by dlorenc**
Fixes #288

### CODE REVIEW

**Comment by jimmidyson** [comment]
Not sure this is very safe tbh. What if they are custom secrets containing token named data?

Wonder if there's a way to reuse private key when regenerating certs instead? Would that keep the secret data valid as signed with same private key? Not sure if that would be enough.

**Comment by dlorenc** [comment]
I understand the concern, but it should be safe since we restrict the deletions to the kube-system namespace. Although I think I can make it even safer with a label query that goes over only service account secrets.

**Comment by jimmidyson** [comment]
I think reusing the private key may work - is that worth investigating?

If you go down this route then won't you need to do the same for all namespaces, not just kube-system? Lots of apps use service accounts to authenticate to API server.

**Comment by dlorenc** [comment]
Ah I think I see what you mean about reusing the private key. I'll give that a try.

You're also right that I got the query wrong. This approach should only be querying over service account secrets. This should also be safe since the token controller takes full control over their lifecycle.

But reusing the secret seems better if I can get it to work.

**Comment by jimmidyson** [comment]
Thinking about this a bit more this should be virtually equivalent to renewing the API server certificate which I hope wouldn't mean regenerating all service account tokens. In order to do this I reckon we will probably need a long-lived CA certificate, with e.g. CN=minikubeCA, that is used to issue the API server certificate. That will mean we won't need to redistribute the API server certificate as clients will be able to validate the server certificate by using the CA certificate.

**Pull request closed without merging**
