### PR TITLE
install losetup from util-linux in the ISO to enable support for VolumeMode=Block PVCs

### PR DESCRIPTION
**Pull request by nixpanic**
The losetup tool is used by Kubernetes to setup BlockMode volumes.
BusyBox provides a version, but it does not have the `-j` option.

This was approved and merged earlier through #10255, until #10286 reverted it for unclear reasons.

Fixes: #8284 (again)

### CODE REVIEW

**Comment by sharifelgamal** [comment]
@nixpanic, can you rebase against upstream? Once you do, we can properly run our iso tests.

**Comment by nixpanic** [comment]
> @nixpanic, can you rebase against upstream? Once you do, we can properly run our iso tests.

Done, thanks.

**Comment by medyagh** [comment]
ok-to-build-iso

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
thank you @nixpanic  this will be included on the next release meanwhile feel free to use the latest binary on the head 

https://storage.googleapis.com/minikube/latest/minikube-linux-amd64
https://storage.googleapis.com/minikube-builds/master/minikube-linux-amd64

**Pull request merged**
