### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by x1wins**
Changed yml to yaml
Added -p multinode-demo

### CODE REVIEW

**Comment by x1wins** [comment]
i just fixed typo with added a few character.
it's not need travis for build.

**Comment by priyawadhwa** [comment]
Hey @x1wins could you please follow the instructions in this [comment](https://github.com/kubernetes/minikube/pull/9004#issuecomment-674312195) to sign the CLA? It's required for merge

**Comment by x1wins** [comment]
> Hey @x1wins could you please follow the instructions in this [comment](https://github.com/kubernetes/minikube/pull/9004#issuecomment-674312195) to sign the CLA? It's required for merge

hi
i did received email of 'CNCF Individual Contributor License Agreement - Signature requested by Linux Foundation E-Signing'
and i did sign just now
and then shoud i waiting for merge?

**Comment by priyawadhwa** [comment]
Thank @x1wins !

**Pull request merged**
