### PR TITLE
Add parallels machine driver to supported list

### PR DESCRIPTION
**Pull request by bassam**
This adds support for parallels [machine driver](https://github.com/machine-drivers/docker-machine-parallels).

It still needs CI tests. Can someone please point me in the right direction to add those?

Ref #2756 and #2606

### CODE REVIEW

**Comment by bassam** [comment]
Hi, we're happy to drive CI changes to enable this support. Can someone please point us in the right direction?

**Comment by dlorenc** [comment]
@praveenkumar where should the CI for this live?

**Comment by praveenkumar** [comment]
@dlorenc The driver changes CI should live to drivers repo and once we have that than minikube should have driver test as part of CI test like it has for hyperkit / virtualbox ..etc.

**Comment by bassam** [comment]
@praveenkumar so I should add a file similar to https://github.com/kubernetes/minikube/blob/master/hack/jenkins/osx_integration_tests_hyperkit.sh?

**Comment by dlorenc** [comment]
> @dlorenc The driver changes CI should live to drivers repo and once we have that than minikube should have driver test as part of CI test like it has for hyperkit / virtualbox ..etc.

SGTM. @bassam I think @praveenkumar is saying the driver changes from this PR should be reverted and moved to a repo in the drivers org. Does that make sense?

**Comment by bassam** [comment]
@dlorenc the parallels driver itself is in github.com/machine-drivers/docker-machine-parallels. The only changes in this repo is enabling minikube to use it just like virtualbox, etc.

**Comment by bassam** [comment]
@dlorenc ping.

**Comment by gbraad** [comment]
It should be enabled like the VMware workstation driver as developed by
@anfernee

**Comment by bassam** [comment]
@gbraad thanks. I believe I've followed the same model as @anfernee VMware fusion implementation. I'd appreciate it if someone can take a deeper look at the changes and let me know what I'm missing.

**Comment by dlorenc** [comment]
@gbraad does this look right to you?

**Comment by gbraad** [comment]
Will take some time to verify tomorrow or over the weekend. Busy schedule
at the moment.

**Comment by fenos** [comment]
I've tried this PR on my local MAC and I've been successfully able to run minikube with `parallels` driver.  🎉 well done.

The cluster came up fine. The only issue i've seen is that when running `minikube status` command, it throws the following error:

```
E0629 13:32:18.945720   17096 status.go:85] Error cluster status: Error: Unrecognized output from ClusterStatus: Running
E0629 13:32:18.946837   17096 util.go:151] Error formatting error message: Error msg with no stack trace cannot be reported
```

same when trying to mount a volume with `minikube mount [path]:[path]`:

```
E0629 13:34:12.490030   17173 mount.go:113] Error getting the host IP address to use from within the VM:  Error, attempted to get host ip address for unsupported driver
```

@bassam Well done!

**Comment by bassam** [comment]
@fenos I rebased and pushed new changes. I'm not seeing the issue with `minikube status`:

```
>out/minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 10.211.55.17
```

I wonder what's different about our environments. Is it possible that you're running an older different  version of minikube when running status vs. the one in the `out/` dir?

**Comment by bassam** [comment]
any update on this? I'm unclear as to what's needed to get this merged.

**Comment by lewisbenge** [comment]
@bassam I've merged this PR locally and run it against the most recent version of Parallels. Although a cluster provisions it never starts. It appears there is an issue when the scripts attempt to configure the  VM. Have you had any similar issues? (Verbose log below)

Starting cluster components...
E0730 19:18:58.179095   77227 start.go:295] Error starting cluster:  kubeadm init error 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns
 running command: : running command: 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

.: Process exited with status 1

**Comment by bassam** [comment]
this PR has been open for 6 months and I'm still unsure what needs to be done for it to get merged.  Maintainers please help.

/cc @dlorenc @luxas @aaron-prindle @jimmidyson @balopat

**Comment by tstromberg** [comment]
Do you mind addressing the merge conflict? I'd like to see about merging this if it's still viable. My apologies for the unnecessarily long delay in reviewing this PR.

I think that this would be a great addition to the codebase as an initially experimental VM driver.

**Comment by bassam** [comment]
I assume this is no longer needed after #953 was merged?

**Comment by bassam** [comment]
closing in favor of #3650

**Pull request closed without merging**
