### PR TITLE
Generate KIC tool versions for website on KIC Base release

### PR DESCRIPTION
**Pull request by andriyDev**
Partially completes #11435. Still need to do ISO.

Kicbase Dockerfile creates /tools.csv containing the versions of all tools. Kicbase release script then extracts this file and uses it to generate the web page.

image

Note: crictl has unknown version due to a bug in the binary itself. See https://github.com/kubernetes-sigs/cri-tools/issues/798 for more

### CODE REVIEW

**Comment by medyagh** [comment]
seems empty here https://deploy-preview-12030--kubernetes-sigs-minikube.netlify.app/docs/releaseinfo/kictoolversions/

**Comment by andriyDev** [comment]
@medyagh I manually backfilled for the current kicbase.

**Comment by andriyDev** [comment]
Moved all the version collection commands to a single script. This reduces the number of layers in the image, simplifies management, and makes version collection reusable.

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Review by medyagh — CHANGES_REQUESTED** [review]
I rather we don't make kic a unique case 
For sake of better maintenaniablity let's just start minikube and spit out versions for docker and a vm driver in automation

**Pull request closed without merging**
