### PR TITLE
Update Ingress-NGINX to 0.24.1 Release

### PR DESCRIPTION
**Pull request by fenglixa**
Update Ingress-NGINX to 0.24.1 Release
Fix for #4578

### CODE REVIEW

**Comment by fenglixa** [comment]
I append my UT result here:
image

@minikube-bot OK to test

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
Thank you for this PR ! it is exciting to see minikube bugs getting closed one after another. 
@fenglixa have you tried the ingress change on your computer locally ? I would recommend deploying a service with ingress and check if it is acting normal

**Comment by fenglixa** [comment]
Thanks @medyagh .
Yes, I created the services and ingress resources, it works well with the code changes.
image

**Comment by medyagh** [comment]
Awesome, thank you so much for the contribution. closes this #4578

**Pull request merged**
