### PR TITLE
Remove heapster addon

### LINKED ISSUE #5017: Remove heapster addon - it's retired.
https://github.com/kubernetes-retired/heapster

"RETIRED: Heapster is now retired. See the deprecation timeline for more information on support. We will not be making changes to Heapster.

The following are potential migration paths for Heapster functionality:

For basic CPU/memory HPA metrics: Use metrics-server.

For general monitoring: Consider a third-party monitoring pipeline that can gather Prometheus-formatted metrics. The kubelet exposes all the metrics exported by Heapster in Prometheus format. One such monitoring pipeline can be set up using the Prometheus Operator, which deploys Prometheus itself for this purpose.

For event transfer: Several third-party tools exist to transfer/archive Kubernetes events, depending on your sink. heptiolabs/eventrouter has been suggested as a general alternative."

### PR DESCRIPTION
**Pull request by rajalokan**
Fixes #5017. As per discussion, needed a rebase and this PR is rebased
to latest master.

### CODE REVIEW

**Comment by tstromberg** [comment]
`make test` fails:

`panic: Failed to define asset deploy/addons/heapster/influx-grafana-rc.yaml.tmpl: Asset deploy/addons/heapster/influx-grafana-rc.yaml.tmpl not found`

**Comment by tstromberg** [comment]
Any luck sorting out the test failure?

You should be able to confirm it locally by running:

`make test`

**Comment by rajalokan** [comment]
Let me try it out in a day. Missed out on it. Please give me a day.

**Comment by rajalokan** [comment]
Hi @tstromberg Can you please take a look when you can.

**Comment by woodcockjosh** [comment]
@rajalokan please rebase from master and resolve conflicts

**Comment by rajalokan** [comment]
@woodcockjosh  Done. Thanks for the review.

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
This PR looks ready to merge, just needs one fix. Change the `removes heapster` commit message to something that doesn't start with "removes" using `git amend` and push. Once that's done I'll merge this.

**Comment by rajalokan** [comment]
@sharifelgamal Can you please take a look.

**Pull request merged**
