### PR TITLE
Change from crio-1.19 to crio-1.20 in kicbase

### PR DESCRIPTION
**Pull request by afbjorklund**

### CODE REVIEW

**Comment by afbjorklund** [comment]
KIC build node broken: `package github.com/go-bindata/go-bindata/...: exec: "git": executable file not found in $PATH`

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Comment by medyagh** [comment]
ok-to-build-image

**Review by medyagh — APPROVED** [review]

**Pull request merged**
