### PR TITLE
Fix node name for "none" driver

### PR DESCRIPTION
**Pull request by laozc**
Recent changes break the host name for "none" driver and the node always falls back to `minikube`.
This makes sure that the host name is picked for node name.

### CODE REVIEW

**Comment by sharifelgamal** [comment]
`node.Name()` is already taken, but I agree that it should probably live in the node package. `node.InternalName()` perhaps? 

I'm ideally doing away with the need for triple hyphens in the machine name soon, but double hyphens is plenty enough for the time being.

**Comment by laozc** [comment]
I believe `minikube---m01` could be a valid host name so it seems like using `---` as a separator is not a good idea.
Considering if the node is naming as `minikube---m01` it is possible with the `none` driver (as it is controlled by the user who creates the machine) but the logic to only splitting by `---` would break it.
It would be better to use `:` or other illegal character for hostname as separator for cluster name/node name.

**Comment by sharifelgamal** [comment]
currently hostname and nodename are coupled, a good solution would be to decouple them then use a weird character as a separator. the best solution is clearly to not rely on hostname to re-extract the cluster name but that's outside the scope of this PR.

**Comment by laozc** [comment]
Let me just move the `KubeNodeName` out of driver package for now.

**Comment by medyagh** [comment]
I created an issue for this PR https://github.com/kubernetes/minikube/issues/7169

**Comment by medyagh** [comment]
> I believe `minikube---m01` could be a valid host name so it seems like using `---` as a separator is not a good idea.
> Considering if the node is naming as `minikube---m01` it is possible with the `none` driver (as it is controlled by the user who creates the machine) but the logic to only splitting by `---` would break it.
> It would be better to use `:` or other illegal character for hostname as separator for cluster name/node name.

I find three dashes odd, I would vote for not having 3 dashes for names

**Comment by sharifelgamal** [comment]
yeah let's use two dashes for now, I will work on no longer relying on embedding the cluster name in the machine name

**Pull request merged**
