### PR TITLE
Fix node InternalIP not matching host-only address

### PR DESCRIPTION
**Pull request by woodcockjosh**
This fixes the issue with the node InternalIP not matching the minikube ip

### CODE REVIEW

**Comment by woodcockjosh** [comment]
#3416

**Comment by afbjorklund** [comment]
Pretty sure that the config was `kubelet.node-ip` (rather than just "node-ip"), but we will see

/ok-to-test

**Comment by woodcockjosh** [comment]
> Pretty sure that the config was `kubelet.node-ip` (rather than just "node-ip"), but we will see
> 
> /ok-to-test

yeah it is inside the `NewKubeletConfig` function which filters the k8s.ExtraOptions on line 540

**Comment by afbjorklund** [comment]
Ok, makes sense.

**Comment by tstromberg** [comment]
This is a perfect example where a long-standing bug has a simple solution, as the true difficulty is in discovering where it went wrong.

Well done, and Thank You!

**Pull request merged**
