### PR TITLE
Buildroot 2020.02

### PR DESCRIPTION
**Pull request by afbjorklund**
The good news is that it actually compiles (at last)

`179M	out/minikube.iso`

The bad news is that it doesn't boot, but hangs...

minikube-buildroot

The upstream Buildroot 2020.02.x works just fine, so this is something in minikube config.
Possibly related to the initial file systems, like the initrd (rootfs) or the sysroot (tmpfs) ?

For #7904

### CODE REVIEW

**Comment by afbjorklund** [comment]
Yup, seems like something went horrible wrong in the init.

It's where we copy the contents of the rootfs to the tmpfs:

```sh
#!/bin/sh
mkdir /sysroot
# the value 90% borrowed from tcl via boot2docker
mount -t tmpfs -o size=90% tmpfs /sysroot
# copy from rootfs, to be able to do switch_root(8)
tar -C / --exclude=sysroot -cf - . | tar -C /sysroot/ -xf -
```

```
�mount: /sysroot: wrong fs type, bad option, bad superblock on tmpfs, missing codepage or helper program, or other error.
```

And then, because of that, it dies in the final step:

```sh
exec /sbin/switch_root /sysroot /sbin/init "$@"
```

```
BusyBox v1.31.1 (2020-05-17 20:20:13 CEST) multi-call binary.

Usage: switch_root [-c CONSOLE_DEV] NEW_ROOT NEW_INIT [ARGS]

Free initramfs and switch to another root fs:
chroot to NEW_ROOT, delete all in /, move NEW_ROOT to /,
execute NEW_INIT. PID must be 1. NEW_ROOT must be a mountpoint.

	-c DEV	Reopen stdio to DEV after switch
[   24.079005] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
```

**Comment by afbjorklund** [comment]
But the actual `mount` command is (pretty much) the same, from util-linux 2.35.1

So it must be something else that is different, most likely it's the kernel version ?

**Comment by afbjorklund** [comment]
Duh, sometimes it is the simple stuff. Like checking if the plug is actually in the wall socket.

Or making sure that tmpfs support is actually in the kernel... (maybe a default changed ?)

At least it boots:

buildroot-booting

But ssh is sad.

**Comment by afbjorklund** [comment]
`ssh-keygen` is segfaulting (when generating the host keys). That is probably bad...

The package was upgraded from 7.9p1 to 8.1p1, maybe something happened to it.

**Comment by afbjorklund** [comment]
Well, ssh starts now. But unfortunately we don't have any network (besides lo)

`vboxguest: PCI device not found, probably running on physical hardware`

`lspci: /sys/bus/pci/devices: No such file or directory`

Apparently `CONFIG_VIRTIO_PCI` went missing along with `CONFIG_PCI`.

**Comment by afbjorklund** [comment]
Good, now `ssh` is back on track as well. Maybe it will start now ?

**Comment by afbjorklund** [comment]
Well, it's always the little things.. No DNS, and other parts missing.

`command_runner.go:102] ! sudo: pgrep: command not found`

**Comment by afbjorklund** [comment]
The missing /etc/resolv.conf was for the same root cause as ssh.

Systemd didn't like LibreSSL, and I hadn't rebuilt everything...

`minikube systemd-resolved[23193]: /usr/lib/systemd/systemd-resolved: error while loading shared libraries: libcrypto.so.45: cannot enable executable stack as shared object requires: Operation not permitted`

It _requires_ the libraries to be built with  `-Wa,--noexecstack`

`MemoryDenyWriteExecute=yes`

----

And the missing access of k8s.gcr.io was for a different reason:

`command_runner.go:102] ! bash: curl: command not found`

**Comment by afbjorklund** [comment]
@medyagh : was there a way to share these "snapshot" ISO, or to make the PR build it ?

**Comment by afbjorklund** [comment]
Probably should try to get upstream to _upgrade_ sysdig, rather than patching the old version.

I don't really know what we are using it for in minikube, but it was enabled in the old config...

**Comment by medyagh** [comment]
> @medyagh : was there a way to share these "snapshot" ISO, or to make the PR build it ?

hm... there should be a way to at leasst have the ISO URL for manual testing

**Pull request merged**
