### PR TITLE
some words are not correct then change it

### PR DESCRIPTION
**Pull request by lilongfeng0902**
find some wrong words, then correct it.

### CODE REVIEW

**Comment by camba1** [comment]
The build is failing (undefined: retryablehttp) because "github.com/hashicorp/go-retryablehttp" was removed from [functional_test.go](https://github.com/kubernetes/minikube/blob/master/test/integration/functional_test.go)  but it is used in function validateDashboardCmd. 

I suggest the dependency is re-added and the PR re-submitted as the rest of the change is good

**Comment by lilongfeng0902** [comment]
> The build is failing (undefined: retryablehttp) because "github.com/hashicorp/go-retryablehttp" was removed from [functional_test.go](https://github.com/kubernetes/minikube/blob/master/test/integration/functional_test.go) but it is used in function validateDashboardCmd.
> 
> I suggest the dependency is re-added and the PR re-submitted as the rest of the change is good

Thanks for your help，this is my first PR, some situations may be difficult for me . By your notion, i have change the file functional_test.go .

**Comment by camba1** [comment]
Thanks for the change @lilongfeng0902 
Unfortunately, it looks like the new commit only changed the comment on line 87 but did not re-add the missing dependency ("github.com/hashicorp/go-retryablehttp"). As such, the build failed again on the same spot and the same error. Please try to re-add the dependency. See line 49 of the [existing code](https://github.com/kubernetes/minikube/blob/master/test/integration/functional_test.go) .
Thanks again!

**Comment by lilongfeng0902** [comment]
> Thanks for the change @lilongfeng0902
> Unfortunately, it looks like the new commit only changed the comment on line 87 but did not re-add the missing dependency ("github.com/hashicorp/go-retryablehttp"). As such, the build failed again on the same spot and the same error. Please try to re-add the dependency. See line 49 of the [existing code](https://github.com/kubernetes/minikube/blob/master/test/integration/functional_test.go) .
> Thanks again!

Yeah，I find my misti> Thanks for the change @lilongfeng0902
> Unfortunately, it looks like the new commit only changed the comment on line 87 but did not re-add the missing dependency ("github.com/hashicorp/go-retryablehttp"). As such, the build failed again on the same spot and the same error. Please try to re-add the dependency. See line 49 of the [existing code](https://github.com/kubernetes/minikube/blob/master/test/integration/functional_test.go) .
> Thanks again!

Yeah，I find my mistake and I re-add  the dependency. Please check my code again, thanks.

**Pull request merged**
