### PR TITLE
Fix hyperkit mounting.

### PR DESCRIPTION
**Pull request by dlorenc**
@r2d4

### CODE REVIEW

**Comment by dlorenc** [comment]
Fixes #2269

**Comment by th3fallen** [comment]
any chance you guys could tag a patch version for this? pretty please?

**Comment by shebiki** [comment]
It looks like you can use `minikube mount --ip 192.168.64.1` as a workaround until the next release.

**Comment by mbarison** [comment]
if you use kvm2 the ip is 192.168.39.1, check it here:
[https://github.com/kubernetes/minikube/pull/2312/files](https://github.com/kubernetes/minikube/pull/2312/files)

**Pull request merged**
