### PR TITLE
Initial implementation of kubectl command

### PR DESCRIPTION
**Pull request by afbjorklund**
~~Some duplication, always using default k8s~~

For #3645

### CODE REVIEW

**Comment by tstromberg** [comment]
After reviewing our uses of kubectl, I'm left wondering if this command is worth the technical debt it incurs. I feel that if users want to use kubectl, they may as well install it properly so that they may use it for a non-minikube cluster.

Thoughts?

**Comment by afbjorklund** [comment]
As long as `kubectl` is just a Recommends in a .deb so that it gets automatically pulled with the `sudo apt install minikube` (which would of course also install needed drivers as Depends), then everything is fine...

But after putting the poor user through:
https://kubernetes.io/docs/tasks/tools/install-minikube/#linux

``` bash
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube
sudo cp minikube /usr/local/bin && rm minikube
```

The last thing to do is making them do:
https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-using-curl

```
curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl
```

Where it "forgets" to use the checksums, and is prone to using the wrong version of `kubectl`. The only difference between this and "properly", seems to be the extra step of copying it along the $PATH ?

----

To be honest I am not sure why we require the user to have `sudo` rights ?
They would probably be just as well off, by copying them to `~/.local/bin`

I've also seen at least a dozen different ways to do the above, with chown etc.
Even these two pages in the Kubernetes docs also vary, ever so slightly.

**Comment by afbjorklund** [comment]
This command can use the new `machine.CacheBinary` function instead, once #3737 is merged.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
This seems ready to merge once we have positive test results.

**Comment by tstromberg** [comment]
Please rebase and merge once ready. Thanks!

**Comment by afbjorklund** [comment]
Will wait for 1.1

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Pull request merged**
