### PR TITLE
minikube-pr-bot enhancements

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Comment by nikhita** [comment]
creating a (dummy) approve comment to re-trigger CI, the approval mechanism was broken for a bit - kubernetes/test-infra#21687

/approve

**Comment by medyagh** [comment]
> **kvm2 Driver**
> Times for minikube: 51.4s 49.1s 52.1s
> Average time for minikube: 50.9s
> 
> Times for Minikube (PR 11011): 49.5s 49.0s 51.6s
> Average time for Minikube (PR 11011): 50.0s
> 
> Averages Time Per Log
> 
> **docker Driver**
> Times for minikube: 17.5s 18.4s 18.6s
> Average time for minikube: 18.2s
> 
> Times for Minikube (PR 11011): 18.1s 19.0s 17.8s
> Average time for Minikube (PR 11011): 18.3s
> 
> Averages Time Per Log

it still shows only 3 Times.... (instead of 5)

**Comment by sharifelgamal** [comment]
> > **kvm2 Driver**
> > Times for minikube: 51.4s 49.1s 52.1s
> > Average time for minikube: 50.9s
> > Times for Minikube (PR 11011): 49.5s 49.0s 51.6s
> > Average time for Minikube (PR 11011): 50.0s
> > Averages Time Per Log
> > **docker Driver**
> > Times for minikube: 17.5s 18.4s 18.6s
> > Average time for minikube: 18.2s
> > Times for Minikube (PR 11011): 18.1s 19.0s 17.8s
> > Average time for Minikube (PR 11011): 18.3s
> > Averages Time Per Log
> 
> it still shows only 3 Times.... (instead of 5)

Yeah this is still the old pr bot, it's still running after all. Once my mkcmp changes are merged (i'm going to open a new PR for that), then we should get 2 comments, one with 3 times and one with 5.

**Review by medyagh — APPROVED** [review]

**Pull request merged**
