### PR TITLE
Remove kubelet options for k8s version < 1.12

### PR DESCRIPTION
**Pull request by prasadkatti**
This does some cleanup, now that the minimum k8s version is bumped up to 1.13

### CODE REVIEW

**Comment by medyagh** [comment]
We should still be able to support v1.12 with --force

**Comment by prasadkatti** [comment]
@medyagh - That should be fine. The options removed in this PR are for versions older than 1.12.

**Comment by prasadkatti** [comment]
I think the test failures are just flakes. Can I get some reviews on this?

**Comment by priyawadhwa** [comment]
Hey @prasadkatti I also think it might be best to leave this in, in case somebody is trying to use any k8s version <1.13 with the `--force` flag

**Comment by prasadkatti** [comment]
@priyawadhwa What is the earliest k8s version one can ask for with minikube?

**Comment by priyawadhwa** [comment]
so we officially only promise to support >=1.13, but right now people can use lower versions with `--force` if they want to. I figure we can keep this code in, in the case people are doing that (we just don't promise it'll work).

It would be nice if we knew if anyone was actually doing that, but I don't think we have those stats...

**Comment by prasadkatti** [comment]
Also as new code gets added we are bound to be breaking things for the older versions. So it would be nice to know what is the oldest version of k8s that still works with minikube 1.11.

**Comment by priyawadhwa** [comment]
@prasadkatti yah I see what you mean; unfortunately we don't really have data around what k8s versions people are using, so it's hard to say if anyone is using <1.12 with `--force`. I say we should play it safe and in case some people are using <1.12 with `--force` I think we should keep this code in.

I'm going to close this PR for now since we want to keep this code in, but thank you for bringing this up!

**Pull request closed without merging**
