### PR TITLE
specify correct context in minikube kubectl test

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Review by medyagh — COMMENTED** [review]
good catch

**Comment by medyagh** [comment]
https://storage.googleapis.com/minikube-builds/logs/9467/f45bea7/Docker_Linux.html#fail_TestFunctional%2fserial%2fMinikubeKubectlCmdDirectly

```
=== RUN   TestFunctional/serial/MinikubeKubectlCmdDirectly
functional_test.go:332: (dbg) Run:  out/kubectl get pods --context functional-20201014131933-626628
functional_test.go:332: (dbg) Non-zero exit: out/kubectl get pods --context functional-20201014131933-626628: exit status 14 (51.030362ms)
** stderr ** 
	Error: unknown flag: --context
	See 'minikube kubectl --help' for usage.

```

**Comment by tstromberg** [comment]
This may be a bug where -- flags don't work properly with minikube linked to kubectl?

**Review by tstromberg — CHANGES_REQUESTED** [review]
This does not seem to fix the test -- yet.

**Pull request closed without merging**
