### PR TITLE
kvm2: fix deleteNetwork error

### PR DESCRIPTION
**Pull request by josedonizetti**
Fix missing network name on an error return.

### CODE REVIEW

**Comment by hpandeycodeit** [comment]
@minikube-bot ok to test

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
Looks good once the conflict is resolved. Thank you!

**Comment by josedonizetti** [comment]
With the merge of the PR https://github.com/kubernetes/minikube/pull/4331 this change is no longer required. The PR already fixed it with a different error message: https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kvm/network.go#L178

**Pull request closed without merging**
