### PR TITLE
Don't drop errors during creation retries.

### LINKED ISSUE #405: Error starting minikube on Windows (Error message is swallowed due to retry loop)
I've run into problems testing out Windows support on my dev machine. I am unable to diagnose what the actual issue is because the initial error is not logged due to the retry loop.

What seems to be happening is that the first attempt with a non-existent `.minikube` directory fails midway for some unknown reason, but it advances long enough so that the call to `api.Exists(constants.MachineName)` returns true on the next attempt.

Once this happens, `minikube` gets confused because it thinks the machine exists but fails later on trying to get the state of a non-existent machine:
```
PS C:\Users\abrand> minikube start  --logtostderr --show-libmachine-logs
Starting local Kubernetes cluster...
Creating CA: C:\Users\abrand\.minikube\certs\ca.pem
Creating client certificate: C:\Users\abrand\.minikube\certs\cert.pem
Running pre-create checks...
Creating machine...
(minikubeVM) Downloading C:\Users\abrand\.minikube\cache\boot2docker.iso from file://C:\Users\abrand\.minikube/cache/iso/minikube-0.5.iso...
I0726 18:47:54.940675    7516 cluster.go:69] Machine exists!
I0726 18:47:55.124184    7516 cluster.go:77] Machine state:  Error
I0726 18:47:55.125149    7516 cluster.go:69] Machine exists!
I0726 18:47:55.303738    7516 cluster.go:77] Machine state:  Error
E0726 18:47:55.304679    7516 start.go:78] Error starting host:  Error getting state for host: machine does not exist
```

I'd like to look into this more, but I am unable to build with `GOOS=windows`. Is there anything else I need to do to build `minikube` on Linux, targeting `windows`? I can spend some cycles on this.

### PR DESCRIPTION
**Pull request by dlorenc**
Fixes #405

### CODE REVIEW

**Comment by aaron-prindle** [comment]
LGTM.  Should Retry collect errors and return some kind of list of all the encountered errors?

**Comment by dlorenc** [comment]
@aaron-prindle PTAL. I switched it to use a multiError.

**Comment by jimmidyson** [comment]
LGTM

**Comment by aaron-prindle** [comment]
LGTM

**Pull request merged**
