### PR TITLE
Revert "Delete and init kubeadm on subsequent starts"

### PR DESCRIPTION
**Pull request by spowelljr**
Fixes https://github.com/kubernetes/minikube/issues/13431
Fixes https://github.com/kubernetes/minikube/issues/13503
Related https://github.com/kubernetes/minikube/issues/12389

Reverting my original PR https://github.com/kubernetes/minikube/pull/13121 as it's causing a regression.

### CODE REVIEW

**Review by sharifelgamal — APPROVED** [review]

**Comment by shaima-mahmoud** [comment]
Hello, I am a beginner with minikube and linux as well, how to I upgrade from 1.25 version to this version on linux ?

**Comment by spowelljr** [comment]
> Hello, I am a beginner with minikube and linux as well, how to I upgrade from 1.25 version to this version on linux ?

Hi @shaima-mahmoud, follow the instructions in our documentation, thanks!

https://minikube.sigs.k8s.io/docs/start/

**Pull request merged**
