### PR TITLE
Implement options for the minikube version command

### LINKED ISSUE #7322: Shorten minikube version output
The output of `minikube version` is currently:
```
minikube version: v1.9.0
commit: 48fefd43444d2f8852f527c78f0141b377b1e42a
```

Whereas I expected only the version number: `v1.9.0`

Supporting JSON output would also work, if you need to keep the commit information, since that would also allow me to parse the version directly

### PR DESCRIPTION
**Pull request by afbjorklund**
Add --short and --output options, just like kubectl

Closes #7322

### CODE REVIEW

**Comment by afbjorklund** [comment]
> Could you please add the output?

https://github.com/kubernetes/minikube/issues/7322#issuecomment-606228206

**Comment by medyagh** [comment]
there is a lint issue

**Comment by afbjorklund** [comment]
Thanks for adding the missing newline

**Pull request merged**
