### PR TITLE
Extend kernel config to support dummy network interface and openvswitch with vxlan

### PR DESCRIPTION
**Pull request by brb**
The missing configuration prevents Weave Net from running on minikube (https://github.com/weaveworks/weave/issues/3124).

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot OK to test

**Comment by brb** [comment]
Is there anything I can do about the CI failures?

**Comment by pgandhipfpt** [comment]
I built minikube after getting these changes . and then starting weavenet , container is showing "CrashLoopBackOff" 

I am trying on mac Sierra . 
These are the steps I did 
a. I got changes on my mac in minikube folder 
b.cd /Users/$NAME/go/src/k8s.io/minikube/
    make
c  ./out/minikube start
d. kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   etcd-minikube                           1/1       Running   0          1m
kube-system   kube-addon-manager-minikube             1/1       Running   0          1m
kube-system   kube-apiserver-minikube                 1/1       Running   0          1m
kube-system   kube-controller-manager-minikube        1/1       Running   0          1m
kube-system   kube-dns-86f4d74b45-md2m6               3/3       Running   0          1m
kube-system   kube-proxy-9h8t5                        1/1       Running   0          1m
kube-system   kube-scheduler-minikube                 1/1       Running   0          1m
kube-system   kubernetes-dashboard-5498ccf677-kgflm   1/1       Running   0          1m
kube-system   storage-provisioner                     1/1       Running   0          1m

e.kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

f.kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
kube-system   etcd-minikube                           1/1       Running            0          21m
kube-system   kube-addon-manager-minikube             1/1       Running            0          21m
kube-system   kube-apiserver-minikube                 1/1       Running            0          21m
kube-system   kube-controller-manager-minikube        1/1       Running            0          21m
kube-system   kube-dns-86f4d74b45-md2m6               3/3       Running            0          22m
kube-system   kube-proxy-9h8t5                        1/1       Running            0          22m
kube-system   kube-scheduler-minikube                 1/1       Running            0          21m
kube-system   kubernetes-dashboard-5498ccf677-kgflm   1/1       Running            0          22m
kube-system   storage-provisioner                     1/1       Running            0          22m
kube-system   weave-net-nm7f2                         1/2       CrashLoopBackOff   8          16m


To verify that I have this fix, I tried this 

grep CONFIG_DUMMY ./deploy/iso/minikube-iso/board/coreos/minikube/linux-4.9_defconfig
CONFIG_DUMMY=m
grep CONFIG_OPENVSWITCH ./deploy/iso/minikube-iso/board/coreos/minikube/linux-4.9_defconfig
CONFIG_OPENVSWITCH=m

I am very new to k8s . Please let me know If I missed anything

**Comment by brb** [comment]
@pgandhipfpt Can you please open a new issue https://github.com/weaveworks/weave/issues/new? Please provide all requested information in the issue template and in addition, an output of `zgrep OPENVSWITCH /proc/config.gz`. Thanks.

**Comment by pgandhipfpt** [comment]
Thanks @brb . Opened https://github.com/weaveworks/weave/issues/3318

**Pull request merged**
