### PR TITLE
kernel: Add config for tc u32 filter and mirred action

### PR DESCRIPTION
**Pull request by amshinde**
These are needed for running Kata Containers in minikube.
Kata uses linux tc for its networking

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by tstromberg** [comment]
Thank you! The test failure is an unrelated flake.

**Comment by tstromberg** [comment]
@minikube-bot ok to test

**Comment by tstromberg** [comment]
As a side note, I am really excited about the possibility of running Kata containers in minikube. Please let me know if there is anything else I can do to help.

**Comment by grahamwhaley** [comment]
Hi @tstromberg - sure - the original issue turned up as I was documenting how to install/run kata under minikube: https://github.com/kata-containers/documentation/pull/445

So, what would it take to get Kata as a supported option in minikube, like I think I have seen gvisor is ? If we can work together on that, that would be great :-)

**Comment by tstromberg** [comment]
> Hi @tstromberg - sure - the original issue turned up as I was documenting how to install/run kata under minikube: [kata-containers/documentation#445](https://github.com/kata-containers/documentation/pull/445)
> 
> So, what would it take to get Kata as a supported option in minikube, like I think I have seen gvisor is ? If we can work together on that, that would be great :-)

You know, I'm not actually sure what it will take, but I'm happy to help point you in the right direction. When the maintainers came up with the [minikube development roadmap for 2019](https://github.com/kubernetes/minikube/blob/master/docs/contributors/roadmap.md), we identified that we wanted support for Kata containers, but no one has yet stepped up to look into it. I think Kata Containers have a great design and would personally love to see support for it.

I agree that following the gvisor addon is a good approach, but if for some reason it's too complicated to include as an addon, I'm happy to entertain alternative ideas. @priyawadhwa wrote the gvisor addon and may have additional guidance.

Feel free to find me on the #minikube slack channel if you have any questions that are better addressed in real time. Thanks for contributing this change!

**Comment by grahamwhaley** [comment]
Hi @tstromberg - ah, thanks for the roadmap link - afaik nobody in the Kata community knew about that - but, now we do! ;-)
I started using Minikube to do quick Kata demos/workshops recently, as it is a nice way to get a small cluster up etc. At that time I also considered what it would take to get Kata as a native component into Minikube. Let me go have a look what it took for `gvisor` and see if that maps at all to how Kata is built/installed/released. It would be nice if we can have Kata releases automatically updating in Minikube etc.

Which leads me to another couple of questions then:

1) Do we know when this PR will land in a Minikube release? Is there a release roadmap etc. - so I know what to document/tell folks in Kata-land about which Minikube versions work with which setups etc.

1) Does minikube run a CI system? In which case maybe we can get it to install Kata and run our tests - that, and/or, we'd probably like to do a similar thing in our Kata CI - to check that we don't break minikube integration either.

**Comment by grahamwhaley** [comment]
FMI, the PR to add `gvisor` looks to be https://github.com/kubernetes/minikube/pull/3399
@amshinde @egernst - this looks quite like it uses a pod to deploy much like [kata-deploy](https://github.com/kata-containers/packaging/tree/master/kata-deploy) (in fact, was there some 'inspiration' there??). That might make it not too onerous to add Kata to Minikube.

We should probably open a new Issue here on Minikube to track this...

**Comment by amshinde** [comment]
@grahamwhaley Yes, I did have a brief look at that PR last week, and much of it is essentially what `kata-deploy` does. 
@grahamwhaley In case you missed it, @tstromberg has opened #4347 to track the support for Kata.

**Pull request merged**
