### PR TITLE
Fixes validation on image repository URL when it contains port but no scheme

### LINKED ISSUE #13022: minikube start --image-repository with port does not work without scheme
Related to PR https://github.com/kubernetes/minikube/pull/11585/files which was release on v1.23.0

**Steps to reproduce the issue:** 
1. Run command `minikube start--image-repository <repository>:<port>` for example: `minkube start --image-repository repository:8080`
2. Observe the output `The --image-repository flag your provided contains Scheme: repository, which will be removed automatically` and on the next line `Using image repository ' without the repository.

If I run `minkube start --image-repository https://repository:8080` it complains about the scheme but trims it out and works with `repository:8080`.
Running minikube without port also works without the schema.

</details>

I'll try to have by the EOD a PR to address this issue.

### PR DESCRIPTION
**Pull request by tmcalves**
Refactor the way validations are done to use regular expression
Explicitly use "auto" as the imageRepo instead of an empty string when URL received is invalid
Fixes #13022

### CODE REVIEW

**Comment by medyagh** [comment]
thank you @tmcalves for the PR, would u plz sign the CLA

**Comment by tmcalves** [comment]
Should all be signed now

**Comment by tmcalves** [comment]
anyone able to take a look at this?

**Comment by tmcalves** [comment]
Rebased to test a more updated version

**Review by spowelljr — APPROVED** [review]

**Pull request merged**
