### PR TITLE
WIP: Use pooling support that's being added to cheggaaa/pb/v3 to fix download progress bar

### LINKED ISSUE #11069: UI progress bars stepping on each other
I noticed that `preloaded-images-k8s` and `index.docker.io/kicbase` progress bars step on each other when downloading is in progress and it is confusing for the user and might be interpreted as a glitch. When the download is finished, they are displayed in separate lines:

```
minikube start --driver=docker
😄  minikube v1.19.0 on Darwin 10.15.7
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.20.2 preload ...
    > gcr.io/k8s-minikube/kicbase...: 357.67 MiB / 357.67 MiB  100.00% 396.74 K
    > preloaded-images-k8s-v10-v1...: 491.71 MiB / 491.71 MiB  100.00% 411.47 K
    > index.docker.io/kicbase/sta...: 357.67 MiB / 357.67 MiB  100.00% 417.22 K
```

### PR DESCRIPTION
**Pull request by yayaha**
Fixes #11069.

This PR is built upon a combination of cheggaaa/pb#188 and #11673 (thanks @cheggaaa and @afbjorklund). More specifically, below are some notable changes:

1. Both image.go and progressbar.go will be using a single DefaultProgressTracker defined in progressbard.go.
2. Set the total size of progress bars in image.go early. Otherwise, the total size is updated only after the download starts, which causes an incorrectly sized progress bar.

Output during download:

```
Downloading Kubernetes v1.21.3 preload ...
    > preloaded-images-k8s-v11-v1...: 89.70 MiB / 481.44 MiB [-->___________] 18.63% 4.95 MiB p/s ETA 1m19s
    > gcr.io/k8s-minikube/kicbase: 35.00 MiB / 361.09 MiB [->________________] 9.69% 1.63 MiB p/s ETA 3m19s
```

Output after download completes:

```
Downloading Kubernetes v1.21.3 preload ...
    > preloaded-images-k8s-v11-v1...: 481.44 MiB / 481.44 MiB [----------------] 100.00% 4.33 MiB p/s 1m51s
    > gcr.io/k8s-minikube/kicbase: 361.09 MiB / 361.09 MiB [-------------------] 100.00% 3.25 MiB p/s 1m51s
```

### CODE REVIEW

**Comment by yayaha** [comment]
Need to look into the failing tests.

**Comment by medyagh** [comment]
@yayaha have u tried this on windows ? is it okay there?

**Pull request closed without merging**
