### PR TITLE
Upgrade buildroot minor version

### PR DESCRIPTION
**Pull request by afbjorklund**
Buildroot 2020.02.12

http://lists.busybox.net/pipermail/buildroot/2021-April/307630.html

Buildroot 2020.02.11

http://lists.busybox.net/pipermail/buildroot/2021-February/304049.html

### CODE REVIEW

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
The build failed because of a missing host dependency on python, and no "python" available on the build machine.

```
/usr/bin/env: ‘python’: No such file or directory
```

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Pull request merged**
