### PR TITLE
ISO: Upgrade buildroot minor version

### PR DESCRIPTION
**Pull request by afbjorklund**
From

`2021.02.4` (August 10th, 2021)

To

`2021.02.12` (April 6th, 2022)

----

https://git.busybox.net/buildroot/plain/CHANGES?id=2021.02.12

https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.19.235

EDIT: Bump from 2021.02.10 to 2021.02.12, the final release (EOL)

Will upgrade to 2022.02.x, when we bump KIC to Ubuntu 22.04 LTS

### CODE REVIEW

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
the test look not good

**Comment by spowelljr** [comment]
> the test look not good

That's likely just the KVM linux machine, we deleted that machine and created a new one, the retest should show the true result

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
@afbjorklund I've ran the tests a couple times and KVM Linux containerd seems to be failing consistently, any idea on what might be the cause?

**Comment by jepio** [comment]
@spowelljr
The failures look to be partially due to the upgrade of ssh server to 8.8, which deprecated ssh-rsa host keys, which go didn't support until recently (https://github.com/golang/go/issues/37278). Try applying one of the following 2 diffs and rerunning the tests:
```patch
diff --git a/go.mod b/go.mod
index 25292b1d0..7c6280b2c 100644
--- a/go.mod
+++ b/go.mod
@@ -72,7 +72,7 @@ require (
        go.opentelemetry.io/otel/sdk v1.6.1
        go.opentelemetry.io/otel/trace v1.6.1
        golang.org/x/build v0.0.0-20190927031335-2835ba2e683f
-       golang.org/x/crypto v0.0.0-20210817164053-32db794688a5
+       golang.org/x/crypto v0.0.0-20220331220935-ae2d96664a29
        golang.org/x/exp v0.0.0-20210220032938-85be41e4509f
        golang.org/x/mod v0.5.1
        golang.org/x/oauth2 v0.0.0-20220309155454-6242fa91716a
diff --git a/go.sum b/go.sum
index 136aba648..29cef54da 100644
--- a/go.sum
+++ b/go.sum
@@ -1206,6 +1206,8 @@ golang.org/x/crypto v0.0.0-20210220033148-5ea612d1eb83/go.mod h1:jdWPYTVW3xRLrWP
 golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2/go.mod h1:T9bdIzuCu7OtxOm1hfPfRQxPLYneinmdGuTeoZ9dtd4=
 golang.org/x/crypto v0.0.0-20210817164053-32db794688a5 h1:HWj/xjIHfjYU5nVXpTM0s39J9CbLn7Cc5a7IC5rwsMQ=
 golang.org/x/crypto v0.0.0-20210817164053-32db794688a5/go.mod h1:GvvjBRRGRdwPK5ydBHafDWAxML/pGHZbMvKqRZ5+Abc=
+golang.org/x/crypto v0.0.0-20220331220935-ae2d96664a29 h1:tkVvjkPTB7pnW3jnid7kNyAMPVWllTNOf/qKDze4p9o=
+golang.org/x/crypto v0.0.0-20220331220935-ae2d96664a29/go.mod h1:IxCIyHEi3zRg3s0A5j5BB6A9Jmi73HwBIUl50j+osU4=
 golang.org/x/exp v0.0.0-20190121172915-509febef88a4/go.mod h1:CJ0aWSM057203Lf6IL+f9T1iT9GByDxfZKAQTCR3kQA=
 golang.org/x/exp v0.0.0-20190306152737-a1d7652674e8/go.mod h1:CJ0aWSM057203Lf6IL+f9T1iT9GByDxfZKAQTCR3kQA=
 golang.org/x/exp v0.0.0-20190510132918-efd6b22b2522/go.mod h1:ZjyILWgesfNpC6sMxTJOJm9Kp84zZh5NQWvqDGG3Qr8=
```
OR
```patch
diff --git a/deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/ssh/sshd_config b/deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/ssh/sshd_config
index d5ece8f30..b7ab4a59a 100644
--- a/deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/ssh/sshd_config
+++ b/deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/ssh/sshd_config
@@ -117,3 +117,8 @@ Subsystem   sftp    /usr/libexec/sftp-server
 #      AllowTcpForwarding no
 #      PermitTTY no
 #      ForceCommand cvs server
+
+# Temporarily accept ssh-rsa algorithm for openssh >= 8.8,
+# until most ssh clients could deprecate ssh-rsa.
+HostkeyAlgorithms +ssh-rsa
+PubkeyAcceptedAlgorithms +ssh-rsa
```

**Comment by jepio** [comment]
Also: how about we bump to 2021.02.11?

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
Sigh, now the ISO build is _totally_ broken.

**Comment by jepio** [comment]
> Sigh, now the ISO build is _totally_ broken.

The log says this about building containerd:
> ERROR: v1.5.11.tar.gz has wrong sha256 hash:
ERROR: expected: 6a289406c1c0583763e5a9754e31a1eced55cd5f162a7bc2a3a315d5eb05c7a1
ERROR: got     : 02b79d5e2b07b5e64cd28f1fe84395ee11eef95fc49fd923a9ab93022b148be6

And I just saw that you already reported this issue before https://github.com/containerd/containerd/issues/6387
So either 2021.02.11 builds or we need to file a patch against buildroot to fix the checksum.

**Comment by afbjorklund** [comment]
That's not buildroot, it's a known issue with a k8s component

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Review by spowelljr — APPROVED** [review]

**Pull request merged**
