### PR TITLE
Update TestCertOptions

### PR DESCRIPTION
**Pull request by prasadkatti**
The PR tries to improve the TestCertOptions test by -

1. verifying that the alternate names/ips are included in the apiserver cert
2. verifying that the apiserver is serving on port passed in via --apiserver-port

### CODE REVIEW

**Comment by priyawadhwa** [comment]
Hey @prasadkatti could you provide some context as to what improvements you're making and why in the PR description? It would help me review this effectively. Thank you!

**Comment by prasadkatti** [comment]
@priyawadhwa - Updated the PR description. I created it as a WIP PR and forgot the update the description later.

**Comment by tstromberg** [comment]
Thank you!

**Pull request merged**
