### PR TITLE
Revert "pause: bump to newest image v3.4.1"

### PR DESCRIPTION
**Pull request by medyagh**
Reverts kubernetes/minikube#10666

this causes 50seconds slow down on minikube charts
Screen Shot 2021-03-05 at 10 21 34 AM

```

medya@cloudshell:~$ time ./minikube-1066 ssh
docker@minikube:~$ docker images
REPOSITORY                                TAG        IMAGE ID       CREATED         SIZE
k8s.gcr.io/kube-proxy                     v1.20.2    43154ddb57a8   7 weeks ago     118MB
k8s.gcr.io/kube-apiserver                 v1.20.2    a8c2fdb8bf76   7 weeks ago     122MB
k8s.gcr.io/kube-controller-manager        v1.20.2    a27166429d98   7 weeks ago     116MB
k8s.gcr.io/kube-scheduler                 v1.20.2    ed2c44fbdd78   7 weeks ago     46.4MB
k8s.gcr.io/pause                          3.4.1      0f8457a4c2ec   7 weeks ago     683kB
kubernetesui/dashboard                    v2.1.0     9a07b5b4bfac   2 months ago    226MB
gcr.io/k8s-minikube/storage-provisioner   v4         85069258b98a   3 months ago    29.7MB
k8s.gcr.io/etcd                           3.4.13-0   0369cf4303ff   6 months ago    253MB
k8s.gcr.io/coredns                        1.7.0      bfe3a36ebd25   8 months ago    45.2MB
kubernetesui/metrics-scraper              v1.0.4     86262685d9ab   11 months ago   36.9MB
k8s.gcr.io/pause                          3.2        80d28bedfe5d   12 months ago   683kB
docker@minikube:~$
```

### CODE REVIEW

**Review by ilya-zuyev — APPROVED** [review]
lgtm

**Comment by prezha** [comment]
i should have been more careful: i've checked and confirmed that the pr https://github.com/kubernetes/kubernetes/pull/98205 was merged before v1.20.4 was released, but i didn't check the specific commit that that version was built from - https://github.com/kubernetes/kubernetes/blob/e87da0bd6e03ec3fea7933c4b5263d151aafd07c/cmd/kubeadm/app/constants/constants.go did not pick it
thanks for catching that @medyagh

**Pull request merged**
