### PR TITLE
Make it possible to use custom GCS with environment variables

### PR DESCRIPTION
**Pull request by afbjorklund**
I know that "localkube" is deprecated, and that there are no official versions of localkube since v1.8.0:
#2134

But since the list of releases is hardcoded, I can't make any custom localkube builds (of 1.8.x) either:
#2156

Plan to move to "kubeadm" eventually (1.9+), but am *not* ready to do it for kubernetes version 1.8

And besides, using docker-machine and localkube still works fine - unless it is hardcoded/blocked...

### CODE REVIEW

**Comment by afbjorklund** [comment]
CLA signed

**Comment by r2d4** [comment]
@afbjorklund you can already pass in a file or url to kubernetes version for localkube

--kubernetes-version=https://...
or 
--kubernetes-version=file:///home/matt/localkube

**Comment by afbjorklund** [comment]
@r2d4 : that was one of the first things that I tried, but it doesn't seem to work - just got errors.

```
E1231 09:14:10.402682    5074 start.go:182] Error parsing version semver:  No Major.Minor.Patch elements found
Kubernetes version downgrade is not supported. Using version: v1.8.0
```
So using the pre-populated cache was a workaround, which worked OK (for v1.8.0, not v1.8.4)

**Comment by afbjorklund** [comment]
The previous version (0.23) just said:
```
Invalid Kubernetes version.
The following Kubernetes versions are available: 
	- v1.8.0
	- v1.7.5
	- v1.7.4
	...
```

**Comment by dlorenc** [comment]
@afbjorklund what string did you try passing as a flag to get that error?

**Comment by afbjorklund** [comment]
@dlorenc : Something like `--kubernetes-version=file:///mnt/sda1/tmp/localkube`

**Comment by afbjorklund** [comment]
Am running 0.24.1, maybe should have said that.

**Comment by afbjorklund** [comment]
Hmm, git says c20ebde4313cfd93ab3a6fc408497f63ffc341cb was included in 0.24.0 already...
Maybe I forgot the `file://` before the path or something ?

Now when I retry same thing with minikube 0.24.1, it does say:
`Starting local Kubernetes file:///tmp/localkube cluster...`

**Comment by dlorenc** [comment]
What's the status here? Can this be closed?

**Comment by afbjorklund** [comment]
@dlorenc : I guess that if you wanted to run e.g. 1.8.7 or 1.9.2 that you would "have" to use something like this since the default list of localkubes is still hardcoded to 1.8.0 and 1.9.2.

But using an URL seems to be working (as a workaround), even if it spews some "semver" errors when trying to parse the URL. Seems to be choking on the first path of the url/path ?

`Error parsing version semver:  Invalid character(s) found in major number "file:///home/anders/"`

But I suppose we could patch it downstream, so you can just close it if you like.

**Comment by afbjorklund** [comment]
It would be nice if this could be merged, since the syntax is much nicer and having validation is good...
It is not supposed to break anything, if you want the defaults and *don't* set the environment variables ?

MINIKUBE_LOCALKUBE_GCS=https://storage.googleapis.com/minikube/k8s_releases.json
MINIKUBE_LOCALKUBE_URL=https://storage.googleapis.com/minikube/k8sReleases/

**Comment by dlorenc** [comment]
Is this still needed? Localkube is on the way out. Please reopen if you think it should be included still.

**Comment by afbjorklund** [comment]
It was used for previous kubernetes releases, but like you say it is not useful without `localkube`.
So I guess I will just keep the patch downstream, and then switch to using `kubeadm` instead...

**Pull request closed without merging**
