### PR TITLE
containerd preload: discard unpacked layers to reduce size

### PR DESCRIPTION
**Pull request by spowelljr**
Closes https://github.com/kubernetes/minikube/issues/9946
Fixes https://github.com/kubernetes/minikube/issues/12355

**Before:**
`preloaded-images-k8s-v13-v1.22.2-containerd-overlay2-amd64.tar.lz4`
Size: 930MB

**After:**
`preloaded-images-k8s-v13-v1.22.2-containerd-overlay2-amd64.tar.lz4`
Size: 580MB

Size reduction:
`-350MB (37.6%)`

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-image

**Comment by spowelljr** [comment]
Found that you need to update containerd config to v2 for `discard_unpacked_layers` to take effect, but requires converting our existing config to from v1 to v2 as shown by the following errors:
```
Nov 02 21:37:56 minikube containerd[517]: containerd: invalid plugin key URI "cri" expect io.containerd.x.vx
Nov 02 21:37:56 minikube systemd[1]: containerd.service: Main process exited, code=exited, status=1/FAILURE
-- An ExecStart= process belonging to unit containerd.service has exited.
Nov 02 21:37:56 minikube systemd[1]: containerd.service: Failed with result 'exit-code'.
-- The unit containerd.service has entered the 'failed' state with result 'exit-code'.
Nov 02 21:37:56 minikube systemd[1]: Failed to start containerd container runtime.
-- Subject: A start job for unit containerd.service has failed
-- A start job for unit containerd.service has finished with a failure.
Nov 02 21:38:01 minikube systemd[1]: containerd.service: Scheduled restart job, restart counter is at 7.
-- Automatic restarting of the unit containerd.service has been scheduled, as the result for
Nov 02 21:38:01 minikube systemd[1]: Stopped containerd container runtime.
-- Subject: A stop job for unit containerd.service has finished
-- A stop job for unit containerd.service has finished.
Nov 02 21:38:01 minikube systemd[1]: Starting containerd container runtime...
-- Subject: A start job for unit containerd.service has begun execution
-- A start job for unit containerd.service has begun execution.
Nov 02 21:38:01 minikube containerd[526]: containerd: invalid plugin key URI "diff-service" expect io.containerd.x.vx
Nov 02 21:38:01 minikube systemd[1]: containerd.service: Main process exited, code=exited, status=1/FAILURE
-- An ExecStart= process belonging to unit containerd.service has exited.
Nov 02 21:38:01 minikube systemd[1]: containerd.service: Failed with result 'exit-code'.
-- The unit containerd.service has entered the 'failed' state with result 'exit-code'.
Nov 02 21:38:01 minikube systemd[1]: Failed to start containerd container runtime.
-- Subject: A start job for unit containerd.service has failed
-- A start job for unit containerd.service has finished with a failure.
Nov 02 21:38:07 minikube systemd[1]: containerd.service: Scheduled restart job, restart counter is at 8.
-- Automatic restarting of the unit containerd.service has been scheduled, as the result for
Nov 02 21:38:07 minikube systemd[1]: Stopped containerd container runtime.
-- Subject: A stop job for unit containerd.service has finished
-- A stop job for unit containerd.service has finished.
Nov 02 21:38:07 minikube systemd[1]: Starting containerd container runtime...
-- Subject: A start job for unit containerd.service has begun execution
-- A start job for unit containerd.service has begun execution.
Nov 02 21:38:07 minikube containerd[535]: containerd: invalid plugin key URI "scheduler" expect io.containerd.x.vx
Nov 02 21:38:07 minikube systemd[1]: containerd.service: Main process exited, code=exited, status=1/FAILURE
-- An ExecStart= process belonging to unit containerd.service has exited.
Nov 02 21:38:07 minikube systemd[1]: containerd.service: Failed with result 'exit-code'.
-- The unit containerd.service has entered the 'failed' state with result 'exit-code'.
Nov 02 21:38:07 minikube systemd[1]: Failed to start containerd container runtime.
-- Subject: A start job for unit containerd.service has failed
-- A start job for unit containerd.service has finished with a failure.
```

**Comment by sharifelgamal** [comment]
should we bump the preload version for this?

**Review by sharifelgamal — APPROVED** [review]

**Pull request merged**
