### PR TITLE
Remove addon manager

### LINKED ISSUE #6333: Remove addon manager
follow up from #6046 [comment](https://github.com/kubernetes/minikube/pull/6046#discussion_r367604663)

### PR DESCRIPTION
**Pull request by priyawadhwa**
Fixes #6333

### CODE REVIEW

**Comment by medyagh** [comment]
in the .txt log files I see 
```
}
HTTP code 403! Retrying in 128 ..
{
  "message": "API rate limit exceeded for user ID 20374350.",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
HTTP code 403! Retrying in 256 ..
Build step 'Execute shell' marked build as failure

```

which are realted github api rate limit 
https://github.com/kubernetes/minikube/issues/6308

**Comment by tstromberg** [comment]
/ok-to-test

I'm concerned about the Hyper-V errors, but they may be just general timeouts.  I want to see the data on the other drivers.

**Comment by priyawadhwa** [comment]
In case we need this in future, here are the integration test logs for the other drivers:

[VirtualBox MaxOS](https://a646c87040050000000000000000001.proxy.googleprod.com/job/VirtualBox_macOS_integration/8118/)

[none](https://a646c87040050000000000000000001.proxy.googleprod.com/job/none_Linux_integration/6893/)

[hyperkit macos](https://a646c87040050000000000000000001.proxy.googleprod.com/job/HyperKit_macOS_integration/6416/)

[virtualbox linux](https://a646c87040050000000000000000001.proxy.googleprod.com/job/VirtualBox_Linux_integration/7793/)

**Pull request merged**
