### PR TITLE
Add the description, no only virtualbox.

### PR DESCRIPTION
**Pull request by warmchang**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
@warmchang The documentation for `minikube_start.md` is generated from https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start.go#L71 and should be changed there.

**Comment by warmchang** [comment]
@aaron-prindle thank you for your advice, I've changed the "start.go" and committed.
Pls review it.

**Comment by r2d4** [comment]
Hey @warmchang can you rebase this?

**Comment by warmchang** [comment]
Hi @r2d4 , got an errors after rebase, any advice to solve it? Or I can close it and recommit a new PR, it look like easier.

> $ git rebase master
> First, rewinding head to replay your work on top of it...
> Applying: Add the VM driver description, no only virtualbox.
> 
> $ git add cmd/minikube/cmd/start.go
> 
> $ git commit --amend
> [minikube_start 82e2aa0d] Add the VM driver description, no only virtualbox.
>  Date: Tue Apr 4 11:40:05 2017 +0800
>  1 file changed, 2 insertions(+), 2 deletions(-)
> 
> $ git push origin minikube_start:minikube_start
> To https://github.com/warmchang/minikube
>  ! [rejected]          minikube_start -> minikube_start (non-fast-forward)
> error: failed to push some refs to 'https://github.com/warmchang/minikube'
> hint: Updates were rejected because the tip of your current branch is behind
> hint: its remote counterpart. Integrate the remote changes (e.g.
> hint: 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by warmchang** [comment]
oops, close this chaotic one and submit a new PR.

**Pull request closed without merging**
