### PR TITLE
ISO: Upgrade falco-module to version 0.31.0

### PR DESCRIPTION
**Pull request by afbjorklund**
Needed a rename, from sysdig to falcosecurity-libs

Replaces #13331

### CODE REVIEW

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by sharifelgamal** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Review by spowelljr — APPROVED** [review]

**Pull request merged**
