### PR TITLE
fix(site): Add favicons using Minikube logo image

### PR DESCRIPTION
**Pull request by shuuji3**
Hello 🙂 Currently, the favicon of the website is the Docsy default file image. This PR adds favicons using the Minikube logo image to the website. 

## Screenshot

**Before**

Screen Shot 2021-05-12 at 22 18 02

**After**

Screen Shot 2021-05-12 at 22 18 13

## How to test

You should be able to compare the favicon between Netlify preview (https://deploy-preview-11398--kubernetes-sigs-minikube.netlify.app/docs/) and the current site (https://minikube.sigs.k8s.io/docs/).

## Comments

I used [icongen](https://cthedot.de/icongen/#output) web service to generate favicons from https://github.com/kubernetes/minikube/blob/master/images/logo/logo.png. This service is recommended by Docsy documentation ([Logos and Images | Docsy](https://www.docsy.dev/docs/adding-content/iconsimages/)).

### CODE REVIEW

**Review by ilya-zuyev — APPROVED** [review]
lgtm. thanks!

**Comment by medyagh** [comment]
nice ! I like the favicon thank you @shuuji3

**Comment by shuuji3** [comment]
Thanks for merging! I like the beautiful Minikube logo. 🥰

**Pull request merged**
