### PR TITLE
Fix status issue with none driver where additional text is being prin…

### PR DESCRIPTION
**Pull request by aaron-prindle**
…ted to console with &>

### CODE REVIEW

**Comment by aaron-prindle** [comment]
I'm not sure what changed but currently stderr output is being printed to console w/ none driver commands which didn't occur in the past.

**Comment by aaron-prindle** [comment]
fixes #1859

**Comment by r2d4** [comment]
Looks like this was me https://github.com/kubernetes/minikube/blob/master/hack/jenkins/common.sh#L74

I think a better fix might be not calling CombinedOutput (which combines them both), but rather just Run (which only prints out stdout)
https://github.com/aaron-prindle/minikube/blob/45c8d476d6212ce84a1db55c0f8eebc327b3576b/pkg/minikube/machine/drivers/none/none.go#L201

**Comment by aaron-prindle** [comment]
Combined output is used here so that the error messages contain the cmd error.

**Comment by dlorenc** [comment]
You could grab Error and Output separately, and log error if you need to.

**Comment by aaron-prindle** [comment]
done.

**Comment by aaron-prindle** [comment]
pushed w/ rebase

**Comment by aaron-prindle** [comment]
tests are still timing out here for none driver

**Pull request merged**
