### PR TITLE
Automatically set flags for MINIKUBE_ prefixed env vars

### PR DESCRIPTION
**Pull request by dfang**
`minikube start` respects MINIKUBE_  prefixed envs for now.

eg. if you want to config registry mirror, you can minikube start `--registry-mirror` or export `MINIKUBE_REGISTRY_MIRROR`,  as well,  `--image-mirror-country`, `--image-repository`,  can be exported as `MINIKUBE_IMAGE_REPOSITORY` and `MINIKUBE_IMAGE_MIRROR_COUNTRY` ...

and these args and envs should be on documentation, this really can save a lot of time for chinese who struggles on pulling images,  especially these two new args (`--image-mirror-country`, `--image-repository`), they are not in release notes, i don't know them until read the source, this is for people don't run minikube start -h on every new release .

btw, i can help on this documentation, this is very helpful for new users in China

### CODE REVIEW

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by dfang** [comment]
@minikube-bot ok to test

**Comment by dfang** [comment]
@RA489 @balopat  the first ci test is failed, how can i check the log ?

**Comment by RA489** [comment]
@dfang https://storage.googleapis.com/minikube-builds/logs/4607/Linux-None.txt

**Comment by dfang** [comment]
```
02:33:51 | ! W0701 02:33:51.758826   12290 exit.go:100] Error restarting cluster: addon phase: running command: sudo kubeadm init phase addon all --config /var/lib/kubeadm.yaml: exit status 1
 02:33:51 | ! X Error restarting cluster: addon phase: running command: sudo kubeadm init phase addon all --config /var/lib/kubeadm.yaml: exit status 1
 02:33:51 | > * Problems detected in "kube-apiserver":
 02:33:51 | ! * Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
 02:33:51 | !   - https://github.com/kubernetes/minikube/issues/new
 02:33:51 | >   - error: failed to create listener: failed to listen on 0.0.0.0:8443: listen tcp 0.0.0.0:8443: bind: address already in use
 02:33:51 | > * Problems detected in "kube-addon-manager":
 02:33:51 | >   - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp [::1]:8443: connect: connection refused
 02:33:51 | >   - error: error when retrieving current configuration of:
--- FAIL: TestVersionUpgrade (143.70s)
    util.go:130: Error running command: start --vm-driver=none  --v=10 --logtostderr --bootstrapper=kubeadm --kubernetes-version=1.15.0 --alsologtostderr --v=2 . Output: * minikube v1.2.0 on linux (amd64)
        * minikube will upgrade the local cluster from Kubernetes 1.10.13 to 1.15.0
        * Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
        * Restarting existing none VM for "minikube" ...
        * Waiting for SSH access ...
        * Configuring environment for Kubernetes v1.15.0 on Docker 18.06.1-ce
        * Pulling images ...
        * Relaunching Kubernetes v1.15.0 using kubeadm ... 
        * Problems detected in "kube-apiserver":
          - error: failed to create listener: failed to listen on 0.0.0.0:8443: listen tcp 0.0.0.0:8443: bind: address already in use
        * Problems detected in "kube-addon-manager":
          - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp [::1]:8443: connect: connection refused
          - error: error when retrieving current configuration of:
```

why this pr can pass driver-hyperkit、driver-kvm2 but not driver-none ?

can you rerun the test ?

**Comment by tstromberg** [comment]
Looks good once merge conflict is addressed.

**Comment by RA489** [comment]
@dfang Please rebase.

**Comment by dfang** [comment]
@RA489  Hi, Rebase on which branch ?

```
~/src/OSS/GITHUB/minikube λ  gb
  develop
* feature/better_minikube_status
  feature/registry_mirror_env
  feature/remove_logrus
  master
```

i use git-flow to keep feature branches, how to keep a clean history in this scenario ?

Thanks

**Comment by RA489** [comment]
@dfang please allign your local branch feature/registry_mirror_env with latest master branch.

**Comment by RA489** [comment]
@minikube-bot OK to test

**Comment by dfang** [comment]
@RA489 jenkins build failed, no idea on how to fix. can you help ?

**Pull request merged**
