### PR TITLE
Separate between Docker Desktop and Docker Engine

### LINKED ISSUE #7440: Getting Started for Linux suggests non-existing Docker Desktop
Currently the documentation for the "docker" driver suggests installing Docker Desktop:

https://minikube.sigs.k8s.io/docs/start/linux/

https://hub.docker.com/search?q=&type=edition&offering=community&sort=updated_at&order=desc

However, that Docker product is **only** available for Windows and Mac - and not for Linux.

* https://hub.docker.com/editions/community/docker-ce-desktop-windows

* https://hub.docker.com/editions/community/docker-ce-desktop-mac

So it should instead link to Docker Engine, listed under Server (rather than Desktop):

* https://hub.docker.com/editions/community/docker-ce-server-ubuntu
* https://hub.docker.com/editions/community/docker-ce-server-debian

* https://hub.docker.com/editions/community/docker-ce-server-fedora
* https://hub.docker.com/editions/community/docker-ce-server-centos

----

It might of course already be available as distribution supported package...
Typically called something like `docker.io` (or `docker-ce` - or `docker`)

* https://packages.ubuntu.com/search?keywords=docker.io
* https://packages.debian.org/search?keywords=docker.io

Newer versions of Fedora and CentOS prefer `podman` over `docker`.
So on those distributions, you might want to use the "podman" driver.

### PR DESCRIPTION
**Pull request by afbjorklund**
See https://www.docker.com/products for the list

Closes #7440

### CODE REVIEW

**Comment by tstromberg** [comment]
Missed one:

```
10:35:31 AM: Error: Error building site: "/opt/build/repo/site/content/en/docs/Reference/Drivers/docker.md:14:1": failed to render shortcode "readfile": failed to process shortcode: "/opt/build/repo/site/themes/docsy/layouts/shortcodes/readfile.md:7:12": execute of template failed: template: shortcodes/readfile.md:7:12: executing "shortcodes/readfile.md" at <readFile>: error calling readFile: file "docs/Reference/Drivers/includes/docker_usage.inc" does not exist
```

**Comment by afbjorklund** [comment]
> Missed one:

Oops.

**Comment by medyagh** [comment]
@afbjorklund  PR looks good to be merged after rebase

**Comment by afbjorklund** [comment]
Should we link directly to the installation instructions, instead of to the Docker Store ?

https://hub.docker.com/search?q=&type=edition&offering=community

**Comment by tstromberg** [comment]
Linking directly to the download page sounds good to me.

**Comment by afbjorklund** [comment]
> Linking directly to the download page sounds good to me.

The store page actually did have some content, like system requirements and such...

So linking directly to the documentation might miss a few details, so will wait with that.

**Comment by afbjorklund** [comment]
I changed my mind. We don't separate between Podman and Podman Remote either.

So we might as well link to "Docker", even though the experience is vastly different...

* Docker Desktop will install a VM-based solution that runs in a hypervisor.

* Docker Engine will install the local daemon, that runs directly on the host.

**Pull request merged**
