### PR TITLE
Add support for --ports parameter for "node add" command

### LINKED ISSUE #16766: minikube node add fails if --ports was given to initial minikube start
### What Happened?

I started a single node cluster

```
minikube start --cpus 4 --memory 16384 --ports 80:80 --driver docker
```

and wanted to add an additional node afterwards

```
minikube node add
```

It uses a different configuration for the added node as the memory shows:

```
Creating docker container (CPUs=4, Memory=2200MB) ...
```

The creation fails since port 80 is bound to the first node

```
stderr:
docker: Error response from daemon: driver failed programming external connectivity on endpoint minikube-m02 (5f7a38f17f200fee0130c69df5aad7f54357fa86e0517d7cb3d08c483504f648): Bind for 0.0.0.0:80 failed: port is already allocated.
```

It would be great if the added node would not inherit the "--ports" configuration to make this scenario possible.

[log.txt](https://github.com/kubernetes/minikube/files/11856669/log.txt)

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11856669/log.txt)

### Operating System

Ubuntu

### Driver

Docker

### PR DESCRIPTION
**Pull request by rmsilva1973**
I do have some concerns regarding this I would appreaciate the maintainers provide some advise one:

- Repeating "ExposedPorts" member on Node struct. Perhaps it should be moved completely from "ClusterConfig" struct to Node?
- Had to change comparision between n and cp since struct with []array members can't be compared (according to the compiler):

https://github.com/rmsilva1973/minikube/blob/84074c99df089695e77b8c0902599dc7ed6c569a/pkg/minikube/machine/build_images.go#L83

fixes #16766

### CODE REVIEW

**Comment by medyagh** [comment]
> I do have some concerns regarding this I would appreaciate the maintainers provide some advise one:
> 
> * Repeating "ExposedPorts" member on Node struct. Perhaps it should be moved completely from "ClusterConfig" struct to Node?
> * Had to change comparision between n and cp since struct with []array members can't be compared (according to the compiler):
> 
> https://github.com/rmsilva1973/minikube/blob/84074c99df089695e77b8c0902599dc7ed6c569a/pkg/minikube/machine/build_images.go#L83
> 
> fixes #16766

@rmsilva1973 do you mind posting the output of minikube BEFORE and AFTER this PR for the speicifc case that was discussed in the issue ?

**Comment by rmsilva1973** [comment]
@medyagh Here's a before screenshot. Will post "after" screenhot in a few minutes...

image

**Comment by rmsilva1973** [comment]
After, creating additional node without specifying mapped ports:

image

**Comment by rmsilva1973** [comment]
And "node add" now supports "--ports" parameter:

image

**Comment by rmsilva1973** [comment]
Besides my initial concerns, the whole issue deserves to be revisited. That being said, I've already began taking a stab at #7891. Soon I'll commit a branch with a proposal (will not push a PR there before discussing with the maintainers since it'll contain quite a few changes with risk of breaking things..)

**Comment by rmsilva1973** [comment]
@medyagh Hold on. Something looks fishy... "Make test" is failing on random values on the TestValidatePorts. Have to take a closer look at this.

**Comment by rmsilva1973** [comment]
@medyagh Not sure what would be the best behaviour, but the ports mapping are applied to the control plane node only...

image

On a side note (since I commented that on this issue) I opened issue #17268 regarding the "make test" failure and raised some propositions on how to address that.

**Comment by rmsilva1973** [comment]
Hi @medyagh . I added the hold label but my concern regarding the failing tests seems unrelated. I created an specific issue where I dug a little bit on it: #17268 

I don't know how to remove the hold label but aside from the points I already mentioned when creating this PR I don't have additional concerns.

**Comment by medyagh** [comment]
> /hold cancel

@rmsilva1973 let me know when you are ready for a review, for now I will stop till you are ready

**Comment by rmsilva1973** [comment]
Hi @medyagh I cancelled the hold. I would be glad to receive your feedback/review on this PR.

**Comment by medyagh** [comment]
> Hi @medyagh I cancelled the hold. I would be glad to receive your feedback/review on this PR.

thank you @rmsilva1973 do you mind updating the Before After for the new changes with different ways of setting the port
including from the minikube start -n=2 ...
and also After start by adding a new node

**Comment by rmsilva1973** [comment]
Hi @medyagh I'm sorry but I don't get it. I think the screenshots I already posted address what you're requesting. I didn't do any additional changes to the PR and those screenshots already represent before and after including the scenarios you requested (AFAIK). I was just checking if the test failures weren't introduced by my PR. But as far as I could see, they weren't. Please kindly let me know what additional screenshots you need and I'll gladly add them here. 👍😉

**Comment by rmsilva1973** [comment]
@medyagh were you able to check my last message on this PR?

**Comment by rmsilva1973** [comment]
@spowelljr or @sharifelgamal could you guys take a look at this PR? It seems like a first step to address #7891

**Comment by rmsilva1973** [comment]
@medyagh Hi! I assume it's a no go on this PR?

**Pull request closed without merging**
