### PR TITLE
Windows: detect Powershell spawned from CMD

### LINKED ISSUE #11984: Fix TestFunctional/parallel/DockerEnv test on Windows
TestFunctional/parallel/DockerEnv fails 100% of the time on Windows

### PR DESCRIPTION
**Pull request by spowelljr**
Fixes #11984

**Problem:**
It's possible to run Powershell from within CMD, but when you do so the `SHELL` environmental variable is still set to CMD. This causes a problem with the `docker-env` command as we tailor the output based on the shell being used. In this case, CMD command output is being used in Powershell and is failing to set docker-env variables.

**Solution:**
Updated the detection logic to do a more in-depth shell detection if SHELL environment variable is set to `cmd`.
This PR outlines the changes made: https://github.com/spowelljr/machine/pull/1
Changing `replace` directive to my fork until PR gets merged on main fork: https://github.com/machine-drivers/machine/pull/34

**Before: (CMD commands were output)**
```
PS > $env:SHELL
c:\windows\system32\cmd.exe
PS > minikube.exe docker-env
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://127.0.0.1:58542
SET DOCKER_CERT_PATH=C:\Users\jenkins\.minikube\certs
SET MINIKUBE_ACTIVE_DOCKERD=minikube
REM To point your shell to minikube's docker-daemon, run:
REM @FOR /f "tokens=*" %i IN ('minikube -p minikube docker-env') DO @%i
```

**After: (Powershell commands were output)**
```
PS > $env:SHELL
c:\windows\system32\cmd.exe
PS > minikube.exe docker-env
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://127.0.0.1:58542"
$Env:DOCKER_CERT_PATH = "C:\Users\jenkins\.minikube\certs"
$Env:MINIKUBE_ACTIVE_DOCKERD = "minikube"
# To point your shell to minikube's docker-daemon, run:
# & minikube -p minikube docker-env | Invoke-Expression
```

### CODE REVIEW

**Comment by medyagh** [comment]
@spowelljr does this actually fix it ?

**Comment by spowelljr** [comment]
> @spowelljr does this actually fix it ?

It does now, updated the file changes and PR description to reflect the new changes.

**Comment by afbjorklund** [comment]
Merged it to machine-drivers 753b247c76dda3215758a48a1272bf99459c6e5f, nothing on docker/machine yet.

**Comment by spowelljr** [comment]
Switched fork back to `machine-drivers` since PR was merged

**Comment by spowelljr** [comment]
Test passed: `PASS: TestFunctional/parallel/DockerEnv (18.15s)`

**Pull request merged**
