### PR TITLE
Add support for official kicbase releases in script

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Comment by sharifelgamal** [comment]
Hi @sharifelgamal,\n\nA new kicbase image is available, please update your PR with the new tag and SHA.\nIn pkg/drivers/kic/types.go:\n\n\t// Version is the current version of kic\n\tVersion = "v1.2.3.4"\n\t// SHA of the kic base image\n\tbaseImageSHA = "sha1234"\n\t// The name of the GCR kicbase repository\n\tgcrRepo = "gcr_repo"\n\t// The name of the Dockerhub kicbase repository\n\tdockerhubRepo = "dh_repo"\nThen run `make generate-docs` to update our documentation to reference the new image.\n\nAlternatively, run the following command and commit the changes:```\n sed 's|Version = .*|Version = "v1.2.3.4"|;s|baseImageSHA = .*|baseImageSHA = "sha1234"|;s|gcrRepo = .*|gcrRepo = "gcr_repo"|;s|dockerhubRepo = .*|dockerhubRepo = "dh_repo"|' pkg/drivers/kic/types.go > new-types.go; mv new-types.go pkg/drivers/kic/types.go; make generate-docs;\n```\n

**Comment by sharifelgamal** [comment]
Hi

**Comment by sharifelgamal** [comment]
Hi

**Comment by sharifelgamal** [comment]
Hi @sharifelgamal,
        
        A new kicbase image is available, please update your PR with the new tag and SHA.
        In pkg/drivers/kic/types.go:
        ```
        // Version is the current version of kic
        Version = "v1.2.3.4"
        // SHA of the kic base image
        baseImageSHA = "sha1234"
        // The name of the GCR kicbase repository
        gcrRepo = "gcr_repo"
        // The name of the Dockerhub kicbase repository
        dockerhubRepo = "dh_repo"
        ```
        Then run `make generate-docs` to update our documentation to reference the new image.
        
        Alternatively, run the following command and commit the changes:``` 
        sed 's|Version = .*|Version = "v1.2.3.4"|;s|baseImageSHA = .*|baseImageSHA = "sha1234"|;s|gcrRepo = .*|gcrRepo = "gcr_repo"|;s|dockerhubRepo = .*|dockerhubRepo = "dh_repo"|' pkg/drivers/kic/types.go > new-types.go; mv new-types.go pkg/drivers/kic/types.go; make generate-docs;
        ```

**Comment by sharifelgamal** [comment]
Hi @sharifelgamal,
        A new kicbase image is available, please update your PR with the new tag and SHA.
        In pkg/drivers/kic/types.go:
        
        ```
        // Version is the current version of kic
        Version = "v1.2.3.4"
        // SHA of the kic base image
        baseImageSHA = "sha1234"
        // The name of the GCR kicbase repository
        gcrRepo = "gcr_repo"
        // The name of the Dockerhub kicbase repository
        dockerhubRepo = "dh_repo"
        ```
        
        Then run `make generate-docs` to update our documentation to reference the new image.
        
        Alternatively, run the following command and commit the changes:``` 
        sed 's|Version = .*|Version = "v1.2.3.4"|;s|baseImageSHA = .*|baseImageSHA = "sha1234"|;s|gcrRepo = .*|gcrRepo = "gcr_repo"|;s|dockerhubRepo = .*|dockerhubRepo = "dh_repo"|' pkg/drivers/kic/types.go > new-types.go; mv new-types.go pkg/drivers/kic/types.go; make generate-docs;
        ```

**Comment by sharifelgamal** [comment]
Hi @sharifelgamal,
        A new kicbase image is available, please update your PR with the new tag and SHA.
        In pkg/drivers/kic/types.go:
        ```
        // Version is the current version of kic
        Version = "v1.2.3.4"
        // SHA of the kic base image
        baseImageSHA = "sha1234"
        // The name of the GCR kicbase repository
        gcrRepo = "gcr_repo"
        // The name of the Dockerhub kicbase repository
        dockerhubRepo = "dh_repo"
        ```
        Then run `make generate-docs` to update our documentation to reference the new image.
        
        Alternatively, run the following command and commit the changes:``` 
        sed 's|Version = .*|Version = "v1.2.3.4"|;s|baseImageSHA = .*|baseImageSHA = "sha1234"|;s|gcrRepo = .*|gcrRepo = "gcr_repo"|;s|dockerhubRepo = .*|dockerhubRepo = "dh_repo"|' pkg/drivers/kic/types.go > new-types.go; mv new-types.go pkg/drivers/kic/types.go; make generate-docs;
        ```

**Comment by sharifelgamal** [comment]
Hi @sharifelgamal,
A new kicbase image is available, please update your PR with the new tag and SHA.
In pkg/drivers/kic/types.go:
        
        
        // Version is the current version of kic
        Version = "v1.2.3.4"
        // SHA of the kic base image
        baseImageSHA = "sha1234"
        // The name of the GCR kicbase repository
        gcrRepo = "gcr_repo"
        // The name of the Dockerhub kicbase repository
        dockerhubRepo = "dh_repo"
        
Then run `make generate-docs` to update our documentation to reference the new image.
        
Alternatively, run the following command and commit the changes:``` 
        sed 's|Version = .*|Version = "v1.2.3.4"|;s|baseImageSHA = .*|baseImageSHA = "sha1234"|;s|gcrRepo = .*|gcrRepo = "gcr_repo"|;s|dockerhubRepo = .*|dockerhubRepo = "dh_repo"|' pkg/drivers/kic/types.go > new-types.go; mv new-types.go pkg/drivers/kic/types.go; make generate-docs;
        ```

**Comment by sharifelgamal** [comment]
Hi @sharifelgamal,

A new kicbase image is available, please update your PR with the new tag and SHA.
In pkg/drivers/kic/types.go:
        
        
        // Version is the current version of kic
        Version = "v1.2.3.4"
        // SHA of the kic base image
        baseImageSHA = "sha1234"
        // The name of the GCR kicbase repository
        gcrRepo = "gcr_repo"
        // The name of the Dockerhub kicbase repository
        dockerhubRepo = "dh_repo"
        
Then run `make generate-docs` to update our documentation to reference the new image.
        
Alternatively, run the following command and commit the changes:
        sed 's|Version = .*|Version = "v1.2.3.4"|;s|baseImageSHA = .*|baseImageSHA = "sha1234"|;s|gcrRepo = .*|gcrRepo = "gcr_repo"|;s|dockerhubRepo = .*|dockerhubRepo = "dh_repo"|' pkg/drivers/kic/types.go > new-types.go; mv new-types.go pkg/drivers/kic/types.go; make generate-docs;

**Comment by sharifelgamal** [comment]
Hi @sharifelgamal,

A new kicbase image is available, please update your PR with the new tag and SHA.
In pkg/drivers/kic/types.go:
        
        
        // Version is the current version of kic
        Version = "v1.2.3.4"
        // SHA of the kic base image
        baseImageSHA = "sha1234"
        // The name of the GCR kicbase repository
        gcrRepo = "gcr_repo"
        // The name of the Dockerhub kicbase repository
        dockerhubRepo = "dh_repo"
        
Then run `make generate-docs` to update our documentation to reference the new image.
        
Alternatively, run the following command and commit the changes:
        
        
        sed 's|Version = .*|Version = "v1.2.3.4"|;s|baseImageSHA = .*|baseImageSHA = "sha1234"|;s|gcrRepo = .*|gcrRepo = "gcr_repo"|;s|dockerhubRepo = .*|dockerhubRepo = "dh_repo"|' pkg/drivers/kic/types.go > new-types.go; mv new-types.go pkg/drivers/kic/types.go; make generate-docs;

**Comment by sharifelgamal** [comment]
ok-to-build-image

**Review by medyagh — APPROVED** [review]

**Pull request merged**
