### PR TITLE
Use Reference, allow caching images with both Tag and Digest

### LINKED ISSUE #3822: "cache add" with sha256 sum: "Failed to cache... repository can only contain the runes"
Right now the minikube cache command allows to cache only  images with tag, it will be great to support caching images with SHAs

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #3822

### CODE REVIEW

**Comment by tstromberg** [comment]
Any chance of adding an integration test to affirm that we don't break this in the future?

**Comment by tstromberg** [comment]
FWIW, It has just come to my attention that `minikube cache` isn't covered by our integration tests. 

😱

**Comment by afbjorklund** [comment]
Sounds like a good idea, for now I just tested it manually and locally.

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
Thanks for the PR! Please merge when ready.

**Pull request merged**
