### PR TITLE
Use preloaded tarball for cri-o container runtime

### LINKED ISSUE #6934: Preload CRI-O images
implement preload for CRI-O runtime

### PR DESCRIPTION
**Pull request by afbjorklund**
Pretty much the same as containerd, minus Restart

Some code should probably move to CRI generic ?

Closes #6934

Requires #8581

### CODE REVIEW

**Comment by afbjorklund** [comment]
Tested OK, with local preload (~/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v4-v1.18.3-cri-o-overlay-amd64.tar.lz4)

`Took 5.294572 seconds to copy over tarball`

`Took 4.255031 seconds t extract the tarball`

`all images are preloaded for crio runtime.`

`Images already preloaded, skipping extraction`

**Comment by medyagh** [comment]
@afbjorklund thanks this PR needs a pull upstream

**Comment by afbjorklund** [comment]
It seems like this was already merged in PR #8581 (eaeb5f6060ef43cc4ad91696b23e54e2476b74fc)

Must have pushed my test code there by mistake.

**Comment by medyagh** [comment]
```
TestStartStop/group/crio/serial/FirstStart	208.4

with preload on CRIO

thats 20 seconds faster

the First Start Test

TestStartStop/group/crio/serial/SecondStart	61.85

and second start is 115 seconds faster !!!

preload makes Second Start significaantly faster

in CRIO

```

**Pull request merged**
