### PR TITLE
Remove all redundant code (const, var)

### PR DESCRIPTION
**Pull request by xichengliudui**
ref: #5471

### CODE REVIEW

**Comment by josedonizetti** [comment]
@minikube-bot Ok to test

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
@xichengliudui it seems like it needs resolving conflicts

**Comment by xichengliudui** [comment]
Ok, I'll take care of it right away

**Comment by xichengliudui** [comment]
@medyagh updated.

**Comment by xichengliudui** [comment]
As before, the build is again a problem.
```
--- FAIL: TestVersionUpgrade (152.05s)
    version_upgrade_test.go:69: (dbg) Run:  /tmp/minikube-release.260641532.exe start -p minikube --kubernetes-version=v1.11.10 --alsologtostderr -v=1 --vm-driver=none 
    version_upgrade_test.go:69: (dbg) Done: /tmp/minikube-release.260641532.exe start -p minikube --kubernetes-version=v1.11.10 --alsologtostderr -v=1 --vm-driver=none : (1m58.226524936s)
    version_upgrade_test.go:78: (dbg) Run:  /tmp/minikube-release.260641532.exe stop -p minikube
    version_upgrade_test.go:78: (dbg) Done: /tmp/minikube-release.260641532.exe stop -p minikube: (10.485996905s)
    version_upgrade_test.go:83: (dbg) Run:  /tmp/minikube-release.260641532.exe -p minikube status --format={{.Host}}
    version_upgrade_test.go:83: (dbg) Non-zero exit: /tmp/minikube-release.260641532.exe -p minikube status --format={{.Host}}: exit status 1 (57.974981ms)
        -- stdout --
        Stopped
        -- /stdout --
    version_upgrade_test.go:85: status error: exit status 1 (may be ok)
    version_upgrade_test.go:93: (dbg) Run:  out/minikube-linux-amd64 start -p minikube --kubernetes-version=v1.16.1 --alsologtostderr -v=1 --vm-driver=none 
    version_upgrade_test.go:93: (dbg) Non-zero exit: out/minikube-linux-amd64 start -p minikube --kubernetes-version=v1.16.1 --alsologtostderr -v=1 --vm-driver=none : exit status 70 (14.546722516s)
        -- stdout --
        * minikube v1.5.0-beta.0 on Debian 9.11
          - KUBECONFIG=/home/jenkins/minikube-integration/linux-amd64-none-5488-20755-71dfdb683299f0f0616a9cbe865d2897ac2a8e64/kubeconfig
          - MINIKUBE_BIN=out/minikube-linux-amd64
          - MINIKUBE_HOME=/home/jenkins/minikube-integration/linux-amd64-none-5488-20755-71dfdb683299f0f0616a9cbe865d2897ac2a8e64/.minikube
          - MINIKUBE_LOCATION=5488
        * Upgrading from Kubernetes 1.11.10 to 1.16.1
        * Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
        * Starting existing none VM for "minikube" ...
        * Waiting for the host to be provisioned ...
        * Preparing Kubernetes v1.16.1 on Docker 18.06.1-ce ...
        * Pulling images ...
        * Relaunching Kubernetes using kubeadm ... 
        * Problems detected in kube-controller-manager [620bab893bdb]:
          - failed to create listener: failed to listen on 0.0.0.0:10252: listen tcp 0.0.0.0:10252: bind: address already in use
        * Problems detected in kube-scheduler [1ef9b95055d8]:
          - failed to create listener: failed to listen on 0.0.0.0:10251: listen tcp 0.0.0.0:10251: bind: address already in use
```
**address already in use**

**Comment by xichengliudui** [comment]
What can I do for you?

**Pull request closed without merging**
