### PR TITLE
Add ingress-dns addon

### PR DESCRIPTION
**Pull request by woodcockjosh**
This addon enables minikube to act as a DNS service for the host OS for ingress hostnames. The ingress hostnames resolve the the minikube ip address. Upon lookup failure the dns lookup falls back to google's DNS servers.

### CODE REVIEW

**Comment by woodcockjosh** [comment]
The Travis test are failing on `TestNewSSHClient` which I have no idea what it has to do with an addon.

**Comment by woodcockjosh** [comment]
Might resolve: https://github.com/kubernetes/minikube/issues/3821
Partially resolves: https://github.com/kubernetes/minikube/issues/5494

**Comment by woodcockjosh** [comment]
Can enable addon to install local ssl certificates: https://github.com/kubernetes/minikube/issues/1701

**Comment by medyagh** [comment]
@minikube-bot OK to test

**Comment by medyagh** [comment]
The travis fail is is a flake test

**Comment by medyagh** [comment]
this is exciting addon ! makes a a lot of things easier. thank you

**Comment by woodcockjosh** [comment]
@medyagh I believe you need /ok-to-test

**Comment by medyagh** [comment]
> @medyagh I believe you need
> /ok-to-test

we have a different setup than kubernetes, I know it confuses people, we have a jenkins that is setup to respond to the keyword comment from the maintainers

**Comment by medyagh** [comment]
@woodcockjosh how about adding a short tutorial to the site too for how to use this addon ?

**Comment by woodcockjosh** [comment]
> @woodcockjosh how about adding a short tutorial to the site too for how to use this addonn?

I certainly don't mind doing this, but can we do as a separate PR? I think we need some type of beta period to make sure everything is good. We have tested this only in a limited context and we may discover that things don't work as expected on all operating systems and vm configurations. Also I think there are some things that I might put in a tutorial which could become irrelevant if this is implemented https://github.com/kubernetes/minikube/pull/5511

> one small concern I have is the images that are used, seems to be from https://github.com/superbrothers/minikube-ingress-dns

As mentioned in our slack discussion the image is here: https://cloud.docker.com/u/cryptexlabs/repository/docker/cryptexlabs/minikube-ingress-dns

The repository as mentioned on dockerhub is here: 
https://gitlab.com/cryptexlabs/public/development/minikube-ingress-dns

**Comment by medyagh** [comment]
looks good ! thank you for this great addon and adding more information about the addon source of image

**Pull request merged**
