### PR TITLE
Upgrade Docker, from 17.12.1-ce to 18.06.1-ce

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Docker >= 18.06 is needed for securityContext.procMount (Kubernetes >= 1.12)

See kubernetes/kubernetes#64283 and docker/docker-ce@67fe100

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by afbjorklund** [comment]
Wow, even `kubeadm` have updated their instructions (for docker, as a container runtime alternative):

> On each of your machines, install Docker. Version 18.06 is recommended, but 1.11, 1.12, 1.13 and 17.03 are known to work as well. Keep track of the latest verified Docker version in the Kubernetes release notes.

This replaces the previous text, that was a lot more conservative (and we ignored, for 17.06 - 17.12)

> On each of your machines, install Docker. Version v1.12 is recommended, but v1.11, v1.13 and 17.03 are known to work as well. Versions 17.06+ might work, but have not yet been tested and verified by the Kubernetes node team.

https://github.com/kubernetes/kubernetes/commit/97c9fa3cb98497460cc8aaed2ae3c1514d6055c6

``` diff
diff --git a/cmd/kubeadm/app/util/system/docker_validator.go b/cmd/kubeadm/app/util/system/docker_validator.go
index d6895fa90d4f1..69b84dc660132 100644
--- a/cmd/kubeadm/app/util/system/docker_validator.go
+++ b/cmd/kubeadm/app/util/system/docker_validator.go
@@ -38,7 +38,7 @@ func (d *DockerValidator) Name() string {
 
 const (
 	dockerConfigPrefix        = "DOCKER_"
-	maxDockerValidatedVersion = "17.03"
+	maxDockerValidatedVersion = "18.06"
 )
 
 // TODO(random-liu): Add more validating items.

```

LGTM

**Comment by afbjorklund** [comment]
Note that the above is true for Kubernetes 1.12, but still might **not** be for earlier versions...
So we should only do this when fixing the rest of the support for the newer versions (> 1.10)

e.g. #3164

**Comment by AkihiroSuda** [comment]
Docker for Mac/Win distributes vanilla Kubernetes v1.10.3 along with Docker v18.06.1.
So I suppose it is safe to use Docker v18.06 with Kubernetes v1.10.3?

**Comment by afbjorklund** [comment]
Supposedly, although someone wanted v1.10.5 (#3074) - so might as well go for v1.10.8 (#3132) ?

Most likely the new Docker would also work with older Kubernetes, but it is untested/unsupported...

**Comment by AkihiroSuda** [comment]
Is there way to override Docker version as in `minikube start --kubernetes-version`?

**Comment by afbjorklund** [comment]
Unfortunately no, it is baked into the ISO... However, you could download one and overwrite it ?

https://download.docker.com/linux/static/stable/x86_64/

**Comment by tstromberg** [comment]
The OSX-Virtualbox failure appears to be https://github.com/kubernetes/minikube/issues/3203

I'm not sure about the OSX-Hyperkit failure: it may be the same issue, a new flake, or a new persistent error. 

The PR looks good, but I want to get to the bottom of the test failure before approving it.

**Comment by AkihiroSuda** [comment]
I can't restart the test, probably because I'm not a maintainer..

**Comment by AkihiroSuda** [comment]
@tstromberg could you restart the failing tests?

**Comment by AkihiroSuda** [comment]
Thanks for merging, any ETA of v0.31 with this commit?

**Pull request merged**
