### PR TITLE
Remove vendored kube2sky, Add kube-dns as cluster addon

### LINKED ISSUE #55: Localkube should vendor kube-dns instead of the current kube2sky solution
Ref: https://github.com/kubernetes/kubernetes/pull/23930

### PR DESCRIPTION
**Pull request by r2d4**
Removes the vendored in kube2sky built into the minikube binary and
replaces the dns solution with kube-dns cluster addon.  This will allow
users to swap out DNS implementations by simply turning off the
kube-dns addon.

TBD: **How to handle older localkube versions?**

These versions will try to run their own DNS unless `--enable-dns=false` is passed into localkube.  This will conflict with the addon's clusterIP.  

**Proposed fix in this PR**
I deprecated the flag in newer versions of localkube, and made minikube always pass in `enable-dns=false`.  This will be a no-op in new versions of localkube and disable DNS in favor of the cluster addon in older versions.  We won't need to rebuild any old versions of localkube, but are stuck with a deprecated flag.  

PTAL a look at the first commit which contains the changes.  The second is only removing the unused vendor packages.

Fixes #55

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
Would you mind rebasing onto master and rerunning tests?

**Comment by r2d4** [comment]
Rebased, test rerunning now

**Comment by dlorenc** [comment]
This should fix #55 by making it obsolete.

**Comment by philips** [comment]
Nice!

**Pull request merged**
