### PR TITLE
More storage provisioner fixes.

### PR DESCRIPTION
**Pull request by dlorenc**
I'm not sure of a better way to ensure /tmp exists in a from scratch container,
but glog appears to just explode without it.

### CODE REVIEW

**Comment by dlorenc** [comment]
Fixes #2167

**Comment by r2d4** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
I have to rebuild and push the container again after this.

**Comment by dlorenc** [comment]
OK, it's actually running now: 

```shell
kube-system   storage-provisioner                              1/1       Running             0          25s
```

**Pull request merged**
