### PR TITLE
Update gvisor-config.toml

### PR DESCRIPTION
**Pull request by fvoznika**
containerd `config.toml` file has been updated to the `version=2` format. Update the gVisor replacement copy accordingly.

Fixes google/gvisor#7877

### CODE REVIEW

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
[fvoznika](https://github.com/fvoznika) do you mind pasting the output of enalbing gvisor addon before/after this PR ?

**Comment by fvoznika** [comment]
I don't have the before at the moment, but it would fail and restart right after: `Restarting containerd...`. As you can see, it completes the installation now:

```
fvoznika@minikube:~/git/minikube/out$ minikube addons enable gvisor
💡  gvisor is an addon maintained by Google. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
    ▪ Using image gcr.io/k8s-minikube/gvisor-addon:3
🔎  Verifying gvisor addon...
🌟  The 'gvisor' addon is enabled

fvoznika@minikube:~/git/minikube/out$ ./minikube kubectl -- get pod/gvisor -n kube-system
NAME                               READY   STATUS    RESTARTS   AGE
gvisor                             1/1     Running   0          25s

fvoznika@minikube:~/git/minikube/out$ ./minikube kubectl -- logs pod/gvisor -n kube-system
2022/09/01 22:58:19 Storing default config.toml at /tmp/config.toml
2022/09/01 22:58:19 Copying gvisor-config.toml asset to /node/etc/containerd/config.toml
2022/09/01 22:58:19 gvisor-config.toml asset path: /tmp/gvisor/gvisor-config.toml
2022/09/01 22:58:19 creating /node/etc/containerd/config.toml
2022/09/01 22:58:19 restartContainerd black magic happening
2022/09/01 22:58:19 Stopping rpc-statd.service...
2022/09/01 22:58:20 Restarting containerd...
2022/09/01 22:58:20 Starting rpc-statd...
2022/09/01 22:58:20 containerd restart complete
2022/09/01 22:58:20 gvisor successfully enabled in cluster
```

**Comment by spowelljr** [comment]
Hi @fvoznika, I see that the GvisorAddon test is failing with:
`network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized`

**Comment by fvoznika** [comment]
Ah, I didn't think that `containerd.runtimes.untrusted` was still being used. Update the file to include it...

**Comment by fvoznika** [comment]
Untrusted runtime was removed in containerd 1.4 (containerd/cri#1277). I'm working on a better fix for `gvisor-config.toml` and will remote the untrusted test as part of that. Let's forget this PR for now and I'll send the other change soon.

**Comment by fvoznika** [comment]
Please see #14996

**Pull request closed without merging**
