### PR TITLE
Set NewestKubernetesVersion to v1.16.0-beta.1

### PR DESCRIPTION
**Pull request by tstromberg**
To prepare for v1.16.0 being the default come next month.

### CODE REVIEW

**Comment by tstromberg** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
Looks like travis is expecting tests for NewestKubernetesVersion

**Comment by tstromberg** [comment]
The test failures are unrelated flakes that do not use this variable:

*none*:
```
        --- FAIL: TestFunctional/group/Registry (350.94s)
            fn_addons.go:212: waiting for registry-proxy pods: timed out waiting for the condition
```

*KVM*:

```
        --- FAIL: TestFunctional/group/Registry (350.94s)
            fn_addons.go:212: waiting for registry-proxy pods: timed out waiting for the condition
```

The tests that do passed:

```
--- PASS: TestVersionUpgrade (431.84s)
```

**Comment by tstromberg** [comment]
friendly ping ;)

**Pull request merged**
