### PR TITLE
Update mount implementation, add mount integration tests, and check t…

### PR DESCRIPTION
**Pull request by aaron-prindle**
…hat path exists.

### CODE REVIEW

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
Were there any manual changes to the new go9p library?

**Comment by aaron-prindle** [comment]
Yes the "same" manual changes needed to be done as before in order to get the server working for Windows.

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Comment by aaron-prindle** [comment]
@minikube-bot retest this please

**Pull request merged**
