### PR TITLE
Added msize and 9p-version flags to mount.  Also changed their defaul…

### PR DESCRIPTION
**Pull request by aaron-prindle**
…ts to be more usable

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Fixes #1562 #1515

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
Tests are actually running now.

**Pull request merged**
