### PR TITLE
Uprade to Kubernetes v1.3.4

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
No manual changes required.

**Comment by dlorenc** [comment]
@aaron-prindle can you take a look?

**Comment by aaron-prindle** [comment]
Integration tests are passing:
https://gist.github.com/aaron-prindle/835fb7449e2dba1c34c594a9d48317ff

**Comment by aaron-prindle** [comment]
LGTM

**Pull request merged**
