### PR TITLE
Update arch linux installer to v0.12.2

### PR DESCRIPTION
**Pull request by r2d4**
I added the arch linux minikube package repository as a submodule because that is how it is pushed to the arch AUR.  I don't think there should be any trouble pulling the minikube repo with this, but I will verify

### CODE REVIEW

**Comment by r2d4** [comment]
ref #737

**Comment by dlorenc** [comment]
What repo are you pointing this to?

**Comment by r2d4** [comment]
The installer is hosted in its own repo on the arch AUR

https://aur.archlinux.org/minikube.git

From
https://aur.archlinux.org/packages/minikube/ 

To update, you create a commit with the upgrade and push it to that repo. 

It looks like I didn't set up the submodule correctly though so I'll try again

**Comment by r2d4** [comment]
ref #787

**Comment by r2d4** [comment]
I added the submodule pointing to 

`url = https://aur.archlinux.org/minikube.git` 

which is the public-readonly git repository.  However, in order to push to the repo - you need to overwrite that url locally by running 

`git config submodule.archlinux.url ssh://aur@aur.archlinux.org/minikube.git
`

**Pull request merged**
