### PR TITLE
Standardize ASCII prefix for info, warning, and error messages

### PR DESCRIPTION
**Pull request by tstromberg**
Example output:

```
> minikube v1.0.0 on linux (amd64)
> Downloading Kubernetes v1.14.1 images in the background ...

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the kvm2 driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`

> Re-using the currently running kvm2 VM for "minikube" ...
> Waiting for SSH access ...
> "minikube" IP address is 192.168.39.241
> Configuring Docker as the container runtime ...
```

See #4157

### CODE REVIEW

**Comment by sharifelgamal** [comment]
Looks like you need to fix a couple of our unit tests to account for these changes.

**Comment by tstromberg** [comment]
Thanks! Once I get some feedback on what styles folks prefer, I'll update this PR to match the top votes: 

https://forms.gle/KjFG9ahgqURNr6k78

**Comment by tstromberg** [comment]
The polling appears to have steered away from dashes as a prefix, so I've updated this PR to match, with tests.

**Comment by tstromberg** [comment]
The tests need a little cleanup before this can be merged.

**Comment by tstromberg** [comment]
PTAL - it seems the asterisks won the votes in the end. Not my personal favorite choice, but it's at least a choice to move forwards with =)

**Comment by sharifelgamal** [comment]
LGTM, can you update the PR description with a new sample output?

**Pull request merged**
