### PR TITLE
Bump version to 1.5.0-beta.0

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by sharifelgamal** [comment]
@minikube-bot OK to test

**Comment by tstromberg** [comment]
The gvisor failures I'm OK with for a beta (`Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "runsc" is configured`), but the consistent failure to get kubelet logs should be fixed:

```
--- FAIL: TestFunctional/parallel/LogsCmd: Error getting machine logs: unable to fetch logs for: kubelet
```

**Pull request merged**
