### PR TITLE
Upgrade Headlamp version to 0.20.0

### PR DESCRIPTION
**Pull request by joaquimrocha**
Upgrade Headlamp version to 0.20.0
  cc: @joaquimrocha

### CODE REVIEW

**Comment by joaquimrocha** [comment]
The PR is actually broken due to a failed CI job. I will update the branch shortly.

**Comment by spowelljr** [comment]
@joaquimrocha Just pining here in case you forgot, but no rush

**Comment by joaquimrocha** [comment]
Completely missed this. I had updated it. Not sure why it says the branch is deleted. I'll take a look. Thanks for the ping, @spowelljr .

**Comment by joaquimrocha** [comment]
So the branch looks fine in https://github.com/headlamp-k8s/minikube/tree/update_headlamp_0.20.0 .
Maybe the force push made this PR assume it's deleted? (Though I think I've done that in the past)
Reopening.

**Comment by joaquimrocha** [comment]
Ah, I see there's another [PR](https://github.com/kubernetes/minikube/pull/17320). Well, we have a task to improve our PR automation. Hopefully that'll avoid this mess. Thanks again.

**Pull request closed without merging**
