### PR TITLE
Update CRI-O from v1.24.1 to v1.26.1

### LINKED ISSUE #15922: Upgrade CRI-O to 1.26.1
Minikube currently uses CRI-O v1.24.1, which is a bit old. It would be nice to update CRI-O to v1.26.1.

### PR DESCRIPTION
**Pull request by 2shiori17**
fixes #15922

### CODE REVIEW

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by akdean** [comment]
I think you'll need to bump the `crictl` version too @2shiori17

**Comment by 2shiori17** [comment]
CRI-O will be automatically update when #15932 is merged.

**Pull request closed without merging**
