### PR TITLE
Upgrade to Kubernetes 1.4.1

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by jimmidyson** [comment]
Do xhyve & hyperv builds ever run?

**Comment by aaron-prindle** [comment]
xyhve does, there was an issue with the xhyve integration tests that was recently fixed #686 
hyperv is a work in progress due to some issues encountered when attempting to run hyperv as a Jenkins slave

**Comment by jimmidyson** [comment]
Looks like it succeeded but status hasn't been updated - https://storage.googleapis.com/minikube-builds/logs/684/OSX-XHyve.txt.

Are you OK with me merging this?

**Comment by dlorenc** [comment]
Yeah feel free. XHyve and hyper-v shouldn't be blocking yet. The status updates should be working now though, FWIW.

**Pull request merged**
