### PR TITLE
Add podman-env for connecting with podman-remote

### PR DESCRIPTION
**Pull request by afbjorklund**
For #6350

### CODE REVIEW

**Comment by tstromberg** [comment]
Part of me wishes we had a vendor-neutral command we could point users to, but I think any terminology we use might be lost on them. docker-env & podman-env are likely more meaningful than any alternative we come up with.

**Comment by tstromberg** [comment]
Merge conflict :(

**Comment by afbjorklund** [comment]
I’m not sure `env --container-runtime=docker` would have really _improved_ the situation ? But that was the original machine command...

**Comment by gbraad** [comment]
> docker-env & podman-env 

you could call it `runtime-env`... we have considered the same. it is in line with seting the runtime option. but just not sure if this is preferred. just wondering, does the code error when `docker-env` is used while the runtime is podman?

**Comment by afbjorklund** [comment]
> just wondering, does the code error when `docker-env` is used while the runtime is podman? (and vice versa)

There will be an error if docker is not running or podman is not installed, but otherwise you're free to choose...

```
$ minikube docker-env
💣  The docker service is currently not active
```

```
$  ./out/minikube podman-env
💣  The podman service is currently not available
```

It is quite common to use docker to build images for `containerd`, or to use podman to build images for `cri-o`.

**Comment by afbjorklund** [comment]
I will have to rewrite this

**Comment by afbjorklund** [comment]
I moved the tests from the pkg (generic) to the cmd (specific), as per the new code at `master`.

There were a lot of symbol conflicts with "env", so had to prefix a lot of things (miss my `static`)

**Comment by medyagh** [comment]
@afbjorklund any chance we could have integraiton test for this or documentation how to use it ?

**Comment by afbjorklund** [comment]
@medyagh : normally I try to write the user-facing documentation in the issue (not the PR)

Included a doc page: https://deploy-preview-6351--kubernetes-sigs-minikube.netlify.com/docs/tasks/podman_service/

**Comment by afbjorklund** [comment]
Stuck on lint

```
pkg/minikube/shell/shell.go:85:2: var `unset` is unused (unused)
cmd/minikube/cmd/podman-env.go:216:60: podmanEnvVars - result 1 (error) is always nil (unparam)
```

**Comment by Honiix** [comment]
Hi @afbjorklund, Thanks for your work!
I landed here because I was reading this: https://minikube.sigs.k8s.io/docs/tasks/podman_service/
But I got "Error: unknown command "podman-env" for "minikube".
It seems to be because this PR is merged but not included in the [last release (1.7.2)](https://github.com/kubernetes/minikube/releases/tag/v1.7.2). Right?

If it's the case, it may be a good idea to release the doc at the same time as the code. Is it feasible?

**Comment by afbjorklund** [comment]
It should be in 1.7.3 now, unfortunately (?) the docs are showing `master`

**Pull request merged**
