### PR TITLE
Update releases for v0.12.0

### PR DESCRIPTION
**Pull request by r2d4**

### CODE REVIEW

**Comment by aaron-prindle** [comment]
Make sure to upload to GCS as well

**Comment by r2d4** [comment]
ref #737

**Comment by dlorenc** [comment]
LGTM

**Comment by dlorenc** [comment]
Uploaded to GCS:

```shell
$ gsutil cat  gs://minikube/releases.json | head -n 9
[
  {
      "name": "v0.12.0",
      "checksums": {
          "darwin": "a96d6e1d53a7999503d00bcd41b4ccaa80f5d57f798608f03e3f4d63a42f9991",
          "linux": "1315a334e701c1558740e4140f8e28985d7734e8a53e4af2153076c2586c3c7d",
          "windows": "373e3e2e1d9e000044711dfafe3a88fdb9620c3050a6b5f9e8ed0eb3e7ffd12e"
      }
  },
```

**Pull request merged**
