### PR TITLE
Set short time Format in Audit log

### PR DESCRIPTION
**Pull request by Nikhil2001**
changed time Format to  time.RFC822 from  time.RFC1123,
Now it looks little shorter than before in auidt logs

### CODE REVIEW

**Comment by Nikhil2001** [comment]
@medyagh

**Comment by klaases** [comment]
Hi @[Nikhil2001](https://github.com/Nikhil2001), would you be able to add a preview of the new time format in the description?

Perhaps an example log before and after this change would be helpful to highlight the difference.

**Comment by klaases** [comment]
Hi @[Nikhil2001](https://github.com/Nikhil2001), would you be able to add a preview of the new time format in the description?

Perhaps an example log before and after this change would be helpful to highlight the difference.

**Comment by Nikhil2001** [comment]
> Hi @[Nikhil2001](https://github.com/Nikhil2001), would you be able to add a preview of the new time format in the description?
> 
> Perhaps an example log before and after this change would be helpful to highlight the difference.

BEFORE : 
Screenshot 2022-04-26 044833

WITH THIS PATCH:
Capture2

**Review by medyagh — APPROVED** [review]
Thank you for this PR! look forward to see more contributions from you

**Pull request merged**
