### PR TITLE
[addons] Add addon support for EFK logging 

### PR DESCRIPTION
**Pull request by kairen**
Feature request #2049. 

The commit added a new addon for EFK logging service, this can help user to log Kubernetes system info using Elasticsearch, Fluentd and Kibana. 

Usage as blow:

The preview as blow:

### P.S. **NEED MORE MEMORY(4G+) !!**

/cc @r2d4

### CODE REVIEW

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by kairen** [comment]
Sorry @r2d4 There are currently no tests for this addon. Do I need to join this update?

**Comment by kairen** [comment]
@r2d4 I think I can extend test for extra addons in future.

**Comment by r2d4** [comment]
@kairen Its no issue.  Obviously it helps identify regressions, but we don't provide any guarantees on the shipped addons (and they are easily overridable)

**Comment by kairen** [comment]
@r2d4 No problem! Thanks a lot.

**Comment by runningman84** [comment]
The memory usage of kibana can be limited using these options
```
          - name: NODE_OPTIONS
            value: "--max-old-space-size=250"
```

**Pull request merged**
