### PR TITLE
Abbreviate too long filenames to show progress

### LINKED ISSUE #9740: Show download progress for the Preload Tarball
image

As you can see in the above screenshot, we don't show the progress of the download. It is missing the bandwidth, size of remaining content, ETA etc. like we show for the ISO.

Since this preload tarball is big, the above information is essential.

### PR DESCRIPTION
**Pull request by afbjorklund**
Closes #9740

### CODE REVIEW

**Comment by afbjorklund** [comment]
This might need a less stupid way to abbreviate the long filenames.

preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4

```
    > preloaded-images-k8s-v6-v1....: 22.89 MiB / 486.35 MiB  4.71% 15.20 MiB p^C
```

We lost the "1.19.4" and "docker" information, along with .tar.lz4

**Comment by afbjorklund** [comment]
Showing it on a separate line before the progress bar, might be one way to handle it

**Review by medyagh — COMMENTED** [review]
this is a good idea

**Pull request merged**
