### PR TITLE
Switch the API implementation to use the local APIs everywhere we can.

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by dlorenc** [comment]
@r2d4 ready for another look.

**Comment by dlorenc** [comment]
@minikube-bot test this pleas

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by dlorenc** [comment]
@minikube-bot test this please

**Comment by aaron-prindle** [comment]
Was this passing the none driver test?  It seems that no entry in ~/.minikube/machines being made now when using the none driver, trying to identify if this is related.

**Comment by dlorenc** [comment]
> Was this passing the none driver test? It seems that no entry in ~/.minikube/machines being made now when using the none driver, trying to identify if this is related.

I think it did, but I guess we lose access to the history now that it's merged :(

**Comment by r2d4** [comment]
You can click on the "details" button on the merge history message in the PR and see the test history.  Looks like the None driver was passing

https://storage.googleapis.com/minikube-builds/logs/1544/Linux-None.txt

**Pull request merged**
