### PR TITLE
Rm localkube

### PR DESCRIPTION
**Pull request by aaron-prindle**
branch based off of: https://github.com/kubernetes/minikube/pull/2870

### CODE REVIEW

**Comment by dlorenc** [comment]
I think you might have to rebase, some of the tests here are still trying to run with bootstrapper=localkube

**Comment by dlorenc** [comment]
@aaron-prindle want to rebase and get this in?

**Comment by aaron-prindle** [comment]
done

**Comment by dlorenc** [comment]
OK, I think this is ready to go.

**Comment by luxas** [comment]
Gotta love PRs that remove 2M LoC :wink:

**Pull request merged**
