### PR TITLE
change crio-bin checksum since it changed upstream

### PR DESCRIPTION
**Pull request by afbjorklund**
Failed again, suspect the same root cause as last time (the git attributes)

#10975

Build success: https://storage.cloud.google.com/minikube-builds/logs/11111/5451ad8/iso_build.txt

```
--2021-04-16 07:04:35--  https://github.com/cri-o/cri-o/archive/v1.20.2.tar.gz
```

Builld failure: https://storage.cloud.google.com/minikube-builds/logs/11218/5a09ce1/iso_build.txt

```
--2021-04-27 23:28:40--  https://github.com/cri-o/cri-o/archive/v1.20.2.tar.gz
```

https://github.com/kubernetes/minikube/pull/11218#issuecomment-828016784

### CODE REVIEW

**Review by sharifelgamal — APPROVED** [review]
ugh

**Comment by afbjorklund** [comment]
Unfortunately I deleted the old tarball, so I cannot verify. But the new one looks OK, just `export-subst`

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
So now it flipped back again, compared to yesterday.

```
ERROR: v1.20.2.tar.gz has wrong sha256 hash:
ERROR: expected: 36d9f4cf4966342e2d4099e44d8156c55c6a10745c67ce4f856aa9f6dcc2d9ba
ERROR: got     : 1c01d4a76cdcfe3ac24147eb1d5f6ebd782bd98fb0ac0c19b79bd5a6560b1481
ERROR: Incomplete download, or man-in-the-middle (MITM) attack
```

```diff
--- cri-o-1.20.2.orig/vendor/k8s.io/client-go/pkg/version/base.go	2021-03-24 03:33:41.000000000 +0100
+++ cri-o-1.20.2/vendor/k8s.io/client-go/pkg/version/base.go	2021-03-24 03:33:41.000000000 +0100
@@ -55,7 +55,7 @@
 	// NOTE: The $Format strings are replaced during 'git archive' thanks to the
 	// companion .gitattributes file containing 'export-subst' in this same
 	// directory.  See also https://git-scm.com/docs/gitattributes
-	gitVersion   string = "v0.0.0-master+d5a999ad0a"
+	gitVersion   string = "v0.0.0-master+d5a999ad0a3"
 	gitCommit    string = "d5a999ad0a35d895ded554e1e18c142075501a98" // sha1 from git, output of $(git rev-parse HEAD)
 	gitTreeState string = ""            // state of git tree, either "clean" or "dirty"
 
diff -ur cri-o-1.20.2.orig/vendor/k8s.io/component-base/version/base.go cri-o-1.20.2/vendor/k8s.io/component-base/version/base.go
--- cri-o-1.20.2.orig/vendor/k8s.io/component-base/version/base.go	2021-03-24 03:33:41.000000000 +0100
+++ cri-o-1.20.2/vendor/k8s.io/component-base/version/base.go	2021-03-24 03:33:41.000000000 +0100
@@ -55,7 +55,7 @@
 	// NOTE: The $Format strings are replaced during 'git archive' thanks to the
 	// companion .gitattributes file containing 'export-subst' in this same
 	// directory.  See also https://git-scm.com/docs/gitattributes
-	gitVersion   = "v0.0.0-master+d5a999ad0a"
+	gitVersion   = "v0.0.0-master+d5a999ad0a3"
 	gitCommit    = "d5a999ad0a35d895ded554e1e18c142075501a98" // sha1 from git, output of $(git rev-parse HEAD)
 	gitTreeState = ""            // state of git tree, either "clean" or "dirty"
 ```

The number of significant digits depends on other factors.

**Comment by afbjorklund** [comment]
Fixed on master now, so hopefully the next release will be more "stable"

**Pull request closed without merging**
