### PR TITLE
Upgrade Buildroot to 2021.02 LTS with Linux 4.19

### PR DESCRIPTION
**Pull request by afbjorklund**
Upgrade kernel minor version to distribution default

```
# From https://www.kernel.org/pub/linux/kernel/v5.x/sha256sums.asc
sha256  83b81e433ba2f8ee143064fb163699ee857e26dd789006bc1e9edf1ccd0bd403  linux-5.10.43.tar.xz
sha256  17ee750a4aeb1c883d721e730d1f7e2855124585e2f47766864a1359a7ebe33c  linux-5.4.125.tar.xz
# From https://www.kernel.org/pub/linux/kernel/v4.x/sha256sums.asc
sha256  d13fa552be602825c443fcca90d6bdd72f4ebef809889ef015dba4593d3224ab  linux-4.4.272.tar.xz
sha256  f8bf0c390ae40ca736e104f10f744446bc534bf87ba1b6dbb2b7c9a8bece1058  linux-4.9.272.tar.xz
sha256  e4eae297a6fefefd8ce4781d98178a7c1ee51ca0a4c8a7e46e61b121fbab8b2a  linux-4.14.236.tar.xz
sha256  aaaebdccf599f77148fe170642fa7dc2452cf994b5cbbb4d39cab9e7f4058896  linux-4.19.194.tar.xz
```

BR2_PACKAGE_LUA_5_1 is required for BR2_PACKAGE_SYSDIG

For #11652

### CODE REVIEW

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
@afbjorklund flake restuls doesnt look good !

**Comment by afbjorklund** [comment]
Looks like the minikube-automount is failing (it adds the .ssh keys)

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
KVM start is alarmingly high

**Comment by afbjorklund** [comment]
The docker driver tests are irrelevant for this PR, it has ISO changes only.

**Comment by afbjorklund** [comment]
@medyagh : looks like the increased startup time is related to not using preload

💡  Existing disk is missing new features (lz4). To upgrade, run 'minikube delete'

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by afbjorklund** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by ilya-zuyev** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Review by ilya-zuyev — APPROVED** [review]

**Comment by afbjorklund** [comment]
The build failure was just the usual problem of the cri-o distfiles being unstable, due to k8s version base:

```diff
diff -ur cri-o-1.20.2.orig/vendor/k8s.io/client-go/pkg/version/base.go cri-o-1.20.2/vendor/k8s.io/client-go/pkg/version/base.go
--- cri-o-1.20.2.orig/vendor/k8s.io/client-go/pkg/version/base.go	2021-03-24 03:33:41.000000000 +0100
+++ cri-o-1.20.2/vendor/k8s.io/client-go/pkg/version/base.go	2021-03-24 03:33:41.000000000 +0100
@@ -55,7 +55,7 @@
 	// NOTE: The $Format strings are replaced during 'git archive' thanks to the
 	// companion .gitattributes file containing 'export-subst' in this same
 	// directory.  See also https://git-scm.com/docs/gitattributes
-	gitVersion   string = "v0.0.0-master+d5a999ad0a3"
+	gitVersion   string = "v0.0.0-master+d5a999ad0a"
 	gitCommit    string = "d5a999ad0a35d895ded554e1e18c142075501a98" // sha1 from git, output of $(git rev-parse HEAD)
 	gitTreeState string = ""            // state of git tree, either "clean" or "dirty"
 
diff -ur cri-o-1.20.2.orig/vendor/k8s.io/component-base/version/base.go cri-o-1.20.2/vendor/k8s.io/component-base/version/base.go
--- cri-o-1.20.2.orig/vendor/k8s.io/component-base/version/base.go	2021-03-24 03:33:41.000000000 +0100
+++ cri-o-1.20.2/vendor/k8s.io/component-base/version/base.go	2021-03-24 03:33:41.000000000 +0100
@@ -55,7 +55,7 @@
 	// NOTE: The $Format strings are replaced during 'git archive' thanks to the
 	// companion .gitattributes file containing 'export-subst' in this same
 	// directory.  See also https://git-scm.com/docs/gitattributes
-	gitVersion   = "v0.0.0-master+d5a999ad0a3"
+	gitVersion   = "v0.0.0-master+d5a999ad0a"
 	gitCommit    = "d5a999ad0a35d895ded554e1e18c142075501a98" // sha1 from git, output of $(git rev-parse HEAD)
 	gitTreeState = ""            // state of git tree, either "clean" or "dirty"
 
```

It has been fixed upstream in https://github.com/cri-o/cri-o/commit/dbca042c11b4449ef1104156f9b3e8ecfa32d839

**Pull request merged**
