### PR TITLE
Fix Windows Makefile target

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by dlorenc** [comment]
Failing build logs are here: https://storage.googleapis.com/minikube-builds/logs/107/build.txt

Not sure how this broke or went unnoticed... The failure looks strange too...

**Comment by jimmidyson** [comment]
Yeah it's weird. Builds fine locally with `make cross`... Wonder if the Jenkins workspace is foobarred? Worth deleting workspace & then rekicking tests?

**Comment by dlorenc** [comment]
@minikube-bot retest this please

**Comment by dlorenc** [comment]
I think this might have been a concurrency issue. Two builds started at the same time and broke each other. I turned off concurrent builds. It seems to be running now.

**Comment by jimmidyson** [comment]
Ah cool! Thanks!

**Comment by dlorenc** [comment]
LGTM

**Pull request merged**
