### PR TITLE
Inform users which version of Kubernetes is starting

### PR DESCRIPTION
**Pull request by everett-toews**
This can be very informative for users new to Kubernetes and minikube.

### CODE REVIEW

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by everett-toews** [comment]
This is the first time I've encountered the Google CLA so I'll need to get that figured out.

**Comment by r2d4** [comment]
I think the Linux foundation CLA is sufficient

**Comment by everett-toews** [comment]
@r2d4 If this can be merged without signing the Google CLA, I'm fine with that. If not, I'm open to signing it. Whatever works.

**Comment by everett-toews** [comment]
The OSX-XHyve and Windows-HyperV seem to be blocked/stalled/broken. The details just return an error.

https://storage.googleapis.com/minikube-builds/logs/1332/OSX-XHyve.txt
https://storage.googleapis.com/minikube-builds/logs/1332/Windows-HyperV.txt

Is there anything I can do to move this forward?

**Comment by dlorenc** [comment]
Yeah it looks like the core kubernes repo got rid of the google CLA webhook, so I'll delete it from this repo as well.

**Comment by dlorenc** [comment]
Thanks for the PR!

**Comment by everett-toews** [comment]
@dlorenc Thanks for clearing up that bit about the Google CLA! 🎩

**Pull request merged**
