### PR TITLE
ISO: Add nerdctl

### PR DESCRIPTION
**Pull request by spowelljr**

### CODE REVIEW

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by medyagh** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Comment by spowelljr** [comment]
ok-to-build-iso

**Review by medyagh — APPROVED** [review]

**Pull request merged**
