### PR TITLE
fix multiple node calico-node not ready

### PR DESCRIPTION
**Pull request by AlexanderChen1989**

### CODE REVIEW

**Comment by tstromberg** [comment]
The CLA bot noticed that your commits appear to come from `11112583` instead of your GitHub username `AlexanderChen1989`:

Screen Shot 2020-08-20 at 2 00 43 PM

https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user has more information on how to fix this, under "Commits are not linked to any user".

Could you please fix this so that I may merge your improvement? Thank you.

**Comment by AlexanderChen1989** [comment]
> The CLA bot noticed that your commits appear to come from `11112583` instead of your GitHub username `AlexanderChen1989`:
> 
> Screen Shot 2020-08-20 at 2 00 43 PM
> 
> https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user has more information on how to fix this, under "Commits are not linked to any user".
> 
> Could you please fix this so that I may merge your improvement? Thank you.

I changed the author

**Comment by tstromberg** [comment]
Thank you!

**Pull request merged**
