### PR TITLE
Remove default cni config when custom CNI is used

### PR DESCRIPTION
**Pull request by michaelhenkel**
When a custom CNI is defined via --cni flag it might take a while to populate the CNIs configuration into /etc/cni/net.d.
Minikube comes up and in case of crio or containerd runtime it has a CNI configuration in /etc/cni/net,d already.
Now if pods using pod network (such as coredns) come up BEFORE the custom CNIs config file is populated, this pod ip address is served by podman. Subsequent pods will be served by the custom CNI but won't be able to communicate with the pods using podman CNI.
This PR removes all CNI configs from /etc/cni/net.d just before the custom CNI manifest is applied.

### CODE REVIEW

**Review by priyawadhwa — CHANGES_REQUESTED** [review]
Hey @michaelhenkel thanks for opening this PR. Some notes:
1. Looks like our linter is failing
```
pkg/minikube/cni/custom.go:76:8: S1039: unnecessary use of fmt.Sprintf (gosimple)
	rm := fmt.Sprintf("rm -rf /etc/cni/net.d/*")
```
2. Right now we skip testing CNI on containerd, but I'm hoping to get that test up and running sometime this week. Let's make sure https://github.com/kubernetes/minikube/issues/10200 is completed before we merge this so that we can run those tests against these changes.

**Comment by priyawadhwa** [comment]
Just opened https://github.com/kubernetes/minikube/pull/10261, let's merge that before we merge this.

**Comment by medyagh** [comment]
@michaelhenkel  do u mind pulling master and also fixing the lint issue ?

make sure to run `make lint` locally

**Review by medyagh — CHANGES_REQUESTED** [review]
plz check lint

**Comment by medyagh** [comment]
@michaelhenkel do u mind pull upstream master to your PR , I see a lot of diffs from other PRs to your PR makes it harder to review

**Comment by michaelhenkel** [comment]
oh, I thought I rebased against master. Will check.

**Comment by michaelhenkel** [comment]
I had to create a new PR:

https://github.com/kubernetes/minikube/pull/10384

Am Fr., 5. Feb. 2021 um 18:56 Uhr schrieb michael henkel <
michael.henkel@gmail.com>:

**Pull request closed without merging**
