### PR TITLE
Use stable networking api in ingress-dns example

### PR DESCRIPTION
**Pull request by lvjp**
Since the `Ingress` resource became stable in the kubernetes API, I upgraded the example to this new stable API.

### CODE REVIEW

**Review by medyagh — APPROVED** [review]

**Review by medyagh — CHANGES_REQUESTED** [review]
@lvjp  do u mind commenting from which version of kubernetes this is stable ?
would this break the addon for older kubernetes versions ?

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
@lvjp  thanks for this contribution, please make sure to sign the CLA so we could accept this PR

**Comment by lvjp** [comment]
> @lvjp do u mind commenting from which version of kubernetes this is stable ?
> would this break the addon for older kubernetes versions ?

I updated the note about the minimum kubernetes version for the example.

**Comment by lvjp** [comment]
@medyagh CLA signed :sunglasses:

**Review by priyawadhwa — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
