### PR TITLE
kic: explicitly provide the type in inspect commands

### PR DESCRIPTION
**Pull request by afbjorklund**
Should avoid errors like: map has no entry for key "State"

When inspecting a volume, rather than a container or image

Should help with #8192

Reviewer note: also fixed a typo in an internal function name

### CODE REVIEW

**Comment by afbjorklund** [comment]
Here is the issue we are trying to address:

```
 docker run -d --name foo -d busybox true
c4e9d99e7c959014b5e0b6c543bc4ca5ff54475b6e79dbc2c717a2fff304971d
 docker inspect foo --format={{.State.Status}}
exited
 docker container inspect foo --format={{.State.Status}}
exited
 docker volume create foo
 docker rm foo
 docker inspect foo --format={{.State.Status}}

Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
 docker container inspect foo --format={{.State.Status}}

Error: No such container: foo
```

That is, when using "inspect" it will match the volume name too. So we add "container" explicitly.

This seems to be a common problem at minikube start, when it tries to re-create the container...

**Comment by medyagh** [comment]
this is a great improvment ! thank you @afbjorklund do you know if this "type" inspect is supported in older docker versions? or is there a min version that we would require for this change?

**Comment by afbjorklund** [comment]
> this is a great improvment ! thank you @afbjorklund do you know if this "type" inspect is supported in older docker versions? or is there a min version that we would require for this change?

It's available in 1.13 / 17.03, I don't think we need to support any older than that...

**Comment by medyagh** [comment]
> > this is a great improvment ! thank you @afbjorklund do you know if this "type" inspect is supported in older docker versions? or is there a min version that we would require for this change?
> 
> It's available in 1.13 / 17.03, I don't think we need to support any older than that...

sounds good

**Pull request merged**
