### PR TITLE
update nvidia gpu support doc address in readme

### LINKED ISSUE #16956: The `NVIDIA GPU support` in readme is Not found
### What Happened?

The doc claims there is `NVIDIA GPU support` ,but the link is not valid

> As well as developer-friendly features:
> 
> [Addons](https://minikube.sigs.k8s.io/docs/handbook/deploying/#addons) - a marketplace for developers to share configurations for running services on minikube
> [NVIDIA GPU support](https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/) - for machine learning
> [Filesystem mounts](https://minikube.sigs.k8s.io/docs/handbook/mount/)
> For more information, see the official [minikube website](https://minikube.sigs.k8s.io/)

image

### Attach the log file

image

### Operating System

None

### Driver

None

### PR DESCRIPTION
**Pull request by anda-ren**
fixes #16956

### CODE REVIEW

**Comment by Lyllt8** [comment]
2023-07-29 9:28 GMT-06:00, linux-foundation-easycla[bot]
***@***.***>:

**Review by medyagh — APPROVED** [review]

**Comment by medyagh** [comment]
@anda-ren can you plz sign the cla so we can accept this contribution

**Comment by anda-ren** [comment]
> @anda-ren can you plz sign the cla so we can accept this contribution

Yes, sure. I'm done.

**Comment by medyagh** [comment]
thanks @anda-ren

**Pull request merged**
