### PR TITLE
Restore mount command and unswap port and mountVersion

### PR DESCRIPTION
**Pull request by q3aiml**
@aaron-prindle this seems to have been a mistake in 6f42d58 (#1705)?

### CODE REVIEW

**Comment by dlorenc** [comment]
@minikube-bot ok to test

**Comment by q3aiml** [comment]
I'm running into one other issue after 6f42d58 where it seems the port and version are swapped:

```
sudo mount -t 9p -o trans=tcp,port=9p2000.u,dfltuid=1001,dfltgid=1001,version=32777,msize=262144 192.168.42.1 /opt/host-persist;
    sudo chmod 775 /opt/host-persist;
    SSH cmd err, output: <nil>: mount: wrong fs type, bad option, bad superblock on 192.168.42.1,
```

Let me know if it is better to add that change here or open a separate PR.

**Comment by aaron-prindle** [comment]
@q3aiml Thanks for catching this!  If you can put the port/version change in this PR that would be great, thanks!

**Comment by q3aiml** [comment]
Sure thing! Thank you for digging into the 9p issues. It's the best after hitting an issue to go and find that not only do others see it too (I'm not alone!) but then there is also a patch

**Pull request merged**
