### PR TITLE
Try updating apt before installing libvirt-dev

### LINKED ISSUE #1162: trusty travis can't grab libvirt-dev
bug report - travis CI tests are failing because travis can't locate libvirt-dev package

tracked here for reference 
https://github.com/travis-ci/travis-ci/issues/7351

### PR DESCRIPTION
**Pull request by dims**
Fixes #1162

### CODE REVIEW

**Comment by r2d4** [comment]
According to the Travis issue I linked, this should have been fixed on their end and we shouldn't have had to change anything

**Comment by dims** [comment]
@r2d4 : i saw a failure in https://travis-ci.org/kubernetes/minikube/builds/203547614 and was not sure

can you please retrigger tests in https://github.com/kubernetes/minikube/pull/1152 please? Thanks!

**Comment by dlorenc** [comment]
I don't think we can re-trigger the travis tests. The PR author usually has to. If you don't see a button in the travis UI, you can always amend your commit and push again.

**Comment by r2d4** [comment]
I retriggered the travis build for #1152.  It looks like it got past the apt-get

**Comment by dims** [comment]
Thanks @r2d4 !

**Pull request closed without merging**
