### PR TITLE
minikube-iso: Use buildroot branch 2017-02

### PR DESCRIPTION
**Pull request by tgraf**
This rebases minikube-iso to the buildroot release 2017-02.

* A change in buildroot required the introduction of a `external.desc` as
  multiple external trees are supported in modern buildroot versions. This
  required change is described here [0].

  [0] https://buildroot.org/downloads/manual/manual.html#br2-external-converting

* The 4.9.13 kernel included in buildroot 2017-02 is not compatible with
  VBox guest additions 5.1.6, thus bump guest additions to 5.1.18.

* The defconfig of 4.9.13 has been cleaned up.

* The existing isolinux.cfg was not included in the config and thus
  ignored, include it.

* systemd 232 included in buildroot 2017-02 is incompatible with docker <
  17.03 without boot parameter systemd.legacy_systemd_cgroup_controller=yes
  Details: https://github.com/opencontainers/runc/issues/1175

### CODE REVIEW

**Comment by r2d4** [comment]
@minikube-bot ok to test

**Comment by tgraf** [comment]
buildroot 2017-02 ships with systemd 232 which broke docker/runc 1.11
https://github.com/opencontainers/runc/issues/1175

Two options:
 * Upgrading docker/moby to >= 17.03.1
 * Specify the boot parameter `systemd.legacy_systemd_cgroup_controller=yes`

**Comment by tgraf** [comment]
Going to 17.04 would solve the systemd issue but k8s obviously doesn't support it yet. I'll see how I can pass in the boot parameter systemd.legacy_systemd_cgroup_controller=yes

**Comment by dlorenc** [comment]
> Going to 17.04 would solve the systemd issue but k8s obviously doesn't support it yet. I'll see how I can pass in the boot parameter systemd.legacy_systemd_cgroup_controller=yes

This approach sounds good.

**Comment by tgraf** [comment]
The latest rebase now sets the boot parameter `systemd.legacy_systemd_cgroup_controller=yes`. I noticed that the existing `isolinux.cfg` was not included in the buildroot build due to a missing config statements so the existing parameters were not effective. I kept the existing parameters as-is and just added the new required option for now.

**Comment by tgraf** [comment]
I've manually downloaded the ISO built in jenkins and it works fine when used in combination with the official minikube 0.18 release binary. However, when I run `go test -v $(REPOPATH)/test/integration` I run into #1422 and so does Jenkins.

**Comment by dlorenc** [comment]
> I've manually downloaded the ISO built in jenkins and it works fine when used in combination with the official minikube 0.18 release binary. However, when I run go test -v $(REPOPATH)/test/integration I run into #1422 and so does Jenkins.

Thanks! I'll take a look today and see if I can figure it out.

**Comment by tgraf** [comment]
> Thanks! I'll take a look today and see if I can figure it out.

I'll continue debugging as well. Any pointer on why #1422 might happen would be useful. I'm not familiar enough yet with all the build logic.

**Comment by r2d4** [comment]
@tgraf Where are you seeing the that panic in jenkins?

Can you try running `make integration` directly?  The command is slightly different than what you're running
https://github.com/kubernetes/minikube/blob/master/Makefile#L113-L114

**Comment by tgraf** [comment]
> @tgraf Where are you seeing the that panic in jenkins?

Running `make integration` I get this panic. Even when using the standard v0.18 ISO:
```
$ cat ~/.minikube/machines/minikube/config.json | grep -i ISO
        "Boot2DockerURL": "file:///home/tgraf/.minikube/cache/iso/minikube-v0.18.0.iso",
```

```
$ minikube logs
[...]
Apr 27 20:38:32 minikube localkube[3538]: fatal error: unexpected signal during runtime execution
Apr 27 20:38:32 minikube localkube[3538]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f4aed84f070]
Apr 27 20:38:32 minikube localkube[3538]: runtime stack:
Apr 27 20:38:32 minikube localkube[3538]: runtime.throw(0x3ee5f0e, 0x2a)
Apr 27 20:38:32 minikube localkube[3538]:         /usr/local/go/src/runtime/panic.go:566 +0x95
Apr 27 20:38:32 minikube localkube[3538]: runtime.sigpanic()
Apr 27 20:38:32 minikube localkube[3538]:         /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc
Apr 27 20:38:32 minikube localkube[3538]: goroutine 6483 [syscall, locked to thread]:
Apr 27 20:38:32 minikube localkube[3538]: runtime.cgocall(0x31e4fd0, 0xc423d8a8f0, 0x0)
Apr 27 20:38:32 minikube localkube[3538]:         /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc423d8a8a0 sp=0xc423d8a860
Apr 27 20:38:32 minikube localkube[3538]: os/user._Cfunc_mygetpwuid_r(0x0, 0xc4239951a0, 0x7f48600008c0, 0x400, 0xc422b00dc0, 0x0)
Apr 27 20:38:32 minikube localkube[3538]:         ??:0 +0x4d fp=0xc423d8a8f0 sp=0xc423d8a8a0
Apr 27 20:38:32 minikube localkube[3538]: os/user.lookupUnixUid.func1(0x42a352)
Apr 27 20:38:32 minikube localkube[3538]:         /usr/local/go/src/os/user/lookup_unix.go:103 +0x1f7 fp=0xc423d8a980 sp=0xc423d8a8f0
Apr 27 20:38:32 minikube localkube[3538]: os/user.retryWithBuffer(0xc4237933d0, 0xc423d8aa78, 0xc4237933d0, 0xc423d8aa97)
Apr 27 20:38:32 minikube localkube[3538]:         /usr/local/go/src/os/user/lookup_unix.go:253 +0x2b fp=0xc423d8a9e8 sp=0xc423d8a980
Apr 27 20:38:32 minikube localkube[3538]: os/user.lookupUnixUid(0x0, 0x0, 0x0, 0x0)
Apr 27 20:38:32 minikube localkube[3538]:         /usr/local/go/src/os/user/lookup_unix.go:105 +0x17d fp=0xc423d8aab0 sp=0xc423d8a9e8
Apr 27 20:38:32 minikube localkube[3538]: os/user.current(0xc423d8ab00, 0xc423d8ab20, 0x4732f5)
Apr 27 20:38:32 minikube localkube[3538]:         /usr/local/go/src/os/user/lookup_unix.go:49 +0x2f fp=0xc423d8aae0 sp=0xc423d8aab0
Apr 27 20:38:32 minikube localkube[3538]: os/user.Current(0x0, 0x0, 0xc423d8ab00)
Apr 27 20:38:32 minikube localkube[3538]:         /usr/local/go/src/os/user/lookup.go:9 +0x22 fp=0xc423d8ab08 sp=0xc423d8aae0
Apr 27 20:38:32 minikube localkube[3538]: k8s.io/minikube/vendor/github.com/godbus/dbus.lookupHomeDir(0x3e47519, 0x4)
Apr 27 20:38:32 minikube localkube[3538]:         /home/tgraf/dev/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/godbus/dbus/homedir_dynamic.go:10 +0x22 fp=0xc423d8ab30 sp=0xc423d8ab08
```

**Comment by r2d4** [comment]
@tgraf You can click on "Details" in job matrix on the PR

**Comment by tgraf** [comment]
> @tgraf You can click on "Details" in job matrix on the PR

That only seems to show me the logs of the Jenkins job itself and not the output of `minikube logs` which would show the panic itself. At least that's the behaviour when I run `make integration` locally.

**Comment by r2d4** [comment]
Yeah sorry - I deleted that comment after I understood that it only shows up in the minikube logs and not the test output

**Comment by r2d4** [comment]
@tgraf do you know what test its failing on?  I'm unable to reproduce locally

**Comment by tgraf** [comment]
> @tgraf do you know what test its failing on? I'm unable to reproduce locally

It's not always failing in the same test which would be explained by the cause being a missing lock around `current()`.

In this instance, this was the first failing test:
```
    --- FAIL: TestFunctional/Mounting (7.41s)
```

```
Apr 27 20:38:31 minikube localkube[3538]: scheduler is ready!
Apr 27 20:38:31 minikube localkube[3538]: Starting kubelet...
Apr 27 20:38:31 minikube localkube[3538]: Waiting for kubelet to be healthy...
Apr 27 20:38:31 minikube localkube[3538]: I0427 20:38:31.870546    3538 feature_gate.go:144] feature gates: map[]
Apr 27 20:38:31 minikube localkube[3538]: E0427 20:38:31.870560    3538 server.go:312] unable to register configz: register config "componentconfig" twice
Apr 27 20:38:31 minikube localkube[3538]: W0427 20:38:31.870594    3538 server.go:715] Could not load kubeconfig file /var/lib/kubelet/kubeconfig: stat /var/lib/kubelet/kubeconfig: no such file or directory. Using default client config instead.
Apr 27 20:38:31 minikube localkube[3538]: I0427 20:38:31.878590    3538 event.go:217] Event(v1.ObjectReference{Kind:"Pod", Namespace:"9slzr4vn8y87svj208oh", Name:"busybox", UID:"796a11f6-2b89-11e7-b813-0800271eeb8e", APIVersion:"v1", ResourceVersion:"108", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' no nodes available to schedule pods
Apr 27 20:38:32 minikube localkube[3538]: I0427 20:38:32.042215    3538 docker.go:364] Connecting to docker on unix:///var/run/docker.sock
Apr 27 20:38:32 minikube localkube[3538]: I0427 20:38:32.042239    3538 docker.go:384] Start docker client with request timeout=2m0s
Apr 27 20:38:32 minikube localkube[3538]: fatal error: unexpected signal during runtime execution
Apr 27 20:38:32 minikube localkube[3538]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7f4aed84f070]
```

**Comment by tgraf** [comment]
> @tgraf do you know what test its failing on? I'm unable to reproduce locally

I see multiple other PRs failing for the same reason so I doubt this is connected to any changes in this particular PR. This should be looked at with the context in issue #1422

**Comment by dlorenc** [comment]
@tgraf would you mind rebasing onto master? I think we've fixed all of the current test flakiness.

**Comment by tgraf** [comment]
> @tgraf would you mind rebasing onto master? I think we've fixed all of the current test flakiness.

Done. I think we are still seeing #1422 to some extent. It's difficult to say for sure without being able to see the actual minikube logs from Jenkins.

**Comment by tgraf** [comment]
Thanks @r2d4, your #1434 fix solved the remaining test failures.

**Comment by dlorenc** [comment]
Thanks for doing this!

**Pull request merged**
