### PR TITLE
doc: refresh roadmap year date and sort checkboxes

### PR DESCRIPTION
**Pull request by JulienBreux**
Hi community 👋🏻 

Another tiny PR to clean some docs issues.

1. Refresh roadmap year date
2. Sort checkboxes from done to todo

### CODE REVIEW

**Review by afbjorklund — CHANGES_REQUESTED** [review]
Not sure if we ever made a minikube roadmap for 2021 ? Looking upstream, removing Docker was one of the big items...

Reordering the checkboxes depending on whether they are finished seems somewhat arbitrary and possibly confusing.

Better have one of the Office Hours do a proper roadmap update, perhaps ?

But I do believe that the SSH driver and Container build boxes should be ticked.

**Comment by afbjorklund** [comment]
One of the bigger items for the project at the moment is completing the ISO for ARM64, so that it works on Apple M1.

**Comment by JulienBreux** [comment]
Ok 😊 

The question is: do you want that I remove this obsolete page finally @afbjorklund?

Or add a link to the repo milestones?

**Comment by afbjorklund** [comment]
I don't think we want to remove it altogether, it is outdated more than obsolete...

Thanks for the reminder, though! @medyagh : should we just bump the year ?

**Comment by JulienBreux** [comment]
> I don't think we want to remove it altogether, it is outdated more than obsolete...
> 
> Thanks for the reminder, though! @medyagh : should we just bump the year ?

Oups, sorry, you're right _outdated_.

That's my point, just a PR to clean year date and sort checkboxes.

Thanks 🙏🏻

**Comment by afbjorklund** [comment]
Ticked some boxes in #12146

**Review by medyagh — APPROVED** [review]

**Pull request merged**
