### PR TITLE
wip: Improve minikube cache

### PR DESCRIPTION
**Pull request by medyagh**
before this PR
cache add was not consistent as described in this bug: https://github.com/kubernetes/minikube/issues/5974

This will be a breaking change !

- `cache add` command will be per profile ! 
- new field in machine config for user Cached Images 
- added integration tests for (cache add, cache delete and cache list, and check image loaded inside node)
- choose smaller images for in integration tests ( 6 mb instead of 655 mb)
- clean up the temporary files

### before this PR 

```
 $ cat ~/.minikube/config/config.json 
{
    "cache": {
        "gcr.io/hello-minikube-zero-install/hello-node": null,
        "k8s.gcr.io/echoserver:1.4": null,
        "med": null
    }
}
```

### after this PR 
- will be new map in profile config
```
{
    "Name": "minikube",
    "KeepContext": false,
    "EmbedCerts": false,
    "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.5.1.iso",
    "Memory": 2000,
    "CPUs": 2,
    "DiskSize": 20000,
    "VMDriver": "hyperkit",
    "ContainerRuntime": "docker",
    "CachedImages": {
        "busybox": "loaded",
        "e4": "loaded",
        "k8s.gcr.io/echoserver:1.4": "loaded",
        "med": "loaded"
    },
...
...
...
```

- will warn if there is a older cache in global config
```
$ ./out/minikube cache list
⚠️  Warning:
        Images [gcr.io/hello-minikube-zero-install/hello-node k8s.gcr.io/echoserver:1.4 med] were cached using older version minikube.
        Please consider re-caching them again using "minikube cache add" commmand.
        Caches are now per-profile.
busybox
e4
k8s.gcr.io/echoserver:1.4
med
```

## TODO: 

1- load image only if it is not already loaded.
2- move the cache logics from machine package to its own package
3- store the image sha in the config map,
4- cache even if minikube is not runninng

### CODE REVIEW

**Comment by priyawadhwa** [comment]
Instead of warning users that old cached images need to be added again, could we automatically add them to all profiles? That way we can do the work for users.

**Comment by medyagh** [comment]
> Instead of warning users that old cached images need to be added again, could we automatically add them to all profiles? That way we can do the work for users.

good idea

**Comment by medyagh** [comment]
this PR is closed in favor of https://github.com/kubernetes/minikube/pull/5975

**Pull request closed without merging**
